### ISSUE TITLE
GUI quits with error 'System tray unavailable'

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#2987]
**Imported issue:**
- Author: Elanor Matheson
- Date: 2012-01-10 19:02:41
- Legacy ID: 3056
- Version: 1.4.5

**Steps to reproduce:**  

Linux Mint 12, 1.4.5 gui  
1. Install synergy  
2. Add 'synergy' to startup applications list  
3. Reboot, Logout, or otherwise restart the computer. Log in.  

Expected: Synergy starts with WM.  
Actual: Error dialog: There doesn't seem to be a system tray available. Quitting  

After this, synergy must be started manually  

**Versions (Synergy, OS):**  

Server: 1.4.5, Linux Mint  
Client 1: 1.4.5, Windows 7  

**Workaround:**  

Start synergy manually after error appears.

**Comment by mahngiel** [comment]
> Start synergy manually after error appears.
Work-around is not functional on Plasma 5, Debian (testing), latest master build.

**Comment by bob-was-here** [comment]
Fresh install of Debian Stretch with KDE Plasma 5.  
apt-get update && apt-get upgrade, then install synergy-master-alpha-588fb4b-Linux-x86_64.deb

"synergy" either from the menu or command line gives the the "System tray unavailable. Quitting" message.

"synergys" at the command line gives "no configuration available"

"synergyc" can be started at the command line.  No icon appears in the system tray.

Same results with synergy-master-alpha-5da7290-Linux-x86_64.deb and 1.7.4 stable as well.

**Comment by mahngiel** [comment]
@bob-was-here 
I found [this](https://github.com/cnsworder/synergy) Fork with an open PR that addresses the Plasma 5 tray issue.  You can add it as an additional remote temporarily and merge it into `master` branch and manually build it (instructions in README). This allows synergy to launch, skipping the systray (just don't close the config GUI)

**Comment by guss77** [comment]
Installing sni-qt allows synergy to use a system notification interface (such as those available under Plasma and Unity) as a system tray. There is still a race condition where if it takes the SNI some time to become ready (such as in Plasma), synergy will still abort instead of waiting.

**Comment by nickguletskii** [comment]
>Installing sni-qt allows synergy to use a system notification interface (such as those available under Plasma and Unity) as a system tray. There is still a race condition where if it takes the SNI some time to become ready (such as in Plasma), synergy will still abort instead of waiting.

There is no sni-qt on Debian Testing.

**Comment by guss77** [comment]
This is debian bug #712938, which looks to have been resolved recently with sni-qt accepted into "experimental": https://tracker.debian.org/news/704158 . 

You should be able to install sni-qt from there, or wait until it gets to "testing".

**Comment by guss77** [comment]
BTW - the feature provided by sni-qt is supposedly implemented "natively" in Qt 5.4. So Synergy can solve this issue by upgrading to Qt 5.

**Comment by se1exin** [comment]
I also have this problem, haven't been able to debug any further than the initial 'System tray unavailable message'

I'm using Enlightenment on Arch Linux with LightDM. I also tried sni-qt as suggested but with no luck.

Synergy 1.8.1 (synergy-git from AUR)

**Comment by paul-suarez** [comment]
Adamo from forums:

I figured it out. For anyone else with the same issue, add the 'System Tray' applet to the Panel.

Right click on the Panel, click on 'Add applets to the panel', then find 'System Tray' and add it. An icon of the running instance will be displayed in the Panel.

For his Synergy server running Linux Mint.
[Missing Synergy Icon in Linux](https://symless.com/forums/topic/2989-missing-synergy-icon-in-linux/#comment-10174) forums thread

**Comment by hesparza** [comment]
In Xubuntu 14.04.5 LTS, running XFCE as the graphical environment. 

Right click on the Panel, click on 'Panel -> Add New Items..', then find 'Notification Area' and add it. After this run Synergy and the icon of the running instance will be displayed in the new notification area.

Thanks to @paul-suarez, I just mimic his solution for this version of Xubuntu.

**Comment by zatricky** [comment]
@paul-suarez that will definitely work for most people. In my case however Synergy prevented me from using the GUI I wanted to use. I don't want a panel, never mind a tray.

**Comment by wildcard27** [comment]
@nbolton This seems to be happening on the latest 1.8 on Ubuntu 17.10, too.

**Comment by bertelschmitt** [comment]
We are now in the year 2020. I still have this with a new Ubuntu 18.04 install. Synergy installed and kept current via apt. No problem on another Ubuntu 18.04  installation.

**Comment by ljburtz** [comment]
exactly same here on Ubuntu 20, also using apt of synergy 2. Also sympton of synergy won't start unless 'system tray unavailable' message is clicked away. @bertelschmitt did you find a solution?

**Comment by andreacndn** [comment]
@ljburtz are you using Synergy 1 or Synergy 2?

**Comment by ljburtz** [comment]
it's version 1.12.2, build date 2020/11/12 downloaded from their website https://members.symless.com/synergy/downloads/list/s1

**Comment by andreacndn** [comment]
Thank you.
Yes, the development of Synergy 2 has been halted, and we are now focusing on improving Synergy 1 while also developing the next generation product (Synergy 3) which is currently approaching the first alpha release.

**Comment by andreacndn** [comment]
Jira Issue:  [SYNERGY-707](https://symless.atlassian.net/browse/SYNERGY-707)

**Comment by ljburtz** [comment]
great! looking forward to Synergy3! especially for the support for monitor of different sizes and positions

**Comment by andreacndn** [comment]
Cannot reproduce the issue
