### ISSUE TITLE
Hook DLL (synrgyhk.dll) is not released

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3082]
**Imported issue:**
- Author: Nick Bolton
- Date: 2012-04-08 12:26:02
- Legacy ID: 3152
- Version: 1.4.8

A lot of users are seeing this error:  

ERROR: failed to init synrgyhk.dll, another program may be using it  
FATAL: failed to start server: unable to open screen  

Could be because synergys/c aren't being closed gracefully.

**Comment by shoelzer** [comment]
I'm still seeing this issue on a nightly of 1.7.4. [dba4670]

**Comment by nyetwurk** [comment]
I am seeing this on 1.7.4 3aebb87

**Comment by nyetwurk** [comment]
Happened again, this time winlogin.exe

**Comment by XinyuHou** [comment]
Closing this issue since it doesn't point to a specific problem.

@shoelzer, @nyetwurk you're probably seeing #4721 where the service or server is crashing without properly cleaning up synwinhk.dll.

**Comment by nbolton** [comment]
Duplicates #4957
