### ISSUE TITLE
Lock all screens when Win+L is pressed

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3084]
Problem: Currently users need to lock all screens individually, which can be a pain when there are several screens to lock.  

Solution: Allow the user to press Win+L once to lock all screens.

https://github.com/symless/synergy/issues/253

**Comment by ChickenProp** [comment]
I had the same problem as kensykora. Turns out it's possible to disable win-l using the registry, so I've done that. This doesn't let you have win-l lock on windows and go-to-location-bar on OSX, so it may not be ideal (though I wasn't using it for locking anyway), but it's definitely an improvement from my perspective. (Also, I guess people assigning shortcuts to ctrl-alt-l might be able to use this to assign them to win-l instead, if they so desire.)

http://www.howtogeek.com/howto/windows-vista/disableenable-lock-workstation-functionality-windows-l/

**Comment by koos147** [comment]
i have created a shortcut on both desktops with 
%windir%\System32\rundll32.exe user32.dll,LockWorkStation"
assign them both witch control+alt+l
in synergy i created a new hotkey called control+alt+k wich forward control+alt+l to the client
when i want to lock my screen i press and hold control+ alt and tap K and L after each other
it is not ideal but at least i can simply lock both clients

lets hope it will be a built in option soon

**Comment by nbolton** [comment]
@koos147 Nice workaround!

**Comment by yeknomerif** [comment]
+1

**Comment by mberger-git** [comment]
+1 !

**Comment by ecowed** [comment]
Could you use the same principle as predator-usb.com (and other key locking programs) - i.e you don't actually lock the client, just render it unusable. You could then have it so that when the master is lock. all clients are unusable (not sure how this is achieved mind) and then when the master is unlocked, Synergy sends a command to the clients to make them usable again? Just a thought?

**Comment by ecowed** [comment]
I have made a little EXE (so Windows only - sorry) that does what I mentioned above (kinda!). 
I put the file on the root of C, created a shortcut on my desktop and then assigned a shortcut key (CTRL + ALT + Q) and then got Synergy to pass this to the client when I press CTRL + ALT + L so to lock my client and server I press that, and then Windows + L. Then I unlock the client, and then have to press CTRL + ALT + K to unlock my client which passes F3 to the client which is the "magic" key to unlock the client - all other input on the client is blocked. 

It's not ideal, but it means I don't have to a) pass CTRL + ALT + DEL to my clients (im on a windows domain) and b) have to input my password 2 or several times. 

I've uploaded the file with a PNG extension, so just rename it to ZIP and the files are in there.

![lockerunlocker](https://cloud.githubusercontent.com/assets/15327493/11393340/1e054606-9357-11e5-864b-9faf1e5c37b4.png)

**Comment by orvarehn** [comment]
I add my vote for a universal lock / unlock mechanism.

**Comment by bilysoo** [comment]
I need this feature too. Even Input Director has the feature.

**Comment by voldi9** [comment]
+1!

**Comment by isbslagelwa** [comment]
+1 this would be great to have

**Comment by noscript** [comment]
:+1:

**Comment by skaven81** [comment]
+1 for this feature

**Comment by GabeFerencz** [comment]
I'd love to see this feature implemented!

**Comment by pdemonaco** [comment]
This feature request could not be more relevant to me - can't wait till it's on the docket.

**Comment by nxtman123** [comment]
+1

**Comment by xstnc** [comment]
+1 for this

**Comment by zbrook** [comment]
Keep in mind that WIN+L is CMD+L in OSX, so please take care when implementing for those of us -- literally dozens! -- who share keyboard/mouse between a Windows PC and a Mac.

**Comment by nlyan** [comment]
Referencing #5596

**Comment by K0HAX** [comment]
+1 I'd like to lock my OS X workstation from my Debian workstation. :)

**Comment by chopskxw** [comment]
+1

**Comment by FatalCatharsis** [comment]
+1

**Comment by hansdg1** [comment]
I see that back in August @nbolton added this to "priority-next". Is there any update? I would use this so many times per day. Thanks.

**Comment by Flos** [comment]
+1 for this, locking and unlocking all connected workstations at once would be nice.
I use "MacOS | MacOS | Windows", also starting/stopping the screen saver at the same time would be nice.

**Comment by bcjordan** [comment]
Using Windows as a host machine with an OS X client and using CMD + L to go to location bar in a web browser ends up (1) locking the Windows screen, (2) putting the Synergy connection in a very odd state, (3) being unable to log back in to Windows or use mouse effectively on the OS X client.

It'd be great if there was some way to disable the locking behavior but still forward the CMD + L, or short of that a way to just disable the shortcut.

**Comment by BlueWombat** [comment]
I'm having the problem that I can't lock Windows 10 clients at all with Synergy.

When I press Win/Super+L, that's is sent directly to the server.

If I'm pressing Ctrl+Alt+Break on a client, it gives me a menu from where I can lock the client, but then client disconnects from the server, and sends the cursor back to the server. This leaves me with only option for locking, to having to press Win/Super+L directly on the laptop keyboard of the client.

I've tried the hack by manually editing the config for the Synergy server, and through there mapping Ctrl+Alt+L to Super+L, but that just doesn't do anything on the client.

So I would love to see some progress on this, and possibly an ETA of implementation.

**Comment by oldjamey** [comment]
For those who are having issues locking an OS X client from a Windows server, I'm sure there's probably an easier way, but I did the following (it's a little lengthy, because I could never get the default OS X keyboard shortcuts to work correctly):

Download/install Quicksilver on the OS X client: [https://qsapp.com/](https://qsapp.com/)

Create a shell script in Terminal:
`#!/bin/bash`
`/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend`
...and save it as Lock.command

Create a trigger in Quicksilver, and set the action/item to open Lock.command.
Set the keyboard shortcut to something like Ctrl+Alt-L.

Back in Synergy, create a keyboard shortcut for Ctrl+Alt-L to execute Ctrl+Alt-L on the OS X client.

Bingo bango.

**Comment by salem83** [comment]
+1

**Comment by cmellwig** [comment]
Please consider those of us, who need to use WIN(Super) + L regularly on non Windows clients

**Comment by K0HAX** [comment]
It could be made a configurable option or key binding. :)

**Comment by arrayown** [comment]
What I noticed is that if I press SUPER+L on the client, it will lock both the client AND the server. I'm using Win10-64bit as server and Ubuntu 16.04-64bit as client. Hope this helps someone.

**Comment by arthurspa** [comment]
+1

**Comment by fiasko** [comment]
For me the Client Super+L didn't work. All I get is the server will lock. Client doesn't respond to the command at all.

1+ for this feature!

**Comment by Svarten** [comment]
Mine actually does this if I have the mouse on the slave machine when doing it.

**Comment by michaelh99** [comment]
+1
I'm running a win7 host and win10 client and Sup+L only locks the host.

**Comment by rwoloszyn** [comment]
+1

**Comment by coma-toast** [comment]
+1

**Comment by zrajnai** [comment]
+1 I LOVE synergy, but this is actually one of the reasons I had to switch to Stardock's Multiplicity
Not only does it lock both of my Windows pc's automatically, but also unlocks the client (you have to supply the password in the configuration though)

**Comment by hsteckylf** [comment]
+1

**Comment by mshieh** [comment]
+1 Yes

**Comment by adam-wood** [comment]
+1

**Comment by hansdg1** [comment]
+1

**Comment by Poeschl** [comment]
![If You could use the +1 reaction of a comment instead of sending annoying mails out, THAT WOULD BE GREAT](https://i.imgflip.com/1maj8q.jpg)

**Comment by Gotcha007** [comment]
+1 THIS IS A MUST.
Windows - MAc - Linux

**Comment by paul-suarez** [comment]
Author: Rob Yardman
Date: 2017-05-05 06:33

Both client and server runs with Windows 7 with the Standard English QWERTY keyboard. Server is a docked laptop with dual monitors and client is a desktop with one monitor.

**Comment by anniesbbs** [comment]
adding a want to this forgotten feature.

**Comment by stphnlee** [comment]
I have a macOS 10.12 server with a Windows 10 client and a Windows 7 client. The Windows 10 client will lock with the Mac, but not Windows 7.

**Comment by skurudo** [comment]
+1, 
miss this feature much ;-(

**Comment by gbirchmeier** [comment]
Can I vote for the opposite of this?  When the mouse is on the Mac-as-client side, I want command+l to not lock anything and just be handled by the Mac.  This hotkey is used by browsers and editors on Mac.

Ideally, command+l could be configurable.

**Comment by paul-suarez** [comment]
@gbirchmeier is it locking something while your mouse is on your Mac's (as a client) screen?

**Comment by gbirchmeier** [comment]
@paul-suarez It doesn't matter which side the mouse is on.  If I hit command+l, the Windows machine (the host) will lock.  It seems that Windows-as-host gets first dibs on this keystroke, regardless of where the mouse is.

**Comment by XiaoningLiu** [comment]
COMMAND+L is used for browsers to locate to address bar in MAC OS. When my mouse is in MAC OS side, press COMMAND+L, the Windows server will lock, instead of locating to my Mac's Chrome address bar.

**Comment by s2patrick** [comment]
+1 for that feature

**Comment by frogstarr78** [comment]
Ditto +1

**Comment by jonny190** [comment]
+1

**Comment by smipi1** [comment]
+1

**Comment by asriznet** [comment]
Has anyone figured it out?

Mac OS High Sierra has included a native keyboard shortcut key to lock screen in the latest update: Control + Command + Q

I have a Windows 10 host and a Mac OS Client and would like to lock both screens at the same time if I can.

Adding keystroke entry, I am able lock my mac but it does not lock the Windows Host.
The only way I can lock my windows host is by pressing Windows + L

But If I added Windows + L as a keystroke and map it to Control + Command + Q for my Mac OS client, it only locks the Windows Host and did not send it to the mac.

Anyone able to map hotkey to lock the screen of a Windows Host?

**Comment by alexforencich** [comment]
This could be implemented by sending keypresses to specific screens, not just the current screen.  That way, pick whatever key command you want to lock, and then configure the proper action for each screen.  Right now, it seems hotkeys can only be sent to the current screen, with some filtering, which I guess is nice for remapping, but it could be a bit more general.

**Comment by zed0** [comment]
If anyone's looking for a workaround for this on Linux to Windows, this my current single shortcut set up:
- An autohotkey script running on Windows (the client) containing `^#l::DllCall("LockWorkStation")`
- A window manager hotkey under Linux (the server) which calls `xdotool sleep 0.1 key --clearmodifiers control+alt+l ; xscreensaver-command -lock`
- A Synergy configuration containing `keystroke(Alt+Control+l) = keystroke(Super+Control+l, *)`
