### ISSUE TITLE
Synergy blocks input to VMWare guests

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3136]
**Imported issue:**
- Author: Nicholas Twerdochlib
- Date: 2012-05-05 20:34:38
- Legacy ID: 3206
- Version: 1.4.17

**Steps to reproduce:**  
1. Synergy server running (same system as VMware Workstation  
2. Attempt any interaction with a VM console  
3. Client is connected, but this test is done on the server  

Expected: Ability to interact with VM  
Actual: VM console will not take any input, mouse or keyboard  

**Versions (Synergy, OS):**  

Server: 1.4.8 Beta 32bit & 64bit  
Client 1: 1.4.8 Beta   

**Workaround:**  

Have tried several workarounds posted, none have worked

**Comment by vbasarkar** [comment]
I upgraded to latest synergy version on server and client and unchecked elevate button. Now I am able to access VM console using keyboard and mouse shared via synergy without any issues. If I check elevate button I can reproduce the problem described above.
HPV: ESXi 5.1.0, 799733
vSphere Client: 5.1.0, 786111

**Comment by dubuaych** [comment]
For what it's worth, I just built from the Synergy repository (synced yesterday) and I'm running VMware (multiple Win7 guests) on my master machine (Windows 7 x64) and I am not having and problems. I haven't tried VMware guests on a Synergy client (to be Win 8.1 and Debian) as yet, but will soon (I have to re-stage my work laptop tomorrow). I'm running VMware Workstation 9.0.3. "Elevate" un-checked, but I have only been using Synergy for a matter of hours so have not had a need to mess with too many settings. Will keep an eye out for any issues.

**Comment by andrewr01** [comment]
Had the same problem this morning with VMware Workstation 11 on Windows 8.1 Update 1, Synergy 1.6.2 Server. Stopped the Synergy service, then restarted and problem went away. Synergy "Elevate mode" not ticked, and "Enhanced virtual keyboard" set to "off" in VMware VM settings.

**Comment by dubuaych** [comment]
I've been using Synergy 1.7.0 now for well over a month, probably two (well yeah two months; last post was 16th Jan), with VMware Workstation and haven't had a problem with VM input; I am typing this on a VM right now. I do 95% of my work on VMs so it would really screw me up if it didn't work!

Win7x64 - VMware Host - Synergy Server
Win 8.1 x64 - Synergy Client - VMware Host.
Various VM guests - Win7, Linux.

Currently using VMware 11.1, but have been using 9.0.3 prior to that.

The only time I found VM input blocked (on the Synergy Server) is when I tried to run Synergy from scripts that are aimed at avoiding the Windows 8.1 focus issue.
~~~~
https://github.com/synergy/synergy/issues/4349
~~~~

Happy to provide any additional information if it is needed.

**Comment by dmarsh26** [comment]
Have you got a 4k monitor ?
Do you have VmWare doing resolution scaling ?
I think that was probably most of the issue, Synergy had the mouse co-ordinates 200% off...

Date: Wed, 18 Mar 2015 00:35:21 -0700

**Comment by dubuaych** [comment]
@dmarsh26: I'm running 1920x1200 on 24" monitors, mostly. Nothing super high res, or super new. I always fit guests to the host; not the other way around.

**Comment by foulowl** [comment]
Same issue. Debian 8 server, Ubuntu 15.10 client. Running vsphere on the client with chromium.

**Comment by IX9** [comment]
Same issue. Also appears to be sporadic that VMWare doesn't capture the mouse/keystrokes and varies between multiple VMs too (one VM will be fine, the other will ignore)

Synergy Server: 1.7.6
Client: 1.7.6 (if it matters)
VMWare Workstation Pro 12.1.0 b3272444
OS Windows 10 Pro 1511 Update

**Comment by MrLundy** [comment]
I have the same issue, I uninstalled Synergy and the following problems went away:

- Mouse would not stay in a game window or fullscreen game with multiple monitors.
- Minecraft and world of tanks could not keep cursor centered on screen in any mode. Minecraft was completely unplayable.
- VMware inputs almost always did not work. I would connect a second mouse and give it to the VM in order to have any input. (linux guests, BSD guest, windows guests.)

These issues happened without Synergy actually running, just installed. 
Windows 10 pro, Synergy 1.7.6

**Comment by c05m1x** [comment]
Still a bug. What's the ETA to have this bug solved?

**Comment by RrodGtHb** [comment]
I can confirm that this is true. I could not get virtual box to accept mouse input and I am was using synergy at the time. The virtual box was running on the synergy server machine. The version of Synergy I'm using is 1.3.8. Upon quitting Synergy now the virtual machine responds as expected.

**Comment by scottresnik** [comment]
This seems to effect me as well.  I've noticed it only seems to effect VMWare after a reboot.  If I shut synergy down, then I can access my Guest machines again.  Even if I start synergy back up, they are fine.  My specs are below.

Synergy Server: 1.7.6
VMWare Workstation Pro 11.1.4 build-3848939
OS Windows 10 Pro 1511 Update

**Comment by Shivaess** [comment]
This impacts me as well.

Exact same specs as above:
Synergy Server: 1.7.6
VMWare Workstation Pro 11.1.4 build-3848939
Running on Windows 10 Pro

**Comment by rlaban** [comment]
Same when using Synergy server on Windows 7 and VMware vSphere webclient console.

**Comment by pikapp1977** [comment]
Same issue for me using Synergy Server v1.8.2
Windows 10
VMWare Workstation 12.1 Build 3272444 running Server 2012R2 x64 Guest OS
Issue also occurs within Server 2008R2 Guest OS

**Comment by mmifsud** [comment]
I solved the issue above with Synergy 1.7.6 by enabling the option "Don't take foreground window on Windows servers" from the Advanced server settings tab.
