### ISSUE TITLE
Quote deadkey doesn't work on Mac OS X

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3188]
**Imported issue:**
- Author: Eduardo Habkost
- Date: 2012-06-23 19:30:15
- Legacy ID: 3258

**Steps to reproduce:**
1. Run client and server on OS X Lion, using U. S. International keyboard layout.
2. Focus on the client
3. Type ["]+[space] to get a quote character

Result on the client log:

```
DEBUG1: recv key down id=0x00000022, mask=0x0000, button=0x0032
DEBUG1: mapKey 0022 (34) with mask 0000, start state: 0000
DEBUG1: key 0022 is not on keyboard
```

**Versions and operating systems:**

Synergy from SVN trunk (revision 1464)

**Temporary workarounds:**

It works if I make the following code change:

```
--- a/src/lib/synergy/CKeyState.cpp
+++ b/src/lib/synergy/CKeyState.cpp
@@ -36,7 +36,7 @@ static const KeyID s_decomposeTable[] = {
        0x02db, 0x0328, 0x0020, 0, // ogonek,       dead_ogonek,      space
        0x02c7, 0x030c, 0x0020, 0, // caron,        dead_caron,       space
        0x02d9, 0x0307, 0x0020, 0, // abovedot,     dead_abovedot,    space
-       0x02dd, 0x030b, 0x0020, 0, // doubleacute,  dead_doubleacute, space
+       0x0022, 0x030b, 0x0020, 0, // quotation,    dead_doubleacute, space
        0x02d8, 0x0306, 0x0020, 0, // breve,        dead_breve,       space
        0x00af, 0x0304, 0x0020, 0, // macron,       dead_macron,      space
```

But I know it's not an appropriate fix because some users may have keyboard layouts where the "dead doubleacute" key actually generates a double acute (instead of a quotation mark).

**Additional comments:**

It seems to be hard to fix this without making the OS X code generate the dead key combinations while taking the system keymap into account (instead of using the static s_decomposeTable entries).

Right now any dead key in OS X that generates a U+0022 char hitting the space key will be mapped to the ambiguous dead_doubleacute key ID (that is at the same time used for U+0022 (quotation mark) and U+02DD (double acute).

**Comment by SteveClement** [comment]
The premium vote stuff seems to have gone :(

I can confirm that this still doesn't work on 1.7.2 

What does work is: `+a -> à

But the tilde, which is on that key too, does not…

**Comment by the-wes** [comment]
SHD-436

**Comment by gildas** [comment]
I think this is still not fixed in 1.7.5

**Comment by SteveClement** [comment]
backtick (`) works tilde does not.
The double quotes and accent key doesn't (' && ")

This obviously seems to be no rush for the mostly non-international keyboard users ;)

**Comment by the-wes** [comment]
ticket # 4786

**Comment by iMilnb** [comment]
Still no news on that issue? I am facing it for a couple of months, and it is really annoying...

**Comment by nlyan** [comment]
@iMilnb : sit tight, we're aware of the myriad of keyboard issues and it's high on our todo list.

**Comment by iMilnb** [comment]
@nlyan thanks for the heads up, and good luck, I presume keyboard mapping issues are not the easiest nor the more interesting to fix

**Comment by giammin** [comment]
duplicated? https://github.com/symless/synergy/issues/4
