### ISSUE TITLE
Repeated message "ipc connection error, connection refused"

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3514]
**Imported issue:**
- Author: Ben Anderson
- Date: 2013-04-21 21:25:30
- Legacy ID: 3584

Windows 7 x64 host, Windows 8 x64 client. They're both doing it. Every second or two, I get these two messages in the Synergy console. There SHOULDN'T be a service running and it SHOULDN'T be trying to connect to it.

I need to be able to readily stop Synergy as it interferes with too many games, but currently the "stop" functionality is broken in service mode (#3583). Therefore, legacy mode for now.

**Comment by thanhnamit** [comment]
Had the same problem on Windows 8. The service was crashed somehow. I also config the Recovery tab in service details so next time if the service fails, it will automatically restart again.

**Comment by vfaler** [comment]
Thank you for the "Recovery" tab tip thanhnamit.

**Comment by milton-rodriguez-uruit** [comment]
The service crashes also if you change your ip (like unplug the ethernet to go to wifi, and then reconnect)

**Comment by vfaler** [comment]
Experiencing reconnect service crash now. Thanks again for the knowledge.

**Comment by SykApps** [comment]
I'm getting this issue and am unable to uninstall or repair. Any ideas?

**Comment by AaronLS** [comment]
This happens to me if the Synergy service is not running.  Usually if it has crashed or I had to kill it because it froze up my mouse/keyboard.

WORKAROUND: Ctrl+Shift+Esc to open task manager.  Switch to the Services tab and find Synergy service, right click, click Start Service.

That's in Win7 professional.  You can usually find Services under the Control Panel somewhere under Administration.

I'm not sure why the "Start" button in the Synergy GUI doesn't attempt to check if the service is running and start it.

**Comment by 1j01** [comment]
Trying to start the service from "Services" (part of "Management Console") since I have Process Explorer which doesn't have a Services tab, I got this error:

```
---------------------------
Services
---------------------------
Windows could not start the Synergy service on Local Computer.



Error 1067: The process terminated unexpectedly.


---------------------------
OK   
---------------------------
```

**Comment by 1j01** [comment]
Restarting the computer worked.

**Comment by hattable** [comment]
Still an issue. I'll usually stop the service / start it while the GUI is closed and the tray icon has been closed. Then after starting it back up you have to deselect the certificate option again on both clients and it _sometimes_ works. Fast mode so you don't have to open services.msc is in a cmd window:
>sc stop synergy
>sc start synergy

**Comment by TheMadComputerScientist** [comment]
@nbolton and @AL Pham - You guys are absolute life savers! Thanks you!

**Comment by GaryPearman** [comment]
It's weird that it worked so well in previous versions, 1.7.5 gives me fits. Tried starting from Task manager, says I haven't the foo. Went thru services, it said "Auto" & was stopped. Started and we're back. Why oh why. Glad it works now. We'll see how long that keeps up.

**Comment by cognifloyd** [comment]
I hit this issue when I built my own copy of synergy. I didn't use the installer, so the daemon wasn't added as a windows service. Following http://stackoverflow.com/a/3582179 I opened a privileged CMD, and ran 

C:\Windows\System32\sc.exe create synergy binPath= "C:\<my path to synergy sources>\bin\Release\synergyd.exe"

And then, I have to start the daemon whenever I want to use it: "net start synergy"

This gets rid of the IPC error for me and allows me to use the apps.

**Comment by Gubith** [comment]
Ran fine for a year, then I switched the client PC and got the "ipc connection error"
I'm still on 1.63, it says 1.7.5 is out.

I tried a few things first...
Exit synergy
sc query synergy    (not running)
sc start synergy     
sc query synergy   (running)
Open Synergy app, igc connection error

Open synergy service, click start.
Open Synergy app, good.

Similar issues in the long past fixes included:
Only have one synergy running, ie: launching from shortcut when it's hiding in the system tray.
Reboot, ofc.
Reinstall / repair synergy

Like windshield wipers, needs a little oil sometimes.

**Comment by joubertredrat** [comment]
Hi,

Since 1.7.6 version, same problem here, but starts only after I suspension my notebook. Then I need to restart notebook to synergy works again. I tried to start Synergy proccess, but always start and stop.

**Comment by stefan123t** [comment]
@nbolton, your tip of starting the synergy service worked for me. Thanks a lot!

Start "Windows Task Manager"
Select "Services" tab
Search for "Synergy" under "Name" column (the "Status" col should show "Stopped").
Right-click on "Synergy" and select "Start Service"

**Comment by joubertredrat** [comment]
My client log about this. I think that problem have relation with memory. Because I have 16Gb RAM on my notebook, because when it stopped working, my memory consumption was 13Gb RAM, then Synergy service fails to start again. After this, I closed one mine browser and memory consumption goes to 9Gb RAM, I tried to start Synergy service and started without problems.

https://gist.github.com/joubertredrat/7d0c5e7e192ba5a732e152e75fee5524

**Comment by joubertredrat** [comment]
Haha, or not. On second time, was possible to start Synergy only after I closed my Opera beta browser. I will test more.

**Comment by joubertredrat** [comment]
Hi guys,
Confirmated, in my case I don't know why, but Synergy don't like opera, it prefer Firefox.

https://vimeo.com/180341799

**Comment by tarvos21** [comment]
Uninstall synergy on windows 10, then install again, it works good after that, connected to my Ubuntu synergy server, yep!

**Comment by matiferrigno** [comment]
Hi, 
Today I've the same problem.
I can solve it enabling the "Synergy" service in Services Manager Windows.

1) Open services.msc and then change the properties of "Synergy" service. 
2) Select Automatic type of start and click start button.
3) Try to use Synergy normally.

This worked fine for me. I hope be helpful.

**Comment by CMCDragonkai** [comment]
If the synergy service can be set to restart automatically, this problem should be solved.

**Comment by Johnthetrader** [comment]
Every few months I get these errors for no know reason. Then I uninstall- reinstall Synergy disable firewalls on both PC's try the start service tip but nothing gets things working again. Then just as I'm about to revert to 2 mice and 2 keyboards things start working through nothing I've done. I got up early today but just spent 3 hours on this and now giving up. Synergy's fab when working but that's not today.

**Comment by CMCDragonkai** [comment]
I found this happening until I found I had to restart the synergy service on the windows host. For some reason synergy processes crashed but the windows service wasn't starting when trying to start synergy again.

**Comment by Johnthetrader** [comment]
I've tried that and all the other tips in the forum. I've even tried the
32bit version on my Windows7 64 bit. Next I'll reinstall an earlier version
I have stored..Life should not be this difficult!!!

  _____

**Comment by rtc1880** [comment]
Hey Guys.

I've had this problem several minutes ago with the newest Synergy 1.8.8-stable-c30301e 64bit on Windows 10 Version 1703 Build 15055.0 64 bit.

Long story short: Manually add a Firewall Rule IN and OUTgoing for Port 24800. Voila!

Hope this helps someone out.

**Comment by CMCDragonkai** [comment]
Why do you need an outgoing rule?  The default network profile on Windows
allows all outgoing ports.

**Comment by rtc1880** [comment]
Yes, thats right. Windows SHOULD allow it. But it don't do it!

When i manually add a rule for a port, then i always set IN and OUT for troubleshooting.
Synergy is in the exception list of the Windows FW but it don't work -> and that is the point, why I sometimes hate Window. It should work but i don't  do it for no fucking apparent reason.

So i added both ports and now it works.
I thought this could help someone.
