### ISSUE TITLE
Hotkeys broken on Mac server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3705]
**Imported issue:**
- Author: Karl Blessing
- Date: 2013-10-21 01:09:56
- Legacy ID: 3775
- Version: 1.5.0
- Server: OSX
  - Client: Windows

**Steps to reproduce:**
1. Use config below steps
2. Start Synergy
3. Move the mouse to the Client named Windows
4. Press Option+A
5. Press Option+B

**Config:**

```
section options:
  keystroke(super+a) = switchToScreen(OSX)
  keystroke(super+b) = switchToScreen(Windows)
```

**Expected Result:**

Option+A should move the cursor and focus to the OSX Server

Option+B should move the cursor and focus to the Windows Client

**Actual Result:**

Option+A moves the cursor and focus to the OSX Server

Option+B does nothing.

**Notes:**
1. This worked properly in 1.4.12
2. In the config file, the modifier keys are named as follows:
   - Control = Control
   - Option = Super
   - Command = Alt
3. The Meta key is not found on a Mac keyboard as far as I know.

**Comment by louwers** [comment]
Happy to find out this is being worked on.
Running Synergy on OS X 10.8 and the hotkey functionality appears to be completely non-functional.

**Comment by miraculixx** [comment]
:+1: same thing here OSX 10.9.5, Synergy 1.7.3.

**Comment by upq** [comment]
Same issue, OSX 10.8.5 server 1.7.4 (Nightly Build) , Ubuntu 15.0.5 Client .
Now here is something interesting , that if I set the hotkey to a mousebutton it works on OSX.
I think the problem is with the OSX keyboard shortcuts setting, the OS ignores them or executes them differently maybe.

**Comment by victorquinn** [comment]
:+1: same thing here, just spent awhile troubleshooting before turning to Google and finding this issue. Using Synergy Pro v1.7.4 on OS X 10.11

**Comment by upq** [comment]
If Anyone wants a kind of temporary fix here is a .conf that works

``` R
section: screens
	Mac:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
	Ubuntu:
    # This makes the Command key a Control key on Ubuntu 
    # so you can basically use the same mac shortcuts you 
    # you are used to
		ctrl = super
		super = ctrl
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
end
section: links
    # I set them both to right of each other so I can switch
    # with one command
	Mac:
		right = Ubuntu
	Ubuntu:
		left = Mac
		right = Mac
end
```

``` R

section: options
	relativeMouseMoves = true
	screenSaverSync = true
	win32KeepForeground = false
	switchCorners = none 
	switchCornerSize = 0
    # Set this as a mouse button
    # So this is (cmd+option+leftclick)
    # assuming you are using a Mac keyboard
	mousebutton(Super+Alt+1) = switchInDirection(right)
end
```

**Comment by Jamiermusic** [comment]
Any update on this? I'll be using the config script for now, but would love a native fix

**Comment by LoganBarnett** [comment]
FYI I have manifested this issue on OSX 10.11.1 using Synergy Pro 1.7.5.

**Comment by ekondrashev** [comment]
The issue is really irritating, how can we increase the priority?
10.11.1/1.7.5

**Comment by manijak** [comment]
@nbolton  @the-wes 
Please guys, just bought a license, and this is making the software useless! Please fix the issue.
Thanks

**Comment by sperberAfop** [comment]
Apple is listed as customer on your side, but this quiet important feature doesn't even work on osx - since 2013 - let's hope that changes soon...
(Other than that - great work)

**Comment by jujes** [comment]
Please fix the issue...

**Comment by sperberAfop** [comment]
@jujes you should ask @nbolton or @the-wes 
My solution right now are 2 keyboards and 2 mice - aka NOT using synergy at all, although I bought the pro version...

**Comment by jptaranto** [comment]
Would be good to look at a fix for this.

**Comment by phonemyatt** [comment]
It is really some annoying bug...I found out after purchase...

**Comment by robbietjuh** [comment]
Count me in on this one.

**Comment by fhill122** [comment]
Can't believe still seeing no progress on this bug after such a long time.

To me, using hotkey to switch screen is a much better way than moving mouse to edge.

I can confirm upq's workaround works, mac only see hotkeys with primary mouse click. But this causes problems as many times the click is still seen by mac system while switched to client, so when moving mouse in client screen, the mac server side acts as being selecting something.

**Comment by spurin** [comment]
Issue still persists with synergy-master-stable-d196ec5-MacOSX1011-x86_64.dmg on OS X 10.11.1, works fine when focus is in other client (windows, ubuntu) but fails when on mac server.  With DEBUG2 enabled, the keypress is being captured but the hotkey action is not activating.

Like the others above, would appreciate if this is resolved, purchase order #204299

Thanks

**Comment by spurin** [comment]
@nbolton @the_wes   Earlier on in this discussion, some code snippets were posted with a patch that worked for a particular user.  I am going to fork the current release and use this as a starting point.  Any known gotcha's?  I can see that the snippet was posted back in 2014-06-30 so am assuming that it either had side effects or has slipped through the net :)

**Comment by spurin** [comment]
Pull request added to resolve this at: https://github.com/symless/synergy/pull/5522

For those who want to use a version with the fix applied whilst waiting for it to be resolved in master, see bin.zip on my forked repo: https://github.com/spurin/synergy/blob/master/bin.zip

It is the output bin directory zipped up, inside is Synergy.app alongside the individual executables.  Compiled on Mac OS X, El Capitan, Synergy version is 1.8.1-stable-d196ec5

**Comment by fhill122** [comment]
@spurin's fix works perfectly on my machine

**Comment by nlyan** [comment]
The impact of this change has to be determined before we commit. We'll look in to it.

**Comment by spurin** [comment]
Can we please put a marker on this for a future release, i.e. v.1.8.4-stable or v.1.8.5 milestone?

**Comment by politicus** [comment]
Using Synergy 1.8.4 (Build Oct 11th, 2016). 
Hotkeys are still not working on Mac server.

**Comment by newgoliath** [comment]
Same here.  Paid support.

**Comment by spurin** [comment]
@nbolton contacted me via email as I had a support case open for this issue, for reference it said the following "Hi James, I'm really sorry for the delay.  I have prioritized your ticket, it's now high priority.  You'll hear from us soon.  Thanks, Nick".  So, fingers crossed, the fix may make it into 1.8.5

**Comment by spurin** [comment]
Merged upstream in pull request, resolving the conflict with the filename change for OSXScreen.mm

**Comment by Celant** [comment]
Anyone still having this issue, can you please try this build from @spurin?
http://symless.com/nightly?filter=f4d9faa

**Comment by spurin** [comment]
@louwers @miraculixx @upq @victorquinn @Jamiermusic @LoganBarnett @ekondrashev @manijak @sperberAfop @jujes @jptaranto @phonemyatt @robbietjuh @fhill122 @xwvvvvwx @newgoliath 

Please see http://symless.com/nightly?filter=f4d9faa for nightly build with included fix, please confirm resolution.  I will test tonight when home.

**Comment by alexciarlillo** [comment]
Working for me.

Host: Linux Mint 18
Client: Linux Mint 17

**Comment by robbietjuh** [comment]
Works perfectly fine. Thanks, @spurin!

Host: Mac OS X 10.11.6
Client: Windows 8.1

**Comment by forairan** [comment]
Not working for me.

Host: OS X 10.11.6
Client: Windows 10 (10.0.14393)

**Comment by politicus** [comment]
Not working for me.


Host and Client: Mac OS X 10.10.5.


Adding a keyboard shortcut makes it impossible to switch from one computers
to the other.


On 20 Nov 2016 at 03:53:15, Devin Ryan (notifications@github.com) wrote:

Not working for me.

Host: OS X 10.11.6
Client: Windows 10 (10.0.14393)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/symless/synergy/issues/3705#issuecomment-261754921>,
or mute
the thread

**Comment by newgoliath** [comment]
Works for me:

Host: MacOS Sierra Version 10.12.1
Client: Windows 7 Enterprise, Service Pack 1

**Comment by spurin** [comment]
@politicus, apologies, missed you off the roll call earlier when doing the list of people who've had the issue, some questions ... will try and recreate your environment if this issue still persists.  

Did you stop/start the server after applying the hotkeys?  

What are you using as the hotkeys for switching (I use the FN F combinations keys, not sure if that makes a difference, please try if using different).  

Can you confirm the versions for server/client (did you use the nightly build for all?)

Lastly, could you please paste the log output when you press the hotkeys

**Comment by manijak** [comment]
Works half-way here. 
Host: macOS Sierra Version 10.12.2 - Synergy build 1.8.6-rc1-f4d9faa
Client: Windows 10 Pro (1607) - Synergy build 1.8.6-rc1-f4d9faa

Restarted both Synergy clients, restarted both machines. 

* Switching from macOS to Win10, works fine via hotkey. (Using F16 on mac-keyboard). 
* Switching from Win10 to macOS, does not work. (Tried all different keys, none work).

**Comment by spurin** [comment]
@manijak @politicus - Commonality in that you are both using Windows 10.  Most of the success cases have been without Windows 10.

@forairan - You're the exception, you had success with Windows 10, did you try the hot keys in both directions?

**Comment by politicus** [comment]
I am not using Windows 10 as I only use Macs.

Le mer. 23 nov. 2016 à 17:39, James Spurin <notifications@github.com> a
écrit :

**Comment by spurin** [comment]
I just installed the nightly build (1.8.6-rc1-f4d9faa) provided in the links above across the 4 systems I use:

Type - OS - Hotkey
==============
Server - Mac OS X 10.11 - Function F12
Client - Mac OS X 10.11 - Function F1
Client - Windows 8 - Function F2
Client - Ubuntu 16.04 - Function F3

I can switch between any of the combinations above without issue.

@politicus - Your reply above had some of the context from Devin Ryan where it mentions Windows 10, hence the confusion.  I'm on El Capitan so slightly newer version but no issues for me.  What hotkeys did you use (maybe try the Function F keys).  Could you please paste the log window from both the server and client when you press the hotkey combination if the problem still persists.

@manijak - I have a Thunderbolt boot disk in which I can boot Windows 10 from my Macbook (what I use as the client), I'll see if I can get that working next

**Comment by politicus** [comment]
@spurin Sorry for the delay in my reply. I didn't have access to my second Mac. 

Working like a charm! Thank you!

**Comment by brusinow** [comment]
I just purchased/installed Synergy today for the first time and realized that I am encountering these same problems - I can't get a single hotkey command to work when focus is on my OS X server (it works coming back from my windows machine). We're way past that nightly build that was working for  a few people so I'm surprised to be having these issues. Here are my specs:

Server: MacBook Pro running OS X Sierra 10.12.2, Synergy 1.8.6-stable-2ab21aa
Client: Dell Latitude running Windows 10, Synergy 1.8.6-stable-2ab21aa

Any help would be much appreciated - I only use one display with an HDMI switch so hotkeys are very important to me.

**Comment by spurin** [comment]
Hi @brusinow

I also use this with a HDMI switch so have the same issues and concerns, hence the pull request that I created with the fix for this problem.  The version you're using is broken, can you uninstall it from both the Mac and Windows and reinstall 1.8.6-rc1-f4d9faa on both of them, available from the following:

http://symless.com/nightly?filter=f4d9faa

Please report back status.  

This needs to be merged into master going forwards for it to be available by default.  We're almost there on this 👍

**Comment by brusinow** [comment]
@spurin,

It does not look like that nightly build is still available at that link - any other suggestions of how I can get it?

-Brent

**Comment by spurin** [comment]
@celant - can you please advise and reopen the nightly build for this or merge to master?  There's positive feedback in many areas on this already, this discussion, the related discussion and in the pull request.  I think it's time for this to go live now don't you?

@brusinow - fearing these might go away, I downloaded them all ... Will share links from  Dropbox for these tomorrow.

**Comment by spurin** [comment]
et voila - please see http://www.twitchy.net/Synergy/

**Comment by brusinow** [comment]
Thanks @spurin,

First off, thank you!

I installed the above mentioned nightly build on my machines and am still not able to use any key commands (from my Mac server) other than main keys like Alt, Control, and Shift. I'm currently using these three together to switch back and forth between my two machines but I'm looking to ideally use function keys.

If I'm running OSX Sierra (10.12.2), is the unspecified osx version acceptable? That's the one I'm running.

**Comment by spurin** [comment]
@brusinow, are you using FN and F keys or just pressing the F keys, I use the function F keys (see my earlier comments) without any issues.

**Comment by spurin** [comment]
@brusinow, just to also note, I implicitly use the nightly build relating to my release not the unspecified one

**Comment by brusinow** [comment]
@spurin Thanks for the followup, I tried reinstalling the specific 10.11 build and still couldn't get it to take numeric FN + F key commands. Fortunately I only have two monitors, so I ended up just using CTRL + OPTION + SHIFT as my switch command with switchDoubleTap set to 10ms. Seems to be working well so far.

**Comment by spurin** [comment]
@brusinow, thanks for following up.  At least it's working now which is something and it's great to have a confirmation of Windows 10 success.

@celant - can we get this in master?  That covers successful use cases for all platforms now.

I think the issue with your choice of hotkeys is something else.  Are you using a Mac keyboard here?  Does it actually register the key as FN and the F key on the input?  May seem like a lame question but have you also fully stopped and started server after applying (worth possibly trying a kill of synergy and restart also).  As I say, I use a pretty similar configuration to yours and my use case is the same.  FN F keys work perfectly.  Might be worth sharing your config file with the entries if you still want to pursue it further.  Also, the log files from the server/client when you press those keys.

**Comment by spurin** [comment]
@brusinow ... Thinking about it, it may be the switchDoubleTap, I'm using the standard key press option with F keys assigned to each machine

**Comment by manijak** [comment]
Issue with macOS as server and Win10 as client still present. Cannot switch back to mac from Win10.

**Comment by spurin** [comment]
Hi @manijak, can you please share your configuration file or at least the hotkey section from the macOS server.  Some people on this discussion and the related have expressed success with Windows 10.  Some questions.  What are you using as the hotkey selector?  Is this still whilst using a mac keyboard?  could you try one of the Function keys from F1 to F12, trying with FN+F key on the keyboard, can you also try the combination that @brusinow reported success with on Windows 10 (CTRL + OPTION + SHIFT).  Let's see from there, otherwise it might be worth going down the verbose logging path to capture what exactly is happening on the server/client, when you press those hotkeys.

**Comment by KjellMorgenstern** [comment]
Just updateing: No reaction for keyboard definitions on the server (tried F14 and F15)

Server OS X El Capitan
Client maxOS Sierra
Synergy 1.8.7-stable-9799e96 (19.January 2017)

**Comment by spurin** [comment]
@KjellMorgenstern : Same combination works for me without any issues.  Can you share your configuration file please and I'll compare, see if we can work out why mine works and yours doesn't.

**Comment by KjellMorgenstern** [comment]
@spurin : I can confirm the patched version works. I replaced 1.8.7 with synergy-pr-5522-hotkey-rc1-f4d9faa-MacOSX1011-x86_64.dmg on my server. The client is still running 1.8.7. I did not modify the configuration, just started 1.8.6-rc-f4d9faa from 18.Nov.2016, and it worked.
My configuration is currently "shift-f15" switch to client "f15" switch to server. I did not find a readable configuration file, my configuration was created with the frontend, and is probably stored in a plist file (or did I miss something about the config file?)

**Comment by manijak** [comment]
@spurin I can also now confirm that the patched version works in combination with macOS Sierra and Windows 10. I am using the following hotkeys: 
"Shift-F13" = switch to Win10 (client)
"Shift-F15" = switch to macOS (server)

Have no idea why it didn't work earlier. Could be that I had a beta version of Sierra OS.

**Comment by spurin** [comment]
@Celant @nbolton @nlyan @XinyuHou  : Can we please push forward to get this into a public release now, we've got a general consensus with the feedback above and also the positive feedback on https://github.com/symless/synergy/pull/5522

There's no reason not to get this in and it's been outstanding no for years!

People like myself are having to rely on the 1.8.6 nightly build and one that I'm having to host for myself at the moment to get round what is a very frustrating issue.

Further to this, because of the release to 1.8.7, it breaks the 'Pro' functionality when having to use 1.8.6, functionality which I personally have paid for to get SSL support.  When it checks for updates it seems to disable the Pro functionality and you need to re-activate it...

I for one, want to be able to download the latest version and use it as expected.

**Comment by politicus** [comment]
@spurin You are so right about that:

>I for one, want to be able to download the latest version and use it as expected.

I lost some time understanding the Pro functionality was broken because I was using 1.8.7. 
Very frustrating.

**Comment by spurin** [comment]
In this https://github.com/symless/synergy/pull/5796 it was originally earmarked for 1.8.7 (that never happened, and then it was changed to 1.9.x beta ... not 1.8.8?).

If we're lucky, we might get it by 1.9.9 at this rate but that's looking like a big if based on current feedback and failed promises.

Can we please get this added to 1.8.8?  Very disappointing if I have to go down the route once again of compiling a release manually with this fix in order to get functionality that have paid for.

**Comment by WibbletheDuck** [comment]
Welp.  I just blew a good half hour trying to get hotkeys to work between two macs, before coming on and finding this.  Golly, will it make it to three years without a fix?

**Comment by spurin** [comment]
WibbletheDuck, welcome to the club, enjoy using 1.8.6 to get the hotkey functionality that you desire that's been broken for 2 years+

I've pretty much resigned to this not being resolved having gone through a multitude of efforts in this thread, and the others, to support this, not to mention, verifying that this works across all platforms.  I've also offered Synergy direct testing and feedback to which they've not followed up further.

Even though I paid for the product, I can't use the pro functionality as the SSL implementation in the version with the fix is flakey, not to mention the new version check seems to lose the pro functionality each time.

If it goes to 3 years without a fix, or again, a major release is made without this fix, I'll be forking my own version, with said fix, the pro functionality permanently enabled and the check for updates disabled.  I'll also be posting details of this on the thread.

Enough is enough.

**Comment by demonbane** [comment]
I can confirm that the version @spurin provided above for 1.8.6 does, indeed work. I'm connecting from OSX 10.12 for the server to a client running Windows 10 and it works fine. (except that the key-mapping UI seems to confused about which key is which, but that's fine)

@spurin thank you so much for all of your work on this and I really hope that Symless folks finally pay attention to this thread. (though, after 3 years, I'm not holding my breath)

**Comment by nomoon** [comment]
So I just purchased Synergy and this feature doesn't work? And a fix has been sitting around in #5796 with no update for 6 months?

**Comment by WibbletheDuck** [comment]
@nbolton ples

**Comment by EasyAsABC123** [comment]
@spurin i appreciate you effort and time, all the links above are broken to download this fix and like you this is a frustrating issue.  Any assistance would be appreciated.

**Comment by spurin** [comment]
I'm loathed to help out on this anymore given that Symless have made a bunch of promises that they don't keep... not to mention, being a pro customer stuck on an old release.  Very annoying that I'm more interested in helping people with this than they are.

@WibbletheDuck @EasyAsABC123 I'll help you out with links to a Mac version that has the fix, can you email me ...  its my first name which is james at my github userid dot com

**Comment by StephanX** [comment]
Still broken for me.  Definitely don't want to give up SSL for this feature, though.

**Comment by ajhsieh** [comment]
3 years since issue opened, and over 6 months with a fix (submitted by a user) sitting in PR 😒

**Comment by EasyAsABC123** [comment]
The fix provided by @spurin solved my issue, this should be merged into master...the fact that it hasn't been properly reviewed and merged can only be described as lazy and negligent.

**Comment by spurin** [comment]
@nbolton 

The update by @EasyAsABC123 again, proves this fix is valid, it is the latest version of Mac OS X as the server.  There's been plenty of time now to review this PR... now that game of thrones has finished this season, maybe give a bit of love back to your supporters and fix this once and for all?  Winter is coming...

**Comment by spurin** [comment]
Please make this a Must or at least a Should, rather than a Could - https://github.com/symless/synergy/projects/4

**Comment by EasyAsABC123** [comment]
@spurin the way to get onto that list, which i believe is completely a bad idea...is based of thumbs up on the first post in the issue...

If you want this fixed...please add a reaction to the top post...

Because they are fixing bugs via this [GitHub Sort](https://github.com/symless/synergy/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20sort%3Areactions-%2B1-desc) which completely ignores this bug...

Go to the top and add a reaction (top right of the post...)

**Comment by spurin** [comment]
Thanks @EasyAsABC123 for the github sort context, agree it shouldn't be triage'd in this way but:

You've all had problems/concerns with this issue at some point, would you please go to the nbolton top post of Oct 13, 2014 and add an appropriate reaction, hopefully this will put it in focus on their fixes to release assignment.  Lets see if we can prevent this issue going on for FOUR years and get it on to the list where it should be anyway... whether or not that makes a difference, we shall see.

@demonbane
@RafaelFCarneiro
@StephanX
@WibbletheDuck
@nomoon
@jujes
@golimpio
@politicus
@manijak
@KjellMorgenstern
@brusinow
@kccai
@forairan
@newgoliath
@robbietjuh
@alexciarlillo
@louwers 
@miraculixx 
@upq 
@victorquinn 
@Jamiermusic 
@LoganBarnett 
@ekondrashev
@sperberAfop
@jptaranto
@phonemyatt
@robbietjuh
@fhill122
@xwvvvvwx
@SeanZicari
@hovissimo
@leenoel1
@divby1

Thank you

**Comment by smidley** [comment]
@spurin Any way I can get a link to the download that actually works? I'm testing with MacOS High Sierra and Windows 10.  Thank you for your efforts!

**Comment by spurin** [comment]
@smidley - no problem, drop me an email, its james@<github userid>.com and I'll send you a link with a working version.

**Comment by spurin** [comment]
@smidley - Here you go, please let me know if you have problems and report back if it's working for you.  You should be okay, I'm on High Sierra, latest version, and also using Windows 10 with latest updates.  You need to bounce the server after applying hotkeys.

https://www.dropbox.com/s/zcm4jrloktsynix/synergy-pr-5522-hotkey-rc1-f4d9faa-MacOSX1011-x86_64.dmg?dl=0

**Comment by smidley** [comment]
It was not working at first but after changing the hot keys a number of times it seems to be working now.  However, while in a game on the windows client, I have no mouse movement and the keyboard presses are very delayed.

**Comment by spurin** [comment]
@smidley - the hotkeys are trial and effort and some key combinations work better than others, I've had success using the F keys on a mac keyboard.  I think the issue with the mouse movement and keyboard delays are more a synergy issue than a hotkeys issue.  Are you using it over wifi?  I found that certain network intensive activities like backups etc or possibly gaming, can affect the use of synergy and given the bi-directional nature of wifi, problems are much more apparent when using this, I'm using a dedicated hard wired network now for Synergy and it works well.

**Comment by smidley** [comment]
Thanks for the info.  I am on WiFi with no easy way to go to a wired connection.

**Comment by spurin** [comment]
@demonbane
@RafaelFCarneiro
@StephanX
@WibbletheDuck
@nomoon
@jujes
@golimpio
@politicus
@manijak
@KjellMorgenstern
@brusinow
@kccai
@forairan
@newgoliath
@robbietjuh
@alexciarlillo
@louwers
@miraculixx
@upq
@victorquinn
@Jamiermusic
@LoganBarnett
@ekondrashev
@sperberAfop
@jptaranto
@phonemyatt
@robbietjuh
@fhill122
@xwvvvvwx
@SeanZicari
@hovissimo
@leenoel1
@divby1

**Comment by nbolton** [comment]
Wow... chill out.

**Comment by nbolton** [comment]
For future reference, you can @ me to ask for an issue to be reopened. It's no problem. Spamming people and being abusive is not helpful.

**Comment by WibbletheDuck** [comment]
@spurin man, reading through some stuff after seeing this pop up, seems they don't have much of a team anymore.  Supposedly those who are left are going back to working on both versions, and S2 is 'back to beta', but whatever.  I officially gave up about a month ago, and moved to the [Barrier fork](https://github.com/debauchee/barrier).  Took a little fiddling to get it to work on my 10.9 Mac, but it does work (with none of the crashes I used to get on Synergy!), and has at least some dev activity that isn't derping around with labels and making empty promises.

@nbolton After **literal years** of empty promises about reviewing/merging a bugfix PR from a _paying customer_, I think he has a right to be a tad agitated.

**Comment by nbolton** [comment]
> empty promises

Ok, seems this thread's getting too heated. Closing for now.
