### ISSUE TITLE
hotkey with comma causes corrupt config file

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3788]
**Imported issue:**
- Author: Frank Zhao
- Date: 2013-12-09 18:12:55
- Legacy ID: 3858

**Steps to reproduce:**

In the GUI, use a "configure server" to configure a hotkey, for example, mine was

```
Control+Alt+Shift+,
```

to switch to a screen

The important part is the comma

**Expected:** the hotkey to do whatever I want it to do

**Actual:** the server fails to load the configuration file

```
ERROR: cannot read configuration "C:/Users/Frank/AppData/Local/Temp/qt_temp.q12268": read error: line 45: missing )
synergys.exe: no configuration available
ERROR: failed to launch, error: process immediately stopped
```

The offending line inside the configuration file is

```
keystroke(Control+Alt+Shift+,) = switchToScreen(pi)
```

**Versions and operating systems:**

server, 1.4.15 beta, Windows 7 Pro 64 bit SP1 build 7601

**Temporary workarounds:**

Do not use comma inside hotkeys, edit the config file to use the key "m" instead of comma

**Similar bugs:**

I tried searching for a similar bug, didn't see any

**Additional comments:**

obviously a configuration file parsing problem

**Comment by biggz** [comment]
I think I'm seeing this same problem again.

    [2015-12-06T12:10:25] ERROR: cannot read configuration "C:/Users/username/AppData/Local/Temp/qt_temp.179664": read error: line 36: missing )
    synergys.exe: no configuration available
    [2015-12-06T12:10:26] ERROR: failed to launch, error: process immediately stopped
    [2015-12-06T12:10:26] INFO: backing off, wait=4s, failures=2
    [2015-12-06T12:10:26] INFO: service command updated

I have hotkeys **Control + .** to switch right and **Control + ,** to switch left. As soon as I change **Control + ,** to **Control + m** the error goes away and the server starts fine.

I'm using version 1.7.5

**Comment by ColeyG** [comment]
This should be looked into again, ran into this bug on windows, latest stable release v1 pro for 12-24-18
