### ISSUE TITLE
Black and white icon for Mac OS X tray

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3791]
**Imported issue:**
- Author: Ryan Anklam
- Date: 2013-12-11 17:35:56
- Legacy ID: 3861
- Version: 1.5.0

The Synergy icon is the ONLY icon in my notification area that isn't black and white and drives my OCD crazy!  Dropbox and Box both let me pick a colored icon or a b/w one. 

https://www.dropbox.com/s/7cmmjv6vep8hszs/synergy_icon.png

**Comment by Ruslang** [comment]
Please, get overt with it!

**Comment by howellzd** [comment]
Surely this shouldn't take months to implement.

**Comment by beporter** [comment]
@howellzd Priorities are important. Certainly the program crashing or consuming 100% CPU must take precedence over a style issue. What good is a nice looking icon if there's nothing functioning properly behind it?

**Comment by skela** [comment]
@beporter , i think people are scratching their heads that a bug that was raised originally on Date: 2013-12-11 17:35:56, still hasn't been addressed. But yeah, you do raise valid points :D

**Comment by beporter** [comment]
I don't disagree with you at all-- the program _should_ look as good as it (usually) works after all, but if you hang around here long enough you're going to see TONS of minor issues getting "ignored" in favor of constant showstoppers. There are items that are close to 10 years old still-- don't take it personally that it's "only" been 2.5 for this one. :wink: 

But seriously: A program like Synergy is about as non-trivial as they get-- triple(+) cross platform, hooks deeply into user input, requires security/encryption, near-realtime performance/networking is mandatory, must handle OS-specific APIs for clipboards, mouse movement, keys/modifiers/shortcuts, different languages/locales, background services, file transfers... yeah, I don't envy the devs at all. Give them as much money as you can afford. :+1:

**Comment by marlowe310** [comment]
Just wanted to add my voice to those asking for a black/white mac icon! Thanks much for all the hard work.

**Comment by zwise** [comment]
+1

**Comment by texastoastt** [comment]
+1

**Comment by cleverinx** [comment]
+1. I'd do it myself by it's not grabbing the icon from the .icns file. Would appreciate it if we could get a black version. Thanks for making this great tool!

**Comment by mattswart** [comment]
+1

**Comment by Wayneoween** [comment]
+1

**Comment by N-Thomas** [comment]
+1

**Comment by nitro3v** [comment]
+1 is now finally available?

**Comment by spacecakes** [comment]
We need this. Synergy is great, but it sticks out like a sore thumb in the menubar. A high-res 1024*1024 app icon wouldn't hurt either.

**Comment by brettonlewis** [comment]
Still waiting...

**Comment by bschlenk** [comment]
+1 is there a way to hack in a black and white icon until there is an official one?

**Comment by Havna** [comment]
+1

**Comment by rodti** [comment]
+1

**Comment by AbhimanyuAryan** [comment]
+1 

I want black/white icons as well. For OSX & Ubuntu both :D

**Comment by Jiriteach** [comment]
+1 

The current icon in OS X looks horrible and is heavily pixelated. I resorted to launching it via terminal without an icon but this is now becoming painful.

Anyone know how I can change the icon on the build and re-compile? 

Thanks

**Comment by AbhimanyuAryan** [comment]
@Jiriteach even I wanna know that. Can't take this icon any longer 👎

**Comment by mattswart** [comment]
If anyone knows the icon path I can design a BW version. Can't find it for the life of me :\

**Comment by AbhimanyuAryan** [comment]
is this black icon out yet with latest beta updates? Please dev team...consider this when so many people requesting

**Comment by nlyan** [comment]
Cosmetic work isn't a priority right now. There is however a pull request for this that nobody here seems to have mentioned

https://github.com/symless/synergy/pull/4937

**Comment by davetroeger** [comment]
+1 retina b/w

**Comment by IncognitoCore** [comment]
I'd like to have this 'feature' too

**Comment by mowardz** [comment]
please do this. also nbolton you are very helpfull thx!

**Comment by liuhk388** [comment]
+1 plz

**Comment by iaian7** [comment]
Another request for a proper MacOS menu bar icon. Please.

**Comment by RubyGemer** [comment]
is this feature out yet?

**Comment by RubyGemer** [comment]
you guys are making mac interface ugly by not supporting this :(

**Comment by sebbean** [comment]
Would love this!

Surely it's pretty simple fix - i saw a PR up there but it seems to be closed

**Comment by nbolton** [comment]
Duplicate of #6396
