### ISSUE TITLE
Mac SDK option broken in build script

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3797]
**Imported issue:**
- Author: Stephen Chin
- Date: 2013-12-14 19:25:49
- Legacy ID: 3867

**Steps to reproduce:**
1. Run a build where the Mac SDK is specified on the command line:
   ./hm.sh config -g1 --mac-sdk 10.8

Expected: Build should configure itself and be ready to compile.
Actual: Build gives an error on the SDK path, pointing to a non-existent directory.

**Versions and operating systems:**

I happen to be building on Mac OS X 9 with Xcode 5.0.2, but I believe the paths changed in Xcode 4.3.  Regardless, hardcoding the SDK path is not cool.

**Fix**

"xcode-select --print-path" is a reliable way to get the SDK folder and works on old and new versions of the Xcode command line interface.
And I think I found an even better way.  "xcodebuild -version -sdk foo" returns the full path to the SDK without any guessing about the Platform/SDK pathing (which has also changed in recent Xcode versions)

**Patch**

<pre>
Index: tools/build/toolchain.py
===================================================================
--- tools/build/toolchain.py    (revision 1928)
+++ tools/build/toolchain.py    (working copy)
@@ -182,7 +182,7 @@
            cmake_args += ' -DCMAKE_BUILD_TYPE=' + target.capitalize()
        
        if self.macSdk:
-           path = "/Developer/SDKs/MacOSX" + self.macSdk + ".sdk/"
+           path = os.popen('xcodebuild -version -sdk macosx' + self.macSdk + ' Path').read().strip()
            cmake_args += " -DCMAKE_OSX_SYSROOT=" + path
            cmake_args += " -DCMAKE_OSX_DEPLOYMENT_TARGET=" + self.macSdk
            os.environ["MACOSX_DEPLOYMENT_TARGET"] = self.macSdk
</pre>

**Comment by guyzmo** [comment]
hi! 

looks to me that at version 1.6.3 most of that has been patched.

Though, trying to build synergy, I found out there's an error, that makes it pass the "darwin" block within `internalCommands`. Here's a patch anyway, based on 1.6.3:

```
From 375366b414327aebc1ef8f06da5a87adff7f414f Mon Sep 17 00:00:00 2001
From: Guyzmo <guyzmo+github@m0g.net>
Date: Mon, 30 Mar 2015 18:06:16 +0100
Subject: [PATCH] fixed macosx build

Signed-off-by: Guyzmo <guyzmo+github@m0g.net>
---
 ext/toolchain/commands1.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ext/toolchain/commands1.py b/ext/toolchain/commands1.py
index 9f4cb4a..092fdd6 100644
--- a/ext/toolchain/commands1.py
+++ b/ext/toolchain/commands1.py
@@ -450,7 +450,7 @@ class InternalCommands:
 		if generator.cmakeName.find('Unix Makefiles') != -1:
 			cmake_args += ' -DCMAKE_BUILD_TYPE=' + target.capitalize()
 			
-		elif sys.platform == "darwin":
+		if sys.platform == "darwin":
 			macSdkMatch = re.match("(\d+)\.(\d+)", self.macSdk)
 			if not macSdkMatch:
 				raise Exception("unknown osx version: " + self.macSdk)
-- 
1.9.5 (Apple Git-50.3)
```

it looks like this isn't solved on HEAD: 

 * https://github.com/synergy/synergy/blob/master/ext/toolchain/commands1.py#L430

HTH

**Comment by nbolton** [comment]
@guyzmo Please could you open a pull request? http://synergy-project.org/wiki/Pull_Requests

**Comment by nbolton** [comment]
@guyzmo Ah, wait, never mind, @rishubil did this already in #4146

**Comment by guyzmo** [comment]
ah, indeed! weird that I missed that line :-)

anyway, I'm currently manually applying the patch ATM. It looks to be a blockage towards automatic machomebrew compilation: https://github.com/Homebrew/homebrew/pull/38200

**Comment by dendrochronology** [comment]
I can confirm that building on both 10.9.5 and 10.10.3 still requires @guyzmo's patch (`elif -> if` on commands1.py:435).

**Comment by nlyan** [comment]
https://blog.update.sh/archives/410
