### ISSUE TITLE
Not working with Logitech Setpoint

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3809]
**Imported issue:**
- Author: Svein Alexander Frotjold
- Date: 2014-01-06 10:03:27
- Legacy ID: 3879

**Steps to reproduce:**
1. Use a logitech mouse and install setpoint
2. Try to use any of the extra custom mouse buttons,  None wil work if synergy is started
3. Stop synergy server and extra mouse actions wil work again

Expected:
Custom/extra mouse buttons should work even if synergy is started on host computer. I do not expect them to work on clients but it should be possible.

Actual: No extra features work on the logitech mouse when synergy is running (server started)

**Versions and operating systems:**
setpoint 6.61.15
Driver 5.60.73
Synergy 1.4.15
Windows 8.1
Synergy running elevated

**Temporary workarounds:**

Stop synergy, Find a replacement application?

**Additional comments:**

This is something that made me reinstall a lot off apps to figure out. it should capture, and Stop local events only when outside host monitors.
It seems that events from the mouse is stopped and delayed when synergy is running.
There should only be location based event tracking before mouse exit's the host monitor to keep synergy thread as quick as posible and let mouse events trough.
it allso seems that some mouse events like scrolling get caught in synergy and are missed on the host.

Synergy is allso keeping computer from entering sleep mode. i cant find a option for this.

**Comment by dragon788** [comment]
@Syngenuity If you go to Settings and run logging at Debug1, do you see the mouse events in the log for Synergy?
