### ISSUE TITLE
Left mouse button gets stuck in right click mode on OS X client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3823]
**Imported issue:**
- Author: Mark Petty
- Date: 2014-01-21 12:52:40
- Legacy ID: 3893

**Steps to reproduce:**

1) Setup Windows Synergy server
2) Plug in standard PC mouse to server
3) Setup OS X Synergy client
4) Move focus to client
5) In Xcode (I've had most success with this application for some reason) press and hold the left CTRL key
6) Then release the left CTRL key and the exact same time as you press and release the left mouse button (I think that you need to do this step quickly enough so that the inputs are captured in the same sampling frame)
7) The left mouse button will get stuck in right click mode

Expected:

The left mouse button does not behave as if it's the right mouse button

Actual:

The left mouse button behaves as id it's the right mouse button

**Versions and operating systems:**

Synergy: 1.4.15
Server: Windows 7 Professional 64 bit
Client: Mac OS X 10.8.5

**Temporary workarounds:**

Press and release the left CTRL key to trigger the key release event

**Similar bugs:**

Loads of sticky key bugs since 2009

**Additional comments:**

(square brackets denote sample frames)

[1:][2:][3:LEFT-CTRL-DOWN][4:LEFT-CTRL-DOWN][5:LEFT-CTRL-DOWN][6:LEFT-MOUSE-BUTTON-DOWN,LEFT-CTRL-UP,LEFT-MOUSE-BUTTON-UP][7:][8:][9:][10:]

I think that in frame 6 something goes wrong that leaves Synergy with the left mouse button mapped to the right mouse button.

**Comment by gtd** [comment]
Just as an FYI, I am experiencing this on OS X Yosemite with no Synergy in sight (this was the top Google hit).  I do have a fair number of applications installed and I'm running a Logitech mouse in addition to my trackpad in my MBP, so there could be some interaction issues there, or it could be a native issue... I haven't tested on a stock system.

**Comment by stevenfrancisco** [comment]
Confirming the issue on synergy 1.5.1 with a Linux Server and a Mac Client.

The Control Key workaround seems to work for stopping the issue as well.

**Comment by beporter** [comment]
Signal boosting: There is [a new nightly build available](https://github.com/synergy/synergy/pull/4564#issuecomment-95926896) that may fix this issue. If anyone monitoring this thread is able to test it, it would be appreciated.
