### ISSUE TITLE
Mac force quit key combo doesn't work

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3864]
command+option+esc

**Imported issue:**
- Author: The Wes
- Date: 2014-03-02 05:37:57
- Legacy ID: 3934
- Version: 1.4.16

**Steps to reproduce:**
1. Connect Mac client to Windows server
2. Switch focus to the Mac
3. Press command+option+esc

Expected: Force Quit dialog appears

Actual: Nothing

**Versions and operating systems:**

Windows server, Mac client
(didn't test with linux yet)

**Temporary workarounds:**

Open the On-Screen Keyboard on the Mac. The key combo then works via Synergy.

**Similar bugs:**

http://synergy-foss.org/spit/issues/details/3709/

**Comment by alanhoyle** [comment]
Problem still occurs in 1.7.2.  Work-around of "Turn on Keyboard Viewer" still works.

**Comment by alanhoyle** [comment]
Problem still occurs in 1.7.6, OSX 10.11.6 (client) , Ubuntu 16.04 (server)

**Comment by alanhoyle** [comment]
@nbolton While I know this is listed as "closed" and "stale" but it appears that at some point it actually got "fixed" instead.  I tested yesterday after upgrading to macOS 10.13.5 client/Ubuntu 18.04 server 1.9.1, and cmd-option-escape did indeed bring up the force quit dialog.

**Comment by nbolton** [comment]
Interesting! Thanks for letting me know.
