### ISSUE TITLE
Mouse pointer speed does not adjust to clients

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3925]
**Imported issue:**
- Author: Andrei Remenchuk
- Date: 2014-03-28 08:26:27
- Legacy ID: 3995

I am using Synergy with very different screen resolutions, and when the mouse moves from server (Retina MacBook) to clients (Windows), the mouse pointer moves significantly quicker than native mouse connected to that system
1. Server - MacbookPro Retina (OS X 10.9 Mavericks). Screen resolution - 2880x1800. Mouse speed in preferences - 7/10
2. Client - Windows 7. Screen resolution - 1920x1080. Mouse speed in Control Panel - 9/11 
3. Move mouse from client to server. As it enters Windows screen, the pointer moves much faster that the physical mouse connected directly to client.
4. Move physical mouse connected directly to client to observe the difference

Expected: mouse speed on client should match OS settings of the client

Actual: mouse speed on client seems to be based on server speed and resolution, and results in excessive speed on clients with lower resolutions. 

**Versions and operating systems:**

Server: OS X 10.9.2 (Mavericks)
Client: Windows 7

**Temporary workarounds:**

Use physical mouse connected directly to client when precision is required 

**Similar bugs:**
Bug #461

**Comment by ihemdat** [comment]
I have this issue running 1.6.3 while both server and client are Macs running OS X 10.10.2 with the same 2560x1440 resolution.
The server is a Macbook connected to an external Apple display and the client is an iMac.

- The client mouse speed setting has no influence on the cursor movements on the client (it does effect the speed of a local USB mouse connected to the client).
- The server speed setting does change the cursor speed on the client.
- The speed of the mouse on the server and on the client is different. The mouse moves much faster on the client. If I want to get a reasonable speed on the client I must set the server speed to such a low speed that makes in unusable.

**Comment by Hypolite** [comment]
Same issue here. Synergy version 1.7.3, Server is a MacBook Pro 15" with a Magic Mouse, client is a Windows 7 with a 1920x1200 resolution screen. On the client, the mouse moves by increment of 5px only, making its movement fast and imprecise.

**Comment by fwenzel** [comment]
I have this happen after server and client (not sure if both or just one is sufficient) go to sleep and wake back up.

I work around by clicking *stop*, then *start* on both the server and client.

However, it appears that it's the **server** that *needs* the synergy service restarted; merely restarting/reconnecting the client service is not sufficient.

I hope that this helps narrow down the location of the bug quite a bit.

**Comment by ramosvacca** [comment]
I have the same problem.

Client: gygabite z68xp-ud3; i7-i2700k; ssd; ubuntu 14.04 up to date. Synergy 1.7.4
Host: Macbook Pro Retina mid 2015. 13 inch. i5-5257U. Mac Os 10.10.5 Yosemite. Iris graphics 6100.

Everytime i suspende them, when i power them on, the mouse on the client is incredibly fast.

So, to fix it I should go to "configure server", then "Advanced server settings"... finally I have to check or uncheck de "use relative mouse moves"....

Looking a little deeper on the mac. There is some files in the folder "/var/folders/mt/jh8pcsw93hsbcs4hxl4l0bpc0000gn/T/..." i guess those are the configuración miles, as each have different true values for the options... you can open them and see... their names are Synergy.[something else] for example: Synergy.MyN576; where the "relativeMouseMoves" parameter is set to be "= true".... 
On the file Synergy.Hts576 this parameter is set to be "=false"...

So i guess i could make a simple script to change the value on the file my synergy is using, instead of changing the advanced configuration. Just change true or false o n the file and reloadit.... we'll see

**Comment by honkaboy** [comment]
I also experience this issue.

Host:
Mac OS X 10.11.2
Synergy 1.8.0-beta, compiled from source (4ff3cddecf3946241560a95d7d48eabdab38c16f)
MacBook Pro Retina mid 2015.  HOWEVER, I do not use my macbook pro's screen - I use two external monitors, one apple branded, the other dell branded.

Client:
Ubuntu 14.04LTS
Synergy 1.4.12, compiled from source (4ff3cddecf3946241560a95d7d48eabdab38c16f)
Dell monitor

Given the other comments in this thread, it might be worth noting that all three of my monitors have the same resolution (2560 x 1440).

Restarting host also fixes issue.  Relative mouse moves check or uncheck does not affect behavior as far as I can tell.

**Comment by shevett** [comment]
Going to add a Me Too on this one.  

Server: Mac OSX 10.10.5, macbook pro circa late 2013
Synergy 1.7.3

Client: Two different windows client machines, both exhibiting the same behaviour.

Mouse movement from the Mac to the client host is showing a 20-ish pixel jump per mouse motion on the client.  Can't get lower resolution in motion than that.  :(

**Comment by miraculixx** [comment]
This issue has come up in my setup too just a few days ago - not sure what caused it, the Synergy versions have been unchanged for some time:

Server: Mac OSX 10.11.1
Client: Linux 3.13.0-24-generic
Synergy 1.7.5

The mouse speed settings on both machines are "middle". The client accelerates mouse movements by about factor 2x (that's a visual estimate).

What would be great is a per-client configuration option to set, e.g. "mouse speed translation factor".

**Comment by nathanabourbih** [comment]
Client: Windows 7 Ultimate
Server: Mac OS X 10.11.2

When entering the Windows 7 machine with the mouse, mouse speed increases dramatically.

I found a solution that works:

Step 1: Press the Apply button on the main synergy window in Windows (Synergy will disconnect and reconnect).
Step 2: Press the Apply button on the main Synergy window on the Mac (Synergy will again disconnect and reconnect).

After doing this, everything goes back to normal.

**Comment by nate6231** [comment]
Client: Windows 7 Ultimate 
Server: Mac OS X 10.11.2

When entering the Windows 7 machine with the mouse, mouse speed increases dramatically.
I found a solution that works:

Step 1: Press the Apply button on the main synergy window in Windows (Synergy will disconnect and reconnect). 
Step 2: Press the Apply button on the main Synergy window on the Mac (Synergy will again disconnect and reconnect).

After doing this, everything goes back to normal.

**Comment by pat-o** [comment]
I am experiencing this issue and @nate6231's suggestion does fix my problem, but only for a few minutes.
