### ISSUE TITLE
Client crashes on Linux 64-bit (CXWindowsScreen::enable)

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3952]
**Imported issue:**
- Author: Jeffrey Putney
- Date: 2014-04-18 15:02:29
- Legacy ID: 4022

Client synergyc crashes on 64bit linuxmint

1) Start synergyc

2) See synergyc connecting to server

3) See synergyc crash

**Expected:** See synergyc not crash

**Actual:** See synergyc crash

**Versions and operating systems:**

_Client:_

Linux Mint 16 Petra \n \l

Linux 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

_Server:_

Linux Mint 16 Petra \n \l

Linux 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

_Synergy_ 1.4.17 Client and Server (Has been an issue for multiple versions)

**Temporary workarounds:**
Swapping client and server works

**Similar bugs:**

**Additional comments:**

**Comment by jeffrey4l** [comment]
has such issue, too, any progress?
