### ISSUE TITLE
Synergy is interfering with Total Commander drag-and-drop functionality

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3977]
**Imported issue:**
- Author: Andrew Krivosheyenko
- Date: 2014-05-15 18:04:33
- Legacy ID: 4047

After of some amount of time running Synergy service (a matter of minutes) and switching between apps. Synergy starts interferring with Total Commander, causing drag and drop functions within Total Commander broken. Also, randomly, this issue may disappear for some minutes but after a few switches get back again. When I stop Synergy service, drag and drop functions in TC are restored immediately.
It does not affect other applications (I tried Desktop and Windows Explorer).

Here's a screencast where I demonstrate the issue: http://screencast.com/t/i2KFJT5Nmk4v
- First, you can see I attempt to drag a file, and the drag is canceled right after mouse move begins (mouse pointer doesn't indicate an item being dragged)
- When I stop Synergy service and get back to Total Commander, and you can see that drag works as expected (mouse pointer changes indicating that an item is being dragged)
- When I start the service again and the issue doesn't exists immediately after start (I hoped it would reproduce in the screencast, but no luck)
1. Get a Total Commander copy here: http://www.ghisler.com/download.htm and start it
2. Reptoduce this issue (http://synergy-project.org/spit/issues/details/4046/) -- open drive selection dialog with ALT+F1 and use up/down keyboard button to change the drive.
3. Try to drag a file from Total Commander files list

Synergy 1.4.17
Total Commander 8.51rc1 x32/x64 "run as Administrator" (this issue also existed with a few previous 8.5x Total Commander versions)
Windows 8.1 Pro x64, Update 1
Also Windows Server 2012 R2 x64

**Comment by the-wes** [comment]
Got another report of this, this time with the password field.
