### ISSUE TITLE
Save config file to web account

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3988]
**Imported issue:**
- Author: Jiejing Zhang
- Date: 2014-05-23 04:07:17
- Legacy ID: 4058

*\* Request **
This is a feature request.

Now we can have an account, like after donate one $.

We can also upload our configs into that account, so we can easier to use them in many many devices, like android, iOS, and PC.

This was insprte by the TeamViewer. 

PS, If you need people to build the server, I can do the help. :)

Expected: TODO

Actual: TODO

**Versions and operating systems:**

TODO

**Temporary workarounds:**

TODO 

**Similar bugs:**

TODO

**Additional comments:**

TODO

**Comment by gth** [comment]
Was this one - #3988 - closed as a duplicate, or was #5537 closed as the duplicate?   Right now they're both closed... how do I +1 a closed enhancement?
