### ISSUE TITLE
Grave accent appears instead of single quote

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4007]
German keyboard

**Imported issue:**
- Author: Max Krickl
- Date: 2014-06-06 07:46:42
- Legacy ID: 4077

**Steps to reproduce:**

Synergy 1.5.0 on OS X 10.9.3 (server on a Mac Mini and client on a MacBook Pro).

When Tying the single quote "'" on the server Mac Mini on my german keyboard, on the client MacBook Pro a grave accent "`" appears.

**Comment by mgaberle** [comment]
Same here...
Server: iMac Late 2015 - OS 10.11.4
Client: MacBook Pro Mid 2010 - OS 10.11.4
Synergy: 1.7.6

**Comment by shaaati** [comment]
This is an awfully annoying bug. I'm typing a long document on my Synergy client (MacBook Pro, OSX 10.9.5) and I need to fall back to the Mac Keyboard whenever single quotes are required.
OSX shows that the combination `Shift+#` (should be `'`) is interpreted as `Shift+´` (resulting in a backtick), while `#` alone results in a button press event of the `3` key.

Server: Windows 10
Synergy 1.7.6 on both computers

**Comment by arnoldpistorius** [comment]
Also experiencing issues. Trying to send quotes and single quotes from Mac OSX (10.11.5) server to Windows 10 server. Both updated to the current version of Synergy 1.7.6.
