### ISSUE TITLE
Middle mouse button broken (Mac client, Windows server)

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4033]
**Imported issue:**
- Author: Ante Vukorepa
- Date: 2014-07-14 03:20:46
- Legacy ID: 4103

Come on, folks.
Are you actually improving this piece of software or regressing it?

Middle mouse button STILL isn't working on Mac OS X, with latest server on Windows and latest client on Mac OS.

It USED to work. Like many other things.
I'm stuck using the prehistoric synergyc 1.3.0 on my Mac because the current version is in shambles.

**Comment by thinker007** [comment]
Solved via：http://www.adilhindistan.com/2012/08/using-mac-as-primary-machine-and-fixing.html

I solved the problem by mapping mousebutton(4) to keystroke(Meta+BracketL) and mouse(button5) to keystroke(Meta+BracketR). The whole config file is shown below:

section: screens
        AHPC:
                halfDuplexCapsLock = false
                halfDuplexNumLock = false
                halfDuplexScrollLock = false
                xtestIsXineramaUnaware = false
                switchCorners = none
                switchCornerSize = 0
        AHMac:
                halfDuplexCapsLock = false
                halfDuplexNumLock = false
                halfDuplexScrollLock = false
                xtestIsXineramaUnaware = false
                switchCorners = none
                switchCornerSize = 0
end

section: aliases
end

section: links
        AHPC:
                right = AHMac
        AHMac:
                left = AHPC
end

section: options
        mousebutton(4)=keystroke(Meta+BracketL)
        mousebutton(5)=keystroke(Meta+BracketR)
        relativeMouseMoves = false
        screenSaverSync = false
        win32KeepForeground = true
        switchCorners = none
        switchCornerSize = 0
end

**Comment by bunjiboys** [comment]
This should be fixed by https://github.com/synergy/synergy/pull/5072
