### ISSUE TITLE
Clipboard broken from Windows client to Mac server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4038]
**Imported issue:**
- Author: LetsServeIt Server
- Date: 2014-07-20 09:55:12
- Legacy ID: 4108

**Steps to reproduce:**
1. Copy selection of text in Windows 7 Client
2. Paste text into any program i.e textedit on OSX 

Expected: Text copies over from Windows 7

Actual: Nothing in clipboard (or existing mac clipboard pastes in)

**Versions and operating systems:**

Using Mac OSX 10.9.4 as Server (Windows 7 Client) [Synergy 1.5.0 on PC & Mac]

**Temporary workarounds:**

NONE 

**Similar bugs:**

UNKNOWN

**Additional comments:**

Copy & paste works from Mac to Win 7, although sometimes I have to enter the Win 7 screen twice for the clipboard to copy over correctly.

**Comment by XinyuHou** [comment]
Hi Guys, please try out our 1.7.5 release to see if it fixes this problem.
