### ISSUE TITLE
Client not working while UAC confirmation window 8.1

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4063]
**Imported issue:**
- Author: Oliver Falkenstein
- Date: 2014-08-18 15:57:50
- Legacy ID: 4133

**Steps to reproduce:**

I do not work with admin rights on the client in Windows 8.1. If I want to install software the UAC window opens to input admin Password. . But the mouse and keyboard do not work then. I had specially to connect a keyboard to fill in this window. I work with Synergy 1.5!

Expected: TODO

Actual: TODO

**Versions and operating systems:**

Server: Ubuntu 14.04 32 bit
Client: Windows 8.1 64 bit
Synergy: 1.5

**Temporary workarounds:**

I have no Workaround!

**Similar bugs:**

TODO

**Additional comments:**

TODO

**Comment by adedomin** [comment]
Just disable UAC display dimming (One notch above never notify in win 8.1).

**Comment by kirashi3** [comment]
I too experience this same issue on Windows 10.

While @adedomin's suggestion might work, I do not feel as though we should have to disable or lower security features as a workaround.

**Comment by paul-suarez** [comment]
Darren Grove from Synergy Forums commented:

 I am looking to pass this onto the Symless team. I could not find their email address to send feedback on possible bugs in their code too.

Background,

For a year or two, I have had issue with using Synergy between a Windows Desktop and Linux (CentOS 6.6) desktop. The issue being that when the screen savers would activate on both machines (say after I went home), my shared mouse would no longer work and I could not unlock my Windows desktop. I had to go to my Linux machine and use it’s mouse to get the screen to appear with the login prompt. After I clicked in the password field to unlock my Linux machine, my shared keyboard would work to allow me to type in my password. Then after the Linux screensaver was unlocked, I had to use the Linux mouse to stop Synergy on my Linux machine to allow my mouse to come back to my Windows desktop to allow me to unlock it.

Setup:

Server:   Windows 7 Pro (I have two monitors hooked up to this machine)

Client:    Linux CentOS 6.6

Today, I downloaded and installed V1.8.8-stable-25a8cb2 and installed it on both my Linux (CentOS 6.6) and Windows 7 Professional hoping it would cure this issue. I am happy to say that I think it fixed the mouse lockout problem. However, I think there is still a bug. When I lock screens  on both machines I am able to unlock my Windows (mouse will not move into my Linux side), but I get a window that pops and says “synergy.exe has stopped working”. I cannot move my mouse into my Linux desktop at this time, but when I close this window, wait for about 10 seconds, it works fine. I don’t have to stop/start synergy or do anything else. The server side seems to automatically pick up my Linux desktop fine.

I thought you would want to know this and hope you can find a fix.

[Link to thread](https://symless.com/forums/topic/2897-uac-synergyexe/)
