### ISSUE TITLE
Cursor not released to VMware console

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4080]
**Imported issue:**
- Author: Joseph W. Guillory
- Date: 2014-09-03 19:02:01
- Legacy ID: 4150

**Steps to reproduce:**
1. I have tried using the VMware console with Synergy turn on and the mouse and keyboard will not switch over.
2. I have tried starting VMware console first and then Synergy but Synergy will not work.
3. I have tried these steps with both the VMware local client and the Web client and the issue is still there. 
4. I am running Win7 64bit and testing VMware 5.5 in a lab environment. 

Expected: Smooth transfer of mouse and keyboard to VMware console.

Actual: No transfer at all.

**Versions and operating systems:**

Synergy 1.5.1 and 1.6.0 vSphere 5.5.  Local system Windows 7 64bit.

**Temporary workarounds:**
Cannot use Synergy while working with VMware.

**Similar bugs:**
none that I know of.

**Additional comments:**

**Comment by JohnnyFlash** [comment]
I am also experiencing this problem in version 1.7.3 Pro

**Comment by ModeenF** [comment]
I have this problem with 1.7.4. and VMWare Player 7.1.2
