### ISSUE TITLE
Backslash and Pipe Fail on client in RDP Session

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4087]
**Imported issue:**
- Author: Raveh Daveh
- Date: 2014-09-11 10:21:53
- Legacy ID: 4157

**Steps to reproduce:**

Use Windows 7SP1x64 Pro Server, Windows 8.1x64 Pro Client
Open a remote desktop session to a server 2008R2 on the windows 8 client
Backslash and Pipe no longer function

**Versions and operating systems:**

Tested with 1.5.0 x64

**Temporary workarounds:**

Copy and paste from elsewhere

**Comment by snbingham** [comment]
I was seeing this with 1.5 and just upgraded to 1.6.2.

OSX 10.10 server, Win 8.1 client.  RDP to 2008R2 no backslash or pipe.  RDP to 2012R2 is fine.  This was working fine when I used 1.3.  Must admit this is very irritating given how critical those keys are.

Likewise my local Win8.1 keyboard works fine.

I see this has been marked as a bug, but doesn't have a milestone.  Is there any further news on this one?

**Comment by edwardsp** [comment]
Please can you fix this issue?  It happens on my Win8 client for virtual box and cygwin

**Comment by FrogSmack** [comment]
Same issue, no backslash via rdc, all current versions of synergy on mac (server) to win 8.1 (client) running Remote Desktop Connection Manager.

**Comment by chaddoncooper** [comment]
+1
