### ISSUE TITLE
Windows 8.1 client display is always on

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4092]
**Imported issue:**
- Author: Ejebagom Ojogbo
- Date: 2014-09-16 02:08:44
- Legacy ID: 4162

**Steps to reproduce:**
1. Set Windows 8.1 PC as client and Windows 7 PC as server, both running Synergy 1.6.0-r2411 or 1.5.1-r2398
2. Mouse over to client and perform any kind of operation. 
3. Return focus/mouse to server and continue working.

Expected: After a certain amount of time (designated by your power settings) the client display should either dim or turn off.

Actual: Display remains on indefinitely.

**Temporary workarounds:**

This really isn't a workaround, but setting Windows 7 as client and Windows 8.1 as server does not cause the problem. Windows 8.1 as client is the problem.

**Additional comments:**

Unchecking "Allow this device to wake the computer" in the WLAN card's Power Management settings does not fix this.
Using "powercfg -requestsoverride PROCESS synergyc.exe" does not fix this.

**Comment by ulijh** [comment]
Hi there,

is there any work being done on this? It would really be great having this solved!!!

I'm using Arch Linux with Cinnamon as server and Win10 as client (same same with old Win7 setup). The client never goes to sleep mode or locks the screen, whereas the server does.

Both machines are running synergy 1.7.6 with encrypted connection.

Let me know if I can provide any logging info or help in an other way!

Thanks
Uli

**Comment by NateJC** [comment]
I'm having this same problem using Synergy 1.8.3 with macOS Sierra 10.12 server and Win 10 Pro client. This issue was first noted back in 2014. Is there still no resolution? :(

**Comment by ulijh** [comment]
This issue seems partially gone for me. with Synergy 1.8.4,  Linux server and Win10 client. Both machines lock the screens after specified time, but the Linux box sometimes doesn't turn it off.

**Comment by NateJC** [comment]
If I set the server setting of screenSaverSync = false, the screen saver will work properly, but the computer won't actually go to sleep (the hard discs continue to spin).
