### ISSUE TITLE
Left clicks in Xcode with mouse hosted on Windows don't work in some cases

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4109]
**Imported issue:**
- Author: Lee Hasiuk
- Date: 2014-09-30 18:58:25
- Legacy ID: 4179

**Steps to reproduce:**
1. Install Synergy on a OSX Mavericks and a Windows 7 64-bit PC.
2. Use the keyboard and mouse connected to the PC.
3. Install Xcode 6.0.1 under Mavericks.
4. Start Xcode, and create a new iOS Single View application.
5. In the navigator window on the left, select LaunchScreen.xib.
6. Click on the Copyright notice or other text in the middle window.
7. Select the properties inspector in the right hand window.
8. Click on the T which is on the right side of the Font field.

Expected: The font selection pop-up window should appear.

Actual: The T momentarily highlights, then goes dim.

**Versions and operating systems:**

Synergy 1.5.1 (but it happens with older versions, as well).
OSX 10.9.5
Xcode 6.0.1
Windows 7

**Temporary workarounds:**

Use a mouse connected directly to the Mac.

**Similar bugs:**

Can't change file names on the left hand side of Xcode by clicking on an already selected file name.  
This file name changing bug, but not the Font selection bug, occurred in previous versions of Synergy, Xcode and OSX, as well.
Another possibly related bug is that, if you use the Synergy connected mouse to perform a Spotlight search, you cannot select the search results with a click.  You can only highlight them, and then need to use the Enter key on the keyboard to select them.

**Additional comments:**

I just spent $4.99 thinking that all I needed was an upgrade to my ancient version of Synergy.  No such luck.

I tried both a wireless Logitech mouse on the Windows PC and a wired Dell mouse, with the same results.

**Comment by SticklyMan** [comment]
This issue appears to have been fixed in 1.7.1. Thanks!
