### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#411]
**Imported issue:**
- Author: sjrmay (Google user)
- Date: 2010-03-22 00:00:00
- Legacy ID: 421

Hi folks,  

I was wondering if anyone was thinking about making a "portable" version of  
Synergy-plus for Windows - ala portableapps.com?  

My use scenario is that I've got a work PC that I can't install Apps on (I  
can run portable apps though :) )  Getting Synergy-Plus working in that way  
would be amazing for me...sure others are the same.  

Any chance?  

Si

**Comment by velvitonator** [comment]
Consider this another vote.

We're a small games studio with our own tools, and Synergy is a great way to get mouse + keyboard going on devices that are either finicky to get to support it or don't have it at all (e.g. consoles, mobile).
I'd be really happy if I could just bundle Synergy with our tools packages and get it to run when the tools start, as opposed to it being in the ether or not.

**Comment by jrhortian** [comment]
Any update on this?

**Comment by telorand** [comment]
I'd also like a portable version. I would like to use it with my work computer (to which I don't have admin rights) and my own personal computer, but without those rights, I'm out of luck. Cameyo is also of no avail.

**Comment by Gitoffthelawn** [comment]
+1

**Comment by pdemro** [comment]
Please give us a portable version!  Client laptops always come locked down and thanks to Nick I am addicted to Synergy

**Comment by pdemro** [comment]
To whoever finds their way here - I was able to find a workaround to enable Synergy on clients without administrator access.  Check out this forum thread here:

http://synergy-project.org/forum/viewtopic.php?f=17&t=547&p=4008#p4008

**Comment by bobpaul** [comment]
pdemro, do [these instructions](https://portableapps.com/comment/190414#comment-190414) look like what you had? 

FWIW, I've tried installing various versions (I haven't yet found the old 1.3.7 build for windows; I bet that would work as protable) and can't get any of them to work on their own.

**Comment by paul-suarez** [comment]
Elsni from forums:

I'd like to run synergy on my company laptop to control my personal mac when I work in home office. But I have no admin rights.

Is it technically possible to provide a synergy version for windows which runs without installation and admin rights?

Thanks!

[Use without install/admin privileges](https://symless.com/forums/topic/2975-use-without-installadmin-privileges/)

**Comment by tandr3i** [comment]
+1 for portable version or at least a workaround to be able to use it on a pc without admin
