### ISSUE TITLE
Copying loses formatting data (only the text is saved)

### ISSUE THREAD

**Issue by vm0824** [symless/synergy-core#4143]
Hello,
    Under certain conditions when I copy something to my clipboard and try to paste it into a window from another machine, I lose all formatting data. Only the text is saved.

   If I have formatted data in MS Word in my client machine and copy it to my server, then it pastes fine. However, if I try to copy a query from MS SQL Server Management Studio on my client and paste into a window from my server, then it does not copy the formatting; just the text. Yet, I can first copy from SSMS to Word on my client and then from Word on my client to Word on my server and it will work.

Speculation:
I think there may be some odd formatting chars that are getting lost. SSMS has these, but Word does not. That is why Word copies correctly, but SSMS copies only text.

Additionally, if I copy a picture to my clipboard in Word on my server and then paste it into Word on my client, it drops a picture there that is empty. As in, a picture object exists and is the correct size, but is completely white.

I do not believe it matters if going from client--> server or vice versa.

**Comment by sinabs** [comment]
This is very serious, Web content cannot be copied
I hope as soon as possible

**Comment by beporter** [comment]
Possibly related to #4394, #4431, #4319, #4143, #4038, #2909? Basically just [search the Issues for "clipboard"](https://github.com/synergy/synergy/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+clipboard).
