### ISSUE TITLE
Steam overlay doesn't work, many steam games don't receive input

### ISSUE THREAD

**Issue by jshufro** [symless/synergy-core#4155]
I'm running 1.5.1 as a server on my windows gaming machine. 

I have one Ubuntu machine connected as a client.

I can't open the steam overlay (hotkey shift+tab) on my windows machine while the Synergy service is running.

Further, in some games, no input is received from they keyboard or mouse at all (aside from mouse movements, i can't click any buttons or press any keys for affect)

**Comment by twodice** [comment]
This is happening to me too, with Windows 10 and the latest version of synergy.

**Comment by jshumaker** [comment]
Same issue here, running:
Synergy 1.7.6 Server on Windows 10. 

I recently upgraded both from Windows 7 to 10 and Synergy 1.7.5 to 1.7.6 so unfortunately not sure which caused the change in behavior, but my bet is on Windows 10.

Specifically, the shift key does not work in some games. Seems to be particularly Unity engine based games.  Free to play example would be Unturned. At least thus far I've only seen it with games using that engine. Others like Witcher 3, or Just Cause 3, have no problems. Something particular to how Unity engine does this.
