### ISSUE TITLE
Keyboard and mouse broadcast option

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4180]
This is a real edge case, but users occasionally ask if we can have a broadcast option. This seems a little odd though, as it seems unlikely that you can synchronize all of your machines.

**Comment by AnthonyWC** [comment]
This "feature" would open a possible vulnerability to MITM (unless encryption is made stronger) and if implemented should only be a toggle type of function.

**Comment by superseani2** [comment]
I would personally LOVE to be able to do that, as nobody have done it yet. I can see ho it would be asome for hackers too. But hackers surely already done this. I think even if its made it would be not that harmfull... BUT I WOULD personallly LOVE to be able to control 2 pc with 1 mouse athesametime, as i would multiseat my pc and use this to multibox diablo 3. It would also make multibox SUPER freaking easy. Please do it. I implore you .
