### ISSUE TITLE
Bluetooth HID emulation

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4185]
If we emulate a HID input device, this may help to provide input on iOS and Android devices that don't allow you to simulate input events via the system API.

**Comment by matthew-lang** [comment]
Was just about to submit this as a feature request. Glad it's on the list!

**Comment by mdagbro** [comment]
Would love this. It would have another benefit - Allowing Synergy on my work PC which is connected to my workplace via VPN. Standard Synergy won't work here since the VPN blocks my LAN, but a Bluetooth HID would work beautifully.
