### ISSUE TITLE
Drag windows between computers

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4189]
Wouldn't it be cool if we could drag a Window from your Windows machine to your Mac or Linux machine? Chris Schoeneman (the first dev) suggested maybe we could copy the data from a window's framebuffer (but this may only apply to Windows). I think MaxiVista, ZoneScreen and spacedesk do this already. I already tried experimenting with integrating VNC, but had to prioritize other things. It would be exciting to return to this.

**Comment by dirac3000** [comment]
I've seen (but not tried) Window Switch: http://winswitch.org/
It looks like it does what you want, but I think it will be quite slow, as it involves many memory copies.

**Comment by dobkeratops** [comment]
I was about to suggest: is there a way you could get the window title from a linux window manager, and synergy could carry that string around between clients,  and some user defined script could say what to do with it when dropping into a client. (e.g. ... like opening a URL in the web browser, or opening a terminal & SSH, or opening a file-browser, opening a file in emacs..). This would be dependant on formatting the string in a particular way.
