### ISSUE TITLE
Many servers, single client, bidirectional sharing

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4232]
Users often want the ability to connect many servers to a single client

Scenario 1: In a meeting room where one machine is a presentation machine.
Scenario 2: In a data center control room with a "main screen" at the front of the room.

**Comment by phalpern** [comment]
This feature would seem to be a clean way to get the desired effect described in issue #461.  I hope to see it implemented soon.  I don't need to share one client among multiple servers simultaneously (although that would be cool for the reasons mentioned).  I would be happy if I could just take my laptop between home and work and have the client automatically connect to the server running on the desk side machine in each location. Right now I have to run two instances of synergyc. That works, but there's no GUI support for the second instance and it's inelegant, plus the second instance doesn't run elevated. So, add me to the list of people who would like to see this feature.

**Comment by lparmentier-quatral** [comment]
+1 need this feature !

**Comment by itavero** [comment]
:+1: This would be awesome (I'm having driver issues on my Linux desktop with my wireless trackpad, this would allow me to connect this to my Windows laptop).

**Comment by ebanders** [comment]
+1  (very desirable feature)

**Comment by stickybyte** [comment]
+1, I realy need this feature. I am switching between homeoffice, office and college. So I have to change the server IPs very often.

**Comment by disco0** [comment]
+1, would upgrade to Pro just for this

**Comment by makaanneo** [comment]
+1, this sound like a great feature for the future

**Comment by AndreVolpi** [comment]
+1, any idea if and/or when will this be made? Would level up pair programming locally by ALOT.

**Comment by ozielg** [comment]
+1, this should be easy to implement, and much really needed

**Comment by binron** [comment]
+1, would be great

**Comment by alexconrey** [comment]
This feature would be fantastic, my use-case scenario is the following:

Girlfriend and I have our desktops underneath a wallmounted TV connected to our media center. I'd like to have our two desktops run as servers and have the media center be listening for both of our desktops.

**Comment by WooterTheTroubleshooter** [comment]
+1

**Comment by sacmt-hciie** [comment]
+1 I need at least at 2 synergy servers, I live in the land of . I have 16 displays and way too many keyboards and mice. I'd like to have 4 input (server) stations for approx 8-12 clients. Any client screen accessable from any server... Can it be done? Please, PRIORITY! Please, and Thank You!

**Comment by jonsparks** [comment]
+1, this would be a great feature. I have 2 desktops and usually a laptop at my desk, and often find myself switching to the laptop's keyboard and Magic Mouse. It'd be convenient to be able switch between peripherals (desktop/synergy server or laptop) and use them across all of my screens without having to restart Synergy on two computers to switch modes.

**Comment by nlyan** [comment]
We have a working implementation of this feature in version 2, which is currently scheduled for release at the end of the year

**Comment by ahmetabdi** [comment]
@nbolton @nlyan Is this issue done now as part of Symergy 2 can be closed?

**Comment by nbolton** [comment]
@ahmetabdi Oh good point! 👍

**Comment by Pomax** [comment]
With version 2 having been cancelled, can we either reopen this to add it back into v1.10, or can a new issue be filed and a link dropped in this comment thread to point to that new issue? It would still be _incredibly_ productivity boosting to have the option of two-way keyboard+mouse syncing, so the server's peripherals _and_ the client's peripherals control text and cursor.

**Comment by Cheezmeister** [comment]
Synergy 2 is cancelled. What's the status now of this very desirable feature?
