### ISSUE TITLE
Middle click does not paste in Terminal on Mac client

### ISSUE THREAD

**Issue by johnstile** [symless/synergy-core#4254]
Server: synergy-1.6.1, gentoo linux.
Client: synergy-1.6.2, osx 10.10.1 (Yosemite)
Using the osx mouse, in Terminal, I can hold left mouse button to highlight text, then click middle mouse button to paste.
Using synergy server mouse, in Terminal on Osx client, I can hold left mouse button to highlight text, but middle mouse button does not paste.
Please make behavior same or offer a work around to  make behavior same.

**Comment by alanhoyle** [comment]
Still the case on Synergy 1.7.6 on OSX 10.11.6 (client)  and Ubuntu 16.04 (server)
