### ISSUE TITLE
Ubuntu 14.10 launcher autohide broken on client

### ISSUE THREAD

**Issue by Vizzard** [symless/synergy-core#4283]
Three configurations, same issue:
1. Both server and client are Ubuntu 14.10 x64 desktop with Unity and Synergy 1.6.2.
2. Server: Windows Technical Preview with Synergy 1.6.2, client: Ubuntu 14.10 x64 desktop with Unity and Synergy 1.6.2.
3. Server: Windows 7 with Synergy 1.6.1, client: Ubuntu 14.10 x64 desktop with Unity and Synergy 1.5.1.

System with Synergy server on the right side with Launcher autohide feature off (Launcher visible all the time) or without Launcher in case Windows server machine.
Ubuntu with Synergy client on the left side with Launcher autohide feature on.

Using local mouse of client machine brings Launcher from hide.
Using mouse on server machine and pushing to the left side of client machine gives nothing. Launcher does not appear.

I found similar threads but they were old, marked as obsolete and closed.

**Comment by draekko** [comment]
I can confirm i get the same issue with Ubuntu 15.04 x64 on desktop and laptop both running the same os version. 

Also doing Alt-F1 gets the launcher to come out of hiding and be shown when set to auto-hide but mouse edge doesn't get picked up and get the launcher to scroll through the list of icons/items in the launcher when they extend beyond the window/screen.

**Comment by draekko** [comment]
Addendum:

(using unity, ubuntu 15.04)

I found that using the 'super' key to unhide works to unhide as well as let me scroll the launcher, using alt-f1 to unhide brigns the launcher up but won't let me scroll through the launcher items and using the mouse to edge trigger the launcher doesn't work. 

When i setup up with client top of server i can use the mouse to edge trigger the launcher but stuck with the above behavior for the client. 

When setup with client left of server then both have the issue with no edge trigger for the launcher and i have to use the 'super' key for both.
