### ISSUE TITLE
More friendly build error for missing Bonjour dependency

### ISSUE THREAD

**Issue by v-yadli** [symless/synergy-core#4298]
Tried to build following the wiki guide but got errors while building the gui:
`In file included from src\ZeroconfRegister.cpp:18:
src\/ZeroconfRegister.h:32:20: error: dns_sd.h: No such file or directory`

Grabbed dns_sd.h and put that file under src/gui/src and then it builds fine.

**Comment by sorinello** [comment]
Which version of mDNSResponder did you download ? I see a lot of versions: http://opensource.apple.com/tarballs/mDNSResponder/

**Comment by v-yadli** [comment]
@sorinello The one with biggest number. :-D
