### ISSUE TITLE
Mouse cursor disappears on client (ubuntu 14.04)

### ISSUE THREAD

**Issue by Dinoshauer** [symless/synergy-core#4317]
I built synergy 1.6.2 following the instructions in the wiki linked in the readme (http://synergy-project.org/wiki/Compiling)

I'm using the same binaries on both the server and client, there are no problems connecting from the client to the server but the mouse disappears on the client when moving from the server to the client.

I have temporary solved this by setting

```
gsettings set org.gnome.settings-daemon.peripherals.mouse locate-pointer true
```

and pressing the `ctrl` key rapidly to see where the cursor is :)

Let me know if you need more info

**Comment by erwelch** [comment]
I have the same issue, version 1.6.2 on both host (windows 7 64bit) and client (ubuntu 14.04).  Just upgraded today to see if this was fixed as it happened on the older 1.5.0 I was running previously.

I usually solve it by moving the mouse back to the server screen, then back to the client.  If i do this a few times the pointer usually shows up on the ubuntu 14.04 client.

Interestingly, I don't have the problem in the reverse order, same machines, ubuntu as the server and windows as the client, never has this issue.

**Comment by panthony** [comment]
I have the same issue with version 1.7.3 and both host on ubunty 14.04.

And like erwelch if I move it back and forth between client and server it will eventually shows up.

**Comment by josiahcarlson** [comment]
I experience the same issue on and off, running 1.7.2 on Ubuntu 14.04 client and Windows 7 server.

Moving the mouse out and back to the Ubuntu machine as erwelch mentioned does not work for me.

**Comment by acron0** [comment]
Experiencing the same issue as @panthony on 1.7.4, both server and client are Ubuntu 14.04

**Comment by lgreer84** [comment]
Is there any update here. I've got the same thing. Ubuntu 15.04 and GNU 4.1. It's strange that the pointer only disappears every other time I traverse screens. Also, when doing a screenshare in Hangouts, the pointer may be invisible on my screen but I can see it in the screenshare. Strange...

**Comment by acron0** [comment]
As of today, this issue is no longer showing itself. Synergy still reports 1.7.4 but something's obviously changed. Weird.

**Comment by panthony** [comment]
After an update on the 1.7.4 I have the same symptoms as @acron0.

It feels a lot less random though as the first time will always fail and the second time will always work.

Note that In my case the client is a laptop and if I touch the trackpad the cursor will immediately reappear where it was supposed to be.

**Comment by acron0** [comment]
That's also a detail I left out actually, thanks @panthony. My client is a laptop also and touching the trackpad does indeed reveal the mouse cursor.

**Comment by Dr4ik** [comment]
I have the same behavior as @acron0  does.
Also I need to mention that the client is working on the notebook with touchscreen when I tap the touchscreen the cursor disappears and mouse movement can't bring it back.

**Comment by magwe** [comment]
I am running 1.6.2 on all of my 3 computers. Ubuntu 15.04 synergy server, to the left an ubuntu 15.10 client and to the right a win8.1 client.

Moving mouse to/from windows works just fine, but moving to the ubuntu client will hide the mouse cursor on every other attempt. This is 100% repeatable so I have learnt to cross screens by going left, right, left.

The mouse cursor can be seen flickering at the edge of the screen before disappearing.

**Comment by anisse** [comment]
@magwe : have you tried the xinput trick ? It did the job for me.

**Comment by magwe** [comment]
@anisse Thanks!  that workaround works for me to, and my ubuntu client has a touch screen as reported in the other thread.

**Comment by acron0** [comment]
Disabling the touchscreen device also fixes it for me, but re-enabling it brings back the issue.

**Comment by panthony** [comment]
For me, the following did the trick: https://github.com/symless/synergy/issues/4289#issuecomment-125449759

**Comment by hojjatabdollahi** [comment]
This bug still exists in:
Synergy 1.8.5 stable ubuntu 16.04.1
The server is: Synergy 1.8.5 stable Windows 10.
If you move the cursor back to the server and then again to the client, it will appear, but it is very inconvenient.

**Comment by chainsawbeaver** [comment]
The bug still exists:
Synergy _Pro_ 1.8.7-stable9799e96 (Build 19.01.2017) (on Windows and Linux)
Client: Ubuntu 16.04
Server: Windows 10 Pro
> If you move the cursor back to the server and then again to the client, it will appear, but it is very inconvenient.
Same for me.
If I use the touchpad of the client the mouse will appear.

**Comment by trent-waddington** [comment]
Okay, weird. The solution I found is:

export DISPLAY=:0
<run synergy>

Strangely without a correct DISPLAY environment variable synergy still works but the cursor display doesn't? Okay.

**Comment by skipcope** [comment]
Know this applies to Ubuntu versions higher than 14.04, but this problem is also caused by running gnome via wayland. Guess they'll eventually need to change their code to support wayland. Once I'd logged out and changed the login option to use straight-up gnome, no problems at all. Just FYI.
