### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by davidgro** [symless/synergy-core#4325]
The place I work has a lot of computers. That's an understatement. The internal network is probably larger than many countries' networks. Anyway despite my work (Synergy server) PC being on what appears to be a class B IPv4 block in the internal network (one of many blocks and types of blocks) any time it goes to sleep or hibernates there is a good chance it will have its IPv4  address stolen by something else that needs one and get itself assigned a new one. My synergy client PC then needs to wait a long while for the DNS to update to pick up my server's new IP. 

In the mean time, everything has an IPv6 and it would be really nice to just give that to the client (or even just have it find it from DNS) since I am pretty sure that one never needs to change.  When I tried it apparently treated it as a hostname and failed to connect.

**Comment by nbolton** [comment]
Duplicates #4154

**Comment by nbolton** [comment]
See PR #4499

**Comment by tjpatter** [comment]
Any updates on IPv6 support?

**Comment by wltjr** [comment]
Synergy is the only program I still have to use IPv4 for....
```
ssh -f -N -L 127.0.0.1:24800:host:24800 host
```
vs
```
ssh -f -N -L [::1]:24800:host:24800 host
```

Really need to add IPv6 support sooner than later. Some of us are looking to stop using IPv4 and synergy is causing it to remain. Thanks!

**Comment by brianjmurrell** [comment]
> Duplicates #4154

That is actually a PR, not an issue.  If that PR actually work{s,ed} and got landed, it would "Fixes #4325", not really duplicate it.

But I guess the latest PR for this is now #4499, but sadly it has not landed either.  It's now listing a ton of conflicts.  I wonder how many of those were present 3 years ago when the PR was pushed.

@nbolton Given that there are patches for this and they just need porting, and given that IPv6 is *now* and not *tomorrow* for [some people](https://en.wikipedia.org/wiki/IPv4_address_exhaustion#Exhaustion_dates_and_impact) is there not even a junior developer who could bang this out in a day or two?

**Comment by wltjr** [comment]
I am not sure about those conflicts. I am using the patches in that PR #4499 , they apply and work fine with synergy-1.8.8. I will comment on the PR.

**Comment by brianjmurrell** [comment]
@wltjr Or push a new PR and let's get this landed already.  :smile:

**Comment by wltjr** [comment]
I considered such but its another's work. I guess it does not apply to 1.9.x thus the conflicts in the PR. I need to check-out or see about running a live version. If need be I can see about stepping up to the plate and taking a swing.

**Comment by wltjr** [comment]
There you go, took a swing :)

**Comment by brianjmurrell** [comment]
@wltjr Make a PR.  Let's get this reviewed by Symless and landed, please.  :-)

**Comment by wltjr** [comment]
@brianjmurrell I did see PR #6178

**Comment by brianjmurrell** [comment]
@nbolton Can you please have somebody review #6178 and land it if it's acceptable?

**Comment by wltjr** [comment]
For anyone interested in IPv6 support in synergy. I think we need to start making noise, daily or weekly till it gets merged. It is going on 3 years now. I remade the patches in another PR. Those now have new conflicts that must be resolved. I had hoped remaking them would get them accepted vs ignored again.

I can remake again, but it needs to be accepted not ignored. I think it is beyond time for this issue to be resolved. Thus we all need to start making noise till that is the case. Seems being patient is not working....

**Comment by nbolton** [comment]
Duplicates #4154
