### ISSUE TITLE
3D Connexion Mouse

### ISSUE THREAD

**Issue by ruthmann88** [symless/synergy-core#4334]
Hi,

I used a USB 3D Connexion Mouse for CAD/CAM software. Have anyone been able to get other mouses working in Synergy besides a standard mouse? I've tried but can't get this going.

Thank you

**Comment by nbolton** [comment]
@the-wes @speaker

**Comment by the-wes** [comment]
This is a feature request. This mouse does not work at all via Synergy, after switching to the client, no mouse events are carried out on the client.
