### ISSUE TITLE
Clicks not registering on MySQL Workbench

### ISSUE THREAD

**Issue by soccerob** [symless/synergy-core#4346]
Version 1.6.2 (client and server)
Left and right clicks are not registering anywhere on the initial launch screen. once I connect to a database, the mouse works normally, just not on the first screen (attached).
I can focus the window if it's not on top, but no other clicks anywhere from the server's mouse register.

![temp](https://cloud.githubusercontent.com/assets/151275/6023892/68db46f8-ab95-11e4-9b88-b6b22ea1394b.png)

**Comment by nbolton** [comment]
Related: #4005, #3811
