### ISSUE TITLE
Drag and drop to client tries to complete a nonexistent file transfer

### ISSUE THREAD

**Issue by LostSnail42** [symless/synergy-core#4377]
Right clicking right after a file was transferred with the drag feature causes the client to try and complete a second transfer. This transfer fails with a debug message saying that there were zero files to transfer.

Windows seams to lock up a little if you do this immediately after the transfer finishes, but so long as the right click is the first [loggable] action to take place after the transfer, this error occurs.

DEBUG: dropping file, files=1 target=C:\Users\Me\Desktop
DEBUG: starting write to drop dir thread
DEBUG: dropping file, files=0 target=C:\Users\Me\Desktop
ERROR: drop file failed: drop target is empty

**Comment by XinyuHou** [comment]
I can reproduce it on my Windows 7 server and Mac OSX 10.10 client with Synergy 1.6.2
