### ISSUE TITLE
Can't relay super key to client

### ISSUE THREAD

**Issue by matzipan** [symless/synergy-core#4379]
Hello,

Ubuntu 14.04 server and Mac OS Yosemite client.

When pressing the super key while the client is active, the server intercepts it and display launcher and help message.

Expected: key press only interacts with mac client.

**Comment by luser** [comment]
I see this as well, Ubuntu 14.04 server with Windows 7 and OS X 10.10 clients. If I press the Windows (super) key with the mouse on one of the client screens it works properly, but when I move the mouse back to the server screen the Ubuntu launcher shows up.
