### ISSUE TITLE
Clipboard unreliable from Mac server to Linux client

### ISSUE THREAD

**Issue by triddle-socialflow** [symless/synergy-core#4394]
I did search the bug reports and obviously copy/paste is a big problem for a lot of people. There's so much I can't identify if this is a duplicate bug report or not. If this is a dupe I'm sorry to cause noise. I have a feeling this will turn into a feature request though.

Synergy versions in use: 1.6.2 on both machines
Mac: 10.8.5
Linux: Debian Wheezy (7.8) all updates applied

Problem description: 
When copying from the Mac and pasting on the Linux computer the paste operation is not reliable. In all my tests the paste destination is the Linux machine and the target program is Konsole.

Things that do work: copy from Firefox and TextEdit (on the Mac) if TextEdit does not perform any text formatting. 

Things that do not work: copy from TextEdit if I try to copy text that I set as bold and copying anything from OS X Terminal (which is configured with a theme so probably contains text formatting data)

Expected behavior: copy from Mac from any program will paste into any program on the Linux side

Workaround: if I run pbpaste on the Mac then attempt the paste operation again (not copy again, just paste again) then the content will paste as expected. I have a feeling Konsole is sensitive to text formatting and that is why it rejects the paste request then pbpaste adjusts the Mac paste buffer to strip formatting info and the paste works on the remote side.

Feature request: If my hypothesis about pbpaste and formatting data is correct add option to synergy server that forces all paste operations to happen as plain text. I would think the best way to do this would be to have the option specifically be "remove text formatting data from paste buffer when performing screen transition" and the default should be off as most bug reports are about people saying they lose the formatting data which is valuable to them.

However for my use case copying plain text is all I ever do. The feature as requested I think would enable my expected behavior. Or at least it works in my head.

Sorry to add more to the copy/paste nightmare of tickets but this is a PITA for me.

Tyler

**Comment by beporter** [comment]
This does sound quite similar to #2909. This issue is that "rich" text or html content is not copied between Synergy machines faithfully; only plain text.

As an alteration on the experiment you've already run:

Copy "rich" text (either formatted TextEdit text, or styled text from a browser) and first paste it into a truly "plain text" editor like [TextWrangler](http://www.barebones.com/products/textwrangler/) _on that same machine_. This has the result of stripping the formatting from the text since the receiving program doesn't support it. (The same as pbpaste does as you describe above.) 

Then **re-copy** the text now-plain text from TextWrangler and attempt to paste it on the linux machine.

This should work pretty reliably, and confirms that the issue is with Synergy's inability to copy rich text across systems, not with any of the apps you're using themselves. Myself, I'd rather that rich text copying worked again (it used to-- this is a regression), instead of always forcing plain text.

**Comment by nbolton** [comment]
Assuming Mac server to Linux client?

**Comment by triddle-socialflow** [comment]
Thanks for paying attention to the issue.

Confirm that the Mac is the synergy server and the Linux machine is the Synergy client.

Here are the results of my experiments:

Using Apple's TextEdit to generate text that is decorated as bold and with a font size increase then pasting into Konsole is unreliable. The kicker here is if I perform the copy command 2 or more times inside TextEdit then paste of the formatted content into Konsole it will work with out any additional steps at all. 

Stopping synergy client and synergy server, then starting them back up again, then using Apple's TextEdit to generate text that is decorated as bold and with a font size increase then pasting into Konsole is reliable. There is no double copy requirement here. Performing a few more copy and past operations will break paste into Konsole. Repeat: when then synergy processes are freshly running paste is reliable but a few additional copy/paste cycles breaks it.

Using Apple's TextEdit to generate text that is decorated as bold and with a font size increase then pasting into TextWrangler, copying the content again, and pasting into Konsole is reliable. Issuing single copy commands on the Mac works fine in this case.

Using Apple's TextEdit to generate text that is decorated as bold and with a font size increase then pasting into TextWrangler then pasting into Konsole (with out copying the content inside TextWrangler) is reliable. 

Using Apple's TextEdit to generate text that is decorated as bold and with a font size increase then running pbpaste then pasting into Konsole remains reliable. 

I hope that helps you find the regression! I was quite surprised to discover freshly running synergy processes don't exhibit the copy/paste problem and it was discovered entirely by accident.

Cheers,

Tyler

**Comment by nbolton** [comment]
Thanks for the extra info Tyler!

**Comment by triddle-socialflow** [comment]
I'd still prefer an option that forces plain text copy/paste all the time as it fits my personal use case perfectly and I'd rather be able to use the tool with out hassle in the face of a regression such as this one.

Thanks again for looking into the issue though.

**Comment by triddle-socialflow** [comment]
Since this is a regression what is the last known version of Synergy that does not have this copy/paste bug? Perhaps using the version prior to the regression is sufficient and I won't have to get my hands dirty with the code in an attempt to make Synergy useful for me.

Thank you.

**Comment by beporter** [comment]
I used v1.4.x for a very long time specifically to avoid this regression. However, there are known issues (with Windows 8 and the shift key just for example) back in 1.4, so even if you solve this particular problem you may end up with a different (worse) one. 

That said, it worked for me because none of the problems in 1.4 happened to affect my use case, so your mileage may vary, and it's definitely worth a shot in my book. That's a better shot than the devs having time to implement your feature request, based on my experience. (**No slam against them**-- they're just incredibly busy putting out the "newest serious fire" pretty much all the time, or implementing new features that people are really clamoring for, like zero-conf connections or drag and drop file transfers. They don't have the resources to also have people working on the "little stuff," but given their revenue model I have to give them a pass for that. They do extremely well with the limited funds they have available.)

**Comment by triddle-socialflow** [comment]
Thanks for the info, I'll give it a shot keeping bug #9 in mind.

**Comment by unix-ninja** [comment]
This has been a long-standing issue with synergy for many years, and it is not limited between Just OSX and Linux. As far as I have ever been able to tell, the problem occurs when copying from a synergy server and trying to paste to a synergy client, regardless of OS or synergy version installed.

I have developed this work-around for my workflow, which sucks but does work for me 100% of the time:

* Copy data on my synergy host
* Mouse over the the synergy client
* Immediately mouse back over to the synergy server
* Immediately mouse back over to the synergy client
* Now paste on the synergy client seems to work as expected

Unfortunately, I have to do that little mouse-dance every time I want to copy/paste something from server to client.

Hopefully someone can narrow down the issue from here.

**Comment by phemmer** [comment]
> I have developed this work-around for my workflow, which sucks but does work for me 100% of the time:

Thank you for this. I've been manually writing the clipboard to files and `scp`ing them over to my other box when I need it (extremely painful). I've just tested and this workaround works much better.

**Comment by knowncitizen** [comment]
This appears to be fixed with #4994 for me

**Comment by XinyuHou** [comment]
Hi Guys, please try out our 1.7.5 release to see if it fixes this problem.

**Comment by unix-ninja** [comment]
Unfortunately, 1.7.5 causes my clipboards to stop functioning altogether between machines. I ended up rolling back to correct.

That said, when I rolled back I got version 1.6.2 on the client (I have 1.7.0 on the OS X server) and now it's working. Weird that 1.7.0 client was not working but an earlier version is.

**Comment by XinyuHou** [comment]
Sorry my bad, I meant to say 1.7.6

http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc1-dcc1c

**Comment by unix-ninja** [comment]
Well, 1.7.6 doesn't appear to kill the clipboards, but it doesn't fix them either. I still have to mouse back and forth twice before I can paste from the server to the client. (This is running 1.7.6 on both server and client).

**Comment by ryancmoon** [comment]
I am experiencing this issue on 1.7.6 as well. Linux server, OSX client.

**Comment by miraculixx** [comment]
I'm experiencing the same issue intermittently in 1.8.2-stable-36cd521. I haven't found a way to reproduce reliably but I notice that it usually works when both machines are freshly booted and then at some point just stops working for no apparent reason...

**Comment by nlyan** [comment]
Can you guys try out 1.8.3 RC2?

http://symless.com/nightly?filter=89c9c58

**Comment by unix-ninja** [comment]
I am testing with 1.8.5 on OSX (server) and still have 1.8.2 on Fedora (client).

It's working about 50% better. Half of the time the clipboard is actually working as intended. But the other half of the time, I still need to mouse back and forth to get my clipboard data on the client. I am not sure what the pattern is when it doesn't work vs when it does. So far it seems rather random.
