### ISSUE TITLE
Allow keystroke to switch system that has focus

### ISSUE THREAD

**Issue by hexmode** [symless/synergy-core#4421]
I would like to be able to avoid using the mouse to switch between systems.

**Comment by hexmode** [comment]
https://twitter.com/hexmode/status/571044125870575617

**Comment by nbolton** [comment]
@the-wes Isn't this possible with hotkeys?

**Comment by the-wes** [comment]
Yes, you can define a hotkey to switch screens, but this is somewhat limited. There is no "toggle" option, to cycle through all the available screens with a single keystroke. We have one to switch to a specific (named) screen, and one to switch in a given direction. We might be able to enhance this by making the directional one wrap around, perhaps optionally.

The other limitation is that this is mostly broken on Mac servers (hotkeys in general, not just screen switching via hotkey).

**Comment by nbolton** [comment]
Thanks @the-wes -- @hexmode does this solve the issue, or do you want to toggle?

**Comment by hexmode** [comment]
the-wes writes:

> We might be able to enhance this by making the directional one wrap
> around, perhaps optionally.

How much effort would it take to implement this?

> The other limitation is that this is mostly broken on Mac servers
> (hotkeys in general, not just screen switching via hotkey).

I don't need this on a mac, so this isn't an issue.

**Comment by the-wes** [comment]
@nbolton You'll have to field the question about how much effort it would take to implement the wrap-around function. I don't know how it works. If there's any significant development required, it makes more sense to spend it on a generalized "switch to next screen" function with some way to configure in which order the screens will be switched to.

**Comment by nbolton** [comment]
Hmm, let me have a think about this. We already have wrap-around so perhaps I'm missing something?

**Comment by hexmode** [comment]
Could you point me to the documentation for the wraparound?  It looks
like I can do this but it requires modifying the configuration file.

I can do that, but how much effort would it be to make this available in
the GUI?
https://davejamesmiller.com/blog/synergy-hotkey-to-toggle-screens

**Comment by nbolton** [comment]
Did you mean a GUI wrap option, or a GUI toggle option, or both?

**Comment by hexmode** [comment]
I meant I would like a way to set synergy from the GUI so that it will
wrap to other desktops since the only way that I see to do that now is
by editing the configuration file.

I'm not sure what you mean by "GUI wrap option, or a GUI toggle option".

**Comment by nbolton** [comment]
> I'm not sure what you mean by "GUI wrap option, or a GUI toggle option".

Well, the title "toggle" - but now there's talk about wrapping. Did you want an option to toggle, or wrap, or both?

**Comment by beporter** [comment]
For future Googlers' reference, here's a sample manual config file for two monitors arranged horizontally, that allows for wrapping the cursor from the outside edge of each screen to the opposite far edge:

**sample synergy.conf**:
```
# Physical monitor arrangement, with machine names as used by Synergy.
#  +----------+----------+
#  | syn-serv | syn-cli  |
#  |          |          |
#  +----------+----------+

section: screens
	syn-serv:
	syn-cli:
end
section: links
	syn-serv:
		left = syn-cli     # "wrapping" arrangement
		right = syn-cli    # "normal" arrangement
	syn-cli:
		left = syn-serv    # "normal"
		right = syn-serv   # "wrapping"
end
```

_(The [current wiki](http://synergy-project.org/wiki/Text_Config) isn't as fully fleshed out, so I used [this old doc](http://synergy2.sourceforge.net/configuration.html) for reference.)_

This may take some fiddling if you have a more complex arrangement. The GUI config tool only exposes a subset of the available options that Synergy supports.

**Comment by legonigel** [comment]
This has been [added to the wiki](http://synergy-project.org/wiki/Text_Config#Cursor_Wrapping). I took @beporter's config example and added it to the wiki.

**Comment by hexmode** [comment]
Updated a smidge to actually include a keypress example: http://synergy-project.org/wiki/index.php?diff=940&oldid=937
