### ISSUE TITLE
Auto config prompt shows for wrong client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4426]
1. Start client GUI (A)
2. Start server GUI (B)
3. See that no prompts appear
4. Start client GUI (C)
5. See that GUI for client A prompts
6. Ignore GUI prompt for client A
7. Restart GUI C
8. See that GUI for client A prompts (again)

**Comment by XinyuHou** [comment]
#4237 More auto config logging for troubleshooting would be helpful for diagnosing this issue.
