### ISSUE TITLE
Exclude 169.254 addresses from IP Addresses list

### ISSUE THREAD

**Issue by the-wes** [symless/synergy-core#4438]
They're basically useless, all they're doing is confusing the users. Please remove them from even being displayed.

**Comment by recluse2** [comment]
I think I might be seeing issues with this, I am looking at my OpenDNS logs and under domains I am seeing unbelievable amounts of traffic listed as *> No Idea what is means but Synergy undoubtedly is the cause. I run Synergy for a day and I am getting 133,000 requests. Don't run Synergy and see the normal ~6000 requests for my network. Just curious as to what would cause such a tremendous jump. Do I have something misconfigured somewhere?
