### ISSUE TITLE
GUI status depends on log level being above note

### ISSUE THREAD

**Issue by daveseah** [symless/synergy-core#4466]
When installing Synergy 1.6.3 on Mac OS 10.10.2 in SERVER mode, I noticed that the process didn't seem to start. The dialog status at the bottom left shows "Synergy is Starting", but it never changes to "Synergy Running". The dropdown in the task bar also never updates status. Synergy however does appear to be functioning intermittently, but there is no way to control the stop/start of the service as I would expect. (see screenshot)

If I change the log level in preferences to NOTE or INFO, then the status and dropdown task menu appears to run correctly. I see the "Synergy Running" as expected, and it appears to work. 

This behavior also seems to be present in the Windows 8.1 64-bit 1.6.3 running as the client. 

![screenshot 2015-03-22 02 40 48](https://cloud.githubusercontent.com/assets/2048828/6768363/eeaddff4-d03c-11e4-8303-e2fe0e63518a.png)

**Comment by XinyuHou** [comment]
This is similar to issue #4836 except for the menu-bar widget instead of the dialog box. When the server is already running, you are giving the option to start it but not to stop it. In other words, the menu doesn't reflect the actual state of the server.
image
Synergy 1.8.2 on Ubuntu 16.04
