### ISSUE TITLE
Firewall exception for GUI on Windows does nothing

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4467]
1. Install on Windows
2. Run GUI
3. See "allow access" dialog

The issue here is that you shouldn't see this dialog in the first place because adding a firewall exception should have taken care of this.

![image](https://cloud.githubusercontent.com/assets/313427/6769093/4d23e4fa-d085-11e4-840e-f60e9d85988a.png)

**Comment by thanhphu** [comment]
You meant you click on the allow access button and nothing happens? Maybe you need to run Synergy with Administrative privilege, just my guess
