### ISSUE TITLE
Linux client without physical mouse never initializes cursor on client

### ISSUE THREAD

**Issue by pglombardo** [symless/synergy-core#4474]
I searched but couldn't find this issue - hopefully not a dup.

OSX 10.9.5 Synergy 1.6.2 server with Ubuntu 14.04.2 LTS synergy 1.6.2 client.

After I boot my linux box, synergy correctly initializes and connects to the client.  But it seems that on the Ubuntu box the X cursor never initializes because there is no physical mouse attached to the box.

Moving the cursor from the OSX screen to the Ubuntu screen shows the cursor disappear from the OSX but nothing is visible on the Ubuntu box.

There is even a message in the Synergy server log but I'm not sure how to resolve other than below:

```
INFO: switch from "the-nothingness" to "hanzo" at 0,271
INFO: leaving screen
WARNING: cursor may not be visible
```

The manual work-around is to attach a physical mouse to the Ubuntu box to initialize the cursor (and then remove it) and synergy works as expected.

Both Ubuntu and OSX use Synergy 1.6.2

**Comment by naniid** [comment]
Same issue. And same platforms combination. OSX 10.10 as server and Ubuntu 14.04 as client.
