### ISSUE TITLE
Server stops working after inactivity on Windows

### ISSUE THREAD

**Issue by danci1973** [symless/synergy-core#4481]
Synergy 1.6.3 (was the same in previous version)

Sometimes when I come back to my computers after a period of inactivity (15+ minutes) I find the Synergy service on Windows 7 not working properly. Opening the GUI, the shows the following:

  NOTE: connecting to service...
  NOTE: connection established
  activeDesktop:Default
  synergys.exe: no configuration available
  ERROR: failed to launch, error: process immediately stopped
  activeDesktop:Default
  synergys.exe: no configuration available
  ERROR: failed to launch, error: process immediately stopped
  activeDesktop:Default
  ERROR: could not get session id for process id 6512

This then repeats until I click the 'Start' button, after which the log shows:

  NOTE: starting server
  NOTE: config file: C:/Users/danci/AppData/Local/Temp/qt_temp.H22292
  NOTE: log level: NOTE
  activeDesktop:Default
  NOTE: started server, waiting for clients
  NOTE: accepted client connection
  NOTE: client "Lightning" has connected

I don't know how to reliably reproduce as it doesn't happen every time I leave the machine, but I notice it about 2-3 times a day (on average day).

**Comment by neutrinog** [comment]
I just had this occur on my computer again. This time I was recording the log.
Here's the log file https://www.wetransfer.com/downloads/e264ddd58ab430cd61b09fd4dd12dbc020150619173510/012c2b212ac11a5d37a07af2bff03ec520150619173510/c543e3
