### ISSUE TITLE
Add license GPLv2 license file to install directory

### ISSUE THREAD

**Issue by legonigel** [symless/synergy-core#4491]
The current installer doesn't include the license in the binary. Under GPL we are required to [distribute the license with the binary](https://www.gnu.org/licenses/gpl-faq.html#WhyMustIInclude). We should also link to this license from with the GUI. Under GPL we are also required to include a written offer to provide source code upon request (I recommend adding a link to the github from the GUI).

**Comment by acook** [comment]
The current installer shows the GPL as part of the installation process, but a license file is missing from the installation directory, and the about screen should link to the github page as well.
