### ISSUE TITLE
Feature request: Capture hotkey on client and invoke it on server

### ISSUE THREAD

**Issue by StephenBeirlaen** [symless/synergy-core#4505]
Since I have connected an audio system with no volume control within reach to my Synergy server, I am using a small application that controls my Windows master volume with F7 and F8. They are system-wide hotkeys, so no other application (including Synergy) is allowed to use them.

I am very used to press these keys randomly to control the volume, so if my client machine has focus and I accidentally press them, it causes me to do unwanted actions that were already tied to these keys in the program currently active on my client. This is pretty annoying, so I tried to setup hotkeys on my synergy client, that will get sent to the server. But it seems I can only setup hotkeys on the server, for use on both the client(s) and the server. This is a problem because I can't register F7 or F8, they are already reserved by my app.

I would like to register hotkeys on individual clients and send them to the server/other clients.

**Comment by beho1der** [comment]
I support this functionality, but I would like that it worked in reverse mode, that is, when on server, press a certain key, the client runs a specific combination of keys on the keyboard (macros)
