### ISSUE TITLE
osx: synergys hotkeys broken - Unable to program mouseless synergy.

### ISSUE THREAD

**Issue by John-Appleseed** [symless/synergy-core#4512]
- Unable to program mouseless synergy.
- synergys is unable to bind keystrokes on osx :( 

Is there a **CLI action to switch displays**  to synergys or synergyc? to benefit mac/linux/windows users to use their own custom hotkey program.

```
synergys --action "switchInDirection(left)" # server side CLI Action
synergyc --action "switchInDirection(left)" # client side CLI Action
```
### GUI Method

keystroke(shift+PageUp) = switchInDirection(Up)
    keystroke(shift+PageDown) = switchInDirection(Down)
    keystroke(shift+Home) = switchInDirection(left)
    keystroke(shift+End) = switchInDirection(right)

*Note: osx Synergy GUI does not capture Home, End, PageUp, or PageDown :(
### synergy.conf Method

``` conf
section: options
    relativeMouseMoves = true
    screenSaverSync = true
    win32KeepForeground = false
    switchCorners = all 
    switchCornerSize = 25
    keystroke(shift+PageUp) = switchInDirection(Up)
    keystroke(shift+PageDown) = switchInDirection(Down)
    keystroke(shift+Home) = switchInDirection(left)
    keystroke(shift+End) = switchInDirection(right)
end
```

**Comment by the-wes** [comment]
To answer your question, there is not currently a way to do this. Also, the hotkey bug is documented here: https://github.com/synergy/synergy/issues/3705
