### ISSUE TITLE
Missing header: XKBlib.h when running configure on ElementaryOS Luna

### ISSUE THREAD

**Issue by MartinDelille** [symless/synergy-core#4514]
I try to compile Synergy on ElementaryOS Luna (based on Ubuntu 12.10 LTS) but I have the following error when trying to run the configure script:

```
$ ./configure
CMake Error at CMakeLists.txt:219 (message):
    Missing header: X11/Xlib.hX11/XKBlib.h

-- Configuring incomplete, errors ocured!
```

Both files _Xlib.h_ and _XKBlib.h_ are present in the _/usr/include/X11_ folder.

**Comment by kevleyski** [comment]
Try editing CMakeFiles.txt to make /usr/local/include /usr/include
