### ISSUE TITLE
Mac icon doesn't drag if clicked inside the circle.  

### ISSUE THREAD

**Issue by alanhoyle** [symless/synergy-core#4523]
This isn't a problem with Synergy running, but a problem with the icon itself under OSX.  The Synergy.app icon is "hollow" from the finder's perspective.  That is, if you try to use the Finder to move the application (e.g. from the .DMG to the Applications folder) and you click on the transparent part inside the blue circle, the click doesn't register as on the icon, but passes through to the background finder object (E.g. the folder window of the DMG or the Desktop).  This issue also occurs when you try to double-click the icon to start it up.  

If you click in the blue part of the "O", everything works as expected, but if you click on the transparent interior of the "O" the clicks don't register as expected.

**Comment by beporter** [comment]
This used to be solved by adding the proper 1-bit hit mask to the icon. It was possible to make the center of the circle transparent (so you could see whatever is "underneath" it) but still "hit-able" (so it was still clickable).

I'm no graphic designer, but I think the Mac icon format has changed with the advent of Retina. [This (old) MacInstruct article](http://www.macinstruct.com/node/59) explains the concepts that used to work. I have no idea if it's still possible to specify an alpha channel to control icon transparency, **and** a hit mask to control click-ability. I haven't been able to find a tool that appears to do it, at least.

**Comment by speaker** [comment]
@nbolton might want to take a look at this.
