### ISSUE TITLE
Work on windows without administrative permission

### ISSUE THREAD

**Issue by zhanghuan** [symless/synergy-core#4531]
I hope there is a way for synergy to work as a client  in a windows without the need for administrative permission.

More specific requirement would be:
1. No need to install to run. Just provide a standalone exe.
2. No need to ask for administrative permission if running as a client.

**Comment by speaker** [comment]
This might be better asked and addressed on the new forums http://synergy-project.org/forum

**Comment by jrhortian** [comment]
Did this get any traction on the forums?
