### ISSUE TITLE
Mac client crashes on SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4558]
Mac 10.10.3
1. Connect Mac client to Windows server
2. Restart Windows server
3. Mac client prints SSL_ERROR_SYSCALL error and crashes

```
DEBUG: hiding cursor
NOTE: connected to server
ERROR: secure socket error: SSL_ERROR_SYSCALL
DEBUG: showing cursor
```

**Comment by XinyuHou** [comment]
@nbolton 

Not reliably reproducible. Should we move it into next milestone?

**Comment by XinyuHou** [comment]
@nbolton 
I guess it is a timing issue. The underlying socket I/O is closed. A SSL call is invoked before the secure socket is notified about the shut down.

**Comment by botsmack** [comment]
I can't reproduce this, but I have experienced twice already. It usually starts working again after I stop the server (Win 8.1 64-Bit) and the client (Yosemite 10.10.3), wait a minute or so, restart the server, and then connect the client.

**Comment by ENickRyan** [comment]
I just wanted to share I can recreate this issue reliably. It occurs when dragging and dropping files between systems. My server  is Win 8.1 64-Bit and the client is Yosemite 10.10.3. After I "start" synergy on the mac it disconnects a second time. After I "start" synergy a third time, it works indefinitely until I accidentally drag a file to the screen edge.

**Comment by bitprophet** [comment]
This seems to happen to me reliably 100% of the time:

* Windows (Win7) system is the Synergy server and is powered down most of the time
* Mac (10.10.3) system is the Synergy client and is always on / always has Synergy running
* On previous Synergy versions, the Mac client would reliably, automatically reconnect whenever the Windows server powered on.
* On 1.7.2, the Mac client halts with the `SSL_ERROR_SYSCALL` message every time the Windows server powers off, forcing me to hit 'Start' on the client again when the Windows server is next powered on.

Re: @ENickRyan's comment, I do not use file drag/drop, only cursor sharing.

**Comment by nbolton** [comment]
Related? #4691

**Comment by nbolton** [comment]
@XinyuHou Happens constantly for me (Mac client), usually when stopping/starting the server. Hard to reproduce reliably though. Just happened now...

![screen shot 2015-05-19 at 1 53 15 pm](https://cloud.githubusercontent.com/assets/313427/7703261/a8908470-fe2e-11e4-98da-de05a4d1f7e6.png)

**Comment by gradedcatfood** [comment]
Wanted to share on this issue. I get this error every time I move my mouse over to my client machine. Dosn't happen any other time (start/stop server is fine), just moving mouse to client I get this error.
Host: 10.10.3 Mac OSX
Client: Ubuntu 14.04/ Windows 7

**Comment by speaker** [comment]
Are people still seeing this issue with 1.7.3 (and the proper plugins installed?)

**Comment by speaker** [comment]
@gradedcatfood @ENickRyan @bitprophet 
Are you still running into this issue with the latest 1.7.3 code? 
If so, do the nightly builds at http://synergy-project.org/nightly?filter=099c984 fix the issue? (they're still building, so be patient :)

**Comment by speaker** [comment]
This issue appears fixed by other changes, if it persists, we'll reopen it and hopefully new logging will help identify the issue better.

**Comment by nbolton** [comment]
@speaker According to what user?

**Comment by nbolton** [comment]
Enhancement #4901 should help in the meantime.
