### ISSUE TITLE
Key autorepeat is translated incorrectly on Windows clients

### ISSUE THREAD

**Issue by rpjohnst** [symless/synergy-core#4568]
X11 sends key repeat events with fake release events interleaved, as "Press Release Press Release..." On the other hand, Windows sends them without release events, as "Press Press Press Release."

This behavior is not correctly translated when using a Linux server and a Windows client, causing problems with applications that involve holding down keys. For example, I ran into it playing a game where holding the spacebar brings up a HUD- without disabling key repeat on Linux, the HUD flickered on and off as if the spacebar were being pressed and released rapidly.

**Comment by the-wes** [comment]
here is a video demonstrating this issue: https://www.youtube.com/watch?v=zpjv1zZwnRU
