### ISSUE TITLE
Wrong shape detection by OSX client

### ISSUE THREAD

**Issue by lacombar** [symless/synergy-core#4589]
I'm having a bit of a trouble with my OSX client. First of all, let me describe a bit of the setup. The OSX machine is on a screen shared with my main desktop, which involve switching the screen's input when moving to OSX. This machine spends a large time in sleep and the lock screen generally kicks in. When I try to start `synergyc`, the first connection generally fails. I turned debugging on today, and noticed the screen shape was incorrectly detected:

```
DEBUG1: saying hello
DEBUG1: parsing hello reply
DEBUG1: querying client "OSX" info
DEBUG1: created proxy for client "OSX" version 1.5
DEBUG: received client "OSX" info shape=-1,-1 -12817x1280 at 1919,16
ERROR: invalid message from client "OSX": DINF
NOTE: new client disconnected
```

Notice the negative resolution ?

On another attempt:

```
DEBUG1: saying hello
DEBUG1: parsing hello reply
DEBUG1: querying client "OSX" info
DEBUG1: created proxy for client "OSX" version 1.5
DEBUG: received client "OSX" info shape=29793,0 0x512 at 1919,16
ERROR: invalid message from client "OSX": DINF
```

Finally, after fiddling around with an attached keyboard (ie. hitting random key to somehow wake it up) the client connects:

```
DEBUG1: saying hello
DEBUG1: parsing hello reply
DEBUG1: querying client "OSX" info
DEBUG1: created proxy for client "OSX" version 1.5
DEBUG: received client "OSX" info shape=0,0 1920x1080 at 1919,16
DEBUG1: send info ack to "OSX"
NOTE: client "OSX" has connected
```

From this point on, I can use everything.

**Comment by jamesawebb1** [comment]
In my setup, I have an SSH tunnel between client (Mac OS X) and server (Ubuntu) with the client connecting to localhost.  I occasionally get a lot of these "invalid message from client <client>: DINF" messages.  I'll set debug logging the next time this occurs.  They're easily solved by restarting the client.
