### ISSUE TITLE
Add visual effect around cursor when making screen transition

### ISSUE THREAD

**Issue by scottresnik** [symless/synergy-core#4599]
Something to make the mouse position obvious when it returns from a client to a server's screen.  Retina mac clients on windows servers would benefit form this greatly.

**Comment by Mutmatt** [comment]
Or vice versa might be nice too.  I like the idea but the implementation would have to be pretty subtle, in my opinion, in order to not detract from the overall goal of a seemless 'Synergy' between machines.

Good idea though
