### ISSUE TITLE
Moving the mouse from a Xubuntu client causes the cursor to reset to the center of the screen

### ISSUE THREAD

**Issue by MitchellSingleton** [symless/synergy-core#4612]
I use the client as a kiosk.  My client is running Xubuntu 32bit and my server is running Windows 8.1 64bit.  I am running xlock on the client to lockout input.

I recently upgraded to Synergy Pro 1.7.1 and, previous versions worked the same, when I move the mouse from the client to the server the mouse on the client resets to the center of the screen.  I would prefer to have the cursor left where the mouse left the screen instead of resetting back to the center.

**Comment by joelcarlton** [comment]
I have had similar issues. Mac Client <-> Windows Server. Dragging mouse from windows to mac screen resets mouse in the center of the windows screen.

Version: 1.7.2
Server: Windows 7 64bit
Client: Mac OS X 10.10.3
