### ISSUE TITLE
Install as a service on linux and autorun

### ISSUE THREAD

**Issue by darkdragon-001** [symless/synergy-core#4622]
It would be nice to add a service script to Debian/Ubuntu/... and then run this service automatically on system startup.

**Comment by speaker** [comment]
This is an interesting topic that really plays into the design of most unix and unix like systems. Unlike the overarching design of windows, *nix separate users far from the notion of the OS. As a result, applications that are user-centric don't really run until that user is logged in. Suppose Synergy was a boot time service, which user would it run as? If root, what remote server would be able to connect to it? What if the one machine was running 4 remote desktop sessions, each would need a user-associated run of synergy, which would be difficult before a user actually logs in.

It really would be great, but we have to figure out how to make it behave properly. There might be some users that have some experience with this kind of use on the forums http://synergy-project.org/forum/

**Comment by avaziri** [comment]
This is definitely a situation where waiting for perfection is paralyzing you. Even if such a feature could only handle one server configuration it would serve the needs of a large amount of people, perhaps even the majority of users. As it stands the lack of this feature means that even after all this configuration I still need a second keyboard on my desk which largely defeats the purpose of this software in my mind.
