### ISSUE TITLE
On Windows, Installer does not preserve existing install folder

### ISSUE THREAD

**Issue by badger200** [symless/synergy-core#4643]
My Synergy is installed to D:\Program Files\Synergy on my Windows XP Pro 32 bit workstation.

But unlike most software, every time I update Synergy, it tries to install to C:\Program Files\Synergy, which seems like it would result in duplicate installs conflicting on my system.

I don't know how all other software is able to recognize existing installs and default re-installs to those folders, but there must be a way. If you're using NSIS and/or MSI, there must be a built in facility in those.

**Comment by tzucker** [comment]
Same on win 7 pro x64.
