### ISSUE TITLE
Connection to server is lost while using Flash website

### ISSUE THREAD

**Issue by drobson1005** [symless/synergy-core#4652]
This one is hard to reproduce, but very annoying.  Part of my day, I've got a firefox browser open on the server (Windows 7), while doing various things on my Mac client, and while this firefox browser is open to this horrible built-on-flash website hotgloo.com, performing actions within that flash window don't always cause the client to suddenly disconnect, but very often do.  I find myself reaching for my Macbook's touchpad to restart the client 30-40 times a day.  The only clue that something went wrong on the client logs is "ERROR: s", and on the server "NOTE: client "<client name>" has disconnected".  Synergy 1.7.2 on both sides.

**Comment by dtrobson099** [comment]
bump - has anyone looked at this?
