### ISSUE TITLE
The rest of the duplicate keyboard shortcuts in the GUI

### ISSUE THREAD

**Issue by davidgro** [symless/synergy-core#4667]
It's nice that Bug #4367 fixed One of the keyboard shortcut duplicates, but what about the rest of them? Alt-S is still both Start/Stop and Server IP, and Alt-C is both Client and Configure Server.

None of these (especially Alt-S, which would be nice to have for Start/Stop) are usable because of this.

(Windows 8.1 amd64, Synergy 1.7.2)

**Comment by speaker** [comment]
So it looks like the following are presently overloaded:
Alt-s is both Start/Stop and Server IP: when client is enabled
Alt-c is both "Configure Server" and "Client (checkbox)"

are there more?
