### ISSUE TITLE
Synergy becomes blocked in windows 7 when opening "everything" tools

### ISSUE THREAD

**Issue by xuelliu** [symless/synergy-core#4669]
Server: Red Hat Linux release 6.4, 1.3.6-1.el6.x86_64.rpm
Client:  Windows7, synergy-1.3.1

synergy works fine after i set up the server and client configuration.
But when i opened the everything 1.3.4 tool (http://www.voidtools.com/) in client to try to find something, (everything got the focus in current display area) the synergy blocks and i can't get any mouse, keyboard input. When i use the client's self mouse and keyboard to minimize everything window, the synergy works again.
No error or warning info for synergy on both server side and client side.
It seems that there is some conflict between synergy and everything tool and i'm not sure it's OK to submit this issue for synergy.
If you don't think so, please close it.

**Comment by xl-liu** [comment]
When a dialog opened in the Window7 (client), the synergy doesn't work either.
Such as i tried to edit the path variable from Advanced Setting of the Properties of Computer, when the edit dialog popup, the synergy doesn't work. And it became normal when i closed this popup.
