### ISSUE TITLE
Automatic client wake-up upon cursor event

### ISSUE THREAD

**Issue by lacombar** [symless/synergy-core#4671]
The following issue is to describe a potential enhancement I just had while thinking about my future working environment. I am not sure if it belongs to synergy in itself, but it might be a cool idea.
## Use case

The behavior I tend to develop in my home office is to have unused machine automatically go to sleep (as in suspend to RAM) after a preset timeout. When I want to use the machine, I proceed to wake it up remotely using wake-on-lan. Then ti can be controlled using synergy
## Problem

The process involved to wake up the machine is quite tedious, requiring to fire up a terminal, lookup for the wake-on-lan command, and then issue it. All this process could be easily automatized.

From synergy point of view, if the cursor goes on the edge, we know the current active hosts, and we know whether or not a host is expected to be on this side of the screen. If the client is not connected, it should be easy to fire-up the wake-on-lan command.
## Proposed implementation

At least on Linux, this could be implemented by adding support to execute a command upon the previous event (cursor at the edge and client not connected). I don't know about the WOL process on Windows or MacOS, though, I could look it up.

**Comment by speaker** [comment]
@lacombar , This is a pretty cool idea. We'll take a look, or maybe one of out community contributors will end up offering a pull request with the feature.

thanks!
