### ISSUE TITLE
error: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by RangerRick** [symless/synergy-core#4732]
I have yet to have an upgrade of Synergy on Windows work.  This time, I get:

`ERROR: failed to launch, error: Cannot create a file when that file already exists.`

I tried rebooting to see if it was just some open filehandle thing but that didn't help.

**Comment by speaker** [comment]
If this in the GUI window, or out of a log file?
Can you please set the logging level to DEBUG and supply the entries that include the command line?
the line will look something like: but include a number of lines around it as well.
`DEBUG: new command, elevate=0 command="C:/Program Files/Synergy/synergys.exe" -f --no-tray`...
