### ISSUE TITLE
Copy/Paste Not working on Mac/Mac

### ISSUE THREAD

**Issue by pozgo** [symless/synergy-core#4743]
Hi,

I have 2 Mac's both OSX 10.10.3 and synergy 1.7.3 and copy/paste doesn't work. 
It only did it once when I first run it and now seems to just stopped. 

I have restarted both machines/programs and whatever I could but problem seems to stay. 
Fix would be nice ;)

**Comment by panamik** [comment]
Is it not working in a specific direction (e.g. client to server, or server to client), or it doesn't work in both directions?

**Comment by pozgo** [comment]
Hi,

It is not working any direction.

Strangely enough once in a while it does work.. Lets say once every 3-4h.

Kind Regards

---


Przemyslaw Ozgo
mobile: +44 (0) 7740 814 002
email: przemyslaw@ozgo.info <mailto:przemyslaw@ozgo.info>
 <https://twitter.com/pozgo>
 <https://uk.linkedin.com/in/przemyslawozgo>
 <https://github.com/pozgo>

**Comment by nikkles** [comment]
Hi,

I have the same issue, with 2 Mac's both OSX 10.10.3 and synergy 1.7.3. If I re-start both synergy apps on both computers, it will work immediately, but not for long (in both directions). 

Then it works sporadically until it doesn't copy and paste at all.

**Comment by XinyuHou** [comment]
@pozgo @nikkles 
Did you use SSL?

If so, please check #4712. There is a nightly ready for test. And please close this issue if it's duplicated.

**Comment by pozgo** [comment]
I do not use SSL. 

So we haven't duplicated the issue I'm afraid.

**Comment by nikkles** [comment]
@XinyuHou, I just turned off SSL in the preferences on both client and server.

This seems to have solved my problem (although, it's only been a few hours, that's longer than I've had since updating to 1.7.3). 

Thanks!

**Comment by pozgo** [comment]
Hmm... My option for SSL is not active so I assume it's off..

![screen shot 2015-06-11 at 19 11 02](https://cloud.githubusercontent.com/assets/1773188/8114594/a1e2e414-106d-11e5-9583-c80074a842b0.jpg)

**Comment by beporter** [comment]
There is a long list of other existing issues that this one may duplicate here: https://github.com/synergy/synergy/issues/4735#issuecomment-108422245

**Comment by XinyuHou** [comment]
@pozgo 

Any log message would be helpful.

**Comment by XinyuHou** [comment]
@pozgo 
Please test this nightly.

http://synergy-project.org/nightly?filter=121080

If the issue persists, please send us both server and client log information. You can change log level to Debug in Synergy->Preferences.

**Comment by Kami-no** [comment]
The problem is trigger combination. In Mac OSX system hotkey is Cmd+C (Win+C). But Synergy trigger is only Ctrl+C
Copy from context menu also do not trigger Synergy.
But when you copy smth to buffer (hotkey or context menu) and then press Ctrl+C, you can paste then to another system.

**Comment by jiMuBao** [comment]
@Kami-no 
This work for me, cmd+c after copy just press ctrl +c and you can paste as normal with cmd + v on other
