### ISSUE TITLE
Windows Service terminates and cannot be restarted

### ISSUE THREAD

**Issue by craigemery** [symless/synergy-core#4771]
I can't say when this happens but only a reboot will fix it.
I'm using the 1.7.3 64 bit Windows in client mode to an Ubuntu 64 bit 1.7.3 Server.

The Windows service quits, so the GUI log has repeated lots and lots of:
"NOTE: connecting to service...
ERROR: ipc connection error, connection refused"

If I go to the service control panel, the Synergy service is stopped, but when I try to start it I get the error

"Windows could not start the Synergy service on Local Computer.
Error 1067: The process terminated unexpectedly."

Only a reboot fixes things! :-(

**Comment by craigemery** [comment]
log\synergy.log has:

DEBUG: adopting new buffer
INFO: using last known command: "C:/Program Files/Synergy/synergyc.exe" -f --no-tray --debug DEBUG --name craig --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir C:\Users\craigem\AppData\Local 10.80.2.90:24800
INFO: service command updated
DEBUG: event queue is ready
DEBUG: found sas.dll
DEBUG: getting elevated token, elevation required
DEBUG: processes in session 1: csrss.exe, winlogon.exe, nvxdsync.exe, nvvsvc.exe, dwm.exe, RAVBg64.exe, RAVBg64.exe, RAVBg64.exe, rundll32.exe, rundll32.exe, scrncap.exe, taskhostex.exe, SynTPEnh.exe, explorer.exe, ClassicStartMenu.exe, TabTip.exe, TabTip32.exe, RapidStartConfig.exe, nvtray.exe, NvBackend.exe, synergy.exe, SettingSyncHost.exe, SkyDrive.exe, SynTPHelper.exe, RtkNGUI64.exe, RAVBg64.exe, RAVBg64.exe, winvnc.exe, GWX.exe, igfxsrvc.exe, hkcmd.exe, igfxpers.exe, quickset.exe, rundll32.exe, iTunesHelper.exe, ShareFileSyncMonitor.exe, SyncEngine.exe, ScanToPCActivationApp.exe, g2mstart.exe, g2mcomm.exe, g2ax_start.exe, g2mlauncher.exe, g2ax_comm_expert.exe, g2ax_user_expert.exe, iSCTsysTray8.exe, hpwuschd2.exe, nsload.exe, concentr.exe, Receiver.exe, Dropbox.exe, redirector.exe, wfcrun32.exe, rundll32.exe, HPNetworkCommunicatorCom.exe, ONENOTEM.EXE, AuthManSvr.exe, IAStorIcon.exe, SelfServicePlugin.exe, conhost.exe, bash.exe, sh.exe, xinit.exe, XWin.exe, conhost.exe, conhost.exe, dbus-launch.exe, dbus-daemon.exe, conhost.exe, fbpanel.exe, thunderbird.exe, lync.exe, slack.exe, slack.exe, slack.exe, slack.exe, RuntimeBroker.exe, slack.exe, Skype.exe, DBRUpd.exe, Toaster.exe, DBRCrawler.exe, conhost.exe, ucmapi.exe, winword.exe, lynchtmlconv.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, Picasa3.exe, McUICnt.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, vlc.exe, McVulAlert.exe, taskhost.exe, nvstreamsvc.exe, conhost.exe, OUTLOOK.EXE, explorer.exe, iTunes.exe, AppleMobileDeviceHelper.exe, conhost.exe, distnoted.exe, conhost.exe, APSDaemon.exe, SyncServer.exe, conhost.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, chrome.exe, splwow64.exe, AcroRd32.exe, AcroRd32.exe, RdrCEF.exe, RdrCEF.exe, AdobeCollabSync.exe, chrome.exe, chrome.exe, chrome.exe, excel.exe, chrome.exe, firefox.exe, jre-7u80-windows-x64.exe, mmc.exe, gvim.exe, chrome.exe, dllhost.exe, 
DEBUG: accepted ipc client connection

**Comment by craigemery** [comment]
This clearly seems to happens sometimes when there's a UAC challenge.

**Comment by iondiode** [comment]
I'm also seeing this if i manually run synergyd.exe i get 
![image](https://cloud.githubusercontent.com/assets/1748527/8097898/95495fca-103c-11e5-8e4f-4976223b1593.png)

**Comment by iondiode** [comment]
Application Log Error Entry from what was probably first crash (laptop was was woken from sleep, on a a new network )

Faulting application name: synergyd.exe, version: 0.0.0.0, time stamp: 0x54ee66d1
Faulting module name: synergyd.exe, version: 0.0.0.0, time stamp: 0x54ee66d1
Exception code: 0xc0000005
Fault offset: 0x000000000000d8b6
Faulting process id: 0xbac
Faulting application start time: 0x01d0966437e1ca78
Faulting application path: C:\Program Files\Synergy\synergyd.exe
Faulting module path: C:\Program Files\Synergy\synergyd.exe
Report Id: cd83f004-0257-11e5-ac7a-a4db30f032d1

**Comment by XinyuHou** [comment]
@craigemery 

Does this mostly happen after a UAC dialog?

**Comment by XinyuHou** [comment]
@iondiode 

>  if i manually run synergyd.exe

Did you start Synergy service in Windows service panel?

**Comment by craigemery** [comment]
Yes.

**Comment by iondiode** [comment]
Yes, I attempted to do that, but it doesn't start. Then i looked at the
service options and saw that it was attempting to run synergyd, so I ran it
manually with the results described. I also ran it in an admin cmd.exe to
make sure, but same result.

**Comment by XinyuHou** [comment]
@iondiode 

On Windows you can go to service control panel to start Synergy.

1. Win+r
2. Type in services.msc
3. Find and start Synergy

**Comment by XinyuHou** [comment]
@craigemery 
Could you test this nightly.

http://synergy-project.org/nightly?filter=121080

If the issue persists, please use log to file feature which in Edit->Settings and send us the log.

**Comment by iondiode** [comment]
as mentioned previously, I did that, service would not start. Presumably
errored to application log.

**Comment by XinyuHou** [comment]
@iondiode 
Typically it is not a good idea to manually run synergyd.

If the service is running. I would assume there was something wrong during installation. Please try uninstall Synergy and reboot then reinstall.

Please use the nightly.

**Comment by iondiode** [comment]
Sure no problem.

But FYI i didn't stop the service. Synergy was working, then it stopped
working.

I went to the service panel to start it, it wouldn't start.

So I tried manually. I thought the error could be of assistance.

This had happened before and restarting fixed the problem as originally
described in this bug report.


Cheers,
Tim

**Comment by craigemery** [comment]
And I already did all that. My log output is the second comment in this report.
What else do you need?
This hits me daily.

**Comment by craigemery** [comment]
The nightly was working for a few hours but now I have a different issue.
I came back from being AFK and the service is running, but the client says "
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to connect secure socket
"

OK, restarting the server process under Ubuntu fixed that.

**Comment by XinyuHou** [comment]
@craigemery 

Is the log you post from logging window or log file?

Synergy service send logging info to GUI through IPC and is also responsible for log to file if it's enabled. Sometimes when service crashes, GUI doesn't have the full logging. I don't think log to file would have all, but it has higher chance to catch the error. Sorry for the inconvenience.

Your second issue is a unknown issue #4750. I will try to solve it in 1.7.5

**Comment by XinyuHou** [comment]
@iondiode 

Sorry I didn't catch all the information you posted.

Are you using Windows 7 or 8? with Synergy 1.7.3?

We just found a major bug related to synergyd and got it fixed in the nightly. I can't say that would be the direct cause to your issue. But it should at least lessen the problem.

http://synergy-project.org/nightly?filter=121080

I will keep this ticket open and try to reproduce it. Free feel to update if you can find any way to reproduce it reliably.

**Comment by craigemery** [comment]
OK. So I just had Synergy survive 3 UAC challenges in a row.

**Comment by craigemery** [comment]
I'm on Win 8.1 64-bit.
My log was from the file.
Things are a lot better with the nightly.

**Comment by speaker** [comment]
@craigemery , That nightly contains a last second fix for #4809 that could cause no end to problems related to logging actions. It specifically seemed to hit hard interactions with synergyd and synergys. This would manifest in total lockouts from the server, to crashes, and everything in between.

**Comment by iondiode** [comment]
Thank you
I will try it

**Comment by speaker** [comment]
@iondiode Any luck with the nightly? Here is a link to the newest one, and candidate for GM v1.7.4. http://synergy-project.org/nightly?filter=415ac8e

**Comment by craigemery** [comment]
I've recently found synergyc crashing.
Nothing to do with UAC.
I lose my connection and have to start Synergy client again.
So I installed that 1.7.4 RC. changeset 415ac8e.
I installed the 64 bit Win Client *and* the 64 bit .deb as my server.
It's working, but I had to downgrade the Linux client back to 1.7.3 stable.
The server crashes as soon as my 1.7.4 RC Windows client connects.
