### ISSUE TITLE
Tray icon does not indicate if process is started

### ISSUE THREAD

**Issue by robert4os** [symless/synergy-core#4791]
OSX 10.10.3
Synergy 1.7.3

Also the menu (start, stop, hide) shows 'stop' disabled although synergy is started, running and working. 

[The configuration window says "Synerhy is starting" and their the stop button is correctly enabled.]

**Comment by Swaagie** [comment]
Seeing the same, especially when killing the server. Client will disconnect and not automatically reconnect, status is not displayed.
