### ISSUE TITLE
Hotkey is not working on other screen

### ISSUE THREAD

**Issue by gausson** [symless/synergy-core#4799]
System setup:
Version: 1.7.3 pro
Windows 8.1 - Server
Mac OSX 10.10.3 - Client

I would like to set a hot key (e.g. "x") and when I press it in OSX screen, it can perform an action on my Win8 screen.
In the hotkeys page, I add keyStroke x to the left and a keystroke action (e.g. Shift+Home) on the right with "only on these screens" to my win8 screen. 

When I press the keystroke in my win8 screen, it works. When I press the keystroke in my OSX, my win8 screen didn't perform the action.

I was able to make this work with same config when my server is arch linux and my client is win8. I can press the keystroke in whatever screen I like and still perform the action in my win8 screen which is wonderful. But this does not work in win8 server + osx client. I also tried to reverse the role of win8 and osx (i.e. win8 client and osx server) but still no luck.

It doesn't look like the focus is lost in win8 for this case because you will be noticed that if the focus is being lost, the text cursor is no longer flashing if you are focusing on a text box. My expected perform action in win8 should be a global hotkey (i.e. no matter what you are focusing on, if you press that button / receive the keystroke, the action should be happened). I also tried to enable "Don't take foreground window on Windows servers" in the configuration window but still not working.

May be it should be a stand alone feature call broadcast hotkey?

**Comment by speaker** [comment]
@gausson , Nice catch. I am able to reproduce this issue between Win7 server and MacOSX10 Client.
