### ISSUE TITLE
GUI immediately opens then closes on Mac OS X 10.11

### ISSUE THREAD

**Issue by bogoroh** [symless/synergy-core#4804]
Synergy won't open the app on version 10.11

**Comment by XinyuHou** [comment]
@bogoroh 

What version of Synergy are you using?

Any error message?

**Comment by bogoroh** [comment]
Version 10.10

Uuhm no error message, It just tries to open the app and closes again

**Comment by XinyuHou** [comment]
@bogoroh 

Maybe Synergy minimize itself. Could you see Synergy icon in the top status bar?

**Comment by bogoroh** [comment]
No the Synergy icon doesn't appear on the top of the status bar

**Comment by XinyuHou** [comment]
Is this your first time opening Synergy?

If yes, it should automatically open Accessibility window in your System Preference. I would assume system failed to open it for some reason. Please open it manually by go to System Preference -> Security & Privacy -> Accessibility then tick Synergy

**Comment by bogoroh** [comment]
Yes, This is my first time opening Synergy.

Also Synergy is not displayed under accessibility.

**Comment by p-blomberg** [comment]
I just upgraded from 1.6.1 to 1.7.3. The first time it started, it asked me to allow it to do accessibility things, but I had already allowed it (for the old version). So I closed system preferences again, and noticed that synergy hadn't started. I started it again, and it asked me to allow it again. I removed it from the list of allowed applications in accessibility, thinking that this would allow me to get "fresh" preferences, but now when I start Synergy it doesn't ask me and doesn't start. :(

**Comment by p-blomberg** [comment]
And now I solved it, by copying the new Synergy.app file to Applications one more time, and restarting it.

**Comment by bogoroh** [comment]
I never get the accessibility popup or it not even showing when I manually access accessibility

**Comment by karlosgarcia** [comment]
You have to give privilegies first onto the Accessibility Pane to successfully run on El Capitan

**Comment by bogoroh** [comment]
That did the deal, Thank you

**Comment by avioli** [comment]
Just a quick add on, if anyone stumbles upon this ticket - Mac OS X 10.11 - El Capitan (beta 2) has the same issue - Go to Preferences and Security & Privacy and press the Plus button to add Synergy to the list. Then tick the box to enable it. I've put the app in /Applications, just in case.

**Comment by MDScranton** [comment]
I just solved this same issue by going to System Preferences ->  Security & Privacy -> Privacy -> Unlock to make changes -> Select Accessibility from the list and then ensure that a.) Synergy was in the list (it was) and b.) un-check and re-check Synergy before locking it back down.

**Comment by the-wes** [comment]
This is a bug - we will need to update Synergy so it can add itself to the Accessibility list on 10.11.

**Comment by jasonjpeters** [comment]
I am having the same issue, app opens, bounces a few times in the dock then closes. 

OSX10.11beta (15A243d) -- fresh install
Synergy 1.7.4 RC8 -- fresh install

No accessibility dialog request or crash dialog presented.

I was able to get it working after these steps...
1. Open System Preferences > Security & Privacy > Privacy 
2. Click the + and search for and the Synergy.app from Applications
3. Launch Synergy

**Comment by bjarnet3** [comment]
@avioli Thank you... 
1. Install Synergy (draging Synergy to Application) 
2. System Preferences -> Security & Privacy -> Privacy -> Unlock to make changes -> Select Accessibility 
3. Install Synergy Again (draging Synergy to Application again)
4. Open Synergy
5. Skip Activation
6. Open Preference -> Uncheck "Use SSL"

This did the trick for me... After trying a few times...

**Comment by bianfeng218** [comment]
I have installed sysnergy 1.4.7 on my OS X 10.11 last day and found it works well! I just use it as a client

**Comment by sk8ingdom** [comment]
I'm still having this issue with macOS Sierra 10.12.5 and Synergy 1.8.8 25a8cb2. I tried removing accessibility options, re-adding them, and installing / uninstalling multiple times to not avail. Is anyone else still experiencing issues?

**Comment by pjobson** [comment]
This is still happening in Catalina 10.15.5 / Synergy 1.13.0.

**Comment by andreacndn** [comment]
Hi @pjobson this is very strange, as we have a very large number of active users on 10.15.
Maybe it's an application firewall or an anti-malware? We have been notified in the past of similar issues with Little Snitch and Norton products.
