### ISSUE TITLE
Swapping control and alt keys doesn't work

### ISSUE THREAD

**Issue by wlodek76** [symless/synergy-core#4808]
ctrl = meta
meta = ctrl

altgr = alt
alt = altgr

These combinations do not work  if we want to swap control and alt keys.

I've checked worked assigns.

ctrl = meta - OK
alt = altgr - OK

<b>meta = ctrl - FAIL</b>
<b>altgr = alt - FAIL</b>

In my "Polish Pro" keyboard setup Alt keys are reversed and I need to input polish chars with accent using left Alt instead of right AltGr, altgr = alt does not work in my setup.

Synergy Basic v1.7.3
Windows 7 64-bit (server)  --->  Mac Mini OS X (client)
Logitech MK120 keyboard (Polish Pro input)

ctrl = meta works and remaps a Command key on the mac but it makes Control key hidden and unusable then.

Unfortunatelly we cannot fix it using KeyRemap4MacBook / Karabinier on the Mac because synergy works internally not as a physical usb keyboard so we cannot remap the keys.

Adding config commands like this could be very useful.
<b>swap ctrl meta
swap alt altgr</b>

**Comment by XinyuHou** [comment]
This might be related to #4280
