### ISSUE TITLE
Auto detect Qt path for Windows installer

### ISSUE THREAD

**Issue by nyetwurk** [symless/synergy-core#4835]
QtPath should not be hardcoded in src/setup/win32/Include.wxi
QtPath should be autodetected. It may not be installed in C:\Qt

**Comment by nyetwurk** [comment]
Sigh.

**Comment by nyetwurk** [comment]
This could easily be added as an env item passed to wxi.in

**Comment by nbolton** [comment]
Patches welcome!

**Comment by nyetwurk** [comment]
I stopped using synergy a while back during the great forking. I may rejoin the project time permitting dependent on the stability of the open source fork.

In this particular case, I only need to try to build the project to submit a PR for this, so thats good news.

**Comment by nyetwurk** [comment]
Can you reopen this pending a PR from me? Thanks :)

**Comment by yupi2** [comment]
The Qt path doesn't need to be hardcoded at all. Here's a snippet of how I build on my fork.
```
mkdir build
cd build
set PATH=%PATH%;C:\Qt\5.9.1\msvc2015_64\bin
cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 14 2015 Win64" ../
cmake --build ./ --config Release
msbuild synwix.sln # wix installer
```
Only thing you'd need to do is open a new cmd prompt to reload the default path if you want to build with a different qt path

**Comment by nbolton** [comment]
@yupi2 Thanks!

**Comment by nbolton** [comment]
I'm pretty sure this is fixed now.
