### ISSUE TITLE
Seamless switching between configs based on location

### ISSUE THREAD

**Issue by datadimension** [symless/synergy-core#4837]
I though it would be good to have a config for client as well as I use a laptop at work as well as a main PC, but then bring it home also to use with another PC but with different network credentials.
The 2 types could be merged using a flag to denote server or client (with inappropriate options greyed out for either type).
A drop down list could then be implemented to select the named configuration so changing locations is a simple one click swap.
This could allow greater variance, for instance using the laptop as a server at work, or a client at home.
This would also free up the main screen space for future dev / more runtime info (or just make it smaller) as well if config was moved fully to a window accessed by the top menu options eg Config as it would only need a named config selection from the main screen.
An example is Filezilla which you have likely used where all the many connection details are usually set once and then the user returns to the main screen and selects by name.

**Comment by beporter** [comment]
Mac also have Network "Locations", which allow for network connections to be swapped around the same way. It's always been a dream of mine for Synergy to detect changes in a Mac's network Location and switch its own configurations to match. This information is available on the command line by running `networksetup -getcurrentlocation` actually, although you'd have to poll that to detect.

Although, programs can subscribe to be notified when network connections change, which would let Synergy make the switch immediately and automatically. Here's a StackOverflow thread demonstrating the approach: https://stackoverflow.com/q/1083701/70876 That could potentially make the configs **completely** automatic for a laptop connecting to different Synergy servers at home and in the office, for example. I wouldn't be surprised if there was something similar on Windows and (some) linux.
