### ISSUE TITLE
SSL plugin links to the wrong libssl/libcrypto on Gentoo

### ISSUE THREAD

**Issue by anomaly256** [symless/synergy-core#4890]
[Making a new issue for this as per @nbolton's suggestion]

I know you're not really looking to support Gentoo, but I thought I'd mention it here that I had to perform the libssl/libcrypto symlinking workaround for 1.7.3.  It downloaded a libns.so version that looks for libssl.so.10 instead of libssl.so.1.0.0

```
    libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f91acf94000)
    libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f91acbc4000)
```

Works fine after the symlink.  I wonder though, is there a better way to test for which libns.so to download apart from explicit per-distro rules?  Maybe like testing the 'SONAME' on /usr/lib/libssl.so?

**Comment by johnstile** [comment]
bump. Why doesn't the build of sinergy include a flag to optionally build libns.so?  Hacking the symlinks works for me but the build could be cleaner.
