### ISSUE TITLE
Supprot non-rectangular monitor configurations

### ISSUE THREAD

**Issue by tangurano** [symless/synergy-core#4993]
I have two 1920x1080 monitors, one vertical and one horizontal, laid out in a side-ways "T" shape. I keep a laptop below the horizontal monitor and would like to use it with Synergy. When I configure the links in Synergy, the "down" edge only includes the lowest edge, ie the 1080 pixels on the bottom of the vertical monitor. The other 1920 pixels on the horizontal edge are just completely unreachable.

**Comment by DrOwl** [comment]
I have a similar issue, My server has 3 monitors one vertical two horizontal, my laptop lives under the second monitor but I can only go down to it from the vertical monitor. The best explanation I have see for this is from a thread on a Google group... https://groups.google.com/forum/#!topic/synergy-users/zEPxMjAah98 

I would very much like to see support for non-rectangular monitor configurations
