### ISSUE TITLE
Fast cursor between VM iMac and OSX MacBook 

### ISSUE THREAD

**Issue by mcahornsirup** [symless/synergy-core#4999]
Here is the setup:
iMac + VMWare Fusion (running Windows) <= SYNERGY =>  MacBook

Moving the mouse directly from within VMWare-Fusion to the MacBook will speed up the mouse pointer.
But if I switch on the iMac to the Finder first and than to the MacBook everything works fine.

**Comment by Malcolmlowe** [comment]
Reported by user yesterday. 

Server: OSX 10.10.5 
Client: Windows XP
