### ISSUE TITLE
Screen icons on configuration grid disappear

### ISSUE THREAD

**Issue by the-wes** [symless/synergy-core#5003]
1. Open Synergy on Windows
2. Click Configure Server
3. Drag a screen icon within its own box (don't drag it to another box)
4. Icon disappears as if it had been dragged to the trash can in the upper left

**Comment by legonigel** [comment]
I do not see this issue on 1.8.0-beta on Linux Mint 17.3. This might be a system dependent issue or might have been fixed in the mean time.
