### ISSUE TITLE
Failed to launch with error 'Invalid interface to SNW_SERVICE'

### ISSUE THREAD

**Issue by dayze** [symless/synergy-core#5023]
Os : Elementary OS 
Version of synergy : synergy-v1.7.4-stable

Hi,
When i'm opening synergy in my console I get the following error "sni-qt/2206" WARN void StatusNotifierItemFactory::connnectToSnw() Invalid interface to SNW_SERVICE" 

I already tried to reinstall sni-qt  and synergy but nothing change.

**Comment by LowryConor** [comment]
Os : Ubuntu 14.04
Version of synergy : synergy-v1.7.4-stable

Also experiencing the exact same issue
