### ISSUE TITLE
Unable to move MS Office window on OSX client with Ubuntu server

### ISSUE THREAD

**Issue by silvester747** [symless/synergy-core#5028]
I have the following setup:
- Server 1.7.4 on Ubuntu 14.04 with one display
- Client 1.7.4 on OSX Yosemite 10.10.5 with two displays

I can move windows for most applications on OSX by clicking the window header and dragging it, except for those that are part of the Microsoft Office suite (15.13.1). I often have to use the touchpad on my MacBook to move those.

**Comment by bsuh** [comment]
I also can't drag and move [Boxy](http://www.boxyapp.co/) window on OS X El Capitan 10.11.6 client 1.8.2 connected to Windows 10 server 1.8.2.
