### ISSUE TITLE
Common time base in logging 

### ISSUE THREAD

**Issue by sthor69** [symless/synergy-core#5050]
One feature introduced in one of the latest releases was including a timestamp in the logs.
It is very useful in order to point out which are the one related to a particular topics, but it is useless to correlate logs between server and client when the timebases are out of phase.
It would be nice to have a sort of "synergy" common timebase, or similar

**Comment by database9-445** [comment]
In my opinion log files should store Universal Coordinated Time (UTC).  I have Synergy running on a Windows 10 machine and a Kubuntu machine, both of which have log file records stamped with local time. I tried to look at the code but I don't have experience coding in C++.

**Comment by sthor69** [comment]
The problem with a "coordinated time" is that it depends upon external synchronization, not always available in restricted environment (such as company offices) where firewalling rules could make it unfeasible. 

Another possibility is to include a message ID in the logs that link related messages in server and client. E.g., if the client sends a CNOP message to the server, the logs in the client "writef(CNOP)" and in the server "msg from xxx: CNOP" could share the same ID

**Comment by database9-445** [comment]
There are some technical differences but UTC is basically equivalent to Greenwich Mean Time. It's the time your computer uses before adjusting for the local time zone. It's useful for log files because it does not require synchronization.

https://en.wikipedia.org/wiki/Coordinated_Universal_Time

**Comment by sthor69** [comment]
I'm not a programmer or a debugger, so my comments are to be considered from a user perspective. 
I perfectly agree in a single application. But when two applications are strictly related, a difference also in the order of ms can make the difference.
In case of the server and the client of Synergy I see in my client and server logs differences in the order of seconds between a "writef" and the related "msg from"

**Comment by nyetwurk** [comment]
This bug is pretty silly, just use NTP and call it a day.

**Comment by sthor69** [comment]
This is not a bug, just a request for improvement.

I'm not a coder nor a programmer. If you think it's useless close it. It 
seemed to me useful.

Inviato con AquaMail per Android
http://www.aqua-mail.com


Il 17 ottobre 2015 20:43:06 Nye Liu <notifications@github.com> ha scritto:

**Comment by srl295** [comment]
By "timebase" do you mean time zone or time synchronization? If timezone: Yes, just use UTC. If time synchronization: That would be out of scope for synergy, except that if the protocol were to support it, you could report that client X (or server Y) is so many seconds fast/slow.

**Comment by sthor69** [comment]
I was referring to time synchronization between log events.
When you have tens of log events when debugging an issue it is difficult to relate client logs with server logs. A sort of correlation tag between logs (not relying on timestamps) could also be a possible solution.

**Comment by srl295** [comment]
@sthor69 It sounds interesting, but I'm still not quite sure what you are referring to. How… would you correlate logs on two machines without using a timestamp?If it's not really "time" it would have to be some other monotonically increasing counter, right?

**Comment by nyetwurk** [comment]
This is how software projects become bloatware

**Comment by srl295** [comment]
@nyetwurk been there, done that, got the T-shirt…

**Comment by sthor69** [comment]
@srl295 maybe only sending and receiving message logs does make sense here, but one solution could be to add in the log the ID# of the sent/received message (if the messages have an ID, otherwise it doesn't make any sense to change the protocol only for log purposes). E.g.

Client: CALV(#13423) sent
Server: CALV(#13423) received
