### ISSUE TITLE
Massive keyboard lag & mild mouse scrolling lag. Monitor flickering (Very Possible).

### ISSUE THREAD

**Issue by leojonathanoh** [symless/synergy-core#5060]
Host: Windows 10 Pro 64bit. Synergy GUI 1.7.4, SSL enabled.
Client: Mac OSX 10.11 (El capitan). Synergy GUI 1.7.4, SSL enabled.

Summary: http://theohbrothers.com/synergy-spikes.txt (seen on host)
- @Line 152-155: Massive keyboard lag when calling Spotlight search on client
- @Line 34-41, 258-261: Mild mouse scrolling lag on client

[Issue 1: Massive keyboard lag when calling Spotlight search on client]
On a stable ac wifi connection, calling Spotlight Search on client (meta+space, or clicking on Magnify icon) results in 2-10s lag spikes:
- sometimes there is no returning of keys on the client, sometimes there is;
- sometimes clients is disconnected (the mouse returns to the server). 
  Server Synergy GUI server log reports disconnected and reconnected client. 
  Client Synergy GUI log: WARNING: failed to connect to server: server is not responding. Then it reconnects.
  - Host CPU usage is fine and host is stable throughout the issue.

[Issue 2: Mild mouse scrolling lag on client]
On a stable ac wifi connection, mouse scrolling on an program results in a CPU usage spike on the scrolled-on program in Activity Monitor, in turn resulting in a ~2-5s jittery mouse.(e.g., scroll on a Twitter app feed uses 100+% CPU.
- Host CPU usage is fine and host is stable throughout the issue.

[Issue 3: Host monitor flickering (very likely)]
Host monitor flickered while I attempted to investigate Issue 1, while I was typing away on the spotlight search. Suddenly the Host monitor lost it's custom settings (screen brightness/color changed), flickered every 3s with everything onscreen still responsive, monitor buttons were unresponsive (so couldn't turn it off/change source/change brightness etc.), all until I closed synergy GUI on the client and the server, then the flickering stopped. Host monitor settings were lost and had to be reset up. I didn't continue to investigate because I don't want to have to keep resetting up my monitor settings.

**Comment by XinyuHou** [comment]
@leojonathanoh 
Do you have any big data in your clipboard?

Please raise another 2 tickets for the last 2 issues, 1 issue for 1 ticket. It's easy for us to track each problem.
