### ISSUE TITLE
GUI freezes after inactivity on Ubuntu server

### ISSUE THREAD

**Issue by sthor69** [symless/synergy-core#5061]
Server: Ubuntu 14.04.1
Client: Windows XP
Synergy 1.8.0 (one of latest nightly builds)

After a pause (typically more than an hour) when I left the server GUI opened, when I reopen GNOME, I find the GUI frozen in grey as in the attached image
![gnu-freeze](https://cloud.githubusercontent.com/assets/3283841/10428163/d6a3e99a-70ef-11e5-9a6a-b8b3e82b28e3.jpg)

**Comment by XinyuHou** [comment]
@sthor69 
Please try to turn down the log level. Maybe there are too many log lines for GUI to handle.
