### ISSUE TITLE
Wizard ended prematurely when upgrade from 1.4 on Windows 10

### ISSUE THREAD

**Issue by shic** [symless/synergy-core#5229]
I used to use Synergy version 1.4. Now I bought the newer version. But I can not install it! Tried version 1.8 and other night build version. But always got "Setup wizard ended prematurely", 

Now my other computers use version 1.7.5, But windows use  version 1.4, but windows can not connect to the other computers.

Please tell me what I should DO!

**Comment by XinyuHou** [comment]
@shic 
Maybe when you uninstall 1.4, it left some info in your registry.

Please try
1. Uninstall Synergy
2. Open registry
3. Search Synergy keyword
4. Delete all the entries you can find that are related to Synergy
5. Install 1.7
