### ISSUE TITLE
Fail to discover server after a network reconnect

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy-core#5234]
1. Desktop connected to Ethernet and configured as a client. 
2. Laptop connected to Ethernet and configured as server.
3. Disconnect laptop from network and reconnect, but somehow assuming a new ip to the laptop. 

Expect: Client find server
Actual: Client machine fails to discover server.

**Comment by thebodster** [comment]
I am also seeing this.  If the service is restarted on the server machine it will re-connect.
