### ISSUE TITLE
Incompatibility with Phrase Express

### ISSUE THREAD

**Issue by ajsedlak** [symless/synergy-core#5269]
In Win 7, using Phrase Express for text shortcut expansion and PureText for unformatted text pasting. Normal functionality fails while Synergy 1.7.6 server is running. Stopping server allows full functionality. There were no problems of this nature with past versions including 1.7.5.

Another user in forums mentioned issues with AutoHotKey which may be related.

**Comment by DiThi** [comment]
I wonder if this is related to #5007 since I don't remember it happening a couple of years ago.
