### ISSUE TITLE
Keystrokes stop working on client when OSX server focus is on a password field

### ISSUE THREAD

**Issue by kantkodit** [symless/synergy-core#5279]
Running OSX server and Win7 clients.  If you navigate to a web page with a password field and put the cursor in it - then mouse to a client monitor and click in another application window and start typing - the keystrokes will go back to the OSX server.

Interestingly - this also applies if you are running Windows10 in paralells on the OSX server (the keystrokes flow back to W10 inside OSX)

Synergy v 1.7.6 on all machines
Server OS X El Capitan 10.11.4
Windows 7 clients

**Comment by themrez** [comment]
I have same issue for years, see closed #3544. I have tried to report problem a few times. Thanks for reporting @kantkodit.
