### ISSUE TITLE
Scrolling is too fast on Mac

### ISSUE THREAD

**Issue by natepelzel** [symless/synergy-core#5280]
Just wanted to let you know that I have a Mac-Mac connection, and the scroll wheel was operating way too fast for it to be usable.

I did some poking around, and found this:

http://blog.stormyprods.com/2008/09/synergykm-mouse-scrolling-fix.html

I know it's an old post, but I was desperate, so I gave it a shot.  It definitely fixed my issue, so I thought I'd let you know.

Sorry if I'm sharing this in the wrong place.  I'm not super familiar with github.  I just wanted to make sure I did my part to make the product better.

**Comment by dwt** [comment]
I'd say this is one of the more pressing issues, as scrolling is one of the main things I do with my mouse (together with #617 which is also quite annoying)

**Comment by tl-salvatore-formisano** [comment]
This is still an issue for me in 2021. Any solution in sight? I am sure it cannot be as simple as this article makes it out to be (http://blog.stormyprods.com/2008/09/synergykm-mouse-scrolling-fix.html) otherwise this would have been fixed over the last 13 years?

Thanks
