### ISSUE TITLE
Client application for Android (without being rooted/hacked)

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#531]
**Imported issue:**
- Author: Issue Importer
- Date: 2010-06-10 00:00:00
- Legacy ID: 542

Related programs: [Share KM](https://sites.google.com/site/droidskm/) ([Android app](https://play.google.com/store/apps/details?id=com.liveov.skm&hl=en))

> What is the problem you wish to solve?  
> Control the Android interface via input-device on network-connected host  
> 
> What is your new feature idea?  
> Port or build of the Synergy client (synergyc) for the Android OS  
> 
> Is there already a less convenient way?  
> No; not that I'm aware of  
> 
> How useful would the feature be to others?  
> Extremely.  
> Will vastly improve Android's appeal & versatility.  

It would be extremely valuable to be able to control the Android mobile from HID's; definitely keyboard, mouse would be nice.  
Taking hands off keyboad & mouse (which may already be controlling numerous systems), to "fiddle" with mobile device or Android MID disrupts productivity flow/pace.  
Entering values, such as strong passwords on small mobiles with compound keyboard is also overly time-consuming, that could be done quickly & easily with a standard keyboard.  

Since Android is also POSIX-based (Linux kernel derivative), it would seem "simple" to rebuild the source the the new architecture, but unfortunately this is beyond my own skill-set.  

[NOTE: this may be a possible duplicate of an existing thread @ "https://code.google.com/p/synergy-plus/issues/detail?id=57":https://code.google.com/p/synergy-plus/issues/detail?id=57 ]

**Comment by chetbox** [comment]
For mouse support without root is it possible to:
- Draw a cursor by overlaying a view on the screen
- Simulate a mouse click using [UIAutomator](https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#click(int, int))

I'm pretty sure the former is possible (this is how Facebook chat heads works) but I'm not so sure about the latter.

Not proper mouse emulation but could do the job.

**Comment by chetbox** [comment]
Have looked into this further and it seems it is not possible to inject mouse events without root. (UIAutomator/Espresso/etc. use `Instrumentation` to inject key events but this is only possible inside the application unless the `INJECT_EVENTS` system permission is used.)

An `InputMethodService` also cannot send mouse events.

Stupid security.

**Comment by chetbox** [comment]
An alternative way of clicking without root is by inspecting the view hierarchy using an `AccessibilityService`. Unfortunately you cannot click at a location, but you can fetch the location on screen of each view and you can send a click event to a particular view.

I've thrown together an example here: https://github.com/chetbox/android-mouse-cursor 
It includes a script to send "mouse events" over UDP and demonstrates that the concept broadly works, but there are some sever limitations so unfortunately it's not a workable solution for everyday use.

**Comment by chozabu** [comment]
@chetbox interesting stuff! Can we use ADB to send touch inputs? https://github.com/chetbox/android-mouse-cursor/issues/1

**Comment by chetbox** [comment]
From chetbox/android-mouse-cursor#1:

> You could, but I don't believe your app will be able to call out to the shell to invoke `input` because it does not have appropriate permissions. (`INJECT_EVENTS` is a system permission.) When running `adb shell` from your computer you have higher privileges than a running app.

> One avenue that may be worth exploring is using `adb shell` to connect to adbd on the device over TCP on localhost. It would require USB debugging and is probably a huge security hole, but might achieve what we want.

**Comment by benjymous** [comment]
Full mouse and keyboard simulation over ADB is definitely possible - he's another synergy-like app that works on Android 4.1+

https://play.google.com/store/apps/details?id=com.floriandraschbacher.deskdock.free

**Comment by mikemol** [comment]
I'm currently using Airdroid to use my Linux setup's keyboard and mouse with my phone, but having to switch to a different browser tab, rather than move my cursor to where my phone rests on my desk, is a pain.

Airdroid uses ADB to get the necessary privileges going with the phone. Please, *please* get this going. I'd love for this to be relatively seamless.

**Comment by Pozzoooo** [comment]
Is it under development?

**Comment by Rukenshia** [comment]
having Android support would be awesome. I'm using a company device, so no rooting or custom ROM allowed. This is holding me back from using synergy right now.

**Comment by hgghyxo** [comment]
+1 on this. Really awaited function.

**Comment by pfsmorigo** [comment]
+1. Any update?

**Comment by pcaro** [comment]
+1 Updates?

**Comment by danehep** [comment]
I was navigating looking for exactly the same as requested here. I wonder if this feature will be available some day...

**Comment by atrauzzi** [comment]
Would love to see this happen!

**Comment by Pozzoooo** [comment]
Just bought it hoping that this feature come sometime in the future :)

**Comment by jvschiavo** [comment]
Suggestion: rename issue to "Platform Request: Android + Chrome OS client support (no root)"

I think the name makes it clearer to everyone searching for it and bring focus to the issue.
But there is no need to close #3363 since a Chrome OS specific app could exist (specially with server support, that would be awesome)

**Comment by uda** [comment]
+1 Any news?

**Comment by chikilinder** [comment]
hay una opcion de  NON-ROOT  para tener control remoto 
se instala del programa de PC al android  pero cuando se reinicia el equipo perder la conexión  y  la contrafigura  hay alguna otra manera de no perder la configuración sin ser ROOT

**Comment by alsolh** [comment]
I really need this feature, the phone is hanged next to the monitor and it would be great to treat it as an extra device, have tried airdroid and it doesnt fit as it worked just like phone link, would appreciate to consider this feature again

**Comment by fallaciousreasoning** [comment]
Did this end up getting supported, or just closed?

**Comment by sithlord48** [comment]
There is iirc a fork for android on f-droid.

**Comment by fallaciousreasoning** [comment]
Nice, it works great :)
https://f-droid.org/packages/org.tfv.deskflow/
