### ISSUE TITLE
Show version number in finder on OSX

### ISSUE THREAD

**Issue by dwt** [symless/synergy-core#5350]
It should be visible
- When selecting the app in the finder
- When showing the 'get info' window on the application in the finder
- When opening the configuration window (at least somehow)
- Last resort: the log should contain it ant it doesn't seem to - but maybe I missed it in the massive amount of logging. 

The log file would be just a workaround anyway. The version really needs to be shown when selecting the application bundle in the finder.

**Comment by XinyuHou** [comment]
@dwt 
> When selecting the app in the finder

Could you give us more information about your first point? A screenshot would be preferable.

**Comment by dwt** [comment]
![bildschirmfoto 2016-05-31 um 17 13 37](https://cloud.githubusercontent.com/assets/57199/15679717/2bcfcf32-2753-11e6-865c-8777f30b7ebe.png)
![bildschirmfoto 2016-05-31 um 17 13 46](https://cloud.githubusercontent.com/assets/57199/15679716/2bbd4df8-2753-11e6-9f77-d0996c2544d7.png)
