### ISSUE TITLE
Service starts an elevated process on startup

### ISSUE THREAD

**Issue by channing** [symless/synergy-core#5358]
"synergys.exe" started by Synergy service at Windows startup incorrectly inherits the service's privilege ("Elevate mode" is not checked):

![image](https://cloud.githubusercontent.com/assets/1191253/15706667/575697f6-2827-11e6-86f8-cd023935e545.png)

After startup, if I just open Synergy UI and click Stop, then Start, the new process privilege is correct:

![image](https://cloud.githubusercontent.com/assets/1191253/15706673/60892eb0-2827-11e6-9ed6-5b9d8cf17d09.png)
- Windows 10 x64
- Synergy 1.8.2-beta-8da57cd (all default settings)

The command line does include a "--stop-on-desk-switch" param which should kill the elevated "synergys.exe" and start a new unelevated one when the user desktop is ready, but it doesn't seem to work.

**Comment by hu6360567** [comment]
It also affects stable build of version 1.76 and 1.81
