### ISSUE TITLE
Unicode support for copy and paste

### ISSUE THREAD

**Issue by jenelcohen** [symless/synergy-core#5365]
Problem:

Synergy cannot read non-English characters. When naming machines, non-English characters result in the following error (example):

```
 ERROR: cannot read configuration "C:/Users/Jonathan/config": read error: line 2: invalid character 0xffffffe6
```

Solution:

Option 1: Add visible documentation that Synergy uses only English characters.

Option 2: Add non-English support to Synergy

**Comment by orcinus** [comment]
Nevermind non english configuration file support.
How about international keyboard support?

This has been broken for a decade. A DECADE.
In fact, over a decade. It worked in 2003. Ridiculous.

**Comment by posita** [comment]
Given the prevalence of Unicode (and increasing support in OSes, and reliance thereupon), I think this should probably be tagged a `bug` rather than an `enhancement`. At this point, it's basically essential functionality that's missing.

**Comment by adamryczkowski** [comment]
The problem persists even on `version 1.10.3-stable, protocol version 1.6` downloaded from github releases.
