### ISSUE TITLE
Setting keyboard layout in client does not hold

### ISSUE THREAD

**Issue by jenelcohen** [symless/synergy-core#5395]
Client: Windows 8.1

Problem: 

Switching the keyboard layout when mouse/keyboard is in the client does not take any effect.

Solution: switch back to the server, change keyboard layout and switch back to the client.

**Comment by toorosan** [comment]
Not sure if it is important:
Server: OSX 10.11.5 (El Capitan)

**Comment by thusby** [comment]
Same applies for Client: Windows 10 and Server :Ubuntu 16.04
English os versions
Input language swiched between Norwegian and English

**Comment by toorosan** [comment]
Any progress?

**Comment by iazami** [comment]
i have the same issue
**client configuration:** ubuntu 16.04 x64 - with two keyboard layout (Persian-standard and English US).
**server configuration:** windows 10 x64- keyboard layouts are same as client.
so i have to choose same keyboard layout for both client and server in order to emulate the keyboard.

**Comment by nlyan** [comment]
Could you guys please explain what you are trying to achieve? The keyboard layout on the server and client should generally be matched while using Synergy.

**Comment by toorosan** [comment]
It would be great if Synergy switched keyboard layout when I am switched to the client desktop and pressing [CMD]+[SPACE]. Now it does change language in OS, but it does not take any effect on keyboard input language = it stays same as on Synergy Server side.

**Comment by CrazyCoder** [comment]
I have the same issue. In my case both the client and server are 64-bit Windows 10 versions running the latest Synergy 1.8.8 release. Keyboard layout is switched by Alt+Shift.

If you switch the layout while the focus is on the client, it doesn't have any effect, you have to move focus to the server and switch the layout there.

It would be really great if this problem could be fixed. I've even purchased the Pro version recently to support the developers.

**Comment by nbolton** [comment]
Duplicates #4309
