### ISSUE TITLE
Unreadable GUI on a higher scaling Windows

### ISSUE THREAD

**Issue by serversage** [symless/synergy-core#5436]
In Windows 10 if you have a device with high ppi and you increase scaling (Display Settings -> "Change the size of text, apps, and other items: X%") from 100% then checks inside check boxes do not scale with the checkbox between logins.  To recreate:
1. Right click on desktop, click Display Settings, and slide the "Change the size of text, apps, and other items: X%" to something larger, like 175%.
2. Sign out of Windows.
3. Sign back into Windows.
4. Open Synergy and check any checkbox.  The check mark will be incredibly tiny compared to the checkbox.

I've seen this with a few other apps, so I assume it's the GUI library hasn't caught up to high PPI displays and display scaling yet.

![smallcheck](https://cloud.githubusercontent.com/assets/551355/16556981/0b651d8c-41d5-11e6-89af-70f8749dc60f.PNG)

**Comment by legonigel** [comment]
This is an issue with QT, however it might be fixed by moving to a newer version of QT.
