### ISSUE TITLE
Uncompatible libcrypto dependency on openSUSE

### ISSUE THREAD

**Issue by smaug42** [symless/synergy-core#5439]
Cannot install Synergy 1.8.1 beta on openSUSE Leap 42.1 due to a "missing" dependency.

>    sudo zypper in ./synergy-v1.8.1-beta-f7377d6-Linux-x86_64.rpm 
>    root's password:
>    Loading repository data...
>    Reading installed packages...
>    Resolving package dependencies...
>    Problem: nothing provides libcrypto.so.10()(64bit) needed by synergy-1.8.1-1.x86_64

In openSUSE, the libcrypto.so.10 is provided by the libopenssl package as /lib64/libcrypto.so.1.0.0.

A possible workaround is to make a symlink:

>    ln -s /lib64/libcrypto.so.1.0.0 /usr/lib64/libcrypto.so.10

This is impractical as a long term solution though.

**Comment by gsancosme** [comment]
I confirm that issue.
both libcrypto.so.10 and libssl.so.10 have to be soft linked to the libraries 
(I used libcrypto.so.36 and libssl.so.37) . i.e.
# ln -s /usr/lib64/libcrypto.so.36.0.0 /usr/lib64/libcrypto.
# ln -s /usr/lib64/libssl.so.37.0.0 /usr/lib64/libssl.so.10

**Comment by mtelesha** [comment]
Thank you this has stoped me from using Synergy at work for almost a year

**Comment by githubrsys** [comment]
I just bought synergy and faced this f***** thing. But the symlinking seems not to work anymore
`synergys: /usr/lib64/libcrypto.so.10: no version information available (required by synergys)`

**Comment by gsancosme** [comment]
As said above, the symlink has to be adapted depending on the version installed. this is not a long term solution.
having a look at my system opensuse42.1 system 
lrwxrwxrwx 1 root root      25 29 sep 16:30 /usr/lib64/libcrypto.so -> /lib64/libcrypto.so.1.0.0
lrwxrwxrwx 1 root root      19  4 jui  2016 /usr/lib64/libcrypto.so.10 -> libcrypto.so.36.0.0
lrwxrwxrwx 1 root root      19  4 jui  2016 /usr/lib64/libcrypto.so.36 -> libcrypto.so.36.0.0
-rw-r--r-- 1 root root 2141048 12 déc  2015 /usr/lib64/libcrypto.so.36.0.0
on the opensuse 42.2 
lrwxrwxrwx 1 root root      25 Nov 29 19:35 libcrypto.so -> /lib64/libcrypto.so.1.0.0
lrwxrwxrwx 1 root root      19 Feb 16 02:11 libcrypto.so.10 -> libcrypto.so.37.0.0
lrwxrwxrwx 1 root root      19 Feb 16 02:08 libcrypto.so.37 -> libcrypto.so.37.0.0
-rw-r--r-- 1 root root 2124728 Jan 23 20:57 libcrypto.so.37.0.0

But neither libcrypto36 (37) nor libssl37(38) are installed by default. You must 
# zypper in libcrypto36 or libcrypto37  
# zypper in libssl37 or libssl38 

(Works with 1.8.7.stable)
Before actually ln -s them
Hope it helps

**Comment by cchriste** [comment]
I'm using Gnome 3.16.2 on SuSE 42.1 and I could not get the symlink solution above to work. However, I was able to rebuild from source and now the application is working. Be sure to use the build script from the instructions, and also to fetch source from github. Otherwise, the compile fails.

**Comment by paulrm** [comment]
Fixed for OpenSuse  Tumbleweed with

```
# zypper in libcrypto38 libssl39
# ln -s /usr/lib64/libssl.so.39.0.1 /usr/lib64/libssl.so.10
# ln -s  /usr/lib64/libcrypto.so.38 /usr/lib64/libcrypto.so.10
```

**Comment by wolvyreen** [comment]
None of the above works for me.   running Synergy 1.8.8-stable and it refuses to work.  No amount of sym links gets this working at all.

**Comment by mmontic** [comment]
I just updated synergy to the latest stable 1.8.8.

For tumbleweed, did you first install the following ?
# zypper in libcrypto38 libssl39

And then only, create the symlinks

# ln -s /usr/lib64/libssl.so.39.0.1 /usr/lib64/libssl.so.10
# ln -s  /usr/lib64/libcrypto.so.38 /usr/lib64/libcrypto.so.10

to ensure your links fulfill their role, try this :
# ldd /usr/bin/synergys

You should have something similar to this : 
/usr/bin/synergys: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergys)
/usr/bin/synergys: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergys)
/usr/bin/synergys: /usr/lib64/libssl.so.10: no version information available (required by /usr/bin/synergys)
        linux-vdso.so.1 (0x00007fff16964000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1307860000)
        libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f13075ef000)
        libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f13073e6000)
        libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f13071c9000)
        libXtst.so.6 => /usr/lib64/libXtst.so.6 (0x00007f1306fc3000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f1306c84000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f1306a72000)
        libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f130686f000)
        libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f1306663000)
        libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f1306453000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f13061f3000)
        libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f1305de8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1305be4000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f1305861000)                                                                                                                                                         
        libm.so.6 => /lib64/libm.so.6 (0x00007f1305563000)                                                                                                                                                                       
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f130534c000)                                                                                                                                                               
        libc.so.6 => /lib64/libc.so.6 (0x00007f1304fa9000)                                                                                                                                                                       
        /lib64/ld-linux-x86-64.so.2 (0x0000563de2ef2000)                                                                                                                                                                         
        libidn.so.11 => /usr/lib64/libidn.so.11 (0x00007f1304d74000)                                                                                                                                                             
        libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f1304b49000)                                                                                                                                                             
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007f13048dd000)                                                                                                                                                           
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007f1304482000)                                                                                                                                                     
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f1304239000)                                                                                                                                               
        liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007f130402a000)                                                                                                                                                     
        libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2 (0x00007f1303ddd000)                                                                                                                                                     
        libz.so.1 => /lib64/libz.so.1 (0x00007f1303bc7000)                                                                                                                                                                       
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f13039c2000)                                                                                                                                                             
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f13037a1000)                                                                                                                                                               
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f1303597000)                                                                                                                                                       
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f13032c5000)                                                                                                                                                             
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f1303095000)                                                                                                                                                     
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f1302e91000)                                                                                                                                                           
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f1302c83000)                                                                                                                                               
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f1302a6c000)                                                                                                                                                             
        libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007f130284f000)                                                                                                                                                           
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f130264a000)                                                                                                                                                               
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f1302446000)                                                                                                                                                         
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f1302220000)                                                                                                                                                           
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f1301fb0000)

synergys is complaining about not having version information for libcrypto and libssl but it works.
Georges

**Comment by gsancosme** [comment]
I just updated synergy to the latest stable 1.8.8.

For tumbleweed, did you first install the following ?
# zypper in libcrypto38 libssl39

And then only, create the symlinks

# ln -s /usr/lib64/libssl.so.39.0.1 /usr/lib64/libssl.so.10
# ln -s  /usr/lib64/libcrypto.so.38 /usr/lib64/libcrypto.so.10

to ensure your links fulfill their role, try this :
# ldd /usr/bin/synergys

You should have something similar to this : 
/usr/bin/synergys: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergys)
/usr/bin/synergys: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergys)
/usr/bin/synergys: /usr/lib64/libssl.so.10: no version information available (required by /usr/bin/synergys)
        linux-vdso.so.1 (0x00007fff16964000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1307860000)
        libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f13075ef000)
        libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f13073e6000)
        libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f13071c9000)
        libXtst.so.6 => /usr/lib64/libXtst.so.6 (0x00007f1306fc3000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f1306c84000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f1306a72000)
        libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f130686f000)
        libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f1306663000)
        libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f1306453000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f13061f3000)
        libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f1305de8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1305be4000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f1305861000)                                                                                                                                                         
        libm.so.6 => /lib64/libm.so.6 (0x00007f1305563000)                                                                                                                                                                       
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f130534c000)                                                                                                                                                               
        libc.so.6 => /lib64/libc.so.6 (0x00007f1304fa9000)                                                                                                                                                                       
        /lib64/ld-linux-x86-64.so.2 (0x0000563de2ef2000)                                                                                                                                                                         
        libidn.so.11 => /usr/lib64/libidn.so.11 (0x00007f1304d74000)                                                                                                                                                             
        libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f1304b49000)                                                                                                                                                             
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007f13048dd000)                                                                                                                                                           
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007f1304482000)                                                                                                                                                     
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f1304239000)                                                                                                                                               
        liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007f130402a000)                                                                                                                                                     
        libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2 (0x00007f1303ddd000)                                                                                                                                                     
        libz.so.1 => /lib64/libz.so.1 (0x00007f1303bc7000)                                                                                                                                                                       
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f13039c2000)                                                                                                                                                             
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f13037a1000)                                                                                                                                                               
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f1303597000)                                                                                                                                                       
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f13032c5000)                                                                                                                                                             
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f1303095000)                                                                                                                                                     
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f1302e91000)                                                                                                                                                           
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f1302c83000)                                                                                                                                               
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f1302a6c000)                                                                                                                                                             
        libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007f130284f000)                                                                                                                                                           
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f130264a000)                                                                                                                                                               
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f1302446000)                                                                                                                                                         
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f1302220000)                                                                                                                                                           
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f1301fb0000)

synergys is complaining about not having version information for libcrypto and libssl but it works.
Georges

**Comment by wolvyreen** [comment]
yes, the packages were installed before creating the symlinks

and ldd will only work IF the package is installed but thats the problem....the package wont install because of the problem we are trying to correct.

so ldd /usr/bin/synergys will only work ONCE the package is installed.  but must i ignore the error and "break" the install and then run ldd?

**Comment by gsancosme** [comment]
Now I understand your problem.

Yes will have to install synergy accepting to "Break" synergy (because of the missing libs).
After that just follow the above and it will work. 
ldd only prints the shared objects (shared libraries) required by each program or shared object specified on the command line.

That's all

**Comment by wolvyreen** [comment]
but thats the thing....it doesnt work....as you can see above, the sym links are there and I did "break" synergy to get it installed but when the app tries to connect to the server, it throws the above ssl error.

that's why im saying it isnt working.

**Comment by gsancosme** [comment]
Are you sure that your server is providing SSL, i.e. did you check the box in : Edit/Parameters on the server ? Because it looks that something is wrong in your SSL config for synergy.

Also check on the server, that in your home folder there is a directory called .synergy
In that directory there are 2 sub-directories : 
plugins and SSL. 
plugins contains a soft link to /usr/bin/../lib/synergy/plugins/libns.so
and SSL contains the Synergy PEM and Fingerprints (in text files).

You should check https://github.com/symless/synergy/wiki/Security for the correct setup.

On my client (server fingerprint looks actually different) : 
```
[2017-04-04T21:44:20] INFO: log level: INFO
/usr/bin/synergyc: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergyc)
/usr/bin/synergyc: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergyc)
/usr/bin/synergyc: /usr/lib64/libssl.so.10: no version information available (required by /usr/bin/synergyc)
[2017-04-04T21:44:20] NOTE: started client
[2017-04-04T21:44:20] NOTE: connecting to '10.5.73.24': 10.5.73.24:24800
[2017-04-04T21:44:20] INFO: OpenSSL 1.0.2j-fips  26 Sep 2016
[2017-04-04T21:44:20] NOTE: server fingerprint: 00:FF:FF:00:F0:FF:99:00:F0:00:9F:F0:99:FF:99:99:99:9F:9F:00
[2017-04-04T21:44:20] INFO: connected to secure socket
[2017-04-04T21:44:20] INFO: server ssl certificate info: /CN=Synergy
[2017-04-04T21:44:20] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
```

On server side : 
```
[2017-04-04T14:53:45] INFO: starting server
[2017-04-04T14:53:45] INFO: config file: /tmp/qt_temp.fB9128
[2017-04-04T14:53:45] INFO: log level: INFO
[2017-04-04T14:53:45] NOTE: started server, waiting for clients
/usr/bin/synergys: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergys)
/usr/bin/synergys: /usr/lib64/libcrypto.so.10: no version information available (required by /usr/bin/synergys)
/usr/bin/synergys: /usr/lib64/libssl.so.10: no version information available (required by /usr/bin/synergys)
[2017-04-04T14:59:28] INFO: LibreSSL 2.3.4
[2017-04-04T14:59:28] INFO: accepted secure socket
[2017-04-04T14:59:28] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2017-04-04T14:59:28] NOTE: accepted client connection
[2017-04-04T14:59:28] NOTE: client "client.domain.tld" has connected
[2017-04-04T14:59:32] INFO: switch from "server.domain.tld" to "client.domain.tld" at 0,34
[2017-04-04T14:59:32] INFO: leaving screen
```

**Comment by wolvyreen** [comment]
My synergy server is running from a Windows Machine.  The "Use SSL encryption" is greyed out on that machine.  On the suse machine, I have not set anything as yet. ONLY the server IP.

I use synergy between a Mac and a Windows machine without any issues.  When I try on suse, I get all the issues above.  all related to ssl.  I also have the SSL license from synergy and was hoping to make use of the license I bought.  I don't see how my set up is wrong as it is normally very straight forward

**Comment by wolvyreen** [comment]
ok! :)  So sort of good news....I disabled the SSL on the suse machine which was enabled by default and I was able to connect without issues.  but it does concern me that I am not connected using ssl.....   :(

**Comment by gsancosme** [comment]
As you purchased the pro version (ssl), you should upgrade your synergy install on the server (windows machine) and then paste into the key provided by synergy. 
You can normally do this in the menu File/activate. after that everything should run flawlessly, and the SSL box will be ungrayed

**Comment by wolvyreen** [comment]
aww fanks!  ok,  let me try that....my bad...I thought it would automagically do it all for me.....hee hee!

I will report back once i have more
