### ISSUE TITLE
Scroll Lock state gets flipped after sleep

### ISSUE THREAD

**Issue by orcinus** [symless/synergy-core#5445]
Steps to reproduce:

1) on Synergy server machine, turn Scroll Lock on, locking the mouse/keyboard focus to that machine
2) put the server to sleep
3) wake the server up
4) observe that the Scroll Lock is now off, but Synergy still behaves as if it were on
5) you now have to turn Scroll Lock ON to disable screen lock, i.e. state is flipped

Expected result: Synergy should poll the system Scroll Lock state more frequently than when turning it on and off only, so it's in sync.

**Comment by erikliland** [comment]
I have the same problem on a Win7 server with a OSX client.
