### ISSUE TITLE
Mouse button swapping doesn't work with modifier keys

### ISSUE THREAD

**Issue by Ofenhed** [symless/synergy-core#5452]
```
mousebutton(6) = mousebutton(4)
mousebutton(7) = mousebutton(5)
```

With this configuration, the mouse buttons work only if no modifier keys (Shift, Ctrl, Super and Alt tested) are pressed, otherwise mousebutton 4 or 5 are not pressed. This is a big problem for gaming.

**Comment by DylanSimowitz** [comment]
From the wiki:
>     mousebutton(button) = actions
> 
> Binds the modifier and mouse button combination button to the given actions. button is an optional list of modifiers (shift, control, alt, meta or super) followed by a button number. The primary button (the left button for right handed users) is button 1, the middle button is 2, etc.

The following config works while holding shift. Obviously replace shift with the modifier you need.

```
        mousebutton(6) = mousebutton(4)
        mousebutton(7) = mousebutton(5)
        mousebutton(shift+6) = mousebutton(4)
        mousebutton(shift+7) = mousebutton(5)
```
