### ISSUE TITLE
Minimizes to taskbar after click close button 

### ISSUE THREAD

**Issue by oucil** [symless/synergy-core#5454]
Currently, when I use the close button the application disappears leaving the service running.  The only way to leave the app in the taskbar is to use the `Window > Hide` menu option.  I would like a preference that would cause the window to Hide when the Close button is pressed.

This would be particularly useful while beta testing, I would like to leave it in the taskbar for quick access to things like the build number, log, etc. and it's quite annoying having to Hide on every machine I'm using it with.

Thanks!

P.S. Windows 10.

**Comment by as14** [comment]
This sounds great....I would like it too please

**Comment by kevdev-ebsco** [comment]
This is one of the only gripes I have about the program. Also Windows 10.

**Comment by szukai** [comment]
All I really want is to have is closing the GUI window do the same thing as "window->hide" and leave the system tray icon in place.  It'll be a huge improvement and follows convention for "windows apps with system tray icons". Also having an option where the system tray icon always show as long as the background process is running would be more useful than having to check taskmgr everytime I want to see if it's running.

**Comment by nbolton** [comment]
> All I really want is to have is closing the GUI window do the same thing as "window->hide" and leave the system tray icon in place. It'll be a huge improvement and follows convention for "windows apps with system tray icons". Also having an option where the system tray icon always show as long as the background process is running would be more useful than having to check taskmgr everytime I want to see if it's running.

We recently changed how this works in v1.15, so I'd love to hear your feedback on how it works now.
