### ISSUE TITLE
Invert scrolling for specified clients

### ISSUE THREAD

**Issue by fridtjof** [symless/synergy-core#5455]
I'm running a Windows desktop acting as a server and a Macbook Pro acting as a client when it's on my desk.

I want to keep on natural scrolling (which inverts scrolling) because I use the trackpad when my Macbook isn't on my desk. However, when using Synergy, this also applies - so scrolling on Windows is normal but on OS X it's inverted.
I'd love a way to invert scrolling for specific clients to neutralize this.

**Comment by yhong-emporia** [comment]
This enhancement should be reopened as I'm trying to do the same thing.  I have a mouse reverser app (Mos) which reverses the mouse locally on my mac but it does not reverse the input coming in from Synergy.  A per device mouse reversing setting would be immensely helpful.
