### ISSUE TITLE
Add client side certificates support

### ISSUE THREAD

**Issue by henryptung** [symless/synergy-core#5488]
Currently certificates are generated in Synergy Pro for server-side usage, to allow the client to properly trust the server. However, I'd like to propose a mode where verification is bidirectional, i.e. the server also requires the client to use its own certificate for SSL handshake, and prompts for trust the same way the client currently does. This allows the connection to be used in a fully untrusted network environment.

**Comment by nlyan** [comment]
Note that the risk of an unauthenticated client connecting to a server is limited to leaking the clipboard contents to that client. This is obviously not entirely acceptable but it's always the server that is in control of input. The server also requires that the config include the new clients screen name and won't allow multiple connections with the same screen name.

At the moment it's a ease-of-use vs absolute security trade-off.
