### ISSUE TITLE
Can't type pipe or back slash into cygwin with UK keyboard

### ISSUE THREAD

**Issue by pwr22** [symless/synergy-core#5507]
Cannot Type Pipe (|) or Back-Slash () Into A Cygwin Window With UK Keyboard
These are the same key, pipe is the key shifted

At the beginning this worked fine (typing into Cygwin on the client). After a while it stopped working. The key events I see generated for this key pressed are `alt+ctrl+#` which does indeed generate the correct key in most things but not Cygwin

Server: Ubuntu 16.04, Synergy Basic 1.7.6, UK keyboard
Client: Windows 10, Synergy Basic 1.7.6, UK keyboard

I've worked around this using a horrible hack with **AutoHotKey** to capture this combination, plus it shifted and convert them

**Comment by XinyuHou** [comment]
@pwr22 
Do you mean it works in other apps but just not in Cygwin and it happens randomly?

**Comment by pwr22** [comment]
@XinyuHou My apologies for the delay in response, been busy with work

Yes, it works in other apps fine including **git-bash** which I think also uses *mintty*, so my guess is it is something to do with **Cygwin**'s input translation layer not liking `alt+ctrl+#`

It doesn't happen randomly though, the following happens

1. To begin with everything works fine
2. Suddenly **Cygwin** breaks as described
3. This never has resolved so far, it continues to be broken once it has occurred
