### ISSUE TITLE
Request for upgrade of setup screens arrangement

### ISSUE THREAD

**Issue by grigorovich** [symless/synergy-core#5619]
### Operating Systems

Client: Any
Server: Any
### Request for upgrade of screen arrangement

"Screen" - i mean ScreenNames of machines in ServerConfiguration/ScreenAndLinks/LayoutGrid.

Probably to add ability to screens arrangement like:
-- move position by mouse dragging of "ScreenName" by X,Y
-- change scale for each 'screen' (this option very helpful for different DPI/size of displays)
-- snap to borders between screens

Note: Now screen arrangement works on grid 5x3 cells very strict.

**Comment by nbolton** [comment]
@nlyan Dupe of #4173?
