### ISSUE TITLE
Hotkey-sending does not work with "Shift" on Win10

### ISSUE THREAD

**Issue by kaluang** [symless/synergy-core#5636]
### Operating Systems

Client: Win10 (Version 1607)
Server: Win10 (Version 1607)
### Synergy Version

1.8.3-stable-db9181b
### Steps to reproduce bug
1. Server-Configuration, Hotkeys
2. Set: keystroke(_anything_) => keystroke(Control+Shift+Alt+") / Only send to client

(Hotkey => Command / Settings)

The client receives a &lt;Control+Shift+Alt+2> instead.
(&lt;"> is a shifted &lt;2> on my german keyboard layout)

It is not possible to send a keystroke like &lt;Control+Shift+Alt+j> anymore, combinations without &lt;Shift> work fine.

Assumption: Synergy probably sends one &lt;Shift> too much, so not only does the client receive the &lt;Shift>-keypress, it also shifts the letter. And at least Autohotkey on a Win10-Client can not recognize combinations like &lt;Control+Shift+Alt+J> with the uppercase &lt;J>.
### Other info
- First occured in 1.8.3, previous versions worked fine.
- Workarounds: Don't use &lt;Shift> in hotkeys OR  For numbers in your hotkeys you can shift the keys in the synergy-settings like &lt;1>=>&lt;!>. That does not work for letters though, because synergy will only save the lowercase version in the configuration.

**Comment by brandjames** [comment]
I have the same bug, it took me awhile to remember I had set a hotkey for shift+q and I only complained when typing and needed the "Q". 

My workaround was I used shift and the tilde key. I don't use it.

Operating Systems
Client: WinXP Pro
Server: Win10 Pro V1607

Synergy Version
1.8.3-stable-db9181b
