### ISSUE TITLE
Server side cursor disappears when entering client screen

### ISSUE THREAD

**Issue by mwong6271480** [symless/synergy-core#5643]
### Operating Systems

Client: Mac OSX Sierra 10.12

Server: Mac OSX Sierra 10.12
### Synergy Version

1.8.3-stable-db9181b
### Steps to reproduce bug

Server side cursor intermittently disappears when entering client screen. It may disappear from both screens for up to 10 seconds before re-appearing. It happens about once every 5-6 times going from server to client.  Log shows the following: WARNING: cursor may not be visible
- When did the problem start to occur? When I I upgraded Server OS to Mac Sierra
- Is there a way to work around it? No, I have to wait until the mouse becomes available again.
- Does this bug prevent you from using Synergy entirely? Yes pretty much as I need instant access to both screens as part of my workflow.

I have downgraded Synergy down to 1.7.3 (currently on 1.8.3) and have verified that the behavior is present in all versions. (Did not occur when I was on El Capitan).

**Comment by mwong6271480** [comment]
Update and more information on this issue. It is related to the clipboard sharing. If I disable clipboard sharing on the server side the problem goes away.

**Comment by grigorovich** [comment]
bug like 'clipboard sharing' setting

**Comment by tomun** [comment]
I'm seeing this issue after upgrading both server and client to sierra.   Per mwong6271480's comment, I disabled clipboard sharing on the server and the issue stops.

**Comment by rietta** [comment]
I am also experiencing this bug.

**Comment by tomun** [comment]
I found that if I disable handoff in system settings > general then the issue goes away.  Seems to be a conflict between the new clipboard sharing via handoff and synergy 's clipboard sharing.

**Comment by rietta** [comment]
I'm testing the disabling handoff trick. Will confirm if that has an impact. Unchecking the clipboard option in Synergy has not been reliable.

**Comment by rietta** [comment]
After a few hours, I can antidotally confirm that turning off handoff on the two Macs stopped the mouse cursor from disappearing until disconnect while moving between the two.

**Comment by redgular** [comment]
Same here. I turned off Handoff and it started working as expected immediately.

**Comment by tsdeng** [comment]
Seeing the same problem in macOS sierra 10.12.2, disabling clipboard sharing seems to fix the problem

**Comment by rstevens011** [comment]
ditto on this with Sierra 10.12.  workaround is disabling clipboard sharing

**Comment by dpickett** [comment]
so much better, thank you so much @tomun this issue was driving me nuts! :-)

**Comment by ZGainsforth** [comment]
I experience this two between two macs.  Problem is, I can't disable clipboard sharing because I use it so much!  Not having clipboard sharing would be more trouble than recovering the mouse cursor 20x/day.

**Comment by daftspunk** [comment]
Issue occuring in latest build (version 1.8.8-stable-25a8cb2) even with clipboard sharing disabled.

Server: Windows 10
Client: Windows 7

Will see if I can find an older version to downgrade to in the meantime.

**Comment by ipv1337** [comment]
I'm on the latest stable 1.8.8 using windows 10 as the server and fedora as the client same issue. Tried disabling clipboard sharing and all that jazz with no luck. Even tried using my fedora as the server and windows 10 as the client with no luck.

**Comment by jarseneault** [comment]
I am experiencing this issue between a Linux server and client.  Linux server running 1.8.8, client running 1.8.7.  Mouse cursor appears to become invisible (though is still active, since you can see the effects of it hovering over icons, though the icon itself is not there), and this happens reliably every other time the cursor enters the client.

**Comment by Mahelita** [comment]
I solved this issue by using the solution posted [here](https://github.com/symless/synergy/issues/4289) by estyrke.
Clipboard sync and handoff are active.
Server: Ubuntu 16.04, Syngergy 1.8.8
Client Mac OS 10.12.4, Syngergy 1.8.8

**Comment by jcomeaux** [comment]
I suppose this bug is still a thing?  I'm running a 10.15.1 Catalina Mac server and a Windows 2000 client...mouse disappears if I have clipboard sharing on..... m u s t   h a v e  c l i p b o a r d  s h a r i n g 😄
