### ISSUE TITLE
Alphanumeric keys stop working on Linux client 

### ISSUE THREAD

**Issue by the-spyke** [symless/synergy-core#5647]
### Operating Systems

Client: Ubuntu 16.04.1 LTS x64 (kernel 4.4.0-38-generic)

Server: Windows 10 Pro x64 (Version 1607)
### Synergy Version

1.8.3-stable-db9181b
### Steps to reproduce bug

It happens randomly. Sometimes, after switching to the client, alphanumeric keys stop working. Command keys continue to work nevertheless. Sometimes switching back to the server and pressing any key there fixes the issue. But sometimes it's not, and even restarting both client/server synergy application doesn't help. It fixes itself over the time.
More rarely this issue is opposite: command keys stop responding and alphanumeric keys work fine. 
### Other info

I had same issue with 1.8.2-stable as well.

**Comment by the-spyke** [comment]
Continue to reproduce on 1.8.4-stable-a6ff907.

**Comment by XinyuHou** [comment]
@the-spyke 
What program do you have focus on your server side after you switch to a client?

**Comment by the-spyke** [comment]
@XinyuHou 
Good question. I've tried a bunch of programs today, and, when it stops, it's Skype and Slack. With other programs in focus it keyboard start working again. But the bug doesn't always immediately appear, when I open Slack for the first time. Often I need to use my PC and switch back and forth for some time to reproduce it.

**Comment by the-spyke** [comment]
Update: it isn't issue with Skype or Slack, but with different input language. If I have different input language enabled in a focused window, then, after switching to the Linux client, I will have keyboard issues.

**Comment by XinyuHou** [comment]
It sounds like a keyboard layout issue. Please have a look at this ticket to see if it's similar to yours. Thanks.
#4280

**Comment by the-spyke** [comment]
@XinyuHou Yes, it looks similar.

**Comment by XinyuHou** [comment]
@the-spyke 
Do you still experience the issue?

**Comment by the-spyke** [comment]
Yes, I'm on 1.8.5-stable and it reproduces all the time.

**Comment by torinaki** [comment]
@XinyuHou I guess my issue https://github.com/symless/synergy/issues/4280#issuecomment-251178608 is related to this ticket.
For some reason Synergy ignores custom layout mapping for = and \` keys:
![image](https://cloud.githubusercontent.com/assets/1269372/23094223/d900d330-f5fd-11e6-8bee-dd5e00b8b5d4.png)

**Comment by emoon** [comment]
I have a similar issue between Windows 7 (server) and Windows 10 (client)

Sometimes it isn't possible to type `;` `[` `]` keys on the client. Switch back to the server and typing these characters in notepad or whatever and then switching back usually fixes this.

**Comment by torinaki** [comment]
@nbolton was it fixed?
