### ISSUE TITLE
Linux client ignores scrolls of less than 120 points

### ISSUE THREAD

**Issue by p12tic** [symless/synergy-core#5670]
### Operating Systems

Client: Ubuntu Linux 16.04
Server: OSX 10.12 Sierra
### Synergy Version

1.8.4 stable
### Steps to reproduce bug
1. Scroll slowly on the server
2. Observe that the client ignores the scroll
3. Observe that the log is filled with "WARNING: Wheel scroll delta (22) smaller than threshold (120)"
### Other info

Will do a PR with a fix shortly

**Comment by p12tic** [comment]
This fix for this issue will resolve https://github.com/symless/synergy/issues/3657 because the fix for the issue underlying the enhancement request will be no longer needed.

**Comment by XinyuHou** [comment]
This may be related to #5604

**Comment by XinyuHou** [comment]
Duplicate of #5604

**Comment by XinyuHou** [comment]
@p12tic 
Could you test our latest 10.12 build on your sierra to see if the problem persists? Thanks.

**Comment by XinyuHou** [comment]
@p12tic 
I can't reproduce this issue with a Sierra server and Ubuntu 15 client. Are you still experiencing the issue?

**Comment by p12tic** [comment]
@XinyuHou The issue is definitely still there. I get plenty of warnings like:
```[2016-11-01T20:07:56] WARNING: Wheel scroll delta (76) smaller than threshold (120)```

Note that I'm using the touchpad, not an external mouse.

The following two PRs fix two different issues causing the observed symptoms:
https://github.com/symless/synergy/pull/5673
https://github.com/symless/synergy/pull/5671

I've re-verified that they fix the problem when applied to the 1.8.6-rc1 version.

**Comment by XinyuHou** [comment]
@p12tic 
Please test this nightly
http://symless.com/nightly?filter=synergy-issue5670-accumulate-scrolls-rc2-02b9a32

**Comment by XinyuHou** [comment]
Please try this nightly which merged pr 5671 and 5673
http://symless.com/nightly?filter=synergy-issue5604-choppy-scrolling-rc2-f03a03a

**Comment by p12tic** [comment]
Hi, I've verified that the nightly build fixes the observed issues.

**Comment by p12tic** [comment]
Closing in favor of https://github.com/debauchee/barrier/issues/67.

**Comment by dogweather** [comment]
If this has been fixed, could you please release it?

**Comment by ghostsarespooky** [comment]
Still seeing this behaviour. Synergy 1.11.1-stable-55ec3105 for client and server. Ubuntu 18.04 client with Catalina 10.15 server. If anyone needs help with testing or log files, I'm more than happy to help!
