### ISSUE TITLE
Windows: uninstallation causes service in a disabled state

### ISSUE THREAD

**Issue by xmstspider** [symless/synergy-core#5675]
### Operating Systems

Client: Windows 10 x64

Server: Fedora 24 x64
### Synergy Version

1.8.x
### Steps to reproduce bug
1. Remove old version 
2. and Install a new version
3. Installation  cannot be completed due to Windows service error
### Other info
- When did the problem start to occur? Every time
- Is there a way to work around it? Yes, the user needs to restart the OS
- Does this bug prevent you from using Synergy entirely? No

Put anything else you can think of here.
After removing the old version, I checked the Services and saw that Synergy service was in Disabled state without controls. The only way how to 'fix' this is to restart the Windows, after thta the installation works as expected. Shouldn't be necessary though...

//Zdenek

**Comment by database9-445** [comment]
I didn't encounter exactly the same glitch but perhaps it's related. 

OS: Windows 10 Home x64.
Synergy Version: 1.8.4-stable-a6ff907
Notes: 
 - Logged on using an Administrator account.
 - Synergy service was running

Steps to reproduce.:
1. From Windows File Explorer ran the installer.
2. Stepped through to the install button.
 - Noted that UAC prompt didn't show
 - Installer did not ask to stop the service or to exit the already running Synergy
 - Installer stalled. It didn't freeze, it just behaved as if it were waiting for something. 
3. Cancelled installation
4. Started a third-party file manager - run as administrator
5. Re-ran installer.
6. Stepped through to the install button.
7. Prompted to elevate (AUC)
8. Installer asked me to close the running Synergy. I didn't note at which step. Done.
9. Continue. Finish. 
10. Start Synergy. No problem.

Additional Information:

Windows Error Log: 
Dates and Times: 
10/17/2016 11:15:47 AM
10/17/2016 11:25:20 AM
10/17/2016 11:36:53 AM
10/17/2016 11:51:49 AM
10/17/2016 12:00:33 PM

Log Name:Application
Source: Bonjour Service
Event ID: 100
Level: Error
Message: Bad service type in ._synergyServerZeroconf._tcp.local. Application protocol name must be underscore plus 1-15 characters. See <http://www.dns-sd.org/ServiceTypes.html>
