### ISSUE TITLE
Broadcast certain keys option

### ISSUE THREAD

**Issue by Hubro** [symless/synergy-core#5701]
### Operating Systems

Server: Windows 10 (version 1511, OS Build 10586.589)
Client: Debian GNU/Linux 8 (jessie) 3.16.0-4-amd64
### Synergy Version

1.8.4-stable-a6ff907
### Steps to reproduce bug

When I'm working on my Linux client, I have music or video running on my Windows server. When I press media keys (like mute) when the Linux client is in focus, the mute key is forwarded to the Linux client properly, as it should. **But:** I would like all media keys (audio up, audio down, mute, play/pause etc.) to always register only on the server, no matter what screen is in focus. This way I can work on my Linux screen while listening on music on my Windows server, and I can click the pause media key to pause the music.

Poking around the wiki here on Github I made this config:

```
section: screens
  beast:
  shiny:
end

section: links
  beast:
    left = shiny
  shiny:
    right = beast
end

section: options
    switchCorners = all
    switchCornerSize = 100
    switchDelay = 0

    keystroke(AudioMute) = keystroke(AudioMute,beast)
    keystroke(AudioDown) = keystroke(AudioDown,beast)
    keystroke(AudioUp) = keystroke(AudioUp,beast)
    keystroke(AudioPlay) = keystroke(AudioPlay,beast)
    keystroke(AudioPrev) = keystroke(AudioPrev,beast)
    keystroke(AudioNext) = keystroke(AudioNext,beast)
end
```

"beast" is the name of my Windows PC, "shiny" is the name of my Linux laptop. As you can see in the options section, I'm trying to get the media keys to register only on "beast", but what happens instead is that the media keys stop working completely.

As soon as I add the line `keystroke(AudioMute) ...` to the config and apply it, the mute button stops working completely both on the client and on the host. As soon as I stop Synergy, the button works again on the server (of course). This goes for all the audio buttons.

I am sure that "beast" is the right screen name, because the log has lines like:

> switch from "beast" to "shiny" at 3439,464

The log says nothing when I try to press the mapped keyboard buttons.

Is this a bug, or have I done something wrong? How do I accomplish what I'm trying to do?

**Comment by Hubro** [comment]
I just tried to map the buttons to themselves, without specifying the screen:

```
    keystroke(AudioMute) = keystroke(AudioMute)
    keystroke(AudioDown) = keystroke(AudioDown)
    keystroke(AudioUp) = keystroke(AudioUp)
    keystroke(AudioPlay) = keystroke(AudioPlay)
    keystroke(AudioPrev) = keystroke(AudioPrev)
    keystroke(AudioNext) = keystroke(AudioNext)
```

Now the media keys work on the Linux client, but not on the Windows host. Is this perhaps a bug where the media keys can't be simulated on Windows hosts?

**Comment by Hubro** [comment]
It's been a month, anybody got any idea about this?

**Comment by XinyuHou** [comment]
This would a feature request

**Comment by mfacenet** [comment]
+1 on this request.  The ability to pin certain keys to the server or a specific client would be rather beneficial.

**Comment by Hubro** [comment]
@mfacenet @XinyuHou 

I'm confused. I wrote this config using your wiki. Isn't this already implemented? Isn't `keystroke(KEY,screen)` supposed to send the key stroke to the specified screen? Have I misunderstood something?

**Comment by Celant** [comment]
I'm afraid that gentleman on StackOverflow might be mistaken. I've just tested it locally in the office and I can't get them working. This, unfortunately, is a feature request as Synergy cannot natively do it

**Comment by nbolton** [comment]
@Celant Could you get Sam to remove his comment please? He must have misunderstood the question on SO.

**Comment by gnarliprime** [comment]
+1 I would also like to see this feature. 

@Hubro to me it looks like the documentation is saying that the the screen portion of the keystroke config makes it so the action will only be performend when the specified screen is focused, not that the keypress will always be sent to the specified screen.

**Comment by tamasd** [comment]
I have Synergy 1.8.8, Windows 10 Home FCU as the server and Ubuntu 17.10 as the client.  I am in a similar situation, as I want to play music on the server, and work on the client.

For me, the play/pause, next track, previous track buttons work, but the volume up/down are not. I have to stop the Synergy server on the server to get back the volume up/down buttons.

This is definitely some kind of a bug.

**Comment by djak250** [comment]
This still exists (dupe of #6275).
