### ISSUE TITLE
macOS: Can't copy paste images into Slack

### ISSUE THREAD

**Issue by Celant** [symless/synergy-core#5703]
### Operating Systems

Server: Windows 10 64-bit
Client: macOS 10.10
### Synergy Version

1.8.5-rc1
### Steps to reproduce bug
1. Copy picture into clipboard on mac
2. Attempt to paste picture into Slack on Windows
3. See image preview shows correctly
4. Click Upload on Slack
5. See that image fails to upload
### Other info

Work around this by pasting the image onto the desktop first, and then drag it into Slack

**Comment by wolfch** [comment]
I used to be able to do this - no more.  Now it's big, complicated workflow.

**Comment by StephenOTT** [comment]
👍

**Comment by jellisii** [comment]
Happens intermittently on Linux as well.

**Comment by discotroll65** [comment]
bump? Would love this functionality on mac, works so well on windows
