### ISSUE TITLE
Can't switch screens with hotkey from OSX server

### ISSUE THREAD

**Issue by auralarch** [symless/synergy-core#5714]
### Operating Systems

Server: Mac OSX 10.8.5
Client: Windows 7
### Synergy Version

1.8.4
### Steps to reproduce bug

Using a hotkey to switch screens from server fails (have tried a plethora a different hotkeys).
If I move the cursor to a client, then the hotkeys work (between clients and back to server), but once I move back to the server screen (manually or with hotkey) they stop working again.
### Other info

The following is an edited versions of significant sections of the log file (I've removed extraneous mouse movements, etc.).
What remains contains the messages of the server starting up and the client connecting, and then movement to the the client screen, the hotkeys working to switch screens, but once back on the server the same key presses do not register as being hotkeys so nothing happens.

[synergy-log.txt](https://github.com/symless/synergy/files/560718/synergy-log.txt)

This same issue was reported by: [https://github.com/jiMuBao](url)
here: [https://github.com/symless/synergy/issues/5641](url)

**Comment by Sod-Almighty** [comment]
Five months and no response. That'd be lame for an open-source project, let alone a paid one.
