### ISSUE TITLE
Sticking keys from Windows server

### ISSUE THREAD

**Issue by j1and1** [symless/synergy-core#5721]
### Operating Systems ###

Server: Windows 10 version 1607 Build 14393.321
Client: Mac OS 10.12.1

### Synergy Version ###

1.8.5-stable-a18eba7

### Steps to reproduce bug ###

So I just upgraded to synergy 1.8.5 and started my day of work! After a while I noticed that "Shift","Alt" and "Command/Win" keys are sticking again! Finding the key which sticks and pressing them down again solves the issue for 5-10 minutes.... and then again they stick again! 

### Other info ###

* When did the problem start to occur? When I updated to Synergy 1.8.5 today!
* Is there a way to work around it? Yes use another keyboard and mice on Mac
* Does this bug prevent you from using Synergy entirely? Yes

I can't even finish this form without issues!!! So I'm going to use my workaround now!

**Comment by borganstein** [comment]
I second this. 

Happens on two windows machines  (Both Windows 10 Pro Insider Previews; Build 14955).
