### ISSUE TITLE
Clear version of tray icon on KDE and Mac

### ISSUE THREAD

**Issue by aaronkjones** [symless/synergy-core#5728]
![screenshot_20161103_213628](https://cloud.githubusercontent.com/assets/17125755/19993888/99050b18-a20e-11e6-8f4d-621ea91b1d86.png)
### Operating Systems ###
lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

uname -a
Linux bidg 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Synergy Version ###
1.8.5-stable-a18eba7, Oct 31, 2016

### Steps to reproduce bug ###
Install and launch.

### Other info ###
An SVG icon works best for tray icons.

**Comment by reality3d** [comment]
The same occurs in OS X (1.8.5-stable)
<img width="96" alt="screen shot 2016-11-09 at 14 59 41" src="https://cloud.githubusercontent.com/assets/3530957/20140742/2e619000-a68d-11e6-8df3-0a9ea903baff.png">
