### ISSUE TITLE
Client receives empty clipboard content

### ISSUE THREAD

**Issue by abienkowski** [symless/synergy-core#5729]
### Operating Systems ###

Server: Windows 10 (Version 1607)
Client: Fedora 23

### Synergy Version ###

1.8.4-stable-984ca-48

### Steps to reproduce bug ###

1. use the system for about a day, sometimes happens multiple time during the day.
2. when mouse is moved to the client (Fedora 23) mouse movement is observed, but not able to click on anything
2.1 or when I copy/past a previous or old clipboard is pasted into the client 

3. workaround stop/start server and wait for client to reconnect.

**Comment by epalzeolithe** [comment]
Hello

same issue with 1.8.5 stable a168eba7

The client are under OSX

The server windows 10

That's really annoying.

The bug can happen fast (lest than 10 mn)

**Comment by kndol** [comment]
I have reported the same issue: https://github.com/symless/synergy/issues/5716

**Comment by XinyuHou** [comment]
@abienkowski @epalzeolithe @kndol 
Please send us some logs with log level set to Debug.
https://github.com/symless/synergy/wiki/Sending-logs

**Comment by kndol** [comment]
http://pastebin.com/fBdASc2P
http://pastebin.com/7UDhrbmN

**Comment by senakafdo** [comment]
@nbolton, what exactly was fixed here, when you marked an important bug as "stale" and resolved it?
