### ISSUE TITLE
Mouse scrolling not working on client in start menu

### ISSUE THREAD

**Issue by makedir** [symless/synergy-core#5731]
Client/server newest stable release.

Client 32bit Windows10
Server 64bit Windows10.

Switching to client, mouse scrolling are not working in the start menu or apps, where it's working for example in normal programs like Edge.

**Comment by oportsac** [comment]
Also having this issue with the latest stable release

**Comment by makedir** [comment]
bump

**Comment by squarephreak** [comment]
I am also currently still experiencing this same problem on current release (1.11.1 "stable"). I have both systems using Win 10 X64. Any sign of a fix forthcoming?
