### ISSUE TITLE
Ubuntu: Can't use mouse in VNC

### ISSUE THREAD

**Issue by Unaidedsteak** [symless/synergy-core#5741]
### Operating Systems ###

Server: Ubuntu 14.10
Client: Windows 10

### Synergy Version ###

1.8.5

### Steps to reproduce bug ###

1. Start Synergy.
2. Move mouse onto Windows screen.
3. VNC into ubuntu server.
4. Try moving mouse on ubuntu server.
5. See that cursor does not move. 

### Other info ###
* Is there a way to work around it? Yes, Move mouse onto ubuntu server before opening VNC session.

**Comment by davidstoll** [comment]
You can also make it work by remoting into Windows machine and then kill synergy.  Then the mouse on the Ubuntu machine starts working again through VNC.

Also, it may be related:  If the mouse is on the Windows client and you try to run XBMC (aka Kodi), the program will begin to start up by showing a black screen.  But until you move the mouse back to the home computer (Ubuntu server) the splash screen for XBMC/Kodi will not come up and therefore the program itself will not finish starting.
