### ISSUE TITLE
Keyboard not shared when using Target Display Mode on Mac server

### ISSUE THREAD

**Issue by loretoparisi** [symless/synergy-core#5748]
### Operating Systems ###

Server: macOS Sierra 10.12.1/iMac
Client: macOS Sierra 10.12.1/MacBookPro

### Synergy Version ###

1.8.1

### Steps to reproduce bug ###

Use Synergy on iMac as server, MacBook Pro as client; iMac in Target Display Mode (F2):

1. Activate server and client
2. Put iMac in Target Display Mode: Command+F2 on iMac shared keyboard
3. Move the shared mouse on the MacBookPro screen

At this point the mouse will move from iMac screen (target display mode) to MBP screen, but the keyboard will not get focus.

### Other info ###
-

**Comment by dctrotz** [comment]
Same here. Has anyone started looking into this. If not I could look into it, any hints as to where to start looking would be appreciated.

**Comment by loretoparisi** [comment]
💯

**Comment by mileswilson** [comment]
Also seeing this - but the function keys (brightness etc) all work, as does the letter a, but only the letter a. Not sure why this would be!

**Comment by cre8ivejp** [comment]
I had the same issue here.

```
Server: iMac (El Captain)
Client: MacBookPro (El Captain)
```

I have contacted them about this few months ago. They said they already about this bug, but it will take about 1 year to fix it, so they refunded me.

I don't think they will fix this soon.

**Comment by GTAGAME** [comment]
Does it only affect Sierra or any version of macOS? If works on SL/Lion/ML/Mavericks without any issues, i would downgrade immediately. I hate the new design of OS X anyway.

**Comment by roshangautam** [comment]
If you are using synergy 2 with GUI you can simply disable and then enable to make it work. Unfortunately using CLI still has issues with iMac in target mode. Would really appreciate any updates here.

**Comment by thepaulswanson** [comment]
Has this been resolved?

**Comment by troldmand** [comment]
> Does it only happen on Sierra or on any version of macOS? If it works on SL/Lion/ML/Mavericks without any issues, i would downgrade immediately. I hate the new design of OS X anyway.

Not sure abut Sierra - but I get the error on High Sierra.

**Comment by troldmand** [comment]
> If you are using synergy 2 with GUI you can simply disable and then enable to make it work. Unfortunately using CLI still has issues with iMac in target mode. Would really appreciate any updates here.

This wasn't my experience - I couldn't disable and enable via. GUI to make it work. At best, it would allow `a` as a typed input and the mouse - but not the full keyboard.
