### ISSUE TITLE
Origin causes click not working on client

### ISSUE THREAD

**Issue by yidhoe** [symless/synergy-core#5750]
### Operating Systems ###

Server: Windows 10
Client: Windows 10 32 & 64.

### Synergy Version ###

1.8.5
### Steps to reproduce bug ###

1. Download Origin from: https://www.origin.com/
2. Open the program Origin, on opened you cannot click on Client machines until you have rebooted the Synergy Server Service.

### Other info ###

* When did the problem start to occur? Few months back I think maybe longer but only just became obvious what it was! :/
* Is there a way to work around it? Restart Synergy Service on the Server works fine unless you restart Origin again.
* Does this bug prevent you from using Synergy entirely? Yes until the server service is rebooted.

Put anything else you can think of here.

EA are Crap, I know it's not helpful but its relevant lol. :)

GL Thanks.

**Comment by cmellwig** [comment]
Can confirm on 1.8.7-stable-9799e96

**Comment by tatelax** [comment]
Can confirm this is still happening.
