### ISSUE TITLE
Distribute in a universal package format

### ISSUE THREAD

**Issue by polarathene** [symless/synergy-core#5769]
Any chance/plans of distributing via any of the Snaps, Flatpak, AppImage universal package formats for Linux? Up until now I've had the distro package managers provide it, just tried out a more niche distro that does not have a package for Synergy and figured one of the mentioned formats could be possibly useful as a distribution option.

**Comment by probonopd** [comment]
Would be especially interesting for the [nightlies](https://symless.com/nightly).

**Comment by polarathene** [comment]
> As for niche distros, the AppImage format would have the advantage that the host system does not need to have a special runtime installed.

Tried AppImage out on KaOS. The format has some expected dependencies/packages to be available by the system that are avoided for some stated reason when packaging apps into the format. In the case of the AppImage I recall trying(not sure if it used the dependency at all or if the format just expects it regardless), GTK was meant to provide a shared library to link against...It's a KDE/Qt only distro and they'll not provide such a dependency. That said that rules out Snaps/Flatpak for them as well apparently(they might be ok with KCP/community build script), so might not be a good example. Figured it was worth mentioning that AppImage isn't always going to work compared to the other formats.

**Comment by probonopd** [comment]
> The format has some expected dependencies/packages to be available by the system that are avoided for some stated reason when packaging apps into the format. 

The person who puts together the AppImage decides what to bundle inside, and what to expect as part of the target system. This decision largely depends on which systems are targeted. For common desktop distributions, it is reasonable to expect Gtk+ to be part of the target system; feel free to disagree and bundle Gtk+ inside the AppImage though.

**Comment by probonopd** [comment]
Generated an experimental AppImage based on the nightly deb, please try:
https://bintray.com/probono/AppImages/Synergy/_latestVersion#files

With 18 MB in size this is very comparable to the macOS version.

I did not test extensively, so it is expected that some fine-tuning might still be needed. I don't have multiple machines around right now to test; feel free to report back here how it works for you.

Here is the recipe that was used to produce it:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/Synergy.yml
As you can see, transforming the deb into an AppImage is really easy.

**Comment by probonopd** [comment]
@polarathene did you have a chance to try out the experimental Synergy AppImage yet?

**Comment by polarathene** [comment]
@probonopd Hi, I just gave it a go in a Manjaro KDE VM, added permission to execute it and right clicked to run via Konsole(defaulted to Ark). Worked perfectly far as I can tell :) 

The app icon is standard X one, so I guess it's not recognizing that properly like my host machine(Also Manjaro KDE) has. That could also be due to a theme set on my host. Systray proper icon is visible.

**EDIT:** Just installed the Synergy package from package manager and the title bar icon is still the X one, but taskbar is using a Synergy icon. I've also noticed the styling of things like checkboxes/radio buttons etc are not respecting the proper styling(I think I've read this is due to sandboxing and requires some XDG config?) For some reason, some text lines are clipped vertically and the `Configure Server` and `Browse...` buttons are squished. I'll try sort you out with a comparison screenshot :)

**Comment by polarathene** [comment]
http://imgur.com/a/C83Rj

![comparison](http://i.imgur.com/l4HySmV.png)

**Comment by probonopd** [comment]
Regarding the icon, please see http://discourse.appimage.org/t/appimage-does-not-show-icon-in-task-bar/40

Regarding the looks, probably the themes are not bundled inside the AppImage.

**Comment by polarathene** [comment]
@probonopd So I need to run that API call or that can be added and  done within the AppImage?

Bundling themes wouldn't make too much sense I'd imagine. I assume the issue can be resolved if  you can use the host Qt instead of bundling Qt into the AppImage? I'd think it a common package to have, or you could provide two images, one with Qt bundled and one that uses the systems Qt(or if you have a way to detect that in a single AppImage and only use bundled if the system one does not exist).

**Comment by probonopd** [comment]
To fix the icon in the upper left hand side of windows, please use `QApplication::setWindowIcon()` in your Qt application. Yes, icons can be bundled within AppImages, but to make them show up correctly that call may be necessary.

As the author of an AppImage, you could decide not to bundle Qt but that would leave users of that AppImage with no or incompatible Qt versions out in the rain. AppImages are supposed to have no dependencies other than what comes with your target systems (Linux distributions) in their default install.

**Comment by polarathene** [comment]
> Also on macOS or Windows, each application bundles its own copy of Qt.

And I imagine they look native and seamless? When I tried the AppImage it was out of place because it did not use the system theme. You suggested bundling the theme, but as a universal package that'd not work as various KDE distro can have different Qt themes, the same I believe is true with Gnome and other DE that might have different Qt theme such as Arc.

On linux it is not unreasonable to expect Qt to be on the system, two images solves the issue too, Synergy, Synergy-sysQt or something along those lines. I love the idea of universal package/app format but if it doesn't integrate well with the desktop visually then I'd be less interested. Qt and GTK are rather common, I think you only run into the issue with niche distributions such as KaOS which are Qt only and don't allow GTK packages, my first AppImage experience was on KaOS and would not work because it expected GTK to be available on the system.

> To fix the icon in the upper left hand side of windows, please use QApplication::setWindowIcon() in your Qt application. 

So that should be added by Synergy devs?

**Comment by probonopd** [comment]
> When I tried the AppImage it was out of place because it did not use the system theme.

Qt least for GTK based systems, Qt 5.8 greatly improves the look-and-feel to "practically native".

**Comment by rugk** [comment]
Can you please re-consider this?

I guess, flatpak is very suited for your project. In contrast to snap, you can self-host it and you get (auto-)updates.
I think auto-updates are a goal for v2, so you may consider flatpak as one way to distribute them.

**Comment by probonopd** [comment]
You can also make AppImages self-updating by bundling AppImageUpdate or using `libappimageupdate`.

**Comment by rugk** [comment]
The advantage of flatpaks is you get an update feature and they are sandboxed.

**Comment by rugk** [comment]
Ah [you can use a third-party tool for updates](https://github.com/AppImage/AppImageUpdate) okay. Still not the same as flatpaks and not as good integrated. Basically, they are just different technologies/concepts, altghough many of your points of course also apply for flatpaks.

So just offer both.

**Comment by probonopd** [comment]
Why third-party? AppImageUpdate is a project from the AppImage project. You could even, if you like, embed self-updating functionality into the Synergy AppImage to make the updating fully self-contained. Might even be integrated into the menu ("About -> Check for updates...") like you can do on the Mac with [Sparkle Framework](https://sparkle-project.org/).
