### ISSUE TITLE
Client list multiple server ips for round robin selection

### ISSUE THREAD

**Issue by demosdemon** [symless/synergy-core#5773]
### Operating Systems ###

Server: Windows 7
Client: macOS Sierra

### Synergy Version ###

1.8.6-stable-2ab21aa

### Other info ###

My server is on three networks and my client can join any of the three networks at will for various reasons. It would be handy-dandy if the client could have the ips of the server stored comma separated. The client would then attempt to connect to each server -- on failure, move on to the next server. The server is already aware that it is a member of multiple networks and displays the multiple ip addresses (although the bolding makes no sense and is wrong on my client).

**Comment by rolandg** [comment]
https://github.com/symless/synergy/issues/3665
