### ISSUE TITLE
Touch Bar of the new MacBook Pro support

### ISSUE THREAD

**Issue by jondong** [symless/synergy-core#5780]
### Operating Systems ###

Server: MacOS Sierra v10.12.2, MacBook Pro 13 inches with Touch Bar
Client: Ubuntu 16.04 x86_64

### Synergy Version ###

1.8.6-stable-2ab21aa

### Steps to reproduce bug ###

1. Start synergy on both Mac and Linux, make Mac as the server and connect Linux as client;
2. Move your mouse to Linux, start a terminal
3. in the terminal, start a vim session: vim foo.txt
4. Press 'i' to enter input mode and start to input something
5. Press the virtual 'esc' in the touch bar to leave the editing mode, and you'll find it is totally not responding.

### Other info ###
If you connect an external keyboard through USB to your mac, the ESC key works fine on Linux in vim. Only virtual esc in Touch Bar is not working.

**Comment by griffc** [comment]
Confirmed no touch bar functions work in 1.8.7-stable-9799e96.  Same configuration as above.

**Comment by chongxi** [comment]
Confirmed. How to solve?

**Comment by guoang** [comment]
Confirmed on windows.

**Comment by Helcaraxan** [comment]
Any news on this issue? Am investigating myself now and it is a real pain to not have this. :cry:

**Comment by Helcaraxan** [comment]
So for the moment the only real thing that I have been able to do is to remap my Caps Lock key to function as a secondary Esc key. This at least does map correctly to the Linux Esc key.

**Comment by emmanuelguerin** [comment]
Hi, with Synergy 2.0 out, any news on this?
