### ISSUE TITLE
change language on the client

### ISSUE THREAD

**Issue by Axlyted** [symless/synergy-core#5798]
Hi,

I got the following setup:

windows 7 desktop ~ server
windows 10 laptop ~ client

When I use synergy on my laptop and I change my language from EN to HEB for example.. it seems like the language switch is working well(I can see that in the botton toolbar).. but as soon as I start typing.. it revert to the previous language... the only "solution" at the moment is go back to my desktop screen.. change the language and then move my mouse to my laptop. it's not actually solution you know..

I think the previous version (1.8.4) didn't had this issue. Is there somewhere I can get this version instead? I mean, In case you don't have a solution for me.

Thank you,
Tom

**Comment by XinyuHou** [comment]
> Operating Systems
> 
> Client: Linux Mint 17.3
> 
> Server: Windows 7 Pro SP1 AMD64 EN
> 
> Synergy Version
> 
> 1.8.8-rc1-fc3cc78 on both sides
> 
> Bug
> 
> On all hosts Ctrl+Shift configured to change language.
> Sometimes language selection ceases to work on client. I press Ctrl+Shift to select EN, tray icon was changed but changes backward to RU on any alphabet char pressed. Even if I try to change language by clicking in tray language will changed to wrong on key press.
> 
> Workaround
> 
> Restart Synergy on client
> 
> Log from client before it restarted: synergy-client.log.txt

**Comment by jack17529** [comment]
Oh we need to revert the changes then?

**Comment by Axlyted** [comment]
I would gladly like it to work.. currently It's unbearable. I want to drop off 3 keyboard and use only 1 but until this issue will be solved, I'm unable to do that.

Also.. when I change language, it's shown as "?????" instead of the actual letters... sometimes it works accordingly but sometimes it doesn't... I think version 1.8.6 was able to use my other language like it should.. instead of "????"

FYI

**Comment by radevop** [comment]
Same here, this bug was reopened a lot of times, but I can't get any reaction from devs on it. #4309

**Comment by Axlyted** [comment]
Please, don't abandon this feature! It's like, super important :o

**Comment by javarool** [comment]
Use Autohotkey with this script:

`~*Ctrl::
	keyCtrlOff := false
	;msgbox down
return

~*Ctrl Up::
	keyCtrlOff := true
	;msgbox ctrlup
return

~*Shift::
	if (keyCtrlOff) 
return
	;msgbox % keyCtrlOff
	SetFormat, Integer, H
	Locale1=0x4090409  ; Английский (американский)
	Locale2=0x4190419  ; Русский
	WinGet, WinID,, A
	ThreadID:=DllCall("GetWindowThreadProcessId", "Int", WinID, "Int", "0")
	InputLocaleID:=DllCall("GetKeyboardLayout", "Int", ThreadID)
	if(InputLocaleID=Locale1)
		SendMessage, 0x50,, % Locale2,, A
	else if(InputLocaleID=Locale2)
		SendMessage, 0x50,, % Locale1,, A
return  `

**Comment by nbolton** [comment]
Hello, thanks for raising an issue. Would you mind re-submitting using the template? For bugs, we need the exact steps to reproduce.

**Comment by idsoftgit** [comment]
Bug is still present in synergy 1.10.1. So, is there any reasonable solution? Or AHK is the best way to fix this issue? This is really annoying bug.
Please give it a little bit more attention.

**Comment by 0xmono** [comment]
It is just not supported.
Answer from support: "Currently, that's not actually a feature we support (multiple language support), but it is a feature request that we're planning to add to Synergy".

**Comment by nbolton** [comment]
Replaced by #6506
