### ISSUE TITLE
Keyboard input doesn't prevent sleep on Mac server

### ISSUE THREAD

**Issue by OmgImAlexis** [symless/synergy-core#5839]
### Operating Systems ###

Server: Mac OS Sierra
Client: Windows 10

### Synergy Version ###
1.8.7 on both client and server

### Steps to reproduce bug ###

1. Use only keyboard on server until server goes into sleep/lock mode
2. Profit?

### Other info ###

* When did the problem start to occur? Always been an issue from what I know.
* Is there a way to work around it? No/Yes, you can disable sleeping/lock after x time on the server
* Does this bug prevent you from using Synergy entirely? Yes and no? It's more of an annoyance

If I use the mouse/trackpad at all on the server this doesn't happen so it seems that keyboard input doesn't prevent locking/sleeping whereas mouse movement does.

**Comment by NoICE** [comment]
It's not only keyboard input. The mouse doesn't prevent the screensaver from running too. The point is, you are with the mouse on the client, and the server thinks the mouse AND keyboard doesn't do anything...
