### ISSUE TITLE
Excessive handle usage in service

### ISSUE THREAD

**Issue by Jonatino** [symless/synergy-core#5856]
### Operating Systems ###

Server: Windows 10 x64

### Synergy Version ###

latest stable build

### Steps to reproduce bug ###
1. Run synergy for a day or two

### Other info ###

I've been experiencing an insane memory leak where synergy just keeps opening handles without closing them. As you can see in the screen shot:

https://dl.dropboxusercontent.com/u/91292881/ShareX/2017/02/Taskmgr_2017-02-22_00-28-00.png

It has 23k handles open even though I haven't even opened synergy at all in the past day. It climbs by about 5-10k handles per hour and gets to the point where it just hogs all the ram on my system and I need to reboot (I have 32gb ram).

**Comment by yupi2** [comment]
You should use [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653) to see what handles it currently has open. And a [post to go along with it.](https://blogs.technet.microsoft.com/yongrhee/2011/12/19/how-to-troubleshoot-a-handle-leak/) 
Feel free to post the handles open in the lower-pane window
