### ISSUE TITLE
Active screen should stop others screensaver kicking in

### ISSUE THREAD

**Issue by cjgibson** [symless/synergy-core#5886]
### Operating Systems ###

Server: Windows 10, Version 1607 (OS Build 14393.693)
Client: elementary OS 0.3.2 "Freya"
Client: Ubuntu 16.04 LTS "Xenial"
Client: Ubuntu 15.10 "Wily"

### Synergy Version ###

Server: 1.8.5
Client: 1.8.2
Client: 1.8.5
Client: 1.8.2

### Steps to reproduce bug ###

This is not a bug, it is a feature request.

### Other info ###

I work for a small startup. As a result of an enlightening external security audit all developer machines are now set to automatically lock following 5 minutes of inactivity. Just curious if there is any way for Synergy to transmit "junk" activity packets to the server and all connected clients in order to prevent the OS from locking the machines when any one of them is being used.

As an aside, it would also be interesting if Synergy could be configured to relay specific key combinations globally between the server and all clients. For example, in my case, the server would be configured to await and intercept the key combination Ctrl+L (the keyboard shortcut for "lock screen" in Windows), and would relay Ctrl+Alt+L (the "lock screen" shortcut within my Linux systems) to all client nodes simultaneously.

**Comment by yupi2** [comment]
The thing about globally sending locks to every screen may work. Hotkeys can send keystrokes to multiple clients AFAIK but I haven't tested. I'm not sure if key combos count as a keystroke or if it needs to be a single key though.

**Comment by nlyan** [comment]
@yupi2 keystrokes for hot keys can consist of any number of modifier keys and exactly 1 regular key or mousebutton.

**Comment by XinyuHou** [comment]
@cjgibson 
Do you mean if Synergy has a feature that can keep all the machines wake as long as one is active?

**Comment by cjgibson** [comment]
@XinyuHou: That is correct. I'm mostly trying to find an easy way to stop my machines from dozing off while staying in compliance.

The suggestion regarding the ability to arbitrarily intercept and redirect / modify keystrokes was a bit of an afterthought on my part while I was typing up the summary. Although it looks like such functionality could potentially solve a number of requests (https://github.com/symless/synergy/issues/5887, https://github.com/symless/synergy/issues/5701, https://github.com/symless/synergy/issues/5369, https://github.com/symless/synergy/issues/4840, https://github.com/symless/synergy/issues/4808, https://github.com/symless/synergy/issues/4280).

**Comment by XinyuHou** [comment]
Thank for the suggestion.

Relaying keys sounds like the original screensaver sync feature which is if one of your machines actives screensaver, the others should trigger that as well.

However,  this request is more like while one machine is active, the others shouldn't trigger screensaver.

I hope I understand it right.

**Comment by cjgibson** [comment]
@XinyuHou: You've got it.

With regard to the concept of arbitrary input interception and redirection, would you like that suggestion broken off into a separate issue? Or just left here?

**Comment by JimConger** [comment]
I work for an bigger company, but we must our security people must have lunch with your security people.  I need this feature, too.  I can't find another way to provide feedback on this as a licensed user (who is willing to pay for features...), so I am adding this comment.

I think that if the keyboard and mouse are active on any screen, synergy should send some "keep alive" input events to the other screens to keep their screen savers from turning on.  I don't think this would be a security problem: I'm still at my systems and using the keyboard and mouse.

**Comment by mfacenet** [comment]
To expand upon this, every platform allows an application to keep a screen open and "hot" in some manner, while synergy is receiving input it should be activating that "hot" screen on all the boxes it's connected to.  I can def. see some additional functionality here as well, a universal lock would be great.  I.e. I hit Win + L to lock my Windows 10 box, perhaps Shift + Win + L locks ALL clients.  Perhaps I just need to start digging into code though.
