### ISSUE TITLE
Failed to connect between non-SSL and SSL nodes

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy-core#5898]
### Operating Systems ###

Server: Any OS
Client: Any OS

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Start a server.
2. Login as a pro user.
3. Configure server to accept the client you are going to setup next.
4. Start a client.
5. Type server IP on client side.
6. Click Start on client.

### Other info ###

* When did the problem start to occur? Since the first version that introduced SSL
* Is there a way to work around it? Either enable SSL on all machines or disable it.
* Does this bug prevent you from using Synergy entirely? No

**Comment by deckar01** [comment]
A good first step might be to detect this scenario and provide clearer messaging to the user.
