### ISSUE TITLE
Server doesn't remember clipboard size limit after reopen

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy-core#5919]
### Operating Systems ###

Server: microOS 10.12

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Open GUI.
2. Go into server configure -> Advanced server settings.
3. Tick Enable clipboard sharing
4. Change size to 3 mb
5. Click Ok.
6. Restart GUI
7. Go to the same page

Before restart

![image](https://cloud.githubusercontent.com/assets/9194706/24200638/9cb35f58-0f05-11e7-996f-b363fcb71abb.png)

After restart

### Other info ###

![image](https://cloud.githubusercontent.com/assets/9194706/24200645/a72addd0-0f05-11e7-8ce9-d03693345f57.png)

* When did the problem start to occur? 1.8.8
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No

**Comment by davidebeatrici** [comment]
I'm using the same version, on Debian Stretch. I don't have the size option.
In my case it doesn't remember the "Enable clipboard sharing" checkbox state, which is ticked automatically every time I restart Synergy.

Maybe the problems are related?
