### ISSUE TITLE
SSL server doesn't accept auto detected clients

### ISSUE THREAD

**Issue by nodje** [symless/synergy-core#5924]
### Operating Systems ###
Server: macos 10.12.3
Client: macos 10.12.3

### Synergy Version ###
1.8.8

### Steps to reproduce bug ###
Open server, open clients, they can't connect:
Server
```
INFO: OpenSSL 1.0.2 22 Jan 2015
INFO: zeroconf client detected: client.local
ERROR: ssl error occurred (system call failure)
ERROR: eof violates ssl protocol
ERROR: failed to accept secure socket
INFO: client connection may not be secure
```
Client
`WARNING: failed to connect to server: Timed Out`
### Other info ###

* When did the problem start to occur? 
A couple of version ago, maybe after 1.8.6
* Is there a way to work around it? 
Not that I know of yet (I've read on some issue that it was possible to disable SSL?)
* Does this bug prevent you from using Synergy entirely? 
Yes

**Comment by dunnydann** [comment]
same

**Comment by mick-t** [comment]
I have the same or a similar problem with a Linux client and a Mac Server.

**Comment by nickinvenco** [comment]
same. Win7 server & Ubuntu client

**Comment by cedriclecoz** [comment]
Same issue here, using a mac server and a linux client.  Work around is to disable ssl (on the server (mac) > menu Synergy / Preferences  /  Network security > untick Use SSL)
but it's not ideal as unsecure...

**Comment by jodyswartz** [comment]
experiencing the same problem with Ubuntu client.
