### ISSUE TITLE
Allow keyboard and mouse focus on different screens

### ISSUE THREAD

**Issue by benjymous** [symless/synergy-core#5957]
### Operating Systems ###

Server: Win10
Client: Win10

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

(Not really a bug, more of a feature request!)

- Server as main workstation, Client on right displaying email/slack/etc
- Window has focus on server machine
- User typing into focused window
- User pushes mouse, which moves the pointer onto the client display
- Keyboard focus switches to the last clicked window on client machine, and keypresses go to that window instead of the expected one. (even though the server machine's window still appears to have focus - i.e. still has a flashing cursor, and "focused" window styling)

Requested (optional) 

- Mouse moves into client machine, but user doesn't click
- Keyboard focus stays with server machine's window, only changes when user explicitly clicks a window on the client machine (i.e. the way you'd expect it to behave with multiple monitors on a single Windows computer)

Also, when the user focuses a window on Machine-N would it be possible to remove focus from all windows on all other machines - this would at least prevent the accidental text capture

**Comment by nlyan** [comment]
Interesting suggestion. Many thanks
