### ISSUE TITLE
User interface failed to load local fingerprint

### ISSUE THREAD

**Issue by maqp** [symless/synergy-core#5959]
### Operating Systems ###

Server: Ubuntu 16.04
Client: Ubuntu 16.04

### Synergy Version ###

1.8.8-stable-c30301e

### Steps to reproduce bug ###

No apparent way to reliably reproduce the bug except exiting the program and restarting it/computer once or a few more times. This problem has persisted for some time as I can't recall a version that did not have the bug. Sometimes after reinstall of OS/Synergy, the fingerprint has been shown, but it later disappears and importantly, I've never seen it reprinted after server side program has once stopped displaying it. It does not prevent me from using Synergy but blind Diffie-Hellman isn't exactly secure.

**Comment by XinyuHou** [comment]
Probably related to #5901

@maqp  could you check ~/.config/Synergy/ directory to see if you can find a finger print file?

**Comment by maqp** [comment]
`~/.config/Synergy/` only has `Synergy.conf` and that file doesn't contain the fingerprint.

I tried following your advice as per [this comment](https://github.com/symless/synergy/issues/5901#issuecomment-286767441): I closed Synergy, deleted the `Synergy.conf` file and restarted Synergy. This creates a new key pair and a fingerprint is again displayed on screen. This does not however create a file for fingerprint, or add it to `Synergy.conf`. Neither does closing the program. When I restart Synergy, the fingerprint is again missing. 

Storing the configuration file when fingerprint is being displayed and restoring it after restart also doesn't help.

**Comment by yupi2** [comment]
Certificate stuff is in `~/.synergy` I believe

**Comment by maqp** [comment]
@yupi2 you are right. The fingerprint resides in `~/.synergy/SSL/Fingerprints/Local.txt`. I double checked and understandably, the fingerprint does not change between deletions of irrelevant `Synergy.conf` file, or restarting the program. 

So it would appear the bug is, Synergy server fails to load fingerprint from the `Local.txt` file during startup. Meanwhile, it's good to know from where I can view it until the bug is fixed.

**Comment by XinyuHou** [comment]
@yupi2 
Good point. This sounds like a bug in GUI side.

**Comment by maqp** [comment]
@nbolton [Looks like the bug is still present](https://imgur.com/a/1mMUB6I): the SSL Fingerprint is not showing.

**Comment by nbolton** [comment]
@maqp Thanks for letting us know.

**Comment by Jnewbon** [comment]
A release candidate is available that incorporates a fix for this issue

[Download v1.11.0-rc2](https://snapshots.symless.com/public/1.11.0-rc2?github#5959)

If you find any bugs in the release candidate related to this issue please comment here.
