### ISSUE TITLE
High CPU usage while moving mouse on Mac client

### ISSUE THREAD

**Issue by mabowers** [symless/synergy-core#5991]
### Operating Systems ###

Server: Windows 7 Pro x64 SP1 (7601)
Client: macOS Sierra 10.12.4 (16E195)

### Synergy Version ###

1.8.8-stable-25a8cb2 on server and client. I am a Synergy Pro customer.

### Steps to reproduce bug ###

**Whenever the mouse is moved on the macOS client, the CPU utilization for Synergy is extremely high. When simply moving the mouse around in a circle, the Synergy CPU utilization reported in Activity Monitor is over 60%** (out of a possible 200%, as reported by macOS Activity Monitor). Meanwhile, the Synergy server uses a more respectable 4-5% (out of a possible 100%, as reported by Process Explorer). The problem only seems to occur with mouse movement. If I mash on the keyboard, the Synergy client CPU usage is only about 5%.

Video: http://bowers.email/synergy/high_cpu_mouse.mov
(Note how the CPU usage skyrockets while the mouse is moving, then stops when the mouse stops.)

### Other info ###

My client and server logs are here: http://bowers.email/synergy/log/ I have included captures at DEBUG1 and DEBUG2 log levels. (Please note, when I captured in "DEBUG2" mode, the Synergy server/client apps used 99% of a core on each machine, and the cursor moved VERY slowly, perhaps 1Hz or less. Capturing in DEBUG1 was fine.)

My Mac (client) is a rMBP 13" late 2013 with 2.4GHz i5-4258U. (Passmark CPU score = 4079)
My PC (server) is an AMD Phenom II X4 B93. (Passmark CPU score = 3377)
They aren't brand-new machines, but they aren't terrible either. (_Heck, I remember using Synergy on a Pentium 4 server and an iMac G3 client in the early 2000s and it ran beautifully!_)

The machines are connected to the LAN via Gigabit Ethernet. (The Mac is using a Thunderbolt-to-Gigabit Ethernet adapter and the Wi-Fi is disabled.)

Things I have tried:
- disabling SSL (no change)
- restarting client and server Synergy apps (no change)
- rebooting client and server machines (no change)
- reinstalling client and server Synergy apps (no change)

Any ideas? I love using Synergy, but 60% CPU utilization each time I move the mouse is hard to justify...

**Comment by XinyuHou** [comment]
Maybe related to #2866
