### ISSUE TITLE
Configuration reset on Ubuntu

### ISSUE THREAD

**Issue by pbouillet** [symless/synergy-core#6000]
### Operating Systems ###

Server: Windows 7
Client: Ubuntu 17.04

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Start Ubuntu OS
2. Synergy client lost all configuration, need to reenter everything (license key, connection information etc.)

### Other info ###

* This does not happen all the time. It's like once a week after multiple restarts that synergy loses the whole configuration somehow and wants me to reenter everything. I have no idea currently what could cause this.

**Comment by XinyuHou** [comment]
@pbouillet 
Do you mean most of the time, Synergy remember your settings, but once a week, it completely loses all the setting information?

**Comment by pbouillet** [comment]
It's just a feeling that it's like once a week. But yes, this is exactly what happens and I need to reenter everything from scratch, as if I would have just installed it.

**Comment by pbouillet** [comment]
@XinyuHou fyi, today it happenend again. I haven't done anything between the last 2 startups that would somehow explain it to me. Do you have any idea on where I could look to pinpoint the problem? This really drives me crazy :smile:

**Comment by XinyuHou** [comment]
@pbouillet 
Please have a look at this file when everything works fine.
~/.config/Synergy/Synergy.conf

Then compare it when you have to reset everything. Note: When you open GUI and realize you need to  reconfigure, don't close GUI, as doing that would update the conf file.

**Comment by boffe** [comment]
Same thing is happening to me too. I believe it started after I upgraded to Ubuntu 17.04. I have Synergy 1.8.7. Will check the .conf file next time it happens.

**Comment by boffe** [comment]
Happened again just now.  The only thing in the file was
`[General]
screenName=mesier-dev
port=24800
interface=
logLevel=3
logToFile=false
logFilename=/var/log/synergy.log
wizardLastRun=7
language=en_US
startedBefore=false
autoConfig=true
elevateMode=false
elevateModeEnum=0
autoConfigPrompted=false
edition=3
cryptoEnabled=true
autoHide=false
serialKey=
lastVersion=1.8.7
lastExpiringWarningTime=0
activationHasRun=false
`

**Comment by XinyuHou** [comment]
@boffe 
> serialKey=

Have you activated Synergy with a serial key before?

**Comment by pbouillet** [comment]
It's the same for me, after this happens, the file looks like this and the serial key is gone.

**Comment by XinyuHou** [comment]
We recently just found a bug in our serial key code. Do you have any non-ASCII character in your name when you registered Synergy account?

**Comment by pbouillet** [comment]
No, all are ASCII characters.

**Comment by boffe** [comment]
Same here, no ASCII characters

**Comment by Garbee** [comment]
I'm seeing this on Elementary OS 0.4.1 (Ubuntu 16.04 based). It typically happens every couple of reboots (which for me means I can hit this multiple times a day.) Now on my laptop I just re-installed it doesn't seem to remember anything except my license key when I restart. I need to constantly re-enter the server hostname and start the process.

**Comment by Garbee** [comment]
I switched to testing OpenSUSE (Leap 42.2) out and this problem also occurs here. So it seems like a general issue on Linux. What I have noticed is it primarily dumps the config when the setting "Hide on startup" is turned on.

<details>
<summary>Synergy.conf</summary>

```
[General]
screenName=linux-4udz.suse
port=24800
interface=
logLevel=3
logToFile=false
logFilename=/var/log/synergy.log
wizardLastRun=7
language=en_US
startedBefore=false
autoConfig=true
elevateMode=false
elevateModeEnum=0
autoConfigPrompted=false
edition=3
cryptoEnabled=true
autoHide=false
serialKey=
lastVersion=1.8.8
lastExpiringWarningTime=0
activationHasRun=false
```

</details>

**Comment by Garbee** [comment]
What I've done to try and work around this (time will tell) is I made my own startup script to copy a backup config file into place and then start synergy.

<details>
<summary><pre>$HOME/bin/synergy-on-startup.sh</pre></summary>

```bash
#!/bin/bash

rm ~/.config/Synergy/Synergy.conf
cp ~/.config/Synergy/Synergy.conf.backup ~/.config/Synergy/Synergy.conf
qsynergy &
exit 0
```

</details>

To get this to autostart in Gnome for example, you need to make a desktop file for your user and set that to autostart.

<details>
<summary><pre>$HOME/.local/share/applications/synergy-on-startup.desktop</pre></summary>

```
[Desktop Entry]
Name=Synergy On Startup
Exec=/home/jonathan/bin/synergy-on-startup.sh
Type=Application
Terminal=false
```

</details>

With that desktop file in place, I logged out and back in to make sure it was recognized. Then in the Gnome Tweak Tool > Startup Applications remove qsynergy I was running directly before and instead run my custom `Synergy On Startup` application.

**Comment by roman-yagodin** [comment]
Same here on Linux Mint Debian Edition 2 "Betsy" server and client.

I wonder, where Synergy GUI settings stored? It's look like GUI use `$(HOME)/.config/Synergy/Synergy.conf`, but it not working just like it it was configured via GUI: e.g. no check mark on systray icon and "Synergy is starting" message do not disappear, while mouse and keyboard sharing working OK.

**Comment by Garbee** [comment]
`$HOME/.config/Synergy/Synergy.conf` is correct. Seems to me from what you described it is operating fine from the config but the GUI isn't triggering things properly for some reason. Perhaps make sure you're using the same GUI to the process in the icon tray. I've noticed sometimes in odd cases I'll open a new Synergy GUI beside the existing process. Which then causes some distortions like you have described.

**Comment by roman-yagodin** [comment]
Then I start Synergy GUI, it creates two processes: `synergy` (GUI, parent) and `synergys` (server, child).

**Comment by eljenso** [comment]
Having this problem on Fedora 25 for a while now.  
Saved config to a file so when Synergy resets, I just configure to use this file and enter serial key.

**Comment by phonosys** [comment]
this issue is so annoying ... 
in my situation , serverHostname in Synergy.conf was resetting every time.
i solved it by set all my settings in ~/.config/Synergy/Synergy.conf (serverHostname,cryptoEnabled,serialKey,autoHide) and then set the file to read only mode.
worked like a charm since.

**Comment by danilocesar** [comment]
Same here... Running Fedora 24 and Fedora 25.

Happens in two of my machines. No special characters in my name. Plain UTF-8 chars.
It basically resets the file, losing all configuration including serial-key.
I'm running the official package, not the one from Fedora.

**Comment by Garbee** [comment]
FTR setting the config to readonly mode is a much better method to get things consistent than constantly re-copying the config in a custom script like my original solution. At least until the bug is fixed, it works like a grand charm as long as you are constantly reconfiguring any servers or clients.

**Comment by mattdawson** [comment]
Just happened to me on Ubuntu 17.04, Synergy 1.8.7

**Comment by sBrecht** [comment]
Happening here as well.  Ubuntu 17.04, Synergy 1.8.7     Happens every few days, system starts up and I get the "Welcome to Synergy" screen on boot.  Have to re-set my configuration from scratch each time.    Connecting to a Windows machine, 1.8.8, never have the issue there.

**Comment by Garbee** [comment]
@sBrecht Please read the discussion. There are a few ways to make it not overwrite the old config, primarily making it read-only once you have it all working. Until the root cause is fixed, it will at least work without being overly annoying.
