### ISSUE TITLE
Clipboard stops working after unlock on Windows

### ISSUE THREAD

**Issue by jwang36** [symless/synergy-core#6020]
### Operating Systems ###

Server: Windows 10
Client: Windows 8.1

Lock on both client and server and then unlock them, the clipboard (from client to server) will most likely be dead. It will be ok again if the client is restarted. But restart server has no effect. Using synergyc.exe in client to connect server will not have such problem but will have server to client issue.

### Synergy Version ###
1.8.8-stable-25a8cb2

### Steps to reproduce bug ###
Both client and server are working as service.

1. Start both client and server. The clipboard works fine.
2. Lock both client and server.
3. And then unlock them one by one
4. Copy some text on client and do paste on server. Nothing pasted. 
5. Copy some text on server and do paste on client. It works.

### Other info ###

* The problem will most likely happen during a round of sign-out/sign-in or lock/unlock.
* Using command line program (synergyc.exe) to connect to server will not have such problem. But copy text on server and paste on client doesn't work.
* This issue is quite annoying. Please fix it ASAP.

**Comment by furlongm** [comment]
Also experiencing this issue with Windows 7 and OS X El Capitan.

Synergy 1.8.8-stable-25a8cb2 on both.

**Comment by yan12125** [comment]
Here is a work-around - automatically restart Synergy upon unlocking:
```Python
import socket
import struct
import winreg

# This script work-arounds an issue [1] by restarting Synergy via the IPC protocol.
# To use it, the script needs to be registered as a scheduler job triggered upon unlocking [2].
# [1] https://github.com/symless/synergy-core/issues/6020
# [2] https://stackoverflow.com/a/1830683

# For details about the Synergy IPC command ICMD, see:
# https://github.com/symless/synergy-core/blob/1.14.5.17/src/gui/src/IpcClient.cpp#L101
def icmd(command, elevate):
    data = b'ICMD'
    data += struct.pack('>i', len(command))
    data += command.encode('ascii')
    data += struct.pack('B', elevate)
    return data

def main():
    synergyKey = winreg.OpenKeyEx(winreg.HKEY_LOCAL_MACHINE, 'SOFTWARE\\Synergy', access=winreg.KEY_READ)
    command, _ = winreg.QueryValueEx(synergyKey, 'Command')
    elevate, _ = winreg.QueryValueEx(synergyKey, 'Elevate')
    elevate = int(elevate)
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(('127.0.0.1', 24801))
    # Send an empty command to stop Synergy
    # https://github.com/symless/synergy-core/blob/1.14.5.17/src/gui/src/MainWindow.cpp#L1006
    sock.send(icmd('', elevate))
    # Send the desired command to start Synergy. Here I use the last recorded command.
    # https://github.com/symless/synergy-core/blob/1.14.5.17/src/gui/src/MainWindow.cpp#L768
    sock.send(icmd(command, elevate))
    sock.close()

if __name__ == '__main__':
    main()
```

**Comment by yan12125** [comment]
The issue still happens from time to time. I still need to restart Synergy to get back working clipboard sharing. @nbolton Could you reopen the issue?

From logs, I noticed the following warning. That line also appears when clipboard sharing works, though.
```
[2024-07-03T13:57:45] WARNING: failed to open clipboard: 5
```
