### ISSUE TITLE
RaspberryPi Package

### ISSUE THREAD

**Issue by paul-suarez** [symless/synergy-core#6029]
Problem:
Want to remotely interact with several raspberry pi systems. Installed latest version of Raspbian OS from RaspberryPi.org. When I do "sudo apt-get install synergy" as the client on the raspi, I get unmet dependencies. See attached screen.
![image](https://cloud.githubusercontent.com/assets/28361305/25702713/d904938e-3104-11e7-861c-b2e8032c3d0e.png)

Solution:
Officially Support Raspberry Pi package.

**Comment by QuAzI** [comment]
In Linux Mint repo (which based on Ubuntu) also too old version. You must use version from official site or build from sources. Maybe it can help
https://groups.google.com/d/msg/synergy-users/8-VzV5ucWB0/vBeRDChCAgAJ

**Comment by andrewssobral** [comment]
It works on NVIDIA Jetson TX2 ? Need I compile Synergy from source? Thanks!

**Comment by nbolton** [comment]
Duplicates #6305
