### ISSUE TITLE
Dump config file to log

### ISSUE THREAD

**Issue by nlyan** [symless/synergy-core#6031]
Problem: Asking users for details of their configuration alongside their log is time consuming. 

Solution: At DEBUG and above dump the config file in to the log when Synergy starts.

**Comment by paul-suarez** [comment]
JDDoesIT from forums:

When we report issues we are often asked for the system information as well as the installation details. Could we get a dump button in the help menu that puts all the info one could possibly need into our clipboard so we don't have to type it? I'm just being lazy, but that is not always a bad thing...

[Forums 2966 link.](https://symless.com/forums/topic/2966-system-dump/)
