### ISSUE TITLE
Sticky scrollbar within Chromium on client

### ISSUE THREAD

**Issue by wltjr** [symless/synergy-core#6038]
### Operating Systems ###

Server: Gentoo Linux, mesa-17.1.0_rc4, xorg-server-1.19.3, efl 1.19.0 (same issues under qt/kwin)
Client: Gentoo Linux, mesa-17.1.0_rc4, xorg-server-1.19.3, efl 1.19.0 (same issues under qt/kwin)

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

I do not have reliable means to replicate this issue. Sometimes it will not occur during the course of an entire work day. Other times it happens quite often. When scrolling pages. Even with releasing the left mouse button. The scroll bar seems to still be stuck to the cursor. Moving the cursor around the page continues to move the scroll bar up and down. I cannot even reliable get it to release at times. I have to click on the scrollbar a few times to release. I am not sure I have tried moving the mouse outside of the window. I know anywhere within the window the scrollbar remains stuck when it occurs. Next it occurs I will try moving outside the window to see if it releases, etc.

I will try to work on at least a reliable way to replicate. I can visit the same website/webpage back to back and not replicate the issue. But on repeated attempts it will come up. This problem does not exist on anything other than Chrome/Chromium. It does not seem to be related to the window manager. I am running EFL 1.19.0/Enlightenment 21.7. I was on Plasma/QT/Kwin before that. Same issues. Maybe a GTK issue given it uses that library and the scrollbar would be part of that vs the window manager.

### Other info ###

This seemed to come up with a past update of Chrome/Chromium. I have filed an issue on the [Chrome/Chromium bug tracker issue #713786](https://bugs.chromium.org/p/chromium/issues/detail?id=713786). It was requested I file one here as well. They have another open linked in that same ticket that has the same issue but under Chrome/Chromium Remote Desktop. I am not sure if the bug is specific to synergy or Chrome/Chromium. It may have started to occur with an update of either. I have used both for years. This is a new issue in the last ~8 or so months maybe.

It does not seem to be related to network issues or other. I have seen synergy stick before. Keep typing the same character etc. Cursor lagging severally or long period between characters typed showing up, and other. All due to network issues, wifi latency, interference, etc.

At one point when it was stuck. I killed synergy client entirely and switched to the track pad on my laptop. The scrollbar remained stuck even then. I had to click around to release it just the same. Which would some what rule out network issues. Anytime a character repeated or other due to network issues. Switching to the keyboard/mouse of the laptop immediately stopped any issue. Not to mention if I stopped/killed synergy client. That for sure ended any network issues between client and server. But the stuck scrollbar remains either way. It could be putting Chrome/Chromium into some odd state triggered by synergy or software movement of the cursor.

**Comment by wltjr** [comment]
Moving the cursor outside the window does not release when it is stuck. Just now on another attempt to replicate. When it was stuck. I clicked on the scrollbar it released. Did not move within the window, nor over the scrollbar. Soon as I moved out it was stuck back to the cursor. But then I came back in, clicked on the scrollbar, and it released. I have not been able to replicate that since.

That at least confirms though that moving outside the window does not release the scroll. At one point it seemed to cause the scrollbar to stick to the cursor, follow movement. When the scrollbar was released, and cursor moved outside the window.

It seems like the cursor is grabbing the scrollbar at times when I am not clicking the mouse. At the same time not fully releasing it. Like if I just mouse over the scrollbar. I cannot replicate that, just seems to be what occurs at times. It is VERY inconsistent! Sorry about not being able to provide accurate steps to reproduce. I am trying to reproduce reliable myself. When I want it to act up it does not, and when I am just doing normal stuff it occurs... :(

**Comment by tharmstrong** [comment]
Steps to reproduce:
1. Click and hold down the primary mouse button on the scroll bar
2. do some scrolling up or down
3. now move mouse pointer outside scroll bar
4. finally release the mouse button
Now if you move mouse up and down, scolling behaves as if the button is still down... which is totally wrong.

**Comment by wltjr** [comment]
Nice! For #3 I have to move the pointer outside of Chromium's window. If I release the button over the HTML or other area of Chromium the scroll bar does not "stick".

Also once it sticks, if you move the mouse over the scrollbar, it acts like the button is still pressed when it is not. Seems like it has a hard time detecting mouse release outside of the window. Right now I have another window, that the scrollbar is not stuck. HOWEVER if I place the cursor over the scrollbar with NO buttons pressed. The scrollbar moves along with the cursor up or down, as if it is stuck. But it is not doing that on the rest of the page.

Sometimes it remains stuck even when the cursor is over the HTML area. Though I cannot use the steps above to replicate that. I can very reliably replicate the scrollbar stuck to cursor when cursor is placed over the scrollbar with no buttons pressed. I just follow the steps above and for #3 release outside the window. Then when I move back over it moves with the cursor despite no buttons pressed.

Good stuff @tharmstrong! Thus far the only reliable way I can replicate some of the behavior. Hopefully others can as well. Still not sure if this is a synergy issue as it only seems to effect Chromium. Not sure if that is the case for @tharmstrong as well or not.

**Comment by tharmstrong** [comment]
More info - don't ask me how I came to deduce this - it just came to me after some days of fiddling around.

It seems there is a feature implemented that, if you have clicked on the scroll bar, moved it, and then you don't release the button for 1sec, then even if you release the button the scroll is kept selected. This seems to be useful if you want to keep scrolling with the mouse. To "unstick" this, you just need to click somewhere. Try it:
1. Click & hold on the scoll bar control
2. Drag the control to another position
3. Count 1sec without moving it
4. Release the button
5. Move the mouse up/down, and the window will scroll with you (you can even move mouse left/right and scrolling will still be in "stick" mode.
6. Now click somewhere and it will return no normal non-scrolling behavior.

The above seems to be designed that way - I have no issue with that - though many users may find it annoying!

In any case my issue was even more confusing, and I still believe there is a bug in this "sticky scroll" implementation. Do this instead:
1. Click & hold on the scoll bar control
2. Drag the control to another position
3. Count 1sec without moving it
4. Release the button
5. Move the mouse up/down, and the window will scroll with you (you can even move mouse left/right and scrolling will still be in "stick" mode.
6. Now use the **keyboard** up/down/pageup/pagedown keys to scroll a whole more.  It works as expected. Scroll some pages down using the keys.
7. Finally move the mouse again - WAIT!  the page jumps back to where it was just before I used the keys!!!

This is a bug --> Using the keys to scroll should disable the "sticky scroll" mode. But it doesn't, so the page jumps!!

Hope this helps.

PD: problem happened to me while editing this post - I'm so used to keep finger down on the button while reading/scrolling - so I am one of the annoyed users...

**Comment by wltjr** [comment]
I am not able to replicate the stuck scrollbar within window. I still have to move outside. I cannot confirm the  "feature" you mentioned but sounds interesting. For me it mostly happens within the window when I do not want. I still cannot replicate that via any means. But I can reliable replicate it by moving outside the window.

I was able to confirm what you mention about the keyboard when stuck. When I got it stuck via moving outside the window. I used the keyboard to scroll to a new position. Soon as I came back in, it snapped back to the position I left off with the cursor and was still stuck.

**Comment by tharmstrong** [comment]
My mistake @wltjr!!  I had "Turn On ClickLock" selected in Mouse Properties (win7 Control Panel).  Disregard that part and stick with original steps to reproduce. (The "feature" was this ClickLock thing from Win7 - confused me more than required)

**Comment by wltjr** [comment]
Good to know the problem exists on Windows, as I am on Linux. Least it rules out anything related to the platform or OS.

**Comment by simoniz0r** [comment]
Holy crap, this is a Synergy issue?  I've been blaming my Chromium based apps for having terrible scroll bars all this time, and it was Synergy? lol

I find this behavior next to infuriating, to be honest.  It happens to me quite frequently in Electron applications especially.  I am using Windows 10 as the host machine and KDE neon (based on Ubuntu 16.04) as the client machine.

**Comment by wltjr** [comment]
No I do not think this is a synergy issue. This only seems to effect Chrome/Chromium on Linux or Windows. Synergy devs requested I open a issue here. But the original is an upstream Chromium bug. Firefox does not have this issue, nor anything else with a  scrollbar. Just seems to happen under synergy. Though there is another related bug upstream when using Chromium via remote desktop.
[Chrome/Chromium bug tracker issue #713786](https://bugs.chromium.org/p/chromium/issues/detail?id=713786)

**Comment by wltjr** [comment]
This is the other issue which for what ever reason is not public. I am about to stop using Chromium/Chrome, and go back to Firefox. There is no reason this should require log in, except maybe egg on Google's face or something. It is not security related, at least was not when I last looked.
[Chrome/Chromium bug tracker issue #683434](https://bugs.chromium.org/p/chromium/issues/detail?id=683434)

**Comment by wltjr** [comment]
I am no longer using Chrome/Chromium so I will be unable to test or comment on this bug any further. Life is to short. This issue, another with hashtags, and my growing dislike and distaste for anything having to do with Google. Maybe someday this will be fixed. Though knowing Google I have little hope.

Unsubscribing from notifications on this issue. Good luck to others!

**Comment by simoniz0r** [comment]
@wltjr Unfortunately, anything that is based on Chrome/Chromium (including electron apps) will be effected by this bug.
