### ISSUE TITLE
Running state not detected when logging level is lower than NOTE

### ISSUE THREAD

**Issue by zelivans** [symless/synergy-core#6056]
If logging level of "Error" or "Warning" is selected, the main window does not detect that the server is actually running (and the "Synergy is running" message won't be displayed). That's because the expected message is logged as "Note". 

Maybe fix this by not relying on the logs at all? See the code in `MainWindow::checkConnected` (MainWindow.cpp). Could `MainWindow::checkLicense` also be affected by this?

**Comment by nlyan** [comment]
Unfortunately, after the service was introduced on Windows, the IPC mechanism was not extended to provide extended signalling beyond relaying log messages and issuing simple commands to the service itself.

The current plan is to replace all of this infrastructure in version 2, so fixing this not a priority.
