### ISSUE TITLE
DPI scaling causes mouse stuck on switching screens

### ISSUE THREAD

**Issue by axlan** [symless/synergy-core#6070]
### Operating Systems ###

Operating Systems

Server: Ubuntu 17.04
Client: Windows 10 Pro Version 1703

Synergy Version

1.9.0-rc3-f987381

See detailed analysis in:
https://github.com/symless/synergy/issues/4041

It appears that this problem has reappeared and the setting options have changed for the work around.
I had to go into the compatibility properties for synergys.exe and select:
```
Override high DPI scaling behavior.
Scaling performed by:
Application
```
and restart the service. 

This still doesn't totally fix the issue, but seems to reduce it.

**Comment by XinyuHou** [comment]
@axlan 
If you don't apply workaround manually, what is the issue? Can't move cursor to client?

**Comment by axlan** [comment]
The issue is that the mouse gets "stuck" after crossing between screens and takes a large amount of movement to fully cross into the other monitor.

**Comment by jongrant** [comment]
This bug is back in Windows 10 r1709. The fix that eventually worked for me was to remove the "Run in compatibility mode for: Windows 7" setting on synergys.exe. Unfortunately the configuration tool forces this setting back on any time you open it.

**Comment by fuzzzerd** [comment]
This is also a problem in 2.x. Exactly as described, the cursor is stuck and requires large movement to cross screens.

**Comment by giammin** [comment]
@fuzzzerd thank you for saving me from buying version 2

this bug ad many others is there since the beginning

**Comment by fuzzzerd** [comment]
When will this issue be addressed in 1.x?

**Comment by yhling** [comment]
I'm using the CLI version of Synergy and fixed this problem by disabling display scaling in the command prompt.

`set __COMPAT_LAYER=HIGHDPIAWARE
@echo off
synergys.exe -c config.conf`
