### ISSUE TITLE
Can't type anything when server uses Chinese input

### ISSUE THREAD

**Issue by mYmNeo** [symless/synergy-core#6075]
### Operating Systems ###

Server: osx sierra 10.12.5
Client: windows 10 15063.0

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Switch input method to Chinese on mac
2. Move cursor to windows client, and type anything
3. NO CHARACTERS on windows

### Other info ###

* When did the problem start to occur? Sometimes, not very often
* Is there a way to work around it? Yes, move cursor to mac client, switch to English, move cursor back to windows client, it works again.
* Does this bug prevent you from using Synergy entirely? No, but it's uncomfortable

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

**Comment by nlyan** [comment]
Related to #4280
