### ISSUE TITLE
Ubuntu Mouse Not Visibly Moving

### ISSUE THREAD

**Issue by rcobelli** [symless/synergy-core#6078]
### Operating Systems ###

Server: Mac OS X 10.12.5
Client: ubuntu 16.04

### Synergy Version ###

1.8.8 (Client & Server)

### Steps to reproduce bug ###

1. Move mouse from server to client 
2. Mouse becomes visible on client (where it previously was moved to using mouse plugged into client)
3. Cursor does not move but is still moving invisibly
    - You can tell by being able to click buttons and type in text fields

### Other info ###

* **When did the problem start to occur?** On instillation (earlier today)
* **Is there a way to work around it?** No
* **Does this bug prevent you from using Synergy entirely?** Yes

**Comment by pbludov** [comment]
This is a known gnome issue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755050

As a workaround

$ gsettings set org.gnome.settings-daemon.plugins.cursor active false

will turn this feature off completely.

**Comment by nlyan** [comment]
@rcobelli were you able to try out @pbludov'ss suggestion?

**Comment by neulaender** [comment]
@pbludov Did not work for me :/. Tried it both on server and client (although I think client should be enough). 

Problem: 
`dconf write /org/gnome/settings-daemon/plugins/cursor/active false`
didn't change anything, while
`gsettings set org.gnome/settings-daemon.plugins.cursor active`
gave me an error: 
**"No such schema 'org.gnome.settings-daemon.plugins.cursor'"**

**Comment by ccidral** [comment]
Same issue here.  I just moved to Ubuntu 17.10 daily build.  I get the "entering screen" message, but the mouse pointer doesn't move.  Keyboard doesn't respond as well.  @pbludov's suggestion didn't work for me.

## Operating Systems

Server: Mac OS X 10.12.6
Client: ubuntu 17.10 (daily build as of Aug/10/2017)

## Synergy Version

1.8.8-stable-25a8cb2 (Client & Server)

**Comment by jameskentTX** [comment]
Same issue here. 

**Operating Systems**
Server: Debian “buster” 64
Client: Debian “buster” 64

**Synergy Version**
1.8.8-stable (for 64), client & server.

**Comment by jameskentTX** [comment]
I solved invisible mouse cursor problem on Debian buster with this post:

https://bbs.archlinux.org/viewtopic.php?pid=1677925#p1677925

Gnome with Xorg and cursor is visible again.

**Comment by knilink** [comment]
Same issue on ubuntu 17.10.
Fix by using "**Ubuntu on Xorg**" option when login.
https://askubuntu.com/questions/961304/how-do-you-switch-from-wayland-back-to-xorg-in-ubuntu-17-10
Thanks to jameskentTX.
