### ISSUE TITLE
Xbox left trigger forwarded from server to clients

### ISSUE THREAD

**Issue by AeliusSaionji** [symless/synergy-core#6085]
Windows 10 pro on both sides.

Issue occurs on at least 1.8.8 and 1.9.0

Playing a game with an Xbox 1 controller on the PC server, left trigger, and ONLY left trigger, is swallowed by synergy if I switch to a client.

**Comment by nlyan** [comment]
@Link-Satonaka any chance you could set your server log level to DEBUG1 and provide us with a fresh log of a session in which this occurs?

**Comment by Link-Satonaka** [comment]
[synergy.log.txt](https://github.com/symless/synergy/files/1161098/synergy.log.txt)

It actually has stranger behavior than I previously mentioned. The left trigger is sent to the game when pressing the start or select buttons.
