### ISSUE TITLE
Synergyd.exe preventing uninstallation

### ISSUE THREAD

**Issue by Mithraw** [symless/synergy-core#6087]
### Operating Systems ###

Server: Windows 7
Client: Windows 10

### Synergy Version ###

1.8.8-stable-25a8cb2
1.90-rc3

### Steps to reproduce bug ###

1. Attempt to uninstall synergy
2. Synergy hangs at around 50% uninstall status until it fails

### Other info ###

* Noticed issue around June 5th, 2017 when attempting to uninstall latest beta version of Synergy to rollback to last stable because latest beta version does not work period on my server
* Is there a way to work around it? Yes. To successfully uninstall synergy, you must kill off all processes in task manager as synergy is uninstalling. You must check "Show processes from all users" and end synergyd.exe process. Sometimes sysnergys.exe needed to be ended also.
* Does this bug prevent you from using Synergy entirely? No.

**Comment by nlyan** [comment]
We are currently investigating this issue on the v1.9 branch but, as far as we are aware, it does not occur in v1.8.x. 

When using v1.9 you should see particular high CPU usage in task manager from synergyd.exe (you'll have to view processes from all users)

Can you confirm?

**Comment by Mithraw** [comment]
Reinstalled v1.9 on my host machine to test. Synergy.exe is using up a lot more memory than v1.8 stable. Syndergyd.exe is using less memory but has a CPU usage of 25% versus 00 for synergy.exe. However, there might be another issue as v1.9 on my host machine is stuck on "synergy is starting" status. Is there a specific debug log you would want me to upload regarding this?
