### ISSUE TITLE
Copying unicode characters between Linux machines fails

### ISSUE THREAD

**Issue by cheese** [symless/synergy-core#6092]
### Operating Systems ###

Server: Fedora 24 x86_64
Client: Fedora 25 x86_64

### Synergy Version ###

1.8.8

And also tested 1.7.6

### Steps to reproduce bug ###

1. Copy a string of wide characters (like Chinese chacters) on the server
2. Paste on the client

### Other info ###

* These pair of machine used to be ok when copying wide characters. At someday the issue just occur. And rebooting any machine does not turn good. I don't know what actually troubles synergy.
* Copying from client to server works good.
* I will be responsible to provide further infomation.

**Comment by cheese** [comment]
It seems the clipboard content is changed when pasting on the client.

If I use a clipboard management tool, the content is good when copy is done on the server before pasting. And after pasting on the client, the clipboard content is changed to the '?' chars.

That means if I copy from the server, and then stop synergy and paste on the client, he content is the good one.

**Comment by dcwaterm** [comment]
I too had same problem of failing to copy/paste from clipboard.  The problem started when my workstation upgraded from fedora 22 to fedora 26.  After compiling my own version, same problem.  To shorten this up,  I finally went back to old-school thinking... why not try starting synergys from /bin/sh (instead of /bin/bash):

``/sh  -c  'synergs'  &

That worked... copy/paste again working.   Simple solution for me.  See if this solves problem for others.

**Comment by cheese** [comment]
The problem only occur when I run a remote-viewer[1] on the client. That seems remote-viewer, after some version, will interfere with synergy.

[1] https://virt-manager.org/

**Comment by krisjace** [comment]
In my case it is the opposit, when I copy from Linux (server) and paste into client (OSX) the Chinese characters persist. The other way around I end up with a sequence of question marks instead.

Version (both server and client): 1.10.0-stable-275cdc1c
Server on Ubuntu 16.04 64 bit
Client on OSX High Sierra

**Comment by orn1983** [comment]
Did you guys ever solve this? I'm experiencing the same when copying from Windows (client) to Linux (server). Question marks instead of UTF8 symbols. Other way around works fine.
