### ISSUE TITLE
Scroll down interpreted as back

### ISSUE THREAD

**Issue by ninjalf2** [symless/synergy-core#6108]
### Operating Systems ###

Server: Arch Linux kernel 4.11.9
Client: Windows 10 version 1703 (build 15063.483)

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###
1. Open browser (Chrome) on client and go to some random page
2. Scroll down on touchpad
3. Browser receives "back" signal and goes to previous page

### Other info ###

* When did the problem start to occur? For as long as I remember
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No

Touchpad driver:
xf86-input-synaptics 1.9.0-1

All OS languages in English but keyboard layout on all machines is Danish.

**Comment by leftyfb** [comment]
This is still a bug in 1.12 as of September 2020, 3 years later. It's REALLY annoying not being able to scroll while browsing or in an application like Slack.
Server: Ubuntu 18.04 running Synergy 1.12
Client: Windows 10 running Synergy 1.12

**Comment by leftyfb** [comment]
Still an issue with version 1.13 with the same server/client configuration mentioned above.
