### ISSUE TITLE
Runtime Error crash on start on Windows

### ISSUE THREAD

**Issue by hannahigu** [symless/synergy-core#6112]
#5966 Synergy.exe Runtime Error crash on start

Operating Systems

Server: Windows 10.1703.15063,483
Client: Windows 10.1607.14393.1480

Synergy Version

synergy-v1.8.8-stable-25a8cb2-Windows-x64.msi

Steps to reproduce bug

Start Synergy in any way (auto-start after installation/autostart on Windows boot/from Start Menu/from .exe directly)
See crash window.
![errorruntime](https://user-images.githubusercontent.com/30383661/28497624-05048500-6f8c-11e7-8227-3df393238477.jpg)

Other info

I bought the product yesterday, but I would get these server errors, so I tried to wipe the program and reinstall, but then this error showed up. I have no idea what to do. Please help.

**Comment by wallden** [comment]
Same for me after downloading the latest release. Worked flawlessly for several months before that

**Comment by Phoax** [comment]
+1
One day, it stopped working.

**Comment by wallden** [comment]
Can we get an update on this please?
