### ISSUE TITLE
Select network device in GUI including device names

### ISSUE THREAD

**Issue by austin6598** [symless/synergy-core#6115]
Mouse without Borders has this feature and I was wondering if you could add it to the server and client options so that if I am setting my computer up with ethernet I don't have to manually enter the IP address but just select from the dropdown menu. Here is a screenshot of the feature:
![image](https://user-images.githubusercontent.com/7825262/28756540-97e99588-753e-11e7-968e-8bd029c37056.png)

**Comment by XinyuHou** [comment]
@austin6598 
Do you mean which network adapt is going to use for local machine or for the remote machine?

**Comment by austin6598** [comment]
I would like to see this type of selection menu on the remote machine since the local machine accepts connections from any network adapter. However it would be convenient to have all the network adapter names listed next to their IP addresses on the local machine, with the ability to hide certain ones. Running ipconfig does the job but this would be really convenient.
