### ISSUE TITLE
Screensaver sync not working on Linux client

### ISSUE THREAD

**Issue by nyetwurk** [symless/synergy-core#6132]
### Operating Systems ###

Server: Windows 10
Client: Linux

### Synergy Version ###

current github master (2.0?)
d0ded4e56b157a50f7b71d70b6577961742d52bc

### Steps to reproduce bug ###

Allow screen saver to activate on server (windows)
Screen saver on client (Linux) does not activate.

### Other info ###

* When did the problem start to occur?

between 1.9 and the 2.0 merge

* Does this bug prevent you from using Synergy entirely?

Not yet :)

**Comment by XinyuHou** [comment]
Maybe related to #3601

**Comment by nyetwurk** [comment]
This shouold not have been closed either, IIRC

**Comment by jakemagee** [comment]
This (and possibly #4229 and #3601) also appears to affect Linux client / server configurations as well.  For me, the screensaver will only activate on whichever system currently has the keyboard / mouse focus (can be either the client or server).  I have tried setting "screenSaverSync" to both true and false on both the client and server, but this appears to have no effect on the issue.

**Comment by nyetwurk** [comment]
Still broken as of 1.10.2

**Comment by nyetwurk** [comment]
It appears as though the server never gets a screensaver activation event from Windows.

**Comment by nyetwurk** [comment]
`onScreensaver()` never gets called with `activated` true.

What is the expected method by which the synergyserver detects the screen saver activated? I can't seem to find it.

**Comment by nyetwurk** [comment]
might need one of SPI_GETSCREENSAVERACTIVE or SPI_GETPOWEROFFACTIVE

**Comment by nyetwurk** [comment]
Looks like SPI_GETPOWEROFFACTIVE is not supported. I think the issue is if you don't use a screen saver but depend on power management to turn off the screen, in which case the server needs to monitor power management, not screen saver status.

**Comment by nyetwurk** [comment]
Looking for SC_MONITORPOWER in synwinhk.cpp works
```
diff --git a/src/lib/synwinhk/synwinhk.cpp b/src/lib/synwinhk/synwinhk.cpp
index 30ba12895..a2bbeef3a 100644
--- a/src/lib/synwinhk/synwinhk.cpp
+++ b/src/lib/synwinhk/synwinhk.cpp
@@ -630,11 +630,14 @@ getMessageHook(int code, WPARAM wParam, LPARAM lParam)
     if (code >= 0) {
         if (g_screenSaver) {
             MSG* msg = reinterpret_cast<MSG*>(lParam);
-            if (msg->message == WM_SYSCOMMAND &&
-                msg->wParam  == SC_SCREENSAVE) {
-                // broadcast screen saver started message
-                PostThreadMessage(g_threadID,
-                                SYNERGY_MSG_SCREEN_SAVER, TRUE, 0);
+            if (msg->message == WM_SYSCOMMAND) {
+                if (msg->wParam == SC_SCREENSAVE ||
+                   (msg->wParam == SC_MONITORPOWER &&
+                    msg->lParam != -1 )) {
+                    // broadcast screen saver started message
+                    PostThreadMessage(g_threadID,
+                                    SYNERGY_MSG_SCREEN_SAVER, TRUE, 0);
+                }
             }
         }
         if (g_mode == kHOOK_RELAY_EVENTS) {
```
but 
```
        if (!m_screensaverActive &&
            m_screensaver->checkStarted(SYNERGY_MSG_SCREEN_SAVER, FALSE, 0)) {
```
in `MSWindowsScreen::onScreensaver()` prevents the `sendEvent()` from happening since there is no local screen saver active, just monitor power off.

**Comment by nyetwurk** [comment]
This this is broken, the default for `screenSaverSync` should be `false`

**Comment by nyetwurk** [comment]
https://github.com/symless/synergy-core/pull/6505

**Comment by nbolton** [comment]
@Jnewbon ^

**Comment by in4mer** [comment]
I'm still getting this on the Linux client as of 1.14.6-snapshot-88fdd263 (strange that in the "About" screen in linux, that text isn't selectable).  In fact, I discovered that `screenSaverSync` in my synergy.conf blows up the server entirely after updating from something Quite A Bit Older.  Has that been a recent design decision?
