### ISSUE TITLE
SSL private key is world readable

### ISSUE THREAD

**Issue by bitsandsalsa** [symless/synergy-core#6135]
### Operating Systems ###

Server: Ubuntu 16.04.3
Client: Ubuntu 16.04.3

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. `ls -l ~/.synergy/SSL/Synergy.pem`
2. Notice the following file permissions:

> -rw-rw-r-- 1 user user 1111 Jan 1  2017 Synergy.pem

### Other info ###

To reduce private key exposure, the key should only be readable by the user; not the group or other. I would expect the following file permissions:

> -rw------- 1 user user 1111 Jan 1  2017 Synergy.pem

This is what I have for my SSH private keys created with ssh-keygen:

> -rw------- 1 user user 1111 Jan 1  2017 id_rsa

**Comment by LeadManPL** [comment]
Looks like synergy-v1.8.8-stable-25a8cb2-Linux-x86_64.deb  still have this issue:

patben@patbenamd:~/.synergy/SSL$ ll
razem 20
drwxr-xr-x 3 patben patben 4096 paź  5 11:50 ./
drwxr-xr-x 4 patben patben 4096 sie 10 13:30 ../
drwxr-xr-x 2 patben patben 4096 lip 27  2016 Fingerprints/
-rw-r--r-- 1 patben patben 1653 paź  5 11:50 Synergy.pem
-rw-r--r-- 1 patben patben 1653 paź  5 11:49 Synergy.pem.bkp
