### ISSUE TITLE
Mouse locked on client when button clicked

### ISSUE THREAD

**Issue by nalt** [symless/synergy-core#6139]
### Operating Systems ###

Server: MacOS 10.12
Client: Ubuntu KDE 16.04

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. On server (MacOS): Push down and hold left mouse button
2. Move mouse to client (Ubuntu)
3. Release mouse button
4. Try to move back to server
4. Cursor stays locked on client. The server logs
`DEBUG: locked by mouse buttonID: 0`

It does not matter whether you actually drag something (a window, a file) or not. The cursor stays locked on the client. Sometimes it helps to click the mouse button multiple times, but mostly the client has to be killed.

I assume the pressed mouse button should result in a mouse lock already on step two. This lock actually does work correctly when the right button is clicked.

### Other info ###

Maybe similar: #6059

**Comment by arooni** [comment]
still effects version 1.10 as well as latest v2-beta.

mac os x sierra host and ubuntu 18.04 client
