### ISSUE TITLE
Restrict cursor on multiple screens to single screen

### ISSUE THREAD

**Issue by neurochen** [symless/synergy-core#6140]
Hi, Thank you so much for this wonderful program. We use this synergy everyday on a multi-pc setup. Recently, we also want to restrict our cursor inside one monitor in a dual-monitor PC. Is it possible to do that, either by having a conf file or modifying the source code? If you guys could make a GUI menu for that, it's really perfect! Thanks.

**Comment by nbolton** [comment]
Not right now, but we may add this feature. What is the exact problem that this would solve?

**Comment by mingguichen** [comment]
thanks for the reply. we use one extended monitor to show some information to customers. while we are moving cursors rapidly, it's really common that we move cursor to the extended screen. this makes us really inconvenient. if you could add this feature, we could for sure get the software.
