### ISSUE TITLE
Support for Ubuntu 14.04 LTS Qt library

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy-core#6152]
### Operating Systems ###

Client: Mint 17.3 LTS

### Synergy Version ###

synergy_2.0.0.beta4-b786+042356d4_amd64.deb

### Steps to reproduce bug ###

On install deb: 

> Dependency is not satisfiable: libqt5core5a (>= 5.5.0)

### Other info ###

Actual versions of LTS editions have Qt 5.2.1 by default.

So I hope some stable v1 releases in plans before November for systems with old versions of libraries.

**Comment by nlyan** [comment]
For v2.x the minimum supported version of Qt is indeed 5.5 (Ubuntu LTS 16.04). We do have a Debian Jessie buildslave for v1.x, but even that is on Qt 5.3

If your distro is behind Debian oldstable then perhaps it's time to upgrade...

WONTFIX

**Comment by QuAzI** [comment]
[C2.](https://community.linuxmint.com/tutorial/view/2316) The KDE edition of Linux Mint isn't upgradable (Linux Mint 18 KDE will use a new and different desktop called Plasma).

**Comment by nlyan** [comment]
I think your best bet is trying to build it yourself from the v1.9,

**Comment by cmooreml** [comment]
Any potential for having 2.0 support for Ubuntu 14.04? A lot of companies still use :/

**Comment by nlyan** [comment]
@cmooreml None. Not with 18.04 LTS around the corner.
