### ISSUE TITLE
Mouse locks on client from a Windows RDP server 

### ISSUE THREAD

**Issue by prophoto** [symless/synergy-core#6153]
Server: Windows 10
Client: macOS

I leave Synergy running all the time on my server and client computers. I have a hardware VPN setup so that I can access my workstations remotely. Windows 10 (synergy server) via RDP the cursor will get locked on the client. The only way to fix is to disable synergy client on the Mac (synergy client), then hook up a mouse to the Mac to turn it back on.

**Comment by HaskellZhangSong** [comment]
I am a similar problem. My synergy server is on my Macbook pro. sometimes it will lock the mouse to the windows client and I have to quit synergy on windows to make the mouse on Macbook work again. I am not sure whether this is  related windows screen saver. My windows machine will automatically lock after 10 minutes.
