### ISSUE TITLE
Cursor doesn't go invisible when off screen

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6154]
1. Connect Mac client to Windows server
2. Move mouse from Windows to Mac
3. See that cursor disappears
4. Move mouse back to Windows
5. Move mouse to Mac once more
6. See cursor is still visible on Windows (center of screen)

Seems very intermittent, but happens most of the time.

Workaround: Minimize all windows on the Windows computer so only the desktop is visible.

**Comment by Alamei** [comment]
I'm pretty sure this is the same issue as #6035. It's a bug introduced with Windows 10 Creators Update (Win10 Build 1703) that impacts a variety of cursor features.
