### ISSUE TITLE
Synergy License Lifetime

### ISSUE THREAD

**Issue by deckar01** [symless/synergy-core#6155]
It looks like the synergy pricing page was updated on July 11th to specify that the "lifetime access" will not apply to Synergy v2. Is there any additional information about this change?

![screen shot 2017-09-15 at 2 47 31 pm](https://user-images.githubusercontent.com/3108007/30500691-107d19ec-9a25-11e7-9b4d-1f28ddea8b06.png)

![screen shot 2017-09-15 at 2 47 44 pm](https://user-images.githubusercontent.com/3108007/30500692-107fb3f0-9a25-11e7-8f7e-69e88d3104dc.png)

**Comment by nlyan** [comment]
Please email nick@symless.com . GitHub isn't the appropriate place to discuss licensing.

**Comment by deckar01** [comment]
Regarding the GPL license in this repo, is it OK for me to backport features from 2.x releases to new 1.x releases on my own fork?

**Comment by dzmitry-lahoda** [comment]
I have bought Synergy basic only because it had open source core. 

It would be nice if Synergy team will document future of `synergy-core`, what features are closed and what are open? Is `synergy-core` dead?

**Comment by acekrystal** [comment]
My friend and I also just bought Synergy life-time licenses not so long ago. We wanted to go for it for some time already, but recently decided to got for it as it is a life time license and the functions started to get better and better. 

We now found out in the mail there is a Synergy 2 coming? what needs new licenses?!? After reading on the synergy forums it also looks like Synergy 1 will be discontinued....

What did we get for our life time license then?!?

Where both really confused.

**Comment by dzmitry-lahoda** [comment]
I have tried other Chanel, but no success:

![default](https://user-images.githubusercontent.com/757125/31756700-0645af40-b4ae-11e7-839d-c1414e90a2f0.png)

![default](https://user-images.githubusercontent.com/757125/31756716-15468596-b4ae-11e7-8369-e208c7379d4f.png)

**Comment by carceneaux** [comment]
False/Skeevy marketing saying "Lifetime Updates" when the developer is simply going to release a new version of the product every couple years where the "Lifetime Updates" don't apply.

**Comment by arooni** [comment]
if we buy this now; do we get lifetime updates for all releases OR NOT?  please specify
