### ISSUE TITLE
Unknown Dependencies for Synergy on Ubuntu 17.04

### ISSUE THREAD

**Issue by smp46** [symless/synergy-core#6156]
Can't even install Synergy on Ubuntu 17.04, tried several methods. Making the source, installing through .deb file, apt-get, all showing I need dependencies which I cannot found what they are, because the Wiki is not available.

**Comment by nbolton** [comment]
The wiki is here: https://github.com/symless/synergy-core/wiki

**Comment by smp46** [comment]
Thank you, sorry you might want to fix the link in the linux install file it has a github wiki address that returns error 404.

**Comment by nbolton** [comment]
Good spot!
