### ISSUE TITLE
Pipe char not sent correctly to client

### ISSUE THREAD

**Issue by andyn** [symless/synergy-core#6157]
### Operating Systems ###

Server:
```shell
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```
```shell
$ uname -a
Linux rin 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Client:
```shell
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"`
```
```shell
$ uname -a
Linux t410s 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
### Synergy Version ###

1.8.8-stable-25a8cb2 on both ends. (For some reason 1.8.8 built from Git commit c30301e has also been distributed back in March. IMNSHO reusing version numbers is a big no-no. However, I'll leave that rant to a completely different time.)

### Steps to reproduce bug ###

1. Set Finnish keymap on server and client. `setxkbmap fi` in a console should work.
2. Try to type the pipe character on the client (AltGr + <, the key next to the left shift key).
3. Get the ı character (dotless i) instead.
4. Note that on the server AltGr + i also gives you the dotless i character, just like it should.
5. Further note that on the server AltGr + Shift + i gives the pipe character, just like it should, too.
6. Find out that if you edit your X11 symbol mapping on the client (e.g. mapping the pipe to AltGr + Shift + u), AltGr + < gives you small letter u. Also find out that the mapping is loaded on the client upon connect.
7. Notice that additionally mapping the bar to AltGr + Shift + O on the client still prints out u or ı
8. Come to the conclusion that Synergy sends keysyms over the network, tries to map them back to the proper keycode on the client, and fails because it likely picks the smallest keycode.

### Other info ###

Erroneus keysym to keycode mapping in client?

* When did the problem start to occur? Has been around for as long as I remember.
* Is there a way to work around it? Yes, AltGr + Shift + i
* Does this bug prevent you from using Synergy entirely? No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs --> the link leads to a 404 location.

**Comment by andyn** [comment]
Another workaround is to edit /usr/share/X11/xkb/symbols/$LANG and remove any double references to the same symbol. However, hacking the system keyboard layout files is not a sustainable way to solve this. 

If my conclusion in the original bug report is correct. the only long-term solution seems to be not converting original data (keycodes) to a lossy form (keysyms) and then back. Is this currently a protocol limitation?

**Comment by XinyuHou** [comment]
@andyn 
Thank you for the information. 

> Come to the conclusion that Synergy sends keysyms over the network, tries to map them back to the proper keycode on the client, and fails because it likely picks the smallest keycode.

Yes, this is what Synergy does right now. It's probably not the best approach when it comes to international keyboard mapping. We are still looking for the alternatives. Feel free to give us any suggestions.

Please have a look at this issue #6005 and leave any further comments on that issue.

**Comment by sheepdestroyer** [comment]
Synergy 1.11 pro
Windows 10 Pro  : Server
Fedora 31 : Client
Keyboard : Standard French Azerty

With both systems configured with input systems as "French", pipe( | ) and @ characters are not appearing on the client. If I set the server's input to US Keyboard, then the client correctly prints them, but I have to change keyboard input each time I move from one machine to the other which is quite inconvenient.
