### ISSUE TITLE
GUI is too small on high DPI screens

### ISSUE THREAD

**Issue by a3gill** [symless/synergy-core#6160]
### Operating Systems ###

Server: Windows 10, Version 1709 (OS Build 16294.1)
Client: Windows 10, Version 1709 (OS Build 16294.1)

### Synergy Version ###

1.8.8-stable-25a8cb2

#### Given: ####

1. Machine is running Windows and using a Display Scaling value (Settings>System>Display: Scale and layout) > 100%.
2. Not as rare as it sounds. Many laptops with huge DPI require it for normal usage. So, if you've never had to use it, you may not know of it, but if you do, then you have to use it.
3. I'm aware this sounds super-needy and frivolous. A year ago, I would have agreed. You'd be surprised how annoying it becomes when every day you have to go through this unnecessary routine on the server and every client to verify connectivity when you get to work, and then again when you get home. And, even more so when the fix is so simple (hate to assume, but I will :)) should it only be known.

#### Repro: ####

1. Launch Synergy app.
2. Done :).

#### Explanation: ####

* My laptop display (13" @ 3200x1800 resolution) runs with suggested scaling of 200%. Notice the app's initial state prevents the reading of anything until it's resized or maximized:
![image](https://user-images.githubusercontent.com/2249642/30778799-e3b9f4d2-a0ac-11e7-9c39-799ce8acbddf.png)
* Individual UI elements are fine. The WinForms framework seems to be handling it.
* The main window's actual **Height** and **Width** values are the problem.
* The child items' dimensions are off too, but probably just because their values are calculated relative to the main window's size.
* As I already mentioned, I get that this is a minor thing, but the reason I am going through the trouble to report it is because of the frequency -- not the severity.

#### Suggestions: ####

* Store the size of the app window in the registry or an xml/json file at close, and then, at launch, use the stored values to size the window.
**OR**
* Make the initial window dimensions dynamic:
_where **scalingFactor** = WindowsDisplayScalingValue/100_
Height = DefaultHeight * **scalingFactor**
Width = DefaultWidth * **scalingFactor**

### Other info ###

* When did the problem start to occur?
_When I purchased my current laptop (Massive DPI), roughly 18 months ago._

* Is there a way to work around it?
_Yes, very easily, enlarge the size of the app window or maximize it. The issue is the frequency, and not the complexity._

* Does this bug prevent you from using Synergy entirely?
_No, mostly :), not out of necessity, but occasionally by choice.
This won't prevent me from using at this time, but for an app that provides functionality I need and not not a single complain otherwise, I'd hate to have to look in a different direction should this annoyance build to something else._

**Comment by anohren** [comment]
I don't think this is a minor thing. That GUI looks unusable.

**Comment by fuzzzerd** [comment]
There is a similar, but slightly different issue with 2.x regarding the size of the screens and the overall window.

**Comment by hackitfast** [comment]
I'm having this issue as of currently. Screen resolution is 3840x2160.

![synergy_2018-12-21_17-06-58](https://user-images.githubusercontent.com/13812987/50365483-d4f02880-0542-11e9-8fe6-b0991073e291.png)

Haven't even tested the program yet but this isn't looking good right now.
