### ISSUE TITLE
Client enters "<" (ASCII=60) instead of "\" (ASCII=92) in vSphere client 6.0.0

### ISSUE THREAD

**Issue by LeadManPL** [symless/synergy-core#6163]
### Operating Systems ###

Server: Ubuntu 17.04   4.10.0-35-generic
Client: Windows 7 ver. 6.1 compilation 7601 SP1

### Synergy Version ###

Server: synergy-v1.8.8-stable-25a8cb2-Linux-x86_64.deb
Client: synergy-v1.8.8-stable-25a8cb2-Windows-x64.msi

### Steps to reproduce bug ###

0. Reproducible: Always
1. On synergy client start software: "VMware vSphere Client Verion 6.0.0"
2. connect to console of running virtual machine
3. try to type "\\" (backslash) sign
4. Instead of "\\" on the console you will see "<"
5. It seems that it happens only with vSphere client, however "\\" on physical KBD is recognised correctly.

### Other info ###

* When did the problem start to occur? 
  Unable to determine.

* Is there a way to work around it?
  Yes, you can connect physical KBD to client and type BACKSLASH sign from KBD that is physically connected, but... you know ;)

* Does this bug prevent you from using Synergy entirely?
  No

This link is not working:
https://github.com/symless/synergy/wiki/Sending-logs

I have made case test with log level set to Debug2. Truncated log file attached.
[synergyd_server_linux_backslash.log.tar.gz](https://github.com/symless/synergy-core/files/1359145/synergyd_server_linux_backslash.log.tar.gz)
[synergyd_client_windows_backslash.log.tar.gz](https://github.com/symless/synergy-core/files/1359146/synergyd_client_windows_backslash.log.tar.gz)

**Comment by XinyuHou** [comment]
@LeadManPL 
Does this only happen within vSphere not on the actual client?

**Comment by LeadManPL** [comment]
Yes, only in vSphere. Typing "\\" in i.e. notepad gives correct character.
I have created a ticket also in VMware helpdesk system, but it seems to be closed, and I think I am not able to provide their's issue number...

**Comment by XinyuHou** [comment]
@LeadManPL 
I'm afraid I have to close this issue as it's more likely an issue in vSphere if you can type the correct character on your client machine via Synergy.

**Comment by LeadManPL** [comment]
I got similar answer from VMware. They claim that it is issue with Synergy. And what am I supposed to do now?
