### ISSUE TITLE
3 Computer - 7 Monitor Layout possible? How can this be configured?

### ISSUE THREAD

**Issue by AustinWinstanley** [symless/synergy-core#6165]
### Operating Systems ###

Server: Ubuntu 17.10
Client: Windows 10
Client: Windows 10

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

N/A

### Other info ###

Is it possible to configure 3 computers (1 Ubuntu 17.10, 2 Windows 10) in a 7 monitor layout like this:

| C1 - M3 | C1 - M4 | C1 - M5 |
| C1 - M2 | C1 - M1 | C2 - M1 | C3 - M1 |

C1 - Ubuntu 17.10
C2 - Windows 10
C3 - Windows 10
M<x> - Monitor<Number>

Currently, the Ubuntu 17.10 machine is the server. Would using C2 / Windows 10 be the correct computer for the server? Would I be able to enter two different monitors on C1 from the left and top of C2?

**Comment by XinyuHou** [comment]
Please use our forum to ask for support.

Github issue track is used only for bug tracking. Thank you.

https://symless.com/forums/login/
