### ISSUE TITLE
Synergy2.0 Unable to connect out through a proxy

### ISSUE THREAD

**Issue by alistair23** [symless/synergy-core#6166]
### Operating Systems ###

Server: Ubuntu 17.10
Client: Doesn't matter

### Synergy Version ###

2.0.0-beta4

### Steps to reproduce bug ###

1. Launch Synergy on a system behind a proxy
2. Click "Sign in with Symless"
3. See the error "Couldn't connect to Synergy Cloud. Please check your internet connection and then try again"

### Other info ###

It looks like 2.0 now relies on internet access which is not a good idea behind corporate networks. It also doesn't seem to have any way to specify a proxy. All the proxy settings are set on the machine and even launching Synergy from bash with the standard proxy environment variables set didn't help.

**Comment by alistair23** [comment]
Ok, I managed to get something working by running synergy2 and synergyd with tsocks. But nothing will connect. This is the syndergyd log:

> [2017-10-10T10:08:36] debug: service log path: /var/log/synergy-service.log
> [2017-10-10T10:08:36] info: starting service...
> [2017-10-10T10:08:36] debug: connectivity test server started
> [rawsocket_server_impl.cpp:94][start] starting rawsocket server
> RawSocket handshake reply received
> connect successful: valid handshake
> RX preparing to receive message ..
> TX message (126 octets) ...
> TX message: hello ["default", {"authid":"", "authmethods":[], "roles":{"subscriber":{}, "callee":{"features":{"call_timeout":true}}, "publisher":{}, "caller":{"features":{"call_timeout":true}}}}]
> [wamp_message_processor.cpp:47][process_message] processing message: hello
> [wamp_router_impl.cpp:108][attach_session] attaching session: session [7090515283965860,default,none]
> [wamp_dealer.cpp:65][attach_session] attach session: session [7090515283965860,default,none]
> [wamp_broker.cpp:51][attach_session] attach session: session [7090515283965860,default,none]
> [wamp_router_impl.cpp:164][process_hello_message] session [7090515283965860,default,none], hello [default, {"authid":"", "authmethods":[], "roles":{"subscriber":{}, "callee":{"features":{"call_timeout":true}}, "publisher":{}, "caller":{"features":{"call_timeout":true}}}}]
> [wamp_router_impl.cpp:192][process_hello_message] session [7090515283965860,default,open], welcome [7090515283965860, {"roles":{"dealer":{"features":{"call_timeout":true, "progressive_call_results":true}}, "broker":{}}}]
> [rawsocket_transport.cpp:39][send_message] sending message: welcome
> RX message (85 octets) ...
> RX message received.
> RX message: welcome [7090515283965860, {"roles":{"dealer":{"features":{"call_timeout":true, "progressive_call_results":true}}, "broker":{}}}]
> [2017-10-10T10:08:36] debug: creating rpc endpoints
> [2017-10-10T10:08:36] debug: rpc endpoints created
> [2017-10-10T10:08:36] info: service started successfully
> RX preparing to receive message ..
> TX message (79 octets) ...
> TX message: publish [1, {}, "synergy.service.log", ["[2017-10-10T10:08:36] debug: creating rpc endpoints\n"]]
> TX message (23 octets) ...
> TX message: register [2, {}, "synergy.core.start"]
> TX message (28 octets) ...
> TX message: register [3, {}, "synergy.profile.request"]
> TX message (24 octets) ...
> TX message: register [4, {}, "synergy.auth.update"]
> TX message (78 octets) ...
> TX message: publish [5, {}, "synergy.service.log", ["[2017-10-10T10:08:36] debug: rpc endpoints created\n"]]
> TX message (84 octets) ...
> TX message: publish [6, {}, "synergy.service.log", ["[2017-10-10T10:08:36] info: service started successfully\n"]]
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [1, {}, synergy.service.log, ["[2017-10-10T10:08:36] debug: creating rpc endpoints\n"], null]
> [wamp_message_processor.cpp:47][process_message] processing message: register
> [wamp_dealer.cpp:304][process_register_message] session [7090515283965860,default,open], register [2, {}, synergy.core.start]
> [wamp_dealer.cpp:345][process_register_message] session [7090515283965860,default,open], registered [2, 1]
> [rawsocket_transport.cpp:39][send_message] sending message: registered
> RX message (4 octets) ...
> [wamp_message_processor.cpp:47][process_message] processing message: register
> [wamp_dealer.cpp:304][process_register_message] session [7090515283965860,default,open], register [3, {}, synergy.profile.request]
> [wamp_dealer.cpp:345][process_register_message] session [7090515283965860,default,open], registered [3, 2]
> [rawsocket_transport.cpp:39][send_message] sending message: registered
> RX message received.
> RX message: registered [2, 1]
> RX preparing to receive message ..
> RX message (4 octets) ...
> [wamp_message_processor.cpp:47][process_message] processing message: register
> [wamp_dealer.cpp:304][process_register_message] session [7090515283965860,default,open], register [4, {}, synergy.auth.update]
> [wamp_dealer.cpp:345][process_register_message] session [7090515283965860,default,open], registered [4, 3]
> [rawsocket_transport.cpp:39][send_message] sending message: registered
> RX message received.
> RX message: registered [3, 2]
> RX preparing to receive message ..
> RX message (4 octets) ...
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [5, {}, synergy.service.log, ["[2017-10-10T10:08:36] debug: rpc endpoints created\n"], null]
> RX message received.
> RX message: registered [4, 3]
> RX preparing to receive message ..
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [6, {}, synergy.service.log, ["[2017-10-10T10:08:36] info: service started successfully\n"], null]
> [wamp_message_processor.cpp:47][process_message] processing message: hello
> [wamp_router_impl.cpp:108][attach_session] attaching session: session [2257228500326156,default,none]
> [wamp_dealer.cpp:65][attach_session] attach session: session [2257228500326156,default,none]
> [wamp_broker.cpp:51][attach_session] attach session: session [2257228500326156,default,none]
> [wamp_router_impl.cpp:164][process_hello_message] session [2257228500326156,default,none], hello [default, {"authid":"", "authmethods":[], "roles":{"subscriber":{}, "callee":{"features":{"call_timeout":true}}, "publisher":{}, "caller":{"features":{"call_timeout":true}}}}]
> [wamp_router_impl.cpp:192][process_hello_message] session [2257228500326156,default,open], welcome [2257228500326156, {"roles":{"dealer":{"features":{"call_timeout":true, "progressive_call_results":true}}, "broker":{}}}]
> [rawsocket_transport.cpp:39][send_message] sending message: welcome
> [wamp_message_processor.cpp:47][process_message] processing message: subscribe
> [wamp_broker.cpp:171][process_subscribe_message] session [2257228500326156,default,open], subscribe [1, {}, synergy.core.log]
> [wamp_broker.cpp:201][process_subscribe_message] session [2257228500326156,default,open], subscribed [1, 1]
> [rawsocket_transport.cpp:39][send_message] sending message: subscribed
> [wamp_message_processor.cpp:47][process_message] processing message: subscribe
> [wamp_broker.cpp:171][process_subscribe_message] session [2257228500326156,default,open], subscribe [2, {}, synergy.service.log]
> [wamp_broker.cpp:201][process_subscribe_message] session [2257228500326156,default,open], subscribed [2, 2]
> [rawsocket_transport.cpp:39][send_message] sending message: subscribed
> [wamp_message_processor.cpp:47][process_message] processing message: subscribe
> [wamp_broker.cpp:171][process_subscribe_message] session [2257228500326156,default,open], subscribe [3, {}, synergy.screen.status]
> [wamp_broker.cpp:201][process_subscribe_message] session [2257228500326156,default,open], subscribed [3, 3]
> [rawsocket_transport.cpp:39][send_message] sending message: subscribed
> [wamp_message_processor.cpp:47][process_message] processing message: subscribe
> [wamp_broker.cpp:171][process_subscribe_message] session [2257228500326156,default,open], subscribe [4, {}, synergy.screen.error]
> [wamp_broker.cpp:201][process_subscribe_message] session [2257228500326156,default,open], subscribed [4, 4]
> [rawsocket_transport.cpp:39][send_message] sending message: subscribed
> [wamp_message_processor.cpp:47][process_message] processing message: subscribe
> [wamp_broker.cpp:171][process_subscribe_message] session [2257228500326156,default,open], subscribe [5, {}, synergy.profile.snapshot]
> [wamp_broker.cpp:201][process_subscribe_message] session [2257228500326156,default,open], subscribed [5, 5]
> [rawsocket_transport.cpp:39][send_message] sending message: subscribed
> [wamp_message_processor.cpp:47][process_message] processing message: call
> [wamp_dealer.cpp:166][process_call_message] session [2257228500326156,default,open], call [6, {"timeout":10000}, synergy.auth.update, [4105, 11318, 4097, <REDACTED>], null]
> [wamp_dealer.cpp:219][process_call_message] session [2257228500326156,default,open], invocation [1, 3, {}, [4105, 11318, 4097, "bG7gtYncGVTywaSx1SAyaXR7"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: invocation
> RX message (40 octets) ...
> RX message received.
> RX message: invocation [1, 3, {}, [4105, 11318, 4097, <REDACTED>]]
> Invoking procedure registered under 3
> [2017-10-10T10:08:50] debug: connecting websocket
> TX message (4 octets) ...
> TX message: yield [1, {}]
> RX preparing to receive message ..
> TX message (77 octets) ...
> TX message: publish [7, {}, "synergy.service.log", ["[2017-10-10T10:08:50] debug: connecting websocket\n"]]
> [wamp_message_processor.cpp:47][process_message] processing message: call
> [wamp_dealer.cpp:166][process_call_message] session [2257228500326156,default,open], call [7, {"timeout":10000}, synergy.profile.request, [], null]
> [wamp_dealer.cpp:219][process_call_message] session [2257228500326156,default,open], invocation [2, 2, {}, [], null]
> [rawsocket_transport.cpp:39][send_message] sending message: invocation
> [wamp_message_processor.cpp:47][process_message] processing message: yield
> [wamp_dealer.cpp:424][process_yield_message] session [7090515283965860,default,open], yield [1, {}, null, null]
> [wamp_dealer.cpp:465][process_yield_message] session [7090515283965860,default,open], result [6, {}, null, null]
> [rawsocket_transport.cpp:39][send_message] sending message: result
> RX message (6 octets) ...
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [7, {}, synergy.service.log, ["[2017-10-10T10:08:50] debug: connecting websocket\n"], null]
> [wamp_broker.cpp:149][process_publish_message] session [2257228500326156,default,open], event [2, 8530991034268898, {}, ["[2017-10-10T10:08:50] debug: connecting websocket\n"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: event
> RX message received.
> RX message: invocation [2, 2, {}, []]
> Invoking procedure registered under 2
> [2017-10-10T10:08:50] error: can't send profile snapshot, not yet received from cloud
> TX message (4 octets) ...
> TX message: yield [2, {}]
> RX preparing to receive message ..
> TX message (113 octets) ...
> TX message: publish [8, {}, "synergy.service.log", ["[2017-10-10T10:08:50] error: can't send profile snapshot, not yet received from cloud\n"]]
> [wamp_message_processor.cpp:47][process_message] processing message: yield
> [wamp_dealer.cpp:424][process_yield_message] session [7090515283965860,default,open], yield [2, {}, null, null]
> [wamp_dealer.cpp:465][process_yield_message] session [7090515283965860,default,open], result [7, {}, null, null]
> [rawsocket_transport.cpp:39][send_message] sending message: result
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [8, {}, synergy.service.log, ["[2017-10-10T10:08:50] error: can't send profile snapshot, not yet received from cloud\n"], null]
> [wamp_broker.cpp:149][process_publish_message] session [2257228500326156,default,open], event [2, 173663057434166, {}, ["[2017-10-10T10:08:50] error: can't send profile snapshot, not yet received from cloud\n"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: event
> [2017-10-10T10:10:20] debug: tcp session ssl handshake error: short read
> [2017-10-10T10:10:20] debug: websocket connect failed
> [2017-10-10T10:10:20] debug: retrying websocket connection in 3s
> TX message (100 octets) ...
> TX message: publish [9, {}, "synergy.service.log", ["[2017-10-10T10:10:20] debug: tcp session ssl handshake error: short read\n"]]
> TX message (81 octets) ...
> TX message: publish [10, {}, "synergy.service.log", ["[2017-10-10T10:10:20] debug: websocket connect failed\n"]]
> TX message (92 octets) ...
> TX message: publish [11, {}, "synergy.service.log", ["[2017-10-10T10:10:20] debug: retrying websocket connection in 3s\n"]]
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [9, {}, synergy.service.log, ["[2017-10-10T10:10:20] debug: tcp session ssl handshake error: short read\n"], null]
> [wamp_broker.cpp:149][process_publish_message] session [2257228500326156,default,open], event [2, 3648815945442074, {}, ["[2017-10-10T10:10:20] debug: tcp session ssl handshake error: short read\n"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: event
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [10, {}, synergy.service.log, ["[2017-10-10T10:10:20] debug: websocket connect failed\n"], null]
> [wamp_broker.cpp:149][process_publish_message] session [2257228500326156,default,open], event [2, 2264775509761427, {}, ["[2017-10-10T10:10:20] debug: websocket connect failed\n"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: event
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [11, {}, synergy.service.log, ["[2017-10-10T10:10:20] debug: retrying websocket connection in 3s\n"], null]
> [wamp_broker.cpp:149][process_publish_message] session [2257228500326156,default,open], event [2, 204675399442696, {}, ["[2017-10-10T10:10:20] debug: retrying websocket connection in 3s\n"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: event
> [2017-10-10T10:10:23] debug: retrying websocket connection now
> [2017-10-10T10:10:23] debug: connecting websocket
> TX message (90 octets) ...
> TX message: publish [12, {}, "synergy.service.log", ["[2017-10-10T10:10:23] debug: retrying websocket connection now\n"]]
> TX message (77 octets) ...
> TX message: publish [13, {}, "synergy.service.log", ["[2017-10-10T10:10:23] debug: connecting websocket\n"]]
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [12, {}, synergy.service.log, ["[2017-10-10T10:10:23] debug: retrying websocket connection now\n"], null]
> [wamp_broker.cpp:149][process_publish_message] session [2257228500326156,default,open], event [2, 4691827547265518, {}, ["[2017-10-10T10:10:23] debug: retrying websocket connection now\n"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: event
> [wamp_message_processor.cpp:47][process_message] processing message: publish
> [wamp_broker.cpp:111][process_publish_message] session [7090515283965860,default,open], publish [13, {}, synergy.service.log, ["[2017-10-10T10:10:23] debug: connecting websocket\n"], null]
> [wamp_broker.cpp:149][process_publish_message] session [2257228500326156,default,open], event [2, 3106030740620377, {}, ["[2017-10-10T10:10:23] debug: connecting websocket\n"], null]
> [rawsocket_transport.cpp:39][send_message] sending message: event

**Comment by XinyuHou** [comment]
Sorry @alistair23 
Please use our forum to report v2 beta issues. Thank you.

https://symless.com/forums/forum/10-early-access-beta/

**Comment by alistair23** [comment]
Thanks, it looks like a lot of others are hitting similar issues. Hopefully this will be fixed in a future release.

**Comment by mickcornut** [comment]
Hi,
This bug has been submitted for the beta, but it seems it's still valid for 2.0.1 stable:
After installing
synergy_2.0.1.stable-b1034+59dd93a0_amd64.deb
on Ubuntu 16.04 LTS, I'm unable to use it at all,  I'm stuck at the Symless signing page due to my company proxy+auth requirements. Neither the environment proxy variables nor the Ubuntu system proxy settings are used for the very first connection phase.

Could this bug be re-opened please, since now Synergy 2.0.1 is in release state?
Thx, BR,
Mick.

**Comment by pwr22** [comment]
I also cannot use Synergy 2

**Comment by mickcornut** [comment]
After testing with the latest 2.0.2, the problem is still present:
https://github.com/symless/synergy-core/issues/6207

**Comment by hex0gen** [comment]
Here it is https://pastebin.com/FQq3RuJy
