### ISSUE TITLE
Synergy 2.0 beta4 doesn't connect from win10-pro to ubuntu-17.04

### ISSUE THREAD

**Issue by pmario** [symless/synergy-core#6167]
### Actual experience

 - Start the synergy UI on host
 - Start the synergy UI on client
 - It seems both PCs see each other (sometimes), 
 - since I was able to drag the client window into the right position below the host. ... 
   - The client position was updated on the client GUI too. 
   - The client symbol didn't change to green. 
 - Host PC symbol is green ... 

**no other feedback (Good luck with color blind users!)**

Host: win 10 pro
synergy: 2.0 beta 4

host log: [synergy2.0-beta4-host.zip](https://github.com/symless/synergy-core/files/1369700/synergy2.0-beta4-host.zip)

client: ubuntu 17.04
synergy: 2.0 beta 4

client log: [synergy2.0-beta4-client.log.zip](https://github.com/symless/synergy-core/files/1369726/synergy2.0-beta4-client.log.zip)

### Expected behaviour

 - Please provide a configuration dialog for those users who are able to enter IP addresses.

**Comment by joso105** [comment]
I am experiencing the same issue. Linux client doesn't change to green, while Windows 10 is green.

**Comment by jameshclrk** [comment]
Same issue on 16.04, no settings menu or anything either. A massive step backward!

**Comment by XinyuHou** [comment]
Sorry guys, Synergy 2.0 is actually another project than synergy core. Please use our forum to report bugs.

https://symless.com/forums/forum/10-early-access-beta/

> Please provide a configuration dialog for those users who are able to enter IP addresses.

The whole idea behind v2 is to eliminate the need of manually typing IP.  So currently this is not on our roadmap. If you guys really think it is necessary, please raise a post and ask for this feature. We take our users' request seriously.

**Comment by pmario** [comment]
thx for the info. I'll definitely post there.

To my companions in musfortune ;) have a look at: https://symless.com/synergy-2-beta4-troubleshooting and if looged in to the beta frum: https://symless.com/forums/topic/4208-how-to-use-with-windows-firewall/#comment-17610 ... I personally will test this one, when I uninstalled 1.x and test 2.x-beta again.

**Comment by joso105** [comment]
thx for the links @pmario. I was able to resolve the issue on my ubuntu and windows machines using the info in the links!

**Comment by ductiletoaster** [comment]
This issue perfectly describes the issues I am having however, I am unable to few the links above as it seems they no longer exist. Could we memorialize the "fix" here?

**Comment by pmario** [comment]
@ductiletoaster links are down. ... may be beta is over. ... I did go with version 1 till now. ... So may be it's time to have an other try. ... Did you use beta or production version?
