### ISSUE TITLE
Problem with spanish keyboard

### ISSUE THREAD

**Issue by w0www** [symless/synergy-core#6168]
### Operating Systems ###

Server: Windows10
Client: Ubuntu Mate 16.04

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. In windows i can wrote "ñ"
2. In client (Ubuntu) i cant wrote "´ñ". when i push the key nothing happens

The same problem with "¿"

**Comment by XinyuHou** [comment]
Duplicate of #4344
