### ISSUE TITLE
Synergy 2.0.0 beta4 comes up to nearly blank screen

### ISSUE THREAD

**Issue by Duleigh** [symless/synergy-core#6170]
In Windows 10 version 1511 and version1607  Synergy 2.0.0 beta4 comes up to a screen that has the computer name in the upper section of the window in a white bar. The lower section of the window is blue and in the middle is a grey box with half the computer name in it. You can move the box around but that is all that happens. 

There are no options to do anything. The software is completely useless. See screenshot

I tried first installing over Synergy 1.8. When this issue came up I uninstalled completely and reinstalled Synergy 2.0.0 beta4 with no fix

### Operating Systems ###

Server: In Windows 10 version 1511 and version1607

### Synergy Version ###

2.0.0 beta4

### Steps to reproduce bug ###

1. Hit windows key
2. Select Synergy

### Other info ###

* When did the problem start to occur? When I installed 2.0.0 beta4
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? Yes

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs
That link you have listed here goes to a 404. thanks

Put anything else you can think of here.
Screenshot
![synergy_v2 0 0-beta4](https://user-images.githubusercontent.com/32684290/31404320-f2e12af2-adb8-11e7-9e22-b8d1afcc9742.jpg)

**Comment by newgrounds** [comment]
I see the same thing on Windows 10.

**Comment by XinyuHou** [comment]
Sorry guys, please use our forum to report v2 beta issues. Thank you.
https://symless.com/forums/forum/10-early-access-beta/
