### ISSUE TITLE
Synergy 2.0.0 support for Debian 9 (current, stable)

### ISSUE THREAD

**Issue by nathan818fr** [symless/synergy-core#6171]
### Operating Systems ###

Client: Debian 9 Stretch

### Synergy Version ###

2.0.0 beta 4

### Steps to reproduce bug ###

On .deb install :
```
 synergy depends on libssl1.0.0 (>= 1.0.0); however:
  Package libssl1.0.0 is not installed.
```

### Other info ###

libssl1.0.0 is not officially supported in Debian 9 (https://packages.debian.org/jessie/libssl1.0.0).
Supported openssl versions are : 1.0.2 and 1.1

Could you officially offer a version compiled for one of these versions?

**Comment by XinyuHou** [comment]
@nathan818fr 
Thank you for raising this ticket. I have forwarded it to our v2 repository issue tracker, which is a private repository. I will close this issue. If you want to track the progress please use our forum.

https://symless.com/forums/forum/10-early-access-beta/
