### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by nkettell-2020teknology** [symless/synergy-core#6175]
### Operating Systems ###

Server: microOS Tiara
Client: Windows 7 Professional Version 6.1 (Build 7601: Servicepack 1)

### Synergy Version ###

2.0.0

### Steps to reproduce bug ###

1. Login to seven computers.
2. Wait for about 5 min
3. None of the computers communicate with eachother.

### Other info ###

When did the problem start to occur? When I signed into more than four computers
Is there a way to work around it? No
Does this bug prevent you from using Synergy entirely? Yes

**Comment by XinyuHou** [comment]
Please use our forum for v2 issue.

https://symless.com/forums/forum/10-early-access-beta/
