### ISSUE TITLE
synergy 2 beta on ubuntu 17 won't start

### ISSUE THREAD

**Issue by kampiamodikuesto** [symless/synergy-core#6176]
### Operating Systems ###

Server: ubuntu 17
Client: osx sierra

### Synergy Version ###

2 beta 4

The application won't work, after i open it i get only a window with only a grey rettangle with the name of my machine. i can see that it try to load someting but nothing happen.
how can debug it?i haven't no item on the app top bar menu so i can olny close the application.

we have to wait beta 5: https://symless.com/forums/topic/4346-unable-to-connect-ubuntu-1704-to-macos-10116/#comment-18139

**Comment by XinyuHou** [comment]
Please use our forum for v2 issue.

https://symless.com/forums/forum/10-early-access-beta/
