### ISSUE TITLE
Synergy 2.0.0-beta4 not pairing

### ISSUE THREAD

**Issue by denormalizer** [symless/synergy-core#6179]
### Operating Systems ###

`Server`: Windows 10 Pro x64
`Client1`: Ubuntu 16.04 x64
`Client2`: Windows 10 Home x64

### Synergy Version ###

2.0.0-beta4 (beta)

### Steps to reproduce bug ###

* After installing `Server` and `Client1` for the first time, it worked straight off the bat.
* After `Server` restarted to install windows updates, they no longer pair

When client is `Client1`:
* Client is no longer aware of `Server`

When client is `Client2`:
* Client is aware of `Server`
* When moving screens around on `Server`, the screen placement syncs up on the `Client2`
* Similarly, moving screens around on `Client2`, the screen placement syncs up on `Server`
* `Server` indicates that it is *online* (green), `Client2` is shown as *offline* (grey)

### Other info ###

* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? Yes
* Currently reverting back to v1.8.8

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.

**Comment by XinyuHou** [comment]
Please use our forum to report v2 beta issues. Thank you.

https://symless.com/forums/forum/10-early-access-beta/
