### ISSUE TITLE
Logitech g710+ gkeys not working.

### ISSUE THREAD

**Issue by popcorn9499** [symless/synergy-core#6180]
### Operating Systems ###

Server: windows 10 version 1709
Client: Arch linux synergy 1.8.8

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###
I was trying to first off bind the gkey dirrectly to synergy but that didnt work so i tried binding the gkeys to something that synergy would see like say ctrl+i or something then making synergy act on that but that sadly didnt work at all. I even used debug mode 1 to see if i could get it to show the events being called but i couldnt

### Other info ###

This bug causes me to not be able to use synergy as intended which is abit of a issue for me. Hopefully someone can either tell me what im doing wrong. Im using logitech gaming software and my logitech g710+ keyboard with synergy v1.8.8

**Comment by XinyuHou** [comment]
I assume the gkey is a programmable key. On Windows, please open on screen keyboard and test if gkey can trigger the keys you bind to. If that is ok, then please send us some screenshots and change Synergy log level to debug2 and send us the log from both server and client sides.

**Comment by popcorn9499** [comment]
Sorry I forgot to close this. After Abit I realised maybe it's Logitech gaming software so I checked that and sure enough it was Logitech gaming softwares side. Idrk what happened but reinstalling fixed this. Sorry to do this for no reason.

**Comment by XinyuHou** [comment]
No problem.

Close as not an issue anymore.
