### ISSUE TITLE
synergy 2 beta 4 does not move the cursor to the other computer on Windows 10 fall creators update

### ISSUE THREAD

**Issue by DamionGans** [symless/synergy-core#6181]
### Operating Systems ###

Windows 10 Fall Creators Update (version 1709)

### Synergy Version ###

2.0.0-beta4

### Steps to reproduce bug ###

1. Install Synergy on computer one and login (and thus activate it)
2. Do the same for computer two.
3. Both computers are found by synergy, screen order is changable.
4. move cursor to the corner towards the other screen.
5. mouse stays on current monitor.

### Other info ###

* When did the problem start to occur? When I tried out the beta
* Is there a way to work around it? No/
* Does this bug prevent you from using Synergy entirely? Yes

**Comment by XinyuHou** [comment]
Please use our forum to report beta issues.

Btw beta5 is out, please first upgrade to the lastest beta version.

https://symless.com/forums/forum/10-early-access-beta/
