### ISSUE TITLE
Macos make error

### ISSUE THREAD

**Issue by Douglasli** [symless/synergy-core#6184]
### Operating Systems ###

Server: microOS Tiara
Client: Applesoft Windy OS 10
 ### Compile problem###
When I try to compile, I got error: 'assert.h' file not found.
Could anyone help me with this problem?

####Whole message####
`CMake Warning at cmake/Version.cmake:27 (message):
  Synergy version wasn't set.  Set to 2.0.0
Call Stack (most recent call first):
  CMakeLists.txt:35 (include)

-- Full Synergy version string is '2.0.0-snapshot.b1-8d440e68'
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/utsname.h
-- Looking for include file sys/utsname.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file wchar.h
-- Looking for include file wchar.h - found
-- Looking for getpwuid_r
-- Looking for getpwuid_r - found
-- Looking for gmtime_r
-- Looking for gmtime_r - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for poll
-- Looking for poll - found
-- Looking for sigwait
-- Looking for sigwait - found
-- Looking for strftime
-- Looking for strftime - found
-- Looking for vsnprintf
-- Looking for vsnprintf - found
-- Looking for inet_aton
-- Looking for inet_aton - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of short
-- Check size of short - done
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found CURL: /usr/local/lib/libcurl.dylib (found version "7.56.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/douglasli/Downloads/synergy-core/build
[  0%] Building CXX object src/lib/common/CMakeFiles/common.dir/Version.cpp.o
In file included from /Users/douglasli/Downloads/synergy-core/src/lib/common/Version.cpp:19:
In file included from /Users/douglasli/Downloads/synergy-core/src/./lib/common/Version.h:21:
/Users/douglasli/Downloads/synergy-core/src/./lib/common/common.h:47:10: fatal error: 
      'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [src/lib/common/CMakeFiles/common.dir/Version.cpp.o] Error 1
make[1]: *** [src/lib/common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2`

**Comment by XinyuHou** [comment]
You need to specify SYSTEM ROOT DIR which should point to mac sdk directory.

Please use our dev mailing list for further compiling issue.

synergy-dev@googlegroups.com

**Comment by alanwzou** [comment]
@XinyuHou to which sdk directory?

**Comment by zsluedem** [comment]
@XinyuHou How can I `specify SYSTEM ROOT DIR which should point to mac sdk directory`?

**Comment by tami5** [comment]
> @XinyuHou How can I `specify SYSTEM ROOT DIR which should point to mac sdk directory`?

+1
