### ISSUE TITLE
Keyboard language auto switch when cmd.exe turn on on the server side

### ISSUE THREAD

**Issue by marco-globalluxe** [symless/synergy-core#6185]
### Operating Systems ###

Server: Windows 10 Pro (Personal notebook)
Client: Windows 10 Pro (Work desktop)

*Same keyboard, language and country set up

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###
1. Turn on cmd on server side
2. Mouse navigate from client side to server side screen
3. The keyboard input language switch in auto (not the current input)
For me, it is English-US keyboard (HKSAR) switch to Chinese- Microsoft Quick(HKSAR)
or 
Chinese- Microsoft Quick(HKSAR) switch back to English-US keyboard (HKSAR)

### Other info ###
Impact: It makes me typing Chinese when I wanna type command lines. I just want the server side with cmd opened, even when I back to server screen, my keyboard remain US keyboard as always.

When started: not sure until recently check out why the issue happened

Cover: seems only cmd.exe will cause the issue

Wild guess: although they are both Windows 10, underlying a bit different.
Especially on cmd code page, client side is using "850 oem multilingual latin i" in default while server side uses "950 (ansi/oem - traditional chinese big5)". Not sure the single byte and double bite things related.

Is there a way to work around it: keep switch keyboard with shortcut...

Does this bug prevent you from using Synergy entirely: No, but very annoying for the language switch

Server side log:  https://gist.github.com/marco-globalluxe/f846076e6424d76d2804ee3820f2d633
Client side side: https://gist.github.com/marco-globalluxe/28c0493d63b7b036d5362cde45e025a1

**Comment by GameScripting** [comment]
I think this also happens when using the `bash for windows`. The reason may be it is based on the cmd or windows console/terminal in general.

In my case it switches between german/english. It also seem to happen when I disable one of the lanuages in the OS, however then I have no way to switch the lanuage back to what I want (using [Windows]+[Space])

**Comment by XinyuHou** [comment]
Same cause as #5530
Merged in
