### ISSUE TITLE
Can't connect to background service on Mac

### ISSUE THREAD

**Issue by dhoepp** [symless/synergy-core#6187]
### Operating Systems ###

Server: Mac OS X 10.11.6
Client: Windows 10

### Synergy Version ###

Synergy 2 RC1

### Steps to reproduce bug ###

1. Open Synergy 2 dmg
2. double click Synergy.app
3. program shows error "There was a problem connecting to the background service"

### Other info ###

This showed up in beta 5, where it asked me to open from the dmg instead of dragging to my applications folder. 

![screen shot 2017-11-06 at 9 00 01 am](https://user-images.githubusercontent.com/2715906/32447181-ecbdcdec-c2d0-11e7-8d2d-2a69c715a365.png)

**Comment by alvis** [comment]
This issue is not completed solved in the latest stable version. The issue above still occurs to me once every two times I start Synergy.

**Comment by dhoepp** [comment]
this still appears to be an issue in version 2.0.0

**Comment by AndreasFurster** [comment]
This also happens for me in the latest version for windows (64) I just downloaded.

**Comment by XinyuHou** [comment]
The workaround is open activity monitor and kill Synergy config, which is the UI.

Please use our forum for further v2 problems.
https://symless.com/forums/?_fromLogin=1

Thank you

**Comment by moonye6** [comment]
does someone have fixed this promblem? I have the same error and I don't know how to fix it.

**Comment by mathieuhemp** [comment]
I do have the same problem

**Comment by synic** [comment]
Cannot believe I paid for this "upgrade", arg.

**Comment by nickfoti** [comment]
Killing Synergy config doesn't work, problem persists with OSX 10.13.1 and Synergy 2.02 stable

**Comment by tomscholz** [comment]
Still an issue

**Comment by mathieuhemp** [comment]
I'm killing synergy-service and it does fix the problem, but it's annoying !

**Comment by xinario** [comment]
facing the same issue with osx 10.12.6

**Comment by xushaoda9** [comment]
I do have the same problem, Killing Synergy config doesn't work

**Comment by rubaiz** [comment]
Not working for me either

**Comment by jonabaptistella** [comment]
I installed the it today and it still is a issue. Any work around or ETA on a fix?

**Comment by TheSweetLily** [comment]
Same issue. Just bought and couldn't get it to work until I kept re-trying to share from my desktop and re-starting the processes several times.

**Comment by wturnerharris** [comment]
@XinyuHou can you reopen this issue? This still seems to be a problem. 

*Where the older computer is the one having issues:*
- MacOSX 10.11.6 <=> MacOSX 10.13.2
- Synergy 2.0.4-stable

--

Looks like I/we need to revert to 1x branch for now unless there's any movement. This is not ideal since the app must be installed to parity on all machines.

**Comment by nbolton** [comment]
@wturnerharris I've reopened this issue. Sorry that Xinyu didn't get back to you. Is it still happening for you?

**Comment by rwuwon** [comment]
I've just managed to get synergy-core v2.0.0-stable successfully working between macOS 10.13.5 and Fedora 28 - both each as client and server in turn. The macOS build was done through the command line whereas the one in Fedora is from the Fedora System repository. I pinched the ~/synergy.conf from Fedora acting as a server to apply to the Mac with no modification apart from a rename to ~/.synergy.conf on Mac.

I hope my experience here can be of use:

`FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.` - this message I received when trying to run `sudo ./synergy-core --server -c ~/.synergy.conf -f` on the Mac was a clue so I searched and found this helpful pointer from Jesus as to which "assistive" system setting needed tweaking:

https://sysadministration.wordpress.com/2013/10/23/synergy-fatal-error-in-mac-osx-mavericks/

Open up System Preferences > Security & Privacy > Privacy (upper right tab) > Accessibility (**not to be confused with** Accessibility under Settings) and add the terminal program you launch `synergy-core --server` from (e.g., iTerm2 or Terminal). Amethyst and Dropbox users will notice entries here already, so click the + button to add a terminal. This will allow synergy-core (server) to accept connections from clients.

While everything is still running, re-enable the macOS Firewall and it should then pop up a notice which should let you allow synergy-core to accept connections. If it helps, start with the other OS as a server first to check that all parts are working (with firewall temporarily disabled of course) as it might be more lenient - once that is working, reverse the process and you should be able to get closer to a result.

Remember with macOS, you have to deal with both the Firewall and "Allow the apps below to control your computer" setting.

**Comment by wturnerharris** [comment]
@nbolton still happens for me and not able to get it up and running.

**Comment by rwuwon** [comment]
@wturnerharris I know your setup is different to mine but when you said:

> and then it looks like the app is not trusted even when Synergy is allowed in Preferences > Security > Privacy > Accessibility.

As far as the command line troubleshooting goes, did you also try allowing Terminal or iTerm2 in that same dialog?

**Comment by 1p0t** [comment]
@rwuwon That made it work! Before, I had only made sure to have Synergy allowed.  This issue was solved for me by going to Preferences > Security & Privacy > Privacy (upper right tab) > Accessibility, and adding Terminal from the list of applications. (My setup is Mac OS 10.13 as a server for Ubuntu 16.04.)

**Comment by jess-fortier** [comment]
I am experiencing this issue right now on both of my machines. Synergy was working assymetrically (e.g. would only let my laptop's mouse move to my desktop but not the other way around as would be actually convenient) so I killed everything on both Windows machines from the task manager. Starting Synergy back up and both windows have a yellow error bar across the top stating "There was a problem connecting to the background service." with a Retry link and a Help link. The Retry link does nothing, and the Help link goes to https://symless.com/synergy/help/connection/background-service?source=s2-app&version=2.0.12-beta which states "The page you have visited is temporarily unavailable"

Really regretting buying this app back in Feb. It's been a headache almost every day since.

**Comment by jess-fortier** [comment]
I reran all executables from the installation directory with no change. Went into my Services and saw that the Synergy service had been Stopped, and manually restarted it. Now I'm back to where I was before (my laptop cursor can move onto my desktop monitors if active, but my desktop cursor will not move to my laptop when shared).

Why aren't the executables starting their own dependent service...?

**Comment by softwarescout** [comment]
> The workaround is open activity monitor and kill Synergy config, which is the UI.
> 
> Please use our forum for further v2 problems.
> https://symless.com/forums/?_fromLogin=1
> 
> Thank you

This worked for me.  I'm running Synergy 2 as Server from Mac OSX Catalina.  Running Synergy 2 from Windows 10 box as client. Only the Mac version said it could not connect to service.  Killed Synergy config in Mac's Activity monitor and it just started working.  Only issue is the Mac Synergy screen shows only the Mac listed but not the windows synergy.  However, Windows synergy does show both Mac and windows communicating with each other.  I'm just happy it works now.
