### ISSUE TITLE
Can't drag a screen on server configuration page

### ISSUE THREAD

**Issue by alexforencich** [symless/synergy-core#6188]
### Operating Systems ###

Server: Arch Linux
Client: Arch Linux

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Open synergy GUI
2. Click on Configure Server...
3. Attempt to reorganize screens or add a new screen by clicking and dragging on an icon
4. Cursor changes to 'not allowed' cursor, nothing is actually moved

### Other info ###

* Server works fine with configuration file created manually

**Comment by KDPRoss** [comment]
I see the same behaviour on Antergos.

**Comment by xurei** [comment]
Same issue. I think the only current workaround is to configure the file manually

**Comment by wirecat** [comment]
I am also experiencing this on Arch Linux. Had to use a config file to get around it.

**Comment by theVKC** [comment]
Also experiencing on Arch. Synergy 1.8.8. Server works fine when manually configured.

**Comment by XinyuHou** [comment]
@alexforencich 
Would you mind send us a screenshot please?

**Comment by alexforencich** [comment]
A screenshot really won't show much; everything looks normal, it's just not possible to drag any of the screens.  Clicking and dragging a screen results in the original screen icon darkening and a new icon appearing at an offset (apparently the icon that should be attached to the mouse cursor while dragging) but the cursor changes to the 'not allowed' cursor and nothing else happens (and I can't click on anything, even in other windows) until I press 'esc'.  Fortunately, pressing 'esc' works; I have run in to drag and drop issues in the file browser where it gets stuck in drag mode and the only way out is to either hard reboot or switch to a virtual terminal and kill the file browser.

**Comment by frankdugan3** [comment]
Having this trouble with 1.8.8 on Solus Linux as well.

**Comment by ice-92** [comment]
Still getting this issue on v1.8.8 on Arch.

**Comment by anndavism** [comment]
running on rhel7, I solved this problem by installing synergy from the redhat rpm.  It added some extra packages:
libmng
qt
qt-settings
qt-x11
