### ISSUE TITLE
Feature request: settings profiles based on connected network

### ISSUE THREAD

**Issue by alexforencich** [symless/synergy-core#6189]
The idea would be to have multiple profiles that synergy can automatically switch between based upon the detected network (enabled interface(s), DHCP prefix, gateway IP/MAC, DNS settings, Wi-Fi BSSID/ESSID, etc.).  This is useful when a device is portable and can be used at different locations.  Perhaps synergy is disabled unless connected to a specific network.  Or it acts as a client on one network and a server on a different network.  Or perhaps it connects to different severs on different networks.  Or some combination of the above.  Useful for a laptop that travels between different desks, home vs office, etc.

**Comment by XinyuHou** [comment]
Hi @alexforencich 
Are you using Synergy v1 or v2?

**Comment by alexforencich** [comment]
I'm running 1.8.8 on Arch Linux

**Comment by nlyan** [comment]
Feature is planned for v2, but will not happen in v1
