### ISSUE TITLE
After installation on Ubuntu 17.10, synergy not works

### ISSUE THREAD

**Issue by Aleinux** [symless/synergy-core#6192]
### Operating Systems ###

Server: Ubuntu 17.10

After installation on Ubuntu 17.10, synergy not works

### Synergy Version ###

2.0 stable

**Comment by flyinprogrammer** [comment]
unfortunately they don't support [wayland](https://wiki.ubuntu.com/Wayland) yet, so their Ubuntu support is only a partial truth: https://github.com/symless/synergy-core/issues/4090

**Comment by XinyuHou** [comment]
Duplicate of #4090

There is a workaround to disable wayland to get Synergy working. Please check #4090
