### ISSUE TITLE
Memory leak on ubuntu server with encryption on

### ISSUE THREAD

**Issue by duchy** [symless/synergy-core#6193]
### Operating Systems ###

Server: Ubuntu 14.04
Client: microOS Sierra

### Synergy Version ###

Github master branch.
master     0bd448d5 [origin/master] Reduce clipboard chunk size to 32KiB

### Steps to reproduce bug ###

Usually it will take ~10 minutes to eat out all of 8GB memory.

### Other info ###

* When did the problem start to occur? When I first install the master version with the head being the same as the one of v2.0.0-stable.
* Is there a way to work around it? Yes, you can disable the crypto feature.
* Does this bug prevent you from using Synergy entirely? Yes

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.

**Comment by XinyuHou** [comment]
@duchy 
Do you normally copy big picture or text?

Disable crypto will eliminate the problem, right?

**Comment by nlyan** [comment]
Encryption removed from master as this implementation is not being used in v2

**Comment by duchy** [comment]
@XinyuHou 
No. I did nothing. No big pitcure or text. The memory usages will increase automatically.

**Comment by duchy** [comment]
@nlyan 
Why remove this feature? 
Any replacement plan for that?

**Comment by renanmarks** [comment]
This issue still exists in the most recent version of Synergy. :(
