### ISSUE TITLE
Unable to send Ctrl+Alt to Windows client

### ISSUE THREAD

**Issue by LeadManPL** [symless/synergy-core#6195]
### Operating Systems ###
Server: Ubuntu 17.10 (GNOME 3.26)
Client: Windows 7

### Synergy Version ###
1.8.8-stable-25a8cb2

### Steps to reproduce bug ###
Reproducible: almost always.
0. Get Server with Ubuntu 17.10
1. Install Gnome extension https://extensions.gnome.org/extension/39/put-windows/
2. Configure it's shortcuts to use Ctrl+Alt+NumPad to place windows in screen position
3. Start Synergy
4. press i.e. Ctrl+Alt+NumPad_7 to place some window in Upper Left part of the screen. Works OK - window is moved on the server.
5. move cursor to client
6. press i.e. Ctrl+Alt+NumPad_7 to place some window in Upper Left part of the screen. Here is failure. instead of moving window on the client, again window on the server is moved.

### Other info ###

* When did the problem start to occur?
After upgrade to Ubuntu 17.10 , which dropped Unity in favor of GNOME 3.26

* Is there a way to work around it?
Yes, disabling "Put Windows" Gnome extension makes it possible to send Ctrl+Alt to the Client. **Apparently this extension "steals" keystrokes before it reaches Synergy**. I will report a bug in this extension also, and will reference it's number here.

* Does this bug prevent you from using Synergy entirely?
No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

**Logs will be prepared, after you will decide which DEBUG level you need.**

**Comment by LeadManPL** [comment]
Please consider this bug report together with following report:
https://github.com/negesti/gnome-shell-extensions-negesti/issues/133

**Comment by XinyuHou** [comment]
Please have a look if #4956 is the same as your issue

**Comment by LeadManPL** [comment]
No. I am able to sent ^F3 from linux keyboard to windows Client and it is recognised properly

**Comment by LeadManPL** [comment]
Half year have passed, any news on that bug?
