### ISSUE TITLE
build error on Fedora 27

### ISSUE THREAD

**Issue by sassmann** [symless/synergy-core#6198]
### Operating Systems ###

Server:Fedora 27

### Synergy Version ###

2.0.0
769e3c6a5b02b0a31c84e81b2896201f0411f856 Apply clang-format

### Steps to reproduce bug ###

cmake .
[...]
[ 21%] Building CXX object src/lib/base/CMakeFiles/base.dir/log_outputters.cpp.o
/home/stefan/devel/github/synergy/src/lib/net/SecureSocket.cpp: In member function ?void SecureSocket::showSecureCipherInfo()?:
/home/stefan/devel/github/synergy/src/lib/net/SecureSocket.cpp:793:49: error: invalid use of incomplete type ?SSL {aka struct ssl_st}?
     STACK_OF (SSL_CIPHER)* cStack = m_ssl->m_ssl->session->ciphers;
                                                 ^~
In file included from /usr/include/openssl/err.h:20:0,
                 from /home/stefan/devel/github/synergy/src/lib/net/SecureSocket.cpp:31:
/usr/include/openssl/ossl_typ.h:144:16: note: forward declaration of ?SSL {aka struct ssl_st}?
 typedef struct ssl_st SSL;
                ^~~~~~
/home/stefan/devel/github/synergy/src/lib/net/SecureSocket.cpp:793:51: error: invalid use of incomplete type ?SSL {aka struct ssl_st}?
     STACK_OF (SSL_CIPHER)* cStack = m_ssl->m_ssl->session->ciphers;
                                                   ^~~~~~~
In file included from /usr/include/openssl/err.h:20:0,
                 from /home/stefan/devel/github/synergy/src/lib/net/SecureSocket.cpp:31:
/usr/include/openssl/ossl_typ.h:144:16: note: forward declaration of ?SSL {aka struct ssl_st}?
 typedef struct ssl_st SSL;
                ^~~~~~
At global scope:
cc1plus: error: unrecognized command line option ?-Wno-unused-local-typedef? [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [src/lib/net/CMakeFiles/net.dir/build.make:135: src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 22%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchSleepUnix.cpp.o
[ 23%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchStringUnix.cpp.o
make[1]: *** [CMakeFiles/Makefile2:547: src/lib/net/CMakeFiles/net.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by XinyuHou** [comment]
Please have a look at PR #6182
