### ISSUE TITLE
Version 2 Pro-Core Interoperability

### ISSUE THREAD

**Issue by deckar01** [symless/synergy-core#6199]
### Operating Systems ###

Server: macOS Sierra
Client: OpenSUSE Tumbleweed

### Synergy Version ###

2.0.1-stable

### Steps to reproduce bug ###

1. Install Synergy 2.0.1 on a mac using the provided DMG
2. Wait at the "install Synergy 2 on another computer" step
3. Install Synergy 2.0.0 on a linux computer by compiling it from synergy-core
4. Run Synergy using `synergy-core --client <server FQDN>`
5. The mac does not detect another Synergy client on the network
6. Closing the Synergy window on the mac breaks Synergy (fails to open again)

### Other info ###

I tried to install the official RPM package on my OpenSUSE client, but I received errors:

1. The initial install can't find `libcrypto.so.10()(64bit)`
2. I symlinked `libcrypto.so.10`/`libssl.so.10` to `libcrypto.so.1.0.0`/`libssl.so.1.0.0` in `/usr/lib64/`
3. The install still gripes
4. I continued the install without the dependency
5. The program says "OPENSSL_1.0.2 not found"

I find this odd, because OpenSSL 1.0.2 (64bit) is installed and I am able to compile synergy-core v2 with openSSL just fine.

**Comment by deckar01** [comment]
I just installed the client on a 32bit Windows 7 VM (manually, because the service is busted). It shows a second computer, but it keeps disconnecting and the mouse isn't actually visible when the cursor moves to the client.

I dug into the mac app contents and tried to open the config, but the window it too tall for my macbook air and I can't click the button.

This is the worst experience I have had with a piece of software in a long time.

**Comment by deckar01** [comment]
I had a hell of a time uninstalling Synergy 2 form my mac. It kept respawning automatically when I killed it, which prevented me from moving the app to the trash.

**Comment by XinyuHou** [comment]
@deckar01 
Synergy 2 uses service to start Synergy core and act as a proxy between cores. The branch 2.0 in synergy-core is only a submodule of Synergy 2. They are not compatible. You need to Synergy 2 on both machines. 

Please use our forum for further Synergy v2 questions.
https://symless.com/forums/?_fromLogin=1

**Comment by deckar01** [comment]
This setup worked fine with synergy 1. It doesnt make any sense that Synergy v2 on the server wouldn’t be able to detect a synergy-core v2 client.
