### ISSUE TITLE
Can't update to Version 2.0.2 of Synergy on macOS

### ISSUE THREAD

**Issue by ndreisg** [symless/synergy-core#6204]
### Operating Systems ###

Client: macOS High Sierra

### Synergy Version ###

2.0.1 / 2.0.2

### Steps to reproduce bug ###

I'm trying to install the new Version 2.0.2 of Synergy on my mac, but I can't because it's not possible to quit Synergy.

1. Install and run Synergy 2.0.1 on your mac
2. Quit Synergy
3. Open .dmg file of Synergy 2.0.2 and try to copy the Application to Applications folder.
4. Copying fails with following message: "The operation can’t be completed because the item “Synergy.app” is in use."

I also tried to quit all Synergy Processes in Activity Monitor, but they are restarting immediately.

**Comment by nlyan** [comment]
Running the following command will allow you to upgrade:

`launchctl unload /Library/LaunchAgents/com.symless.synergy.synergy-service.plist`

**Comment by ndreisg** [comment]
how can you close this???
It's definitely a bug when the user needs to run a command in terminal to quit synergy!
When I quit synergy from Menu (or with Command + Q) it should be quit and not hidden (which seems to be the case now)
