### ISSUE TITLE
Can't connect screens

### ISSUE THREAD

**Issue by ndreisg** [symless/synergy-core#6205]
### Operating Systems ###

Server: Windows 10
Client: macOS High Sierra

### Synergy Version ###

2.0.1

### Steps to reproduce bug ###

Don't know exactly how to reproduce.

Log from Server (win10)
https://synergy-logs.symless.com/2017-11-24/980-2017-11-24T08-13-44.log
Log from Client (macOS)
https://synergy-logs.symless.com/2017-11-24/980-2017-11-24T08-07-59.log

I tried to restart the mac but it still didn't work.
A restart of the windows pc solved the problem.

**Comment by XinyuHou** [comment]
@ndreisg 
Thank you for the information.

The bug is caused by a stale user information. Like you said restarting service/pc would solve it. And it's a one time issue so it shouldn't happen again.

Please use our forum for v2 questions in the future.
https://symless.com/forums/?_fromLogin=1
