### ISSUE TITLE
Text too small on Windows 10

### ISSUE THREAD

**Issue by andyneff** [symless/synergy-core#6206]
Text is too small to read/use. Resizing the windows doesn't help. Uninstalling and deleting every reference to synergy from the registry didn't help. Works on other Windows 10 system, but not ark.

![image](https://user-images.githubusercontent.com/7596961/33231021-eb25d6ba-d1bb-11e7-93ca-66e82efdbc8a.png)

I have a normal HD (1920x1080) display, DPI setting in Windows is 100%, changed to 150% and no change in Synergy.

### Operating Systems ###

Server: Windows 10 Version 1709

### Synergy Version ###

2.0.1, 2.0.2

### Steps to reproduce bug ###

1. Start synergy-config

### Other info ###

* When did the problem start to occur? As soon as I upgraded to Synergy 2
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No, but it makes it really annoying to use

https://synergy-logs.symless.com/91ed06c94d1790de1a22e1ca9b2c8db0/logs/376-2017-11-25T08-35-30.log - Computer ark

**Comment by nlyan** [comment]
Hi Andy,

What is the physical size of your screen? Are we dealing with a standard 13-15" monitor?

**Comment by andyneff** [comment]
@nlyan actually, I use a projector. So even though my screen is roughly 120", there's no way the computer would know that. I never told windows how big my screen is as far as I can recall.

**Comment by XinyuHou** [comment]
@andyneff 
Thanks for raising this issue for us.

I have created a new issue in our v2 repository.

Please contact our support for further v2 questions.
https://symless.com/contact
