### ISSUE TITLE
Synergy 2 cannot log to Symless behind a proxy

### ISSUE THREAD

**Issue by mickcornut** [symless/synergy-core#6207]
**Operating Systems**

Server: Ubuntu 16.04 LTS
Client: Doesn't matter

**Synergy Version**

2.0.2

**Steps to reproduce bug**

Launch Synergy on a system behind a proxy using authentication
Click "Sign in with Symless"
See the error "Couldn't connect to Synergy Cloud. Please check your internet connection and then try again"

**Other info**

It looks like 2.0 relies on internet access. It also doesn't seem to have any way to specify a proxy. All the proxy settings are set on the machine and even launching Synergy from bash with the standard proxy environment variables set didn't help.

[synergy-combined.log](https://github.com/symless/synergy-core/files/1506233/synergy-combined.log)
[synergy-config.log](https://github.com/symless/synergy-core/files/1506234/synergy-config.log)
[synergy-router.log](https://github.com/symless/synergy-core/files/1506235/synergy-router.log)
[synergy-service.log](https://github.com/symless/synergy-core/files/1506236/synergy-service.log)

**Comment by pwr22** [comment]
I've hit this too and had to roll back to 1.8

**Comment by aneely** [comment]
I've also hit this issue. After turning off the proxy, both machines seem to be waiting eternally on the other one. Restarting services has no effect.

**Comment by XinyuHou** [comment]
Thank you guys for the information.

This is a v2 issue. I have forwarded this to our v2 repository issue tracker. Please use our forum for v2 discussion.
https://symless.com/forums/?_fromLogin=1

**Comment by furlongm** [comment]
Hi, this is no longer just a beta issue.

This occurs on 2.0.2-stable. Synergy is now unusable without an internet connection?

Why is that the case? Can someone please reopen this issue?

**Comment by ChrisGibb** [comment]
Same problem Synergy v2.0.6.

I used synergy a long time ago when it was free. Now I need it again and I find it's a paid product, which I'm not complaining about. I'm happy you guys can commercialise it... it ~~is~~ was a great product.

But I'm behind corporate proxy and it doesn't work. So my $29 gets me what exactly?

I'm requesting a refund and may consider buying if this gets fixed. It's a shame guys

**Comment by pwr22** [comment]
@ChrisGibb so it still isn't fixed yet? It should be a trivial fix but there isn't even a public bug tracker anymore so we don't know what's going on :-1:. I'm extremely hesistant to encourage this kind of behaviour by buying Synergy 2 again even when this does get fixed!

**Comment by robinhood018** [comment]
I still have the same issue today. Can't log in via Symless. It's just stuck forever. 
![image](https://user-images.githubusercontent.com/71723339/143836339-cea36dab-68f9-461c-94f1-6daddf81abe7.png)
