### ISSUE TITLE
Mouse takes over on client, goes insane, clicks and moves around randomly.

### ISSUE THREAD

**Issue by assumptionsoup** [symless/synergy-core#6208]
### Operating Systems ###

Server: Windows 10
Client: Fedora 27

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Use synergy for a few hours
2. Eventually, synergy will go crazy on the client and start moving the mouse on its own, clicking around, and in general, try to destroy your computer.  I've had it close programs, open new ones, edit text, drag files around - all by left/right clicking and dragging things around randomly.
4. Moving the mouse back to the server screen will **not** stop the client from doing this.
5. Moving the mouse to the client will allow you to move the mouse a little, but it still jumps around and clicks.

### Other info ###

* When did the problem start to occur? When I installed synergy.  And used it.  It seems more frequent after a windows reboot and linux sleep/awake cycle.
* Is there a way to work around it? No.  Stopping the server does not halt this behavior.  Restarting the server doesn't stop it either.  You can't stop it on the client because there's no way to type into the terminal fast enough while the mouse is clicking around. 
* Does this bug prevent you from using Synergy entirely? Yes.

I wouldn't mind trying synergy 2, but I can't find any indication that this bug has been reported or fixed and there is no trial version to test things out.  It has also occurred to me that my computer could be compromised, but if that were the case, I would expect a more human-like approach to destroying my work.  The cursor jumps and moves about randomly, often moving directly to a new location, rather than a path.  This feels more like a bug.

**Comment by XinyuHou** [comment]
@assumptionsoup 
Please check if there are 2 instances of synergy running on your client and any suspicious program running in the background.

**Comment by XinyuHou** [comment]
Close because of insufficient information.

**Comment by thomasrice** [comment]
I had this problem too and for ages couldn't figure out what was causing it... just realised that when I started Synergy on my laptop (being controlled) I'd also close the lid, and closing the lid caused those wild mouse movements and clicks (not Synergy), presumably because the laptop screen was somehow interacting with the laptop's trackpad...
