### ISSUE TITLE
Can't move cursor back to Win10 Server when locked

### ISSUE THREAD

**Issue by ndreisg** [symless/synergy-core#6209]
### Operating Systems ###

Server: Windows 10
Client: macOS High Sierra

### Synergy Version ###

2.0.1

### Steps to reproduce bug ###

Could not move my mouse back to Windows screen when Windows was locked.

1. Move Cursor to Client (mac)
2. Do nothing and wait until Windows is locked automatically
3. Can't move cursor back to Server anymore?

**Comment by ndreisg** [comment]
could not reproduce this issue today... maybe i was missing a step... will update when I know more :)

**Comment by craigkovatch** [comment]
This also happens when a privilege prompt appears on Windows -- Visual Studio Code installed an update which wanted Administrator permission. My mouse was on my Mac client, and now the mouse/keyboard worked on neither computer. I had to unplug the network cable on my Mac to get my inputs back.
