### ISSUE TITLE
Synergy 2.02 complains that has a problem connecting to the auto-config service.

### ISSUE THREAD

**Issue by ttelfer** [symless/synergy-core#6210]
### Operating Systems ###

Server: Windows 10 Version 1703
Client: Mac OS High Sierra 10.13.1

### Synergy Version ###

2.02

### Steps to reproduce bug ###

Start the app and all it says at the top is "There was a problem connecting to the auto-config service. Retry."

Hitting Retry does nothing.

### Other info ###

[2145-2017-11-28T18-29-24.log](https://github.com/symless/synergy-core/files/1512259/2145-2017-11-28T18-29-24.log)

Was unable to use the contact form on the website. Wouldn't let me upload the log files from chrome.

**Comment by XinyuHou** [comment]
@ttelfer 
Please try a clean uninstall and reinstall.

Please use our forum to get support. Thank you.
https://symless.com/forums/forum/17-self-support/
