### ISSUE TITLE
Mouse cursor movement drifts toward upper left direction - Bug Persist in 2.0.2

### ISSUE THREAD

**Issue by zhangd116** [symless/synergy-core#6212]
### Operating Systems ###

Server: microOS 10.13.1
Client: Microsoft Windows 7 Enterprise

### Synergy Version ###

2.0.2

### Steps to reproduce bug ###

Similar to issue [#5648](https://github.com/symless/synergy-core/issues/5648). There is a fix for 1.8.8 but this bug has not been fixed in 2.0.2.

Behavior: Moving mouse along circle, the cursor will slowly moving toward upper left direction. Slow movement causes more drifting, and fast movement shows almost no drifting. dragomireckijj provided pictures in issue [#5648](https://github.com/symless/synergy-core/issues/5648) showing the drifting.

### Other info ###

* Problem started to occur after upgrading to 2.0.1. 2.0.2 does not fix this problem.
* Lowering the mouse report rate from 1000 to 125 alleviate the drifting, but it is still noticeable.
* This bug does not prevent me from using Synergy entirely.

**Comment by XinyuHou** [comment]
@zhangd116 
Thank you for the information.

I have merged this into #5648

**Comment by kekkokk** [comment]
PERSIST IN 2.0.3
THIS BUG IS MORE THAN 1Y OLD.
THE PATCH EXIST. YOU ONLY NEED TO MERGE.
YOU SAID YOU WERE BUSY IN THE V2. NOW THAT V2 IS OUT SAME RESULT.
I PAID FOR THE V1 AND FOR V2. THIS IS TOTALLY NONSENSE.
