### ISSUE TITLE
Cannot send some key combinations

### ISSUE THREAD

**Issue by kndol** [symless/synergy-core#6215]
### Operating Systems ###

Server: Windows 10 (Ver. 1709.16299.98)
Client: macOS High Sierra (10.13.2)

### Synergy Version ###

2.0.3

### Problems ###

Synergy cannot send or receive key combinations: Ctrl-Space, or Shift-Space.

### Other info ###

Server Log: https://synergy-logs.symless.com/17c8e88e90f07d7d18ace209fed1d055/logs/14635-2017-12-09T20-22-07.log
Client Log: https://synergy-logs.symless.com/17c8e88e90f07d7d18ace209fed1d055/logs/14635-2017-12-09T20-22-16.log

**Comment by Avamander** [comment]
Same problem on:
Server: Kubuntu 17.04
Client: Windows 10
With key combination AltGr+2 ("@").

**Comment by XinyuHou** [comment]
@kndol 
Please use our support for v2 issues. Thank you.
https://symless.com/contact
