### ISSUE TITLE
Cursor movements get lost with a full-screen game

### ISSUE THREAD

**Issue by Avamander** [symless/synergy-core#6217]
### Operating Systems ###

Server: Kubuntu 17.04
Client: Windows 10 1709

### Synergy Version ###

Server: 1.8.7-stable-debian
Client: 1.8.8-stable-c30301e

### Steps to reproduce bug ###
0. Move cursor to client's screen
1. Open Steam
2. Start "Human: Fall Flat"
3. Cursor is hidden by the game and then mouse movements do not work any longer, mouse clicks do. Using another physical mouse on the client works properly.

### Other info ###

* When did the problem start to occur? Always has
* Is there a way to work around it? Using a second physical mouse
* Does this bug prevent you from using Synergy entirely? No

Client DEBUG2 log: https://files.fm/f/tppwwttt

**Comment by XinyuHou** [comment]
@Avamander 
Could you try to restart Synergy after the game is running? Thank you.

**Comment by Avamander** [comment]
Tried restarting Synergy. Still the same behaviour, when the game hides the cursor it stops moving (clicks still work like I said).

**Comment by Avamander** [comment]
Can confirm this issue exists in Portal 2 too, the cursor moves but the movements are unpredictable and too fast.

**Comment by sdfg2** [comment]
@Avamander when I had that happen, I found that locking the mouse to that screen helped.

I am experiencing this too.

**Comment by theLucasAntunes** [comment]
Near 9 years later and this is still an issue, why exactly was it closed as not planned?

**Comment by sithlord48** [comment]
We have almost no control over how games take over input . This is why its closed as not planned . It does not happen with every game i play many in full screen w/o issue.

**Comment by theLucasAntunes** [comment]
> We have almost no control over how games take over input . This is why its closed as not planned . It does not happen with every game i play many in full screen w/o issue.

Figures! Also does not happen with every game for me. Thanks for the explanation, I was just looking for one :)
