### ISSUE TITLE
Stop button to disable when not in use

### ISSUE THREAD

**Issue by mikebentley15** [symless/synergy-core#6219]
### Operating Systems ###

Server: Ubuntu 17.10
Client: Ubuntu 17.10

### Synergy Version ###

2.0.2

### Enhancement Request ###

It doesn't seem like there is a way through the UI to disable the Synergy synchronization.  For example, I only want to share the mouse and keyboard when I'm in the office.  But when I'm not in the office, my mouse and keyboard are still capable of being shared (because my desktop machine has a public static IP).  With Synergy 1.x, I was able to click "Stop" until I was in the office again, and then I could click "Start".  Could we have that functionality somewhere?

**Comment by nlyan** [comment]
This is definitely something we will add. In the mean time I recommend stopping the synergy service as a workaround using 'systemctl stop synergy' from the terminal.

**Comment by mikebentley15** [comment]
Sounds good.  Thanks @nlyan

**Comment by OmgImAlexis** [comment]
@nlyan how would I go about this on a Mac or Windows machine? Both have v2 installed and after I closed the window I can no longer reopen it to stop the connection as the gui never shows.

**Comment by fuzzzerd** [comment]
This is a major missing feature, since due to network interruptions, computer sleep cycles its extremely common for Synergy to stop working and need to be restarted. In the 1.x world, stop/start was dead simple and highly effective. 

The regressions in 2.x are becoming more difficult to work around, despite the marginally better high dpi usability gains.

**Comment by mikebentley15** [comment]
One workaround I found is to move the screens apart in the GUI.  It keeps them running, but at least your mouse won't wander over.

Also, the scroll lock will still lock your mouse to your current screen.  It's an easy and effective way to do it as well.

For me, I use the workaround `systemctl stop synergy` on Linux
