### ISSUE TITLE
AltGr in client cause crash in Server.

### ISSUE THREAD

**Issue by sniffarte** [symless/synergy-core#6220]
### Operating Systems ###

Server: Windows 10 ver. 1703 comp. 15063.768
Client: Windows 10 ver. 1703 comp. 15063.608

### Synergy Version ###
2.0.3

### Steps to reproduce bug ###

1- Move to client
2- Press AltGr
3- Server Crash and restart.

LOG: https://synergy-logs.symless.com/1e959e31ec0eb05f37d1d4927a345abf/logs/9266-2017-12-14T13-05-37.log

**Comment by XinyuHou** [comment]
@sniffarte 
Please use our support for v2 issues. Thank you
https://symless.com/contact

**Comment by sniffarte** [comment]
ok. Thanks
