### ISSUE TITLE
Legacy Windows hook ships as a DLL

### ISSUE THREAD

**Issue by nlyan** [symless/synergy-core#6226]
Problem: The Windows hook (synwinhk.dll) is unnecessary. Shipping the hook as a DLL is only required when using the "high level" hook infrastructure within Windows. When using the "low level" hook, which has been the default and only supported option for years, this is unnecessary and wreaks havoc with the Windows installer, which is unable to determine that shutting down the service will free the DLL (and so it doesn't bother).

Solution: Move the DLL hook code in to the core process, remove all high level hook code.

**Comment by nbolton** [comment]
Duplicate of #4957
