### ISSUE TITLE
Synergy 2 Couldn't connect to Synergy Cloud.

### ISSUE THREAD

**Issue by andforce** [symless/synergy-core#6231]
### Operating Systems ###

Server: macOS 10.13.2
Client: Windows 10

### Synergy Version ###

2.0.3-stable

### Steps to reproduce bug ###

when i click launch icon, i can't go next step, it just show me " Couldn't connect to Synergy Cloud. Please check your Internet connection and then try again"

I hava check my internet connection again adn again, it's no problem.

### Other info ###

* When did the problem start to occur? When I...
* Is there a way to work around it? No/Yes, you can...
* Does this bug prevent you from using Synergy entirely? Yes/No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.

**Comment by xclidongbo** [comment]
me too. Same Error.
