### ISSUE TITLE
Feature request: remap any key to any key between screens

### ISSUE THREAD

**Issue by guyzmo** [symless/synergy-core#6237]
On MacOS, I remap the left command key to <kbd>shift</kbd>-<kbd>F13</kbd> to enable a compose key. My keyboard/mouse is shared from linux onto MacOS, and yet Synergy v1 enables key swapping of the modifier keys, but only to other modifier keys. It would be great to make it possible to swap any key to any other key (or set of keys).

**Comment by XinyuHou** [comment]
@guyzmo 
Please use our support for the v2 feature request.

https://symless.com/contact

**Comment by guyzmo** [comment]
I'd have thought that would be a -core feature request… 

Wouldn't such an implementation happen in it?
And if it does, how hard would that be? 
And did someone try such a thing?
And where should I look, if I wanted to make it happen?
