### ISSUE TITLE
Cursor to stay in same place on server switch

### ISSUE THREAD

**Issue by guyzmo** [symless/synergy-core#6238]
Would it be possible to make every connected host a server *and* a client? So that whichever keyboard you use you're typing at the same place, and whichever mouse you use, you're moving only one pointer, whichever screen it is on.

That would simplify the issue of choosing what machine is a server, and which ones are clients as well.

That would enable switching seamlessly from a keyboard to another, with input staying on the same screen, or having a keyboard connected to one machine, but mouse connected to another one.

**Comment by XinyuHou** [comment]
@guyzmo

Do you mean you can use a keyboard from one machine and a mouse from another machine at the same time?

**Comment by guyzmo** [comment]
that would be a consequence, yes.

But what if each mouse connected to each host was controlling the same cursor, instead of acting independently when not controlled by the server host? I don't know if that would be feasible at all, but if it was, that would be awesome! :)

**Comment by guyzmo** [comment]
BTW, that's what I thought that, from the announce mail, the following:

```
** Share Any Keyboard
------------------------------------------------------------

You can control any computer using any keyboard and mouse. No more server and client, no more reconfiguring.
```

meant what I'm asking, but I've tried and it's not that :(

**Comment by XinyuHou** [comment]
@guyzmo 
I see. I have marked as a feature. But we don't have an estimation for it right now. I will let our marketing team know the confusion. Thank you for the request

**Comment by nbolton** [comment]
@guyzmo Actually with Synergy 2 you can do this. The issue at the moment is that you have to click your mouse or press a key to activate sharing, and you can only use 1 keyboard and mouse at one time (not both). Does clicking your mouse or pressing a key solve the issue?

**Comment by nbolton** [comment]
Assuming I understand your issue correctly, I've renamed the issue. Let me know if this is incorrect.

**Comment by guyzmo** [comment]
Hello, I haven't checked that issue for a while, but that's not really what I meant, what I really mean is that for every node that runs synergy and are connected together, every keyboard and mouse can be used for input.

Let's say I got Node A on the left and Node B on the right, for the sake of the example both are laptops (thus with mouse and keyboard). I'm working on the Node B and move the cursor to the left and switch to Node A and write some stuff there. Then for whatever reason I switch to the Node A keyboard and then I move to the far right and it switches to the Node B.

Then we could imagine crazy stuff like using keyboard of Node A, and mouse of Node B if I want 😉

But most importantly, the whole thing would enable one to not think of what is a server and what is a client, just instantiate and interconnect, setup the nodes layout and you're done.
