### ISSUE TITLE
Disable autostart

### ISSUE THREAD

**Issue by jbpoulsen** [symless/synergy-core#6240]
Hello there, i just bought synergy and so far i love it.

But i do not want Synergy to be running every time i boot my Macbook. On Windows i managed to set the Windows Service startup to manual, that works just fine, but on Mac i cannot seem to find out why the program autostarts.

Can i get a short write-up on how to disable/enable the synergy service?

**Comment by XinyuHou** [comment]
@jbpoulsen 
It sounds you are using Synergy v2. Please use our support for feature request. Thank you.

https://symless.com/contact
