### ISSUE TITLE
New configuration utility uses an obscene amount of RAM

### ISSUE THREAD

**Issue by SwooshyCueb** [symless/synergy-core#6241]
OS: Windows 7 Pro SP1  
Synergy version:  2.0.4-stable

The new configuration utility seems to have a memory leak, as I've had it running since the 5th, and I've watched the RAM usage balloon to ~4.5GB, where it currently sits. Yesterday, it was around 4GB.

![image](https://user-images.githubusercontent.com/1675114/34778464-014a993a-f5e3-11e7-8fd3-674627a56c5e.png)

![image](https://user-images.githubusercontent.com/1675114/34778468-0399f1f4-f5e3-11e7-96b6-2e71e24a6d93.png)

**Comment by XinyuHou** [comment]
@SwooshyCueb 
Thank you for raising this issue. I have moved it to our v2 repository. Unfortunately, that repo is private. We will contact you after we fix the issue.
