### ISSUE TITLE
Locking server and client results in quantum tunneling

### ISSUE THREAD

**Issue by aholmes** [symless/synergy-core#6244]
### Operating Systems ###

Server: Windows 7 (Version 6.1 Build 7601 SP 1)
Client: Windows 7 (Version 6.1 Build 7601 SP 1)

### Synergy Version ###

2.0.4-stable

### Steps to reproduce bug ###

1. Move cursor to server
2. Lock client on client keyboard (laptop), then lock server
3. Try to unlock by logging in (press ctrl+alt+del to see login prompt)
4. Observe that the client has focus of the keyboard and mouse
5. Try to move cursor to server and observe that the cursor is stuck in the lower-right corner of the client
6. Open Synergy configurator
7. Notice the "dot" under the client; the client is sharing its peripherals now
8. Observe that the client's peripherals work between both machines
9. Right-click the server and select "share from ..."
10. Observe that everything is back to normal

### Other info ###

* When did the problem start to occur? Since installation
* Is there a way to work around it? Switching control back to the server from the client
* Does this bug prevent you from using Synergy entirely? Yes, it's an impediment which is made worse with more than one client

**Comment by XinyuHou** [comment]
This is caused by the problem as #6209
