### ISSUE TITLE
Local input detection does not work properly on Linux desktop

### ISSUE THREAD

**Issue by dmchurch** [symless/synergy-core#6248]
### Operating Systems ###

Server: Windows 10
Client: Linux (Gentoo, also Xubuntu 17.10)

### Synergy Version ###

2.0.4

### Steps to reproduce bug ###

1. Start Synergy on a Linux/Windows pair. Set the Linux machine to master using the Synergy-2 configuration app, but leave the pointer on the Linux desktop.
2. Press a key on the Windows desktop. Note in the Synergy-2 config app that the Windows desktop switches to master.
3. Move the mouse on the Linux desktop. Note that the Linux desktop does _not_ switch back to master.
4. From the Windows machine, move the cursor over onto the Linux desktop, then move the cursor back to the Windows desktop.
5. Move the mouse on the Linux desktop again. Note that this time, the Linux desktop _does_ switch back to master.

### Other info ###

The issue here is that the local input detection code on Linux only fires when clients believe they do not own the shared cursor, and Linux clients incorrectly initialize believing they own the shared cursor. Since Synergy-2 relies on synergy-core's local input detection code to decide when to switch to master, this means that a Linux desktop can't claim (or reclaim) master until the master has sent the cursor over there at least once. PR incoming.

**Comment by XinyuHou** [comment]
@dmchurch 
Thank you for raising this issue. I have migrated it into our v2 repo.
