### ISSUE TITLE
synergy-2.0.0-1.fc26.x86_64 fails on Fedora26

### ISSUE THREAD

**Issue by daobrien** [symless/synergy-core#6254]
### Operating Systems ###

Server: Fedora 26, GNOME Classic
Client: Any?

### Synergy Version ###
synergy-2.0.0-1.fc26.x86_64 

### Steps to reproduce bug ###
CLI
1. synergys --> get message about deprecated syntax
2. synergy-core --server --> message saying no config exists
GUI
1. WinKey > type "Synergy"
2. Click Synergy icon
3. Nothing happens.

Read web page about using Symless to install. Doesn't exist.

### Other info ###

* Is there a way to work around it? Yes, you can downgrade to synergy-1.7.6-3.fc26.x86_64
* Does this bug prevent you from using Synergy entirely? Yes, unless I downgrade.

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.
Even if this is a valid change, the previous method of starting should still work with a notice that it's being deprecated.

**Comment by sheepdestroyer** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1541640
https://bugzilla.redhat.com/show_bug.cgi?id=1542286

Synergy 2 is an inferior rewrite with the apparent aim to force people to buy the pro version (I say this as a paying customer). I regret buying the pro version as v2 is so broken.

I tried both the 2.0.0-1 from fedora and 2.0.0-4 from my account on official synergy site, and the results are the same : no sane way for old config to work, no sane GUI to configure server, no sane GUI to configure client to point to server's IP (I use multiple vpn, I need a Easy GUI where I can put the Server LAN's IP). The auto detection is broken/unwanted.

You can revert to last supported fedora build, or like me, to v1.8.8 from : 
https://www.brahma.world/synergy-stable-builds/
https://github.com/brahma-dev/synergy-stable-builds/releases/download/v1.8.8-stable/synergy-v1.8.8-stable-Linux-x86_64.rpm

**Comment by sheepdestroyer** [comment]
Update to synergy have been posted to rollback the faulty upgrade to version 2 : https://bugzilla.redhat.com/show_bug.cgi?id=1542286

synergy-1.8.8-3.fc26 has been pushed to the Fedora 26 testing repository
synergy-1.8.8-3.fc27 has been pushed to the Fedora 27 testing repository

**Comment by mrsixw** [comment]
Hi, can you try the official 2.0.x release binaries from the Symless website?

**Comment by nbolton** [comment]
> Synergy 2 is an inferior rewrite

Synergy 2 is not a rewrite.
