### ISSUE TITLE
Scrolling over Start Menu on client machine is laggy

### ISSUE THREAD

**Issue by carlosfvp** [symless/synergy-core#6255]
### Operating Systems ###

Server: Windows 10
Client: Windows 10

### Synergy Version ###

2.0.5

### Steps to reproduce bug ###

I have a Razer mouse. Model Ouroboros to be specific.

1. Move the mouse from the server to a client.
2. On the client open the Start Menu
![imagen](https://user-images.githubusercontent.com/4541969/36182713-fde8bf84-10f8-11e8-9612-4d68a984c475.png)
3. Try to scroll when mouse is over the menu
5. Mouse lags completely for undefined period of time. Sometimes mouse never responds, sometimes it takes a few seconds work again.

Logs already sent.

**Comment by mrsixw** [comment]
Hi, can you reattach the logs?

**Comment by carlosfvp** [comment]
I might try this again on monday to confirm! Best wishes

**Comment by nbolton** [comment]
Thanks, please let me know if it's fixed or not.

**Comment by carlosfvp** [comment]
With the version 2.0.12-beta the bug is not experienced.

At the time I opened this ticket I was suspecting the bug was caused by the new Windows Start Menu since it only happened there. They way it could have been handling mouse events, maybe not redirecting them to other applications.

**Comment by nbolton** [comment]
How about with 1.9? Also, 1.10 is out next week.

**Comment by nbolton** [comment]
Let's say this is fixed, but if you see it again please let me know and I'll reopen.

**Comment by carlosfvp** [comment]
I am currently using 1.9, the bug is not present. I will try next week on 1.10.
