### ISSUE TITLE
Binding hotkey to F24 key fails

### ISSUE THREAD

**Issue by hobnob11** [symless/synergy-core#6258]
### Operating Systems ###

Server: Windows 10 1709
Client: Fedora 27 KDE

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

1. Set up a hotkey, on keystroke f24 is pressed down, set an action to press down the f24 key on the host
2. Second hotkey, on keystroke release f24, set action to release f24 on the host
3. When starting the server, get error 
`    [2018-02-15T10:43:17] WARNING: failed to register hotkey F24 (id=efd5 mask=0000)`

### Other info ###

* When did the problem start to occur? 
When i tried to fix my push to talk not being triggered while on other desktops by using hotkeys
* Is there a way to work around it? No, Not that I've found. 
* Does this bug prevent you from using Synergy entirely? No, It's just a pain to have to move my mouse back to the host to press my ptt. 

Put anything else you can think of here.

I Use a Logitech mouse that has a key bound to f24, I use this for push to talk to make sure it doesn't conflict with any other bindings, but when i try to press my push to talk hotkey on another computer with synergy, it doesn't get sent back.

I Tried setting up a hotkey in server settings to press the F24 key on my main desktop when i press the key, but i get "failed to register hotkey F24 (id=efd5 mask=0000)" when the server starts

my config looks like this:
Keystroke(F24) -> keyDown(F24,Hob-PC)
Keystroke(F24) -> keyUp(F24,Hob-PC)

(Second keystroke set to when the hotkey is released)

**Comment by warp42** [comment]
I'm having a similar issue. I'm trying to set hotkey ctrl+tab and ctrl+shift+tab on my pc to commands

[2019-02-21T16:24:10] DEBUG: registered hotkey Control+Tab (id=ef09 mask=0002) as id=2
[2019-02-21T16:24:10] WARNING: failed to register hotkey Control+Tab (id=ef09 mask=0002)
[2019-02-21T16:24:10] DEBUG: registered hotkey Shift+Control+Tab (id=ef09 mask=0003) as id=3
[-02-21T16:24:10] WARNING: failed to register hotkey Shift+Control+Tab (id=ef09 mask=0003)
