### ISSUE TITLE
No keyboard events on ubuntu client with osx synergy server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#626]
**Imported issue:**
- Author: elkpitano (Google user)
- Date: 2010-07-30 00:00:00
- Legacy ID: 639
- Version: 1.4.2

Hi  

If I run synergy as a server on my osx 10.6.4 machine, my ubuntu (10.04 tls) client does not receive any keyboard events.  

in fact, the ubuntu client just crashed with the message  
synergyc:../../src/xcb_io.c:249: process_responses: Assertion `(((long) (dpy->last_request_read) - (long) (dpy->request)) <=0)' failed.  

(running both the server and the client with -d DEBUG2 -f -no-daemon)  

communication seems to work if ubuntu is the server and osx is the client. However, for my setup it would be preferable, if osx could be the server.  

can anyone help?

**Comment by keathmilligan** [comment]
This bug also affects Mac OS X clients and presumably Windows clients as well since there are no keyboard events being sent to the client at all. This leaves Mac OS X server completely non-functional with current versions of Synergy. The only work-around is to downgrade to a very old version.

**Comment by keathmilligan** [comment]
This issue appears to be fixed in the latest 1.7.1 nightly.

**Comment by nbolton** [comment]
@tomaszluczynski Fixed for you too? http://synergy-project.org/nightly

**Comment by jwwalker** [comment]
It sounds like the bug that keathmilligan said was fixed in 1.7.1 may be a completely different bug than my newer #5176 bug that was closed.  In the newer case it appears that keyboard events are being sent by the server and received by the client, but not handled correctly by the client.

**Comment by rbgarga** [comment]
This issue is blocking me to use synergy. I'm running 1.8.5 pro on OSX as server and connecting from FreeBSD client, also 1.8.5.

When I add only synergy on login items to be automatically loaded it works, but after suspend/resume (or maybe after some time) server stops receiving keyboard events. Running server with DEBUG1 I don't see any keyboard activity

**Comment by rbgarga** [comment]
FYI, If I close lastpass app, close synergy, open synergy again it works

**Comment by LSmith-Zenoscave** [comment]
I have the same issue and found stopping keybase fixes it.
