### ISSUE TITLE
Changes system keyboard language, doesn't type the character and doesn't change the layout back

### ISSUE THREAD

**Issue by Avamander** [symless/synergy-core#6260]
### Operating Systems ###

Server: Linux Ubuntu 18
Client: Windows 10

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

1. Try to type { on client using Linux PC's keyboard (Estonian layout)
2. Language switches to ENG-US on the client, even if it isn't one of the system languages (thus in the layout selection)

This causes two major annoyances:
 - The new absolutely abhorrent wrong layout can't be removed from the system keyboard layout list because it isn't there (but the PC is most certainly using it!)
 - It doesn't type the character
 - It doesn't return to the previous layout

**Comment by YellowAfterlife** [comment]
Possibly related to https://github.com/symless/synergy-core/issues/4344 (Synergy has general issues with keyboard layouts and languages)

**Comment by devcline** [comment]
Confirmed

**Comment by mrsixw** [comment]
Duplicate of #4344

**Comment by hanandjun** [comment]
fsdfrdsfetwetewrefrewrwerewr
