### ISSUE TITLE
Support newest version of libssl on Kali Linux

### ISSUE THREAD

**Issue by rx13** [symless/synergy-core#6264]
### Operating Systems ###

Server: Kali Linux (Debian 4.14.17-1kali1)
Client: Windows 10

### Synergy Version ###

2.0.6

### Steps to reproduce bug ###

Install Synergy 2 on a Kali Debian 4.14.17-1kali1 install (latest)

(purge existing installations) apt-get purge synergy

Download and Install libssl1.0.0
    (file) libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
`dpkg -i libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb`
`apt-get install qml-module-qtquick-controls libxrandr-dev libxtst-dev`
Download and Install Synergy 2.0.6
    (file) synergy_2.0.6.stable.deb
`dpkg -i synergy_2.0.6.stable.deb`

### Steps to resolve bug ###

`nano /lib/systemd/system/synergy.service`
Add line to [Service] section:
`Environment=DISPLAY=:1`
`systemctl daemon-reload`
`systemctl restart synergy`
`synergy-config`
Login to Symless, and you should be able to connect to your other boxes. (no more Display 0.0 errors)

### Other info ###

Happens in default Kali install, since screen defaults to :1 instead of :0.0

**Comment by nlyan** [comment]
All of those prerequisites, except for the -dev packages which aren't required, are listed as explicit dependencies of our debian package.

Is there something about Kali specifically that prevents apt from fulfilling the dependencies?

**Comment by nlyan** [comment]
OpenSSL seems to be the stickler, the package on Kali we should depend on is libssl1.0.2. Naming seems to vary across debian distros.

@rx13 FYI the DISPLAY bug should be fixed in v2.0.7

**Comment by rx13** [comment]
Correct, libssl1.0.0 is the primary item that needs manual resolution. Thanks!
