### ISSUE TITLE
How do you compile the GUI?

### ISSUE THREAD

**Issue by revolter** [symless/synergy-core#6272]
### Operating Systems ###

macOS High Sierra 10.13.3 (17D47)

### Synergy Version ###

ffb0a5e

### Steps to reproduce bug ###

Successfully built using the instructions from the [wiki](https://github.com/symless/synergy-core/wiki/Compiling#Mac_OS_X_1010_and_above)

No `.app` was generated, except the [one](https://github.com/symless/synergy-core/tree/master/dist/macos/bundle/Synergy.app/Contents) that's in the repo which has no executable.

### Other info ###

* When did the problem start to occur? When I...
* Is there a way to work around it? No/Yes, you can...
* Does this bug prevent you from using Synergy entirely? Yes/No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.

**Comment by epakai** [comment]
The GUI code has been removed in synergy-core master. The new GUI (Synergy 2) is a closed source component available from (Symless)[https://symless.com/synergy].

If you want to build the old GUI consider using one of the synergy forks ([yupi2](https://github.com/yupi2/synergy) or [barrier](https://github.com/debauchee/barrier)). You could also use an old release or one of the v1.9 branches that I think still contain the GUI code.

**Comment by sebbean** [comment]
how does one do it?
