### ISSUE TITLE
Why did you release 1.9.0 after 2.0.0?

### ISSUE THREAD

**Issue by yurivict** [symless/synergy-core#6280]
```
v1.9.0-stable
@nlyan nlyan released this 9 days ago · 10 commits to v1.9 since this release
...
v2.0.0-stable
@nbolton nbolton released this on Nov 9, 2017 · 43 commits to master since this release
```

Could you please make another release with a sequentially increasing version number, ex. 2.1.0?

Systems wouldn't pick your version 1.9.0 because they already have 2.0.0 available.

Thanks!

**Comment by yurivict** [comment]
@nlyan

**Comment by ccoenen** [comment]
Why not? It's pretty common to keep more than one version up to date. The changes themselves are described in the Changelog, and they look like mostly build system related and one macOS Bug:

https://github.com/symless/synergy-core/blob/b70b8e0fc4cb520f6e15503c91321addba90f903/ChangeLog#L1-L15

**Comment by mrsixw** [comment]
There are essentially two lines of the Synergy product now. The 1.x.x series refers to the product in this repository and we are continuing to release periodic updates. 

The 2.x.x releases refer to the Synergy product with the simpler configuration UI and cloud sync which is Symless' main focus.
