### ISSUE TITLE
%CMAKE_BUILD_TYPE% not being substituted when compiling

### ISSUE THREAD

**Issue by anohren** [symless/synergy-core#6281]
I'm getting this when trying to compile according to the wiki:

```
[my path...]\synergy-core\build\synergy-core.sln.metaproj : error MSB4126: The specified solution
 configuration "%CMAKE_BUILD_TYPE%|x64" is invalid. Please specify a valid solution configuration using the Configurati
on and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those
properties blank to use the default solution configuration.
```

So I guess I'm wondering why %CMAKE_BUILD_TYPE% is not being substituted properly. Which step is supposed to ensure that this variable has a value?

### Operating Systems ###

Windows 10 pro 32 bit

### Synergy Version ###

2

### Steps to reproduce bug ###

Running `msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=%CMAKE_BUILD_TYPE% /m` as per compilation instructions, after following the previous instruction steps, with some necessary modification to the path of ` call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"` since I'm on 32 bit windows.

Omitting /p:Configuration=%CMAKE_BUILD_TYPE% results in a successful Debug build.

**Comment by Psychopath24** [comment]
Yeah i got the same thing if i say instead of %CMAKE_BUILD_TYPE% i get 2 errors that shouldnt be there it doenst see another file what has to be something to do with cmake
keep me up to date

**Comment by mrsixw** [comment]
Hi there, thanks for raising this and for contributing. We have a synergy-core development sub-forum, which is the best place to ask questions like this.
https://symless.com/forums/topic/5586-read-first-are-you-a-core-developer/
