### ISSUE TITLE
Description of binaries?

### ISSUE THREAD

**Issue by anohren** [symless/synergy-core#6282]
Hello, I just compiled on xubuntu and windows 10 by following the wiki compilation instructions, and I was wondering where I could find a description of all the different binaries that were created? I couldn't find a description in the wiki or anywhere else. 

I also could not find any information on the GUI.

### Operating Systems ###

xubuntu 17.10
windows 10

### Synergy Version ###

2

**Comment by mrsixw** [comment]
Hi there, thanks for raising this and for contributing. We have a synergy-core development sub-forum, which is the best place to ask questions like this.
https://symless.com/forums/topic/5586-read-first-are-you-a-core-developer/
