### ISSUE TITLE
macOS not compiling: Fails on Building C object src/lib/platform/CMakeFiles/platform.dir/OSXDragSimulator.m.o

### ISSUE THREAD

**Issue by Koxiaet** [symless/synergy-core#6284]
### Operating Systems ###

macOS 10.13.4

### Synergy Version ###

Synergy 2

### Steps to reproduce bug ###

1. Follow [this guide](https://github.com/symless/synergy-core/wiki/Compiling), up to the part about compiling on macOS.
2. When running make, it runs successfully until 51%, on:` [ 51%] Building C object src/lib/platform/CMakeFiles/platform.dir/OSXDragSimulator.m.o`. Then lots of errors are displayed.

### Other info ###

* When did the problem start to occur? When I try to compile Synergy
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? Yes

My ~/.bash_profile contains:
```
export CMAKE_PREFIX_PATH="/usr/local/Cellar/qt/5.10.1"
export LD_LIBRARY_PATH=$(brew --prefix openssl)/lib
export CPATH=$(brew --prefix openssl)/include
export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
export PATH="/usr/local/opt/qt/bin:$PATH"
```

**Comment by mrsixw** [comment]
Hi there, thanks for raising this and for contributing. We have a synergy-core development sub-forum, which is the best place to ask questions like this.
https://symless.com/forums/topic/5586-read-first-are-you-a-core-developer/
