### ISSUE TITLE
Windows not compiling: Failed on /p:Configuration=%CMAKE_BUILD_TYPE%

### ISSUE THREAD

**Issue by Psychopath24** [symless/synergy-core#6285]
Hello I've tried to compile the latest stable version of synergy and I keep getting an error.

# **My Taken Steps:**
I use visual studio 2017 and the x64 architecture these are the steps i take:
 git clone https://github.com/symless/synergy-core.git
 cd synergy-core
 mkdir build
 cd build
 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
 cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ..
 msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=%CMAKE_BUILD_TYPE% /m

# **The Error:**
I get the following by going through these steps:
![image](https://user-images.githubusercontent.com/38137580/38460556-c61bf178-3abc-11e8-8c00-964161a10e4e.png)
![image](https://user-images.githubusercontent.com/38137580/38460562-d972a0e6-3abc-11e8-86f3-51b917fe431e.png)

also i tried to solve this by changing /p:Configuration=%CMAKE_BUILD_TYPE% to /p:Configuration=Debug
Or Release and it still did not work
I've python 2.7 and 3.6
latest version of all the other programs and I coulndt find the Qt file that supposed to be in the PATH so i just did multiple of the Qt path
Thank you already if you have an answere or a solution.
Does anyone else have this? and do you need more info?

**Comment by mrsixw** [comment]
Can you please direct problems of this nature to the Synergy Core Developers forum - https://symless.com/forums/topic/5586-read-first-are-you-a-core-developer/?
