### ISSUE TITLE
TIS/TSM error message on Mac client

### ISSUE THREAD

**Issue by garza** [symless/synergy-core#6286]
### Operating Systems ###

Server: macOS High Sierra 10.13.4
Client: macOS High Sierra 10.13.4

Every hour or so, I'm forced to restart the client, the log shows the following error (repeated several times):

```
2018-04-10 12:41:00.570 synergyc[59909:9473966] pid(59909)/euid(824209644) 
is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
```

server logs report
```
[2018-04-10T12:41:10] INFO: switch from "RR153456IP01.local" to "RR170563IP01.local" at 2559,861
[2018-04-10T12:41:10] INFO: leaving screen
[2018-04-10T12:41:10] WARNING: cursor may not be visible
2018-04-10 12:41:10.540 synergys[552:6526] pid(552)/euid(824209644) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
```

### Synergy Version ###

1.8.8-stable-25a8cb2 on both client and server

### Steps to reproduce bug ###

1. start server
2. start client
3. use for a while
4. pointer movements begin to lag
5. see errors in log
6. restart synergy client

### Other info ###

* Can't determine when/why/how these errors are triggered
Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs
* General usage: I'm a web developer, so I usually have multiple browser windows open on both server and client, text editors (vim, atom), and sometimes adobe products open working on image assets, office (outlook) and terminal

**Comment by ryansyah** [comment]
I can confirm that I am seeing this issue. The mouse point will stop working on client for a short period of time (5-15 seconds).

server: 1.8.8-stable-25a8cb2 on macOS 10.14.4
client: 2.0.0_2 on FreeBSD 11, installed from ports

Error Message on client:
`2018-04-13 15:40:15.999 synergyc[36175:336842] pid(36175)/euid(316453797) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!`

I only noticed this issue today when working with large spreadsheets in Microsoft Excel. In my case, synergy is able to recover gracefully and resume normal operation with no outside intervention or restarts.

**Comment by mrsixw** [comment]
Are you seeing this https://symless.com/help/mac-wifi-lag?

**Comment by garza** [comment]
I don't see any mouse lag, just lots of these errors in the log and eventual stop in operation, which i guess starts as lag, but quickly progresses to non-operational w/o a restart of synergy client.

Updated to both server and client to 1.9.1-stable-2a0225c1, but now I just see more of the same log message.  Problem is still just as common.

**Comment by 360Zen** [comment]
Was there a resolution to this issue? It's being discussed here and [here ](https://symless.com/forums/topic/5524-synergy-19-and-high-sierra-10134/). I finally decided to downgrade back to 1.9 and am now receiving this same error, which seems to be preventing my keyboard from working on client computers.

**Comment by nbolton** [comment]
TIS/TSM

**Comment by nbolton** [comment]
Moved to #6326
