### ISSUE TITLE
Control is lost until logged in when RDP used

### ISSUE THREAD

**Issue by skyscooby** [symless/synergy-core#6287]
### Operating Systems ###
Server: Ubuntu 17.10 4.13.0-39-generic
Client: Windows 10 1709 16299.334

### Synergy Version ###
2.0.9

### Steps to reproduce bug ###

1. Setup Synergy Pro and have keyboard/mouse connected to Linux machine.
2. Connect remotely to Windows Machine via RDP.
3. Linux machine is no longer able to control the Windows mouse / keyboard to log in.

### Other info ###

This is a really pestering issue as every morning I need to connect a mouse and keyboard to the Windows machine in order to log in.

As soon as I log in synergy continues to work normally.

**Comment by mrsixw** [comment]
Are you running the synergy-core process directly? If so, what parameters are you using?

**Comment by skyscooby** [comment]
Do you need more information? Were you able to reproduce this? So nice that a commercial product just closes tickets without even a word as to why.
