### ISSUE TITLE
Delay when typing accents on Portuguese keyboard

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6291]
### Operating Systems ###

Server: ?
Client: ?

### Synergy Version ###

2.0.9

### Steps to reproduce bug ###

1. Use Portuguese keyboard
2. Move mouse to client
3. Quickly type: "ç" (specific key), "~" then "a", "o"

Expected: "ção" to be typed
Actual: "çao" is typed

### Other info ###

After upgrading to 2.0.9 I have to wait almost a second to type accents in characters, which really slows me down (we have a lot of these characters). I tried different configurations, and it works fine when I remove Synergy. A frequent use for example is the suffix "ção", which is typed "ç" (we have a key for that), "~" then "a", "o". At my normal typing speed, the result has become "çao".

Forum post: https://symless.com/forums/topic/5601-keyboard-delay-when-typing-accents-in-portuguese-after-209/

**Comment by gb78** [comment]
This bug is happenning on both Windows 7 and 10, even when there is no client connected. Oddly, it affects Windows Notepad and Chrome, but not the Geany text editor. 

I sent a video on Youtube showing a text field on Chrome vs Geany on Windows 10: https://youtu.be/SqBklNapeQI

**Comment by antoniodourado** [comment]
The same bug is happening here. I have to stop Synergy service to prevent this bug to happen.
