### ISSUE TITLE
Compiling error in mac OS High Sierra (10.13.3)

### ISSUE THREAD

**Issue by oribit** [symless/synergy-core#6292]
### Operating Systems ###

Server: macOS High Sierra 10.13.3
Client: macOS High Sierra 10.13.3

### Synergy Version ###
2.X

### Steps to reproduce bug ###

export CMAKE_PREFIX_PATH="/usr/local/Cellar/qt/5.10.1/Frameworks"
export LD_LIBRARY_PATH=$(brew --prefix openssl)/lib
export CPATH=$(brew --prefix openssl)/include
export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
 git clone https://github.com/symless/synergy-core.git
 cd synergy-core
 mkdir build
cmake -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_OSX_ARCHITECTURES=x86_64

### Other info ###

It fails Linking integtests:

[ 91%] Linking CXX executable ../../../bin/integtests
Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      CurlFacade::~CurlFacade() in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_easy_escape", referenced from:
      CurlFacade::urlEncode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_easy_init", referenced from:
      CurlFacade::CurlFacade() in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_easy_perform", referenced from:
      CurlFacade::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_easy_setopt", referenced from:
      CurlFacade::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_easy_strerror", referenced from:
      CurlFacade::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_free", referenced from:
      CurlFacade::urlEncode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_global_cleanup", referenced from:
      CurlFacade::~CurlFacade() in libarch.a(ArchInternetUnix.cpp.o)
  "_curl_global_init", referenced from:
      CurlFacade::CurlFacade() in libarch.a(ArchInternetUnix.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/integtests] Error 1
make[1]: *** [src/test/integtests/CMakeFiles/integtests.dir/all] Error 2
make: *** [all] Error 2

And the solution is to add "**-lcurl**" into the linking command: src/test/integtests/CMakeFiles/integtests.dir/link.txt

**Comment by mrsixw** [comment]
Fixed by fb2db9b802d0bb0906e56a707e3e667dbfa9128a
