### ISSUE TITLE
Server and Client switching roles when moving mouse to client

### ISSUE THREAD

**Issue by sasjafor** [symless/synergy-core#6295]
### Operating Systems ###

Server: Windows 10 Version 1709
Client: Ubuntu 18.04

### Synergy Version ###

v2.0.10

### Command Line ###

Running executable from start menu on both client and server

### Steps to reproduce bug ###

1. Start server and client
2. Use normally

### Other info ###

Server and Client seemingly randomly switch their roles. I'm only moving the mouse from the pc i want to use as server. The client only has a touchpad which I'm not using when the switching occurs. From what I can tell, the switching of the roles happens when I'm moving the mouse to the client. It doesn't happene every time, however.

Here are the logs: 
Server: https://synergy-logs.symless.com/f5c6a42b2fbe649a0c39b2b6d6abd9a7/logs/62991-2018-05-01T13-50-19.log
Client: https://synergy-logs.symless.com/f5c6a42b2fbe649a0c39b2b6d6abd9a7/logs/62991-2018-05-01T13-54-19.log

**Comment by bvulaj** [comment]
Having the same issue with a Windows server and a RHEL client. Happens constantly, but not every time.

**Comment by mrsixw** [comment]
Please raise an issue with Synergy support for this.

**Comment by sasjafor** [comment]
Customer support? So you think this is just a problem with installation and setup?
Well I didn't have this problem with Synergy 1.8 so, this clearly looks like a bug to me.

**Comment by mrsixw** [comment]
As per the other issue, perhaps, but this is not the bug tracker we use for Synergy 2 - it's internal to use and we use customer support as a means of added to it.

These issues are only for Synergy Core or the Open Source Synergy 1.x series.

**Comment by sasjafor** [comment]
Alright, I understand that, but then maybe you should clearly state that in the template for bug reports and when replying to me, because it just seemed like you were trying to get rid of me.

Additionally, but that is just my opinion, a public bug tracker like here on github is way more transparent to us customers. Here, everyone that has a problem can check if it is tracked already, or if it has been fixed already. With an internal tracker you just submit a problem and hope for the best.

**Comment by mrsixw** [comment]
Ok, I've updated the issue template to try and clarify the situation.

**Comment by sasjafor** [comment]
Great to hear!
