### ISSUE TITLE
Keyboard strokes not working since 2.0.9

### ISSUE THREAD

**Issue by tycameron** [symless/synergy-core#6296]
Keyboard strokes don't work at all even after update to 2.0.10

### Operating Systems ###

Server: MacOS 10.13.4
Client: MacOS 10.13.4

### Synergy Version ###

Synergy 2.0.10-stable

### Steps to reproduce bug ###

1. Synergy Connects between client and server.
2. Mouse transitions between client and server and interacts no problem
3. Keystrokes do not work

### Other info ###

I have uninstalled and reinstalled both client and server multiple times and have deleted preference files. There is no workaround. 

Server Log: https://synergy-logs.symless.com/73d8bd8dbf44fe6dc19ea50205204b0e/logs/32180-2018-05-01T10-08-16.log

Client Log: https://synergy-logs.symless.com/73d8bd8dbf44fe6dc19ea50205204b0e/logs/32180-2018-05-01T10-09-02.log

**Comment by mrsixw** [comment]
Please raise a case with Synergy support for this.
