### ISSUE TITLE
Mouse on client trapped within rectangle

### ISSUE THREAD

**Issue by sasjafor** [symless/synergy-core#6297]
### Operating Systems ###

Server: Windows 10 Version 1709
Client: Ubuntu 18.04

### Synergy Version ###

v2.0.10

### Command Line ###

Running executable from start menu on both client and server

### Steps to reproduce bug ###

1. Run server and client normally
2. Client has two screens that are cloned, one has higher resolution
3. Mouse on client gets trapped in the resolution of the screen with the lower resolution

### Other info ###

This worked completely fine using Synergy 1. The mouse cursor would just move outside of what the screen with the smaller resolution could display. On the display with higher resolution everything worked fine. This seems like the natural way of using Synergy to control a notebook with an additional connected screen with a higher resolution.

I did get it to work when going into the Ubuntu settings and setting the screens to a different setting and then back to cloned, setting the resolution of the higher resolution screen to its natural resolution.
However, this is quite inconvenient having to do this every time I disconnect and reconnect the second screen on the notebook.

**Comment by sasjafor** [comment]
Update: Clicking the Icon of the Server in the GUI seems to fix the problem as well.

Here are the logs:

Server: https://synergy-logs.symless.com/f5c6a42b2fbe649a0c39b2b6d6abd9a7/logs/62991-2018-05-03T15-28-58.log
Client: https://synergy-logs.symless.com/f5c6a42b2fbe649a0c39b2b6d6abd9a7/logs/62991-2018-05-03T15-29-57.log

**Comment by mrsixw** [comment]
Please raise an issue with Synergy support for this - https://symless.com/contact/customer-support

**Comment by sasjafor** [comment]
Customer support? So you think this is just a problem with installation and setup?
Well I didn't have this problem with Synergy 1.8 so, this clearly looks like a bug to me.

**Comment by mrsixw** [comment]
Perhaps, but this is not the bug tracker we use for Synergy 2 - it's internal to use and we use customer support as a means of added to it.  

These issues are only for Synergy Core or the Open Source Synergy 1.x series.
