### ISSUE TITLE
question on how to build

### ISSUE THREAD

**Issue by johnny-mac** [symless/synergy-core#6299]
Hi, I am just wondering how to get CMAKE to build the newest version, I get the following error when doing cmake .. or cmake -DCMAKE_BUILD_TYPE=Release .. 

CMake Warning at cmake/Version.cmake:27 (message):
  Synergy version wasn't set.  Set to 2.0.0
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)

-- Full Synergy version string is '2.0.0-snapshot.b1-ecbf7137'

sorry IDK where to find the right words.. wish it was in your wiki.
I've been trying to google solutions for a while now using various different keywords, having a lot of trouble & hope you guys can help. thank you.

**Comment by johnny-mac** [comment]
I have another question - where is the executable? I built synergy-core but there's no executable to launch synergy with & make install doesn't work, so how do I make it work??? :/

**Comment by johnny-mac** [comment]
make[2]: *** [src/lib/net/CMakeFiles/net.dir/build.make:102: src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:550: src/lib/net/CMakeFiles/net.dir/all] Error 

synergy-core-1.8.8-stable/src/lib/net/SecureSocket.cpp: In member function ‘void SecureSocket::showSecureCipherInfo()’:
synergy-core-1.8.8-stable/src/lib/net/SecureSocket.cpp:810:46: error: invalid use of incomplete type ‘SSL’ {aka ‘struct ssl_st’}
  STACK_OF(SSL_CIPHER) * cStack = m_ssl->m_ssl->session->ciphers;

**Comment by nbolton** [comment]
Hey, sorry to see that people are thumb's downing your issue, not very cool of them. Would you mind posting your issue on our Synergy Core forum? That's the best place to get help with compiling. Thanks! https://symless.com/forums/forum/19-core-developers/
