### ISSUE TITLE
Don't lock client's keyboard and mouse

### ISSUE THREAD

**Issue by yiown** [symless/synergy-core#6300]
### Read before raising an issue ###
Please only raise issue for *actual* bugs on synergy-core. For developer support topics, such as designs, compiling issues etc, please see the Core Developers forum: https://symless.com/forums/forum/19-core-developers/

### Operating Systems ###

Server:  All ( I have several Fedora versions and Windows versions )
Client:  All ( I have several Fedora versions and Windows versions )

### Synergy Version ###

1.9.1

### Command Line ###

I simply click the Synergy icon in the main menu.

### Steps to reproduce bug ###

a. I install Synergy server.
b. I install Synergy clients on several PCs.

1. Using the Server's keyboard and mouse I can control clients according to focused client. This is fine.
2. While focus is on client "bob" using client's "alice" keyboard and mouse does nothing. THIS IS UNDESIRED.
2-fix: I would like to use any and all keyboard and mouse as needed. ( on previous versions of Synergy this was the normal behavior ). Of course the Server's keyboard and mouse is the only one capable of controlling other PC, while each client's keyboard and mouse can only control themselves.

### Other info ###

* When did the problem start to occur? Around Synergy 1.8.x since I recall not having this problem before.
* Is there a way to work around it? No and since this changes the behavior until that version, it would have been nice to have the option to enable or disable this.
* Does this bug prevent you from using Synergy entirely? Not really, but it pushes me to look after previous versions of Synergy (and since Synergy 2 is unusable, I am really considering on keeping the old versions).

**Comment by LeadManPL** [comment]
I have 1.8.8-stable-debian and can use server's input devices everywhere, an still can use clients inp dev locally on client, so this regression must have occurred after 1.8.8

/label regression

**Comment by yiown** [comment]
Confirmed.
I downgraded to version 1.9.1 from Synergy download page, and everything went back to normal.
( I had version 2.0.0-3 from my linux distro, but somehow the UI and capabilities were those of 1.x.x )

**Comment by nbolton** [comment]
Hey, would you mind posting this on our forums? Seems like you may need help troubleshooting! https://symless.com/forums/forum/17-general-discussion/
