### ISSUE TITLE
Using kdeconnect causes copy/paste to fail

### ISSUE THREAD

**Issue by oemunoz** [symless/synergy-core#6302]
### kdeconnect with synergy makes copy/paste fails ###
General issues:
- Some time after Synergy start, copy/paste (Ctrl V/C) fails.
- The middle bottom of the mouse is not affected.

### Operating Systems ###

Server: Ubuntu Bionic
Client: Ubuntu Bionic

```
apt-cache policy kdeconnect
kdeconnect:
  Installed: 1.3.0-0ubuntu1
  Candidate: 1.3.0-0ubuntu1
  Version table:
 *** 1.3.0-0ubuntu1 500
        500 http://co.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

### Synergy Version ###

```
apt-cache policy synergy
synergy:
  Installed: 1.8.8-stable+dfsg.1-1build1
  Candidate: 1.8.8-stable+dfsg.1-1build1
  Version table:
 *** 1.8.8-stable+dfsg.1-1build1 500
        500 http://co.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

### Command Line ###

I think this logs are relative:
 ```
/build/synergy-3N7yN5/synergy-1.8.8-stable+dfsg.1/src/lib/client/ServerProxy.cpp,570
[2018-06-07T19:11:12] ERROR: ssl error occurred (system call failure)
	/build/synergy-3N7yN5/synergy-1.8.8-stable+dfsg.1/src/lib/net/SecureSocket.cpp,576
[2018-06-07T19:11:12] ERROR: eof violates ssl protocol
	/build/synergy-3N7yN5/synergy-1.8.8-stable+dfsg.1/src/lib/net/SecureSocket.cpp,579
[2018-06-07T19:11:13] NOTE: disconnected from server
	/build/synergy-3N7yN5/synergy-1.8.8-stable+dfsg.1/src/lib/synergy/ClientApp.cpp,324
[2018-06-07T19:11:14] NOTE: connecting to '172.23.33.36': 172.23.33.36:2480
	/build/synergy-3N7yN5/synergy-1.8.8-stable+dfsg.1/src/l
```

```
v[2018-06-07T19:26:29] INFO: found key in group 0
	/build/synergy-3N7yN5/synergy-1.8.8-stable+dfsg.1/src/lib/synergy/KeyMap.cpp,548
[2018-06-07T19:26:29] DEBUG: lost clipboard 0 ownership at 253313069
```

### Steps to reproduce bug ###

On client and a server start kdeconnect and synergy.

Enable share clipboard en both systems:

![image](https://user-images.githubusercontent.com/17658927/41155462-bd043aee-6ae3-11e8-80d3-5bed9a327f07.png)

### Other info ###

* When did the problem start to occur? When the two system runs on the same kde session.
* Is there a way to work around it? Yes, you can disable clipboard share on kdeconnect
* Does this bug prevent you from using Synergy entirely? No, the client restart but with the copy/paste the client kde-session do work any more. The server is not affected.

**Comment by nbolton** [comment]
Thanks for reporting a bug!

**Comment by nbolton** [comment]
Label added by mistake.
