### ISSUE TITLE
Failed to install on Raspberry Pi?

### ISSUE THREAD

**Issue by jiapei100** [symless/synergy-core#6303]
Hi, 

I used raspberry Pi b3 to build synergy-core, but failed with the following error message:

> Installing with make install...

========================= Installation results ===========================
/usr/bin/cmake -H.../synergy-core -B.../synergy-core/build --check-build-system CMakeFiles/Makefile.cmake 0
Makefile:435: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Segmentation fault

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

> 

Any suggestions? synergy on Raspbeery Pi? How to?

Cheers
Pei

**Comment by nbolton** [comment]
Looks like an issue with the build system. Could you please post on our forums? https://symless.com/forums/forum/19-open-source-core/
