### ISSUE TITLE
Hotkey to reset cursor to pre-specified position

### ISSUE THREAD

**Issue by iiyt** [symless/synergy-core#6311]
### Read before raising an issue ###
Please only raise issue for *actual* bugs on synergy-core. For developer support topics, such as designs, compiling issues etc, please see the Core Developers forum: https://symless.com/forums/forum/19-core-developers/

### Operating Systems ###

Server: microOS Tiara
Client: Applesoft Windy OS 10

**READ ME, DELETE ME**: On Windows, hold the Windows key and press 'r', type 'winver' and hit return to get your OS version. On Mac, hit the Apple menu (top left of the screen) and check 'About this Mac'. Linux users... you know what you're using ;)

### Synergy Version ###

1.8.π

**READ ME, DELETE ME**: Synergy 2.x run `synergy-core --server --version` and Synergy 1.x run `synergys --version` (please do not rely on package manager versioning)

**READ ME, DELETE ME**: If you are running Synergy 2.x, have a issue and are *not* running the core manually, please raise an issue with Syngery Support

### Command Line ###

**READ ME, DELETE ME**: How are you running Synergy? Please include all command line arguments.

### Steps to reproduce bug ###

**READ ME, DELETE ME**: Try to be succinct. If your bug is intermittent, try and describe what you're doing when it happens most.

1. Click things.
2. Type things.
3. Bug occurs.
4. ... 
5. Profit?

### Other info ###

* When did the problem start to occur? When I...
* Is there a way to work around it? No/Yes, you can...
* Does this bug prevent you from using Synergy entirely? Yes/No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.

**Comment by nbolton** [comment]
Duplicates #5387

**Comment by nbolton** [comment]
@iiyt To request an issue be reopened simply comment on that issue (rather than raising a new one).
