### ISSUE TITLE
Install on KUbuntu 18.04 removes Steam

### ISSUE THREAD

**Issue by Nixellion** [symless/synergy-core#6317]
I have a weird issue, I'm not sure if it's me or software...

I use Steam and Synergy (1.x) on KUbuntu 18.04. I installed both, working fine.

Next morning I wake up and notice that Synergy is not there. Shrugging, I ran .deb install again, and noticed that first lines were "dpkg removing steam-launcher...".

And it happens every time now. I install Synergy, it removes Steam. I install Steam back, I don't think it removes Synergy, did not notice it at least. It works until I reboot, and after reboot there's no Synergy.

And after two or three days or this routine it now says:

`ERROR: ssl certificate doesn't exist: /home/nix/.synergy/SSL/Synergy.pem`

Whats going on? O_O

Is there some library incompatibility issue or something?

**Comment by nbolton** [comment]
How strange! I have a funny feeling it's down to the libcurl3 dependency, but it's just a hunch. If that's the case, then https://github.com/symless/synergy-core/issues/6312 will fix that (due for release next week). 

> ERROR: ssl certificate doesn't exist: /home/nix/.synergy/SSL/Synergy.pem

This will be unrelated. Try disabling and enabling SSL in Synergy's settings.
