### ISSUE TITLE
Copy on client doesn't trigger Universal Clipboard

### ISSUE THREAD

**Issue by alanhoyle** [symless/synergy-core#6320]
### Operating Systems ###

Server: Ubuntu 18.04
Client: Apple macOS High Sierra 10.13.5

### Synergy Version ###

1.9.1
### Command Line ###

synergys --enable-crypto --enable-drag-drop

/Applications/Synergy.app/Contents/MacOS/synergyc -f --no-tray --debug INFO --name CLIENT --enable-drag-drop --enable-crypto server.example.com:24800

### Steps to reproduce bug ###

1. Set up macOS client machine and a related iPhone (or possibly another Mac:  untested) to use the Continuity feature with Universal Clipboard (see https://support.apple.com/en-us/ht204681 for how to do this)
2. Bring mouse to client machine
3. Highlight text
4. Do something that would cause the text to copy to the clipboard (keyboard cmd-c/cmd-x or use the mouse to go to the Edit Menu and select Copy or Cut)
5. Go to the iPhone and try to paste the text in any text box

EXPECTED RESULT:  the iPhone pastes the clipboard copied from the mac
ACTUAL RESULT:  either nothing (i.e. clipboard is empty so the phone doesn't offer the "Paste" option) or the iPhone pastes what was already on the iPhone clipboard.  

### Other info ###

* When did the problem start to occur? A while ago, but I just figured it out today that it was related to Synergy.  
* Is there a way to work around it? Yes, you can use the keyboard attached to the client.  When using the built-in keyboard or mouse continuity works.  
* Does this bug prevent you from using Synergy entirely? No

**Comment by nbolton** [comment]
Thanks for raising a bug report! If there's anything I can do to help, please let me know.
