### ISSUE TITLE
Packaging scripts for Windows, Linux, and macOS

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6324]
Problem: The `hm.py` toolchain script was removed at around v1.9 when moving over to Jenkins, which unfortunately included the packaging scripts (which are now commands in Jenkins).

Solution: Introduce a new toolchain (but not `hm.py`, ugh) which can be used to easily run these commands.

**Comment by yupi2** [comment]
Would shellscripts not be sufficient for packaging?

I do [this for .debs](https://github.com/yupi2/synergy/blob/0d1aad0dacc071f9981f778e2ee8a10f36b57ec5/package_deb.sh) along with [this to setup the files for it](https://github.com/yupi2/synergy/blob/bf71f9af401e97d24fbc342cc746ac803ae53b7e/CMakeLists.txt#L369-L383). [One last automated example](https://github.com/yupi2/synergy/blob/bf71f9af401e97d24fbc342cc746ac803ae53b7e/.travis.yml#L39-L45)

For Windows I use [`configure_file` for Wix stuff](https://github.com/yupi2/synergy/blob/bf71f9af401e97d24fbc342cc746ac803ae53b7e/CMakeLists.txt#L462-L472) to build only an x32 or x64 bit solution then and then manually run msbuild on the resulting solution file that's placed into the specified build directory. [One last automated example](https://github.com/yupi2/synergy/blob/bf71f9af401e97d24fbc342cc746ac803ae53b7e/.appveyor.yml#L37)

**Comment by nbolton** [comment]
Good shout, I'll definitely consider that option!
