### ISSUE TITLE
Key combo broken on client with Russian layout

### ISSUE THREAD

**Issue by Nixellion** [symless/synergy-core#6327]
Host: Linux (Kubuntu 18.04)
Client: Windows 10

If I change layout (host) to RU (or any other non-english one), then shortcuts stop working on the client. Things like:

Ctrl+C, Ctrl+V, Ctrl+X, Win+LeftArrow, Win+RightArrow and others.

It also causes instabilities with some programs, like 3ds max hanging.

I did not notice this issue on Windows Host, but there's another issue: #6307 

Both issues might be related to:  #6005

These issues make it really hard to use Synergy in my day to day tasks. I need to keep a close eye on current layout, otherwise I often end up crashing and losing my work.

If I use Windows client I can not type in Russian at all, making it impossible to do a lot of tasks on the Client PC as well.

Will have to switch to a hardware USB switch until all of this is fixed.

ShareMouse had none of these problems, but it does not work in Linux.

**Comment by vitalPixel** [comment]
This should now be fixed with the release of Synergy 1.14.2.

If you're experiencing this problem please make sure you are running Synergy latest version (you can download it by logging in to your account here: https://symless.com/synergy/download).

Please let us know if you run into any issues.
