### ISSUE TITLE
Stop and restart options on macOS menubar

### ISSUE THREAD

**Issue by ylluminate** [symless/synergy-core#6330]
One big problem I'm having is restarting `synergy` properly. I find that sometimes I need to restart synergy to get it to work with a Windows computer that I control from macOS. There's no longer a way to do this easily from the menubar in macOS or system tray in Windows.  

This is a critical function and needs to be restored immediately.  The current system just does not always renegotiate things properly and sometimes it must be manually restarted!

**Comment by nbolton** [comment]
Hello, thanks for raising an issue. Would you mind re-submitting using the template? For bugs, we need the exact steps to reproduce.

**Comment by nbolton** [comment]
@ylluminate Is this in S1 or S2?

**Comment by ylluminate** [comment]
Synergy 2.  Synergy 1 was great in this regard, but v2 just doesn't have such a feature yet.

**Comment by nbolton** [comment]
The wording has changed slightly in Synergy 2, and the icon has changed too. Selecting disable will stop the core process, and enable will start it again; it's effectively like clicking the Apply button from Synergy 1. 

![screen shot 2018-07-09 at 11 47 20](https://user-images.githubusercontent.com/313427/42446357-dc81a616-836d-11e8-8522-bb9c169b7b62.png)
