### ISSUE TITLE
Clicks not registered in Netbeans on client

### ISSUE THREAD

**Issue by SirIntellegence** [symless/synergy-core#6331]
### Operating Systems ###

Server: Windows 10 (version 1803)
Client: Mac 10.10

### Synergy Version ###

2.0.12

### Command Line ###
Server: synergy-core --server --enable-drag-drop -d DEBUG
Client: /Applications/Synergy.app/Contents/Resources/synergy-core --client --enable-drag-drop -f -d DEBUG {server address}

### Steps to reproduce bug ###

1. Open Netbeans and create an instance of the sample project "Anagrams".
2. Open the files "StaticWordLibrary.java" and "Anagrams.java"
3. Add some gibberish to "StaticWordLibary.java" so you have to compile errors
4. Try to navigate to warning and error lines marked to the right of the scroll bar

Expected: Netbeans gets the click and scrolls to the line in question.
 Actual: Nothing happens. It may work if you rapidly click in that spot though.

5. Click on one of the warning lightbulbs in the left margin of the file.

Expected: Netbeans gets the click and shows a menu with hints in it
Actual: Nothing happens. This also might work with rapid clicks.

### Other info ###

* When did the problem start to occur? Upgraded to 2.0.12
* Is there a way to work around it? Rapid clicking or multiple retries
* Does this bug prevent you from using Synergy entirely? No, but it is a big enough issue that I rolled back to the 1.* version where #4578 is broken

**Comment by nbolton** [comment]
@SirIntellegence Is Netbeans running on the client or the server?

**Comment by SirIntellegence** [comment]
Client

**Comment by SirIntellegence** [comment]
Any progress on this one? I assume this applies to all Java programs but is most easily reproduced with Netbeans.

**Comment by nbolton** [comment]
@SirIntellegence I appreciate your frustration. We'll prioritize this if it is reported by more people.

**Comment by Sexual** [comment]
Experiencing this as well. @nbolton 

Server: Windows 10
Client: MacOS Catalina 10.15.2 Beta

**Comment by Feanux3** [comment]
Issue persists across all Java applications it appears.

Server: Windows 11
Client: MacOS BigSur 11.5.2
Application: SQL Developer on MacOS

The issue persists across all versions of MacOS, as well as Windows 10.

**Comment by synconclick** [comment]
My colleagues and I am also having this issue on Java-based tools such as Burp Suite. Whenever you switch apps via clicking away, you would not be able to use any keyboard strokes and clicks will not register. Please fix this!

**Comment by vitalPixel** [comment]
Hi @synconclick, can you please confirm which version of Synergy you're using?

**Comment by synconclick** [comment]
> Hi @synconclick, can you please confirm which version of Synergy you're using?

I am using Synergy 1.14.1
