### ISSUE TITLE
OS name and arch in installer packages

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6341]
Problem: When the package files are in the same dir, it's impossible to tell them apart; e.g. the Debian and Ubuntu builds have the same name, and the two Windows 32-bit and 64-bit builds have the same name.

Solution: Add the OS name to all filenames, somehow fitting them into the package filename convention for the OS.

![image](https://user-images.githubusercontent.com/313427/55491470-70f2fb00-562d-11e9-8e4a-45922a0262e9.png)

![image](https://user-images.githubusercontent.com/313427/55491454-66d0fc80-562d-11e9-8d62-22e2d09a9c53.png)

**Comment by Jnewbon** [comment]
This issue is dependant on the CI solution chosen.
