### ISSUE TITLE
Updated translations and i18n in config app

### ISSUE THREAD

**Issue by p-bo** [symless/synergy-core#6357]
In app, there are strings, that were localized on this translation service, but never merged :(

**Comment by nbolton** [comment]
@p-bo Hey, we're no longer using getlocalization.com. We plan to use crowdin.com for future i18n.

**Comment by p-bo** [comment]
Ok, let us translators know when it will be possible to contribute please (trough this bug, in contribution section of main website / Github readme). Thanks :)
