### ISSUE TITLE
Key input broken with Mac and Linux lock screens

### ISSUE THREAD

**Issue by ian-sl** [symless/synergy-core#6363]
Server: MacBook Pro
* OS-X 10.12.6
* Synergy 1.9.0-snapshot-f0852871 from open-source repo, compiled locally, using GUI client

Client: Dell desktop
* Ubuntu 16.04 LTS
* Synergy 1.9.0-snapshot-f0852871 from open-source repo, compiled locally, using GUI client

Steps to repro:
* run Synergy GUI client on both machines
* set the MacBook as the server and the Ubuntu machine as the client
* lock both machines
* with both lock-screen showing use either machine's mouse to move mouse pointer to client machine's password box and click to give it focus
.. note that the password fields of both machines appear to have focus
* type using the server machine's keyboard
.. the masked '*' characters will appear in the server machine's password field
... note that the server machine's password field works fine and if you unlock the server machine first, the client machine can then be unlocked using the server keyboard

Repro rate: 90%
I have been observing this over several days and I would say 100% but as I was testing just now I actually saw it in another state where one keypress on the server was auto-repeated into the client password field. I rebooted the Ubuntu box to clear a pending O/S update and the symptoms reverted to those described above.  Possible the pending O/S update modified the behavior somehow? I know OS-X can get squirrely when it has an O/S update with a required reboot pending.

**Comment by ian-sl** [comment]
Update: I have now see the alternate auto-repeating keystroke behavior a second time.  I cannot consistently repeat it but both behaviors appear to be symptoms of the same bug.  I suspect if you find the root cause, you will be able to resolve both symptom variants.

**Comment by eliezio** [comment]
I'm facing the same problem. The only workaround I've found so far was to lock and unlock the Mac screen once more
