### ISSUE TITLE
Incomplete type build error when using Qt 5.11

### ISSUE THREAD

**Issue by targodan** [symless/synergy-core#6366]
### Operating Systems ###

Arch Linux with 4.17.5 Kernel

### Synergy Version ###

1.10.0

### Command Line ###

Build as per instructions with qt version 5.11. Will output errors with incomplete type QButtonGroup and more.

### Steps to reproduce bug ###

See above

### Other info ###

There are include files missing. I got the build working. Will try to draft a pull request by Monday evening.

PS: Sorry about the initially empty issue, I accidentally hit enter.

**Comment by nbolton** [comment]
Duplicates #6375

**Comment by hopeseekr** [comment]
Hey, I ran into this trying to install synergy on Arch Linux. I fixed it for you.

**Comment by nbolton** [comment]
@hopeseekr How does your fix compare to PRs #6358 and #6359 by @jpwhiting?

**Comment by jpwhiting** [comment]
It's the same, it was merged into master at one point, then reverted later for some reason...

**Comment by Jnewbon** [comment]
The changes have been merged into `v1-dev` See #6489. We are currently doing the internal review for a release that will pull all the changes on the `v1-dev` branch onto the `master` branch.

**Comment by nbolton** [comment]
Also, https://github.com/symless/synergy-core/issues/6475 is probably relevant.
