### ISSUE TITLE
Typing on client shows special chars and capitals

### ISSUE THREAD

**Issue by AvishayRapp** [symless/synergy-core#6367]
### Operating Systems ###

Server: Windows 10 Enterprise LTSB (v1607) [ OS Build: 14393.2312 ]
Client: Linux Mint 19 Linux BlackBox 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (Sorry if extra info is there, take what your need)

### Synergy Version ###

2.0.12-beta
Protocol Version 1.6

### Command Line ###

n/a

### Steps to reproduce bug ###

1. Windows OS must be set to another keyboard layout besides en_us.
2. Move the mouse to the secondary machine and try to type.
3. Typing will result in just special chars and capital (en_us only) letters and not the secondary layout.

### Other info ###

* When did the problem start to occur?
> immediately, no delay.
* Is there a way to work around it? No/Yes, you can...
> Not at the moment.
* Does this bug prevent you from using Synergy entirely? Yes/No
> No, simple interruption, not actually breaking the system, just have to remember to switch layout before moving screens. 

Windows OS Logs:
https://synergy-logs.symless.com/1c63faf24f23bb256eccd8b2f04d3457/logs/71251-2018-07-22T09-41-53.log

Linux Mint OS Logs:
https://synergy-logs.symless.com/1c63faf24f23bb256eccd8b2f04d3457/logs/71251-2018-07-22T09-42-49.log

**Comment by rwuwon** [comment]
Is this the same as #4?

If so, I've suggested workaround that might tie you over; but you will need to set the client to have the non-US layout and server as US-layout only - not both.

With that setup, if you then need non-ASCII characters on the server end, have a keyboard shortcut toggle it back and forth there (I recommend Ctrl+Super+Alt+Space).
