### ISSUE TITLE
macos: Synerge 2 macos package does not include a symlink to Applications

### ISSUE THREAD

**Issue by ssbarnea** [symless/synergy-core#6377]
Dragging Symless.app to Applications is quite hard (especially on latest MacOS Mojave) because the package is missing a symlink to Applications. The right click menu does not include copy and going to application folder will close (reuse) the current package window.

Also the application lacks the ability to detect that is run from another folder and to prompt user to move itself to ~/Applications.

Including a symlink is usually the most common installation workaround used around, also easy to implement.

**Comment by nbolton** [comment]
In Synergy 2, you simply double-click the app from the DMG (it works more like an installer). Synergy 1 still has the symlink.
