### ISSUE TITLE
Can't send Super key to Windows client

### ISSUE THREAD

**Issue by jasonfisherjlf** [symless/synergy-core#6387]
### Operating Systems ###

Server: Windows 10 Version 1709
Client: Windows 10 Version 1709
Client: Ubuntu 18.04

### Synergy Version ###

1.10.0-stable-275cdc1c
synergys 1.10.0, protocol version 1.6

### Command Line ###

N/A - Running from UI

### Steps to reproduce bug ###

Using the "Super" key doesn't work in Windows. It works just fine on my "Jason_work_compy" (Ubuntu 18.04 client), but does nothing on Windows. If this worked, then hotkeys would be far more useful with my setup. Not a deal-breaker, but a very big bummer.

Using config file
1. Open config file
2. Under "section: options" add line: "keystroke(Control+Shift+End) = keystroke(Super+L)"
3. On server UI, click "Apply"
4. Perform keystroke "Control+Shift+End"
5. ***Nothing happens on server machines*** Ubuntu 18.04 machine logs out as expected.

### Other info ###

* When did the problem start to occur? I'm a new user, so it has always been doing this...
* Is there a way to work around it? Don't use the "Super" key
* Does this bug prevent you from using Synergy entirely? No

Looking at the link below, it says that version 1 isn't supported. If that is the case, why is version 1 listed as "stable", "mature", and "recommended" while version 2 is listed as "beta", "may contain bugs", and requires extra money for Beta access?
Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.

**Comment by drilus** [comment]
I'm on 1.11 stable and also experiencing this issue. Major pain that the super key can't be sent.

**Comment by ConnorMcF** [comment]
I'm also on 1.11 stable I seem to have the opposite problem, I'm not able to send the Super key from Windows 10 to Fedora 30.
