### ISSUE TITLE
Switching to login screen causes reconnect

### ISSUE THREAD

**Issue by jasonfisherjlf** [symless/synergy-core#6388]
### Operating Systems ###

Server: Windows 10 Version 1709
Client: Windows 10 Version 1709
Client: Ubuntu 18.04

### Synergy Version ###

1.10.0-stable-275cdc1c
synergys 1.10.0, protocol version 1.6

### Command Line ###

N/A - Running from UI

### Steps to reproduce bug ###

 On my corporate Windows computer (Jason_email_lappy), it has a CTRL-ALT-DEL command to get to the login. I found the post about using "Pause" instead, and that works. My problem is this:
1. Press "Ctrl-Alt-Pause"
2. Client disconnects and puts my cursor back to my server computer
3. Wait for reconnect
4. Move cursor back to login text box, click, fill out the password and log in
5. Client disconnects again and puts my cursor back to my server computer
6. Wait for reconnect
7. Move cursor back to Jason_email_lappy and FINALLY do whatever it was that I wanted to do in the first place.

### Other info ###

* When did the problem start to occur? I'm a new user, so it has always been doing this...
* Is there a way to work around it? Yes, wait patiently
* Does this bug prevent you from using Synergy entirely? No

Looking at the link below, it says that version 1 isn't supported. If that is the case, why is version 1 listed as "stable", "mature", and "recommended" while version 2 is listed as "beta", "may contain bugs", and requires extra money for Beta access?
Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy-core/wiki/Sending-logs

Put anything else you can think of here.
This isn't completely blocking me from using Synergy with that computer, but it is very annoying...

**Comment by jasonfisherjlf** [comment]
As an update to this, I have found that it will also temporarily disconnect whenever Windows asks the user for permissions to perform a task.

**Comment by xmstspider** [comment]
@jasonfisherjlf - yes this is a common issue, when UAC shows the modal dialog, and it has been discussed as long as I remember.

IMHO the UAC is designed like this to prevent keylogger to interfere with elevated or sensitive processes.

**Comment by jasonfisherjlf** [comment]
@xmstspider OK, I figured as much but I was told to log it anyway. It would be really convenient if it didn't disconnect you every time, but it also doesn't surprise me that there isn't anything Synergy can do about Windows' decisions...

**Comment by makcuber** [comment]
Noting that I have the same issue in Win10 20.04 running Synergy 1.10.3 as a client, UAC will kick Synergy but its able to reconnect after a few seconds. Major annoyance for sure but at least it does work albeit with the delay, plus I highly doubt there's nothing Synergy can do about UAC's anti-keylogger design.

**Comment by awhl** [comment]
As described in #6449 i cannot send Ctrl Alt Del to my Client. During this Key Sequence the mouse pointer switches back to Master and in the log i can see "Leaving screen" and "Disconnected from Server" as long as i click Cancel on the Master.
I think both Problems have the same background. Happy to help that this issue will be solved.
Thanks, Fritz

**Comment by Smylers** [comment]
I think this the same issue as #3637.

The fix is in the client's preferences to set ‘Elevate privileges’ to ‘Always’.
