### ISSUE TITLE
TLS fingerprint shown as dialog for better UX

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6391]
Problem: The TLS fingerprint is quite discreet on the main window, and most users have no idea what it's for until they have to figure it out when a client connects.

![image](https://user-images.githubusercontent.com/313427/43944128-cdacc3c0-9c75-11e8-885f-fd4e6552f16c.png)

Solution: Show a dialog box on the server (much like the one shown on the client) when a new client connects. It'd be nice if you could also reject a client from this screen since currently the trust is based on the client's computer name. We need to make sure we use "TLS Fingerprint".

**Comment by devurandom** [comment]
+1 for mutual authentication. I am using v1.10.2 on the client and this feature appears to be still missing.
