### ISSUE TITLE
Synergy 2 overwrites manually installed Synergy 1 in Fedora

### ISSUE THREAD

**Issue by xmstspider** [symless/synergy-core#6393]
Hi,

I am running Synergy 1.10 on Fedora 28 64-bit and I got an issue, since Synergy 2 is in official Fedora repositories.

1. Install Synergy 1.10 manually
2. Run "dnf update"
3. Synergy is updated to version 2.0

The workaround is to exclude synergy package, but system-wise solution would be to replace Synergy 2 with version 1 in Fedora official repositories.

**Comment by nbolton** [comment]
Sadly we have no control over the Fedora repo. Would you mind raising a bug on the Fedora bug tracker? https://fedoraproject.org/wiki/How_to_file_a_bug_report

**Comment by pgagne** [comment]
Actually one way you could fix this is by setting the Epoch of the Synergy 1.10 RPM you distribute:

https://rpm-packaging-guide.github.io/#epoch

**Comment by pgagne** [comment]
Workaround for this that seems to work with PackageKit in Fedora 30

You need to add 

```
exclude=synergy
```

to the `[updates]` section in `/etc/yum.repos.d/fedora-updates.repo` AND `[fedora]` section in `/etc/yum.repos.d/fedora.repo` 

To get DNF to ignore the 2.x version and only use the 1.x. Also this will work with tools like Gnome Software which use packagekit (you may need to do something like `pkcon refresh`)

see https://bugzilla.redhat.com/show_bug.cgi?id=1256108 for more info

**Comment by xmstspider** [comment]
I think the best option is to have a new package called synergy2 which differs from version 1 so version 1 won't be replaced automatically.
