### ISSUE TITLE
Black and white icons for macOS toolbar

### ISSUE THREAD

**Issue by sebbean** [symless/synergy-core#6396]
### Operating Systems ###
Mac OS X

The only icon I have that's not BW!

<img width="536" alt="screen shot 2018-08-10 at 3 41 08 pm" src="https://user-images.githubusercontent.com/423997/43984171-d6b86508-9cb3-11e8-80e7-353258a31cbd.png">

Looks related to this issue:
https://github.com/symless/synergy-core/issues/3791

Noticing this on most recent version of 1.x branch.

**Comment by jm3** [comment]
cross-referencing related PR #4937

**Comment by dinolatoga** [comment]
I hope someday they implement this.

**Comment by sebbean** [comment]
@nbolton is today the dayyy Baby?

Would frigggin love this merged

**Comment by nbolton** [comment]
I reopened the PR, thanks for the heads up.

**Comment by nbolton** [comment]
Fixed by  #4937
