### ISSUE TITLE
Mojave not working?

### ISSUE THREAD

**Issue by ylluminate** [symless/synergy-core#6400]
Running macOS 10.14 beta 7 and only getting a "There was a problem connecting to the background service. Retry"

Running 2.0.12 beta.

Any idea as to what's going on here?

**Comment by L4Z3RC47** [comment]
Running 10.14 GM here and no issues with connectivity

**Comment by TTimo** [comment]
Just upgraded to Mojave and synergy-core aborts with `ERROR: failed to create quartz event tap`

`CGEventTapCreate` returns 0 .. (OSXScreen.mm)

**Comment by TTimo** [comment]
https://forums.developer.apple.com/thread/109283

**Comment by TTimo** [comment]
synergy-core is a naked mach-o binary and not a bundle, so far I don't know how to deal with `NSAppleEventsUsageDescription` to get a fix. Running from under XCode in the debugger works fine though!

**Comment by STrRedWolf** [comment]
Running 1.10.1 Pro and getting the same error on macOS 10.14 release...

...got it working.  Here's the work-around:

1. Open up System Preferences >> Security and Privacy >> Accessability
2. Unlock the settings here. (yes, authenticate).
3. Uncheck Synergy from the allowed list.
4. Check it again.
5. Lock the settings back down again.
6. Run Synergy.

**Comment by TTimo** [comment]
That didn't work for me, tried it several times. That's probably because I compile a naked Mach-O binary and run it outside of an application bundle. The same method worked for similar apps that have the problem (Moom in my case).

**Comment by nbolton** [comment]
Hi all, Synergy 1 & 2 are actually supported on Mojave. However, there's a bug that occurs when upgrading to Mojave. Here's the workaround:

1. Reinstall Synergy from fresh
2. Remove the app from System Preferences ("Security & Privacy > Accessibility")
3. Open the Synergy app
4. From System Preferences, enable Accessibility access, as requested
5. Configure Synergy as normal

**Comment by STrRedWolf** [comment]
I think it's if you compile from source, it's failing; grabbing the published binary DMG here works with the work-around.

**Comment by MattGerg** [comment]
@nbolton Yes, the workaround was successful!  I am using Mojave with Synergy 2.0.12- beta.  Thanks!

**Comment by bonly** [comment]
> Just upgraded to Mojave and synergy-core aborts with `ERROR: failed to create quartz event tap`
> 
> `CGEventTapCreate` returns 0 .. (OSXScreen.mm)
> 
> (latest git master)

same as me

**Comment by RosayGaspard** [comment]
> Running 1.10.1 Pro and getting the same error on macOS 10.14 release...
> 
> ...got it working. Here's the work-around:
> 
> 1. Open up System Preferences >> Security and Privacy >> Accessability
> 2. Unlock the settings here. (yes, authenticate).
> 3. Uncheck Synergy from the allowed list.
> 4. Check it again.
> 5. Lock the settings back down again.
> 6. Run Synergy.

Solution still good for Mac OS Big Sur beta ! (Synergy 1.11.1)
