### ISSUE TITLE
Mouse can't leave unless window touches edge

### ISSUE THREAD

**Issue by kevinmershon** [symless/synergy-core#6404]
### Operating Systems ###

Server: Linux: openSUSE Tumbleweed 20180818 (Wayland 1.20.0-2.1)
Client: macOS High Sierra 10.13.6

### Synergy Version ###

- openSUSE: 1.8.8-4.1
- Mac: 1.8.8-stable-c30301e

### Steps to Reproduce ###

1. Start server on Linux
2. Start client on Mac
3. Close all other windows on Linux
4. Mouse will not transfer controls to the Mac when leaving screen edge
5. Open a full screen window or any window which touches the edge of the screen on Linux
5. Mouse traversal across screen edge now transfers controls to the Mac

### Run Method ###

Linux: `synergys -c synergy.conf`
Mac: Application GUI

**Comment by azekeil** [comment]
I have the same issue going from Fedora 28 to Windows. It was working fine before an update. Also, it seems that only some applications are 'good' and allow the cursor to move to the client, leading me to think it is some GTK library update that has broken synergy. A 'good' window is Firefox, a 'bad' window is 'Terminal'.

**Comment by azekeil** [comment]
Also, seems like the same issue as https://bugs.launchpad.net/ubuntu/+source/synergy/+bug/872083

**Comment by darkdragon-001** [comment]
I have a similar issue on Ubuntu 18.04:

- Edges with _system bars_ like AppShortcuts (left) or Status/Tray (top) don't work
- Empty edges (no windows) work generally
- Edges with Chrome work
- Edges with Terminal don't work

**Comment by buxtonpaul** [comment]
I also have the issue on Fedora 29 server. Windows client.

**Comment by Leicas** [comment]
Same issue here on Fedora 30 server and Windows client.

**Comment by ericlowry** [comment]
Having the same issue on Centos 8.3

**Comment by andreacndn** [comment]
Hi @ericlowry which version of Synergy and what are the operating systems acting as server and client?

**Comment by azekeil** [comment]
btw the workaround for me is to use xorg server (from the cog icon on the login screen on Linux) - this lets it work as expected (so likely interaction with Wayland is also part of the problem here).

**Comment by ericlowry** [comment]
@andreacndn I was able to resolve the problem but switching to xorg... it was the whole "we don't support wayland" thing, I forgot about synergy when I upgraded my machine...

**Comment by andreacndn** [comment]
@ericlowry thanks for the update.

**Comment by kinekt4** [comment]
This seems to be a dupe of #6191. Can someone please confirm. I would like to add some notes to the primary/active issue. Thanks

**Comment by andreacndn** [comment]
> This seems to be a dupe of #6191. Can someone please confirm. I would like to add some notes to the primary/active issue. Thanks

Yes it seems the same issue

**Comment by kinekt4** [comment]
> btw the workaround for me is to use xorg server

To further clarify, this appears to be only a Gnome desktop issue. I've tried quite a few other desktops (not Gnome) and they don't exhibit the same behaviour raised in this issue.

Like @azekeil , I've switched over to Gnome (xorg).

**Environment**
Synergy Server: Fedora 33
Synergy Client: Windows 10
