### ISSUE TITLE
Mouse gets stuck on client's bottom right corner of secondary screen!!!

### ISSUE THREAD

**Issue by eloboscl** [symless/synergy-core#6405]
I have a DELL XPS L502X, W10 i7 2720HQ 8GB & a MSI GT626RE Dominator Pro W10 i7 6700HQ 40GB that worked great until today.
I rebooted both laptops, reinstalled synergy 2.0.12 on both of them, but the freaking mouse of my MSI keeps getting stucked on my DELL's secondary monitor bottom right corner (where the time and date are displayed).

What in the world is going on????? Please, help me out on this one. It is beyond frustrating like u wouldn't know.
What can I do???

Thanks in advance!

**Comment by eloboscl** [comment]
This happens when the MSI is acting as server. The problem """"goes away"""" when I change the server, but why would I want to do that... it throws away the reason why I trusted Symless and Synergy. This is getting on my nerve real fast.

**Comment by xmstspider** [comment]
@eloboscl Do you have the same issue when installing synergy 1.10? Because synergy 2 is now considered beta.

**Comment by nbolton** [comment]
Hello, thanks for raising an issue. Would you mind re-submitting using the template? For bugs, we need the exact steps to reproduce.
