### ISSUE TITLE
Hostname error shows in auto config mode

### ISSUE THREAD

**Issue by clankill3r** [symless/synergy-core#6413]
Client: OSX 10.12.6
Synergy: 1.10.1
Sever: ...

When I want to use synergy as a client I get:

<img width="733" alt="screen shot 2018-09-05 at 15 08 46" src="https://user-images.githubusercontent.com/738650/45095227-dd505f00-b11d-11e8-9f85-2594e35d4db2.png">

However, there is nowhere a host name input field to be found...

**Comment by eN0Rm** [comment]
I got the same. Think it got something to do with newer version of encryption.

**Comment by nbolton** [comment]
Probably a duplicate of #6392
