### ISSUE TITLE
Mouse scroll wheel does not zoom on Mac client

### ISSUE THREAD

**Issue by RobertLowe** [symless/synergy-core#6418]
### Operating Systems ###

10.13.6 (17G65)
10.13.4 (17E199)

### Synergy Version ###

v2.0.12-beta_b1807

### Steps to Reproduce ###

1. Try to zoom on client device.

### Run Method ###

Synergy 2 Beta app

### Log URLs ###

N/A

### Extra Info ###

Behaviour is reproducible between primary (source device) and slave (remote device).

When trying to Control+Zoom (scroll)  on a remote device nothing happens. Key equivalents work. Zooming works when using the devices local inputs, but not as clients. Test both directions, both fail (Source -> Remote & Remote <- Source)

**Comment by nbolton** [comment]
@RobertLowe Hey, are you using a Mac server and also a Mac client?

**Comment by RobertLowe** [comment]
Yes

**Comment by RobertLowe** [comment]
Also I tested this with a trackpad and mouse. Behaviour seems the same.
