### ISSUE TITLE
Cmd and Ctrl keys select address bar in Chrome

### ISSUE THREAD

**Issue by RobertLowe** [symless/synergy-core#6419]
Operating Systems
10.13.6 (17G65)
10.13.4 (17E199)

Synergy Version
v2.0.12-beta_b1807

Steps to Reproduce
On client, open the latest chrome, focus on the address bar and deselect any test (press left), then press Command or Control, this will cause the address/omnibar to select all text
Synergy 2 Beta app

Log URLs
N/A

Extra Info
This doesn't happen in Firefox or very (<50 versions) of chrome. 

Additionally keydown/etc events `$( document ).keydown(function( event ) { console.log(event) })` do not fire at all (control, option, command)

Using host keyboards work as expected

**Comment by heberallred** [comment]
I'm getting this, also.  Only in Chrome (I'm using Synergy 1).  I wish there was a fix.

**Comment by RobertLowe** [comment]
@heberallred annoying but cheaper than a symless license: https://www.amazon.ca/gp/product/B01MXXQKGM
