### ISSUE TITLE
Install fails on Ubuntu 16.04 with libssl1.1 error

### ISSUE THREAD

**Issue by 130s** [symless/synergy-core#6420]
### Operating Systems ###

```
$ cat /etc/issue
Ubuntu 16.04.5 LTS \n \l
```

### Synergy Version ###

```
$ synergys --version
synergys: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### Steps to Reproduce ###

1. Download a .deb file from https://symless.com/synergy/downloads/list/s1
2. Run:
```
sudo dpkg -i synergy_1.10.1.stable_b87+8941241e_debian_amd64.deb 
:
Unpacking synergy (1.10.1.stable~b87+8941241e) over (1.8.6) ...
dpkg: dependency problems prevent configuration of synergy:
 synergy depends on libqt5core5a (>= 5.7.0); however:
  Version of libqt5core5a:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.
 synergy depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1 is not installed.

dpkg: error processing package synergy (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Errors were encountered while processing:
 synergy

$ sudo apt-get update -qq && sudo apt-get install libssl1.1
:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.1' has no installation candidate
```

### Extra Info ###

- On Xenial it seems the available version of `libssl` is 1.0.0 https://packages.ubuntu.com/xenial/libssl-dev
- I ended up uninstalling 1.10 and re-installed 1.8.8, which went fine.

**Comment by nirodg** [comment]
It's a UI bug, if you check the .deb you just downloaded is for Debian, not Ubuntu.
This is the right url for Ubuntu https://symless.com/synergy/download/direct?platform=ubuntu&architecture=x64

Anyways, a lib is missing  `Package libavahi-compat-libdnssd1 is not installed.`

So the workaround is the following
1. `cd /tmp && http://launchpadlibrarian.net/227449616/libavahi-compat-libdnssd1_0.6.32~rc+dfsg-1ubuntu2_amd64.deb`
2. `sudo dpkg -i http://launchpadlibrarian.net/227449616/libavahi-compat-libdnssd1_0.6.32~rc+dfsg-1ubuntu2_amd64.deb`
3. Download synergy form the link given above and execute `sudo dpkg -i /tmp/synergy_1.10.1.stable_b81+8941241e_ubuntu_amd64.deb`

**Comment by a-d-v-e-n-t-u-r-o-u-s** [comment]
@cavorn is right, same is happening to me.
