### ISSUE TITLE
Windows 10 Can’t compile /MP — missing file or dir

### ISSUE THREAD

**Issue by wfleming801** [symless/synergy-core#6423]
Windows 10. 
Synergy 1.9? 
Visual Studio 2017
(Not sure where the vcvarsall.bat is )
QT 5.9.5
From qt creator make parses ok, but build fails with three errors stating missing file or directory. Starting with “/MP” :missing file or directory.  “/D” : missing file or directory. “Can’t remember the next option passed” : missing file or directory.

**Comment by nbolton** [comment]
> (Not sure where the vcvarsall.bat is )

You'll need to run from the VS command line (found in the start menu or from VS itself).

What build command are you running? Try this:

```
cd Projects\synergy
mkdir build
cd build
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Debug ..
msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Debug /m
```
