### ISSUE TITLE
International keyboards still do not work.

### ISSUE THREAD

**Issue by andyn** [symless/synergy-core#6424]
_Originally posted by @nbolton in https://github.com/symless/synergy-core/issues/6005#issuecomment-426570946_

The aforementioned bug report was closed in error, for two reasons:
1) _All_ international keyboard issues have been closed and their authors have been told to describe their issues by commenting #6005.
2) Nearly all of the problems seem to stem from #6157, which also was closed in error – it describes the root cause and tells what is needed to fix the bug.

**Comment by nbolton** [comment]
Thanks for the feedback, I have reopened #6157.
