### ISSUE TITLE
Certain chars in config path causes config error

### ISSUE THREAD

**Issue by andrenasturas** [symless/synergy-core#6426]
Synergy cannot start in server mode on Windows and does not explicit the problem. It works well in client mode. Server logs are saying `synergys.exe: no configuration available` whenever I specify the path of an actually existing and valid configuration file or use the the interactive configuration.

I discovered that the issue is due to the presence of a space _and_or_ an accent in a path. The config file was located in C:\Users\Surname Name\synergy.sgc, where "Surname Name" contains a space and an accent. If a specify another location without space and accent, it works well. If I am not wrong, this reveal a bug in Synergy 1 in the config file path parsing.

### Operating Systems ###

Server : Windows 10 (and maybe all versions of Windows, or even all platforms)
Client : Any system (the issue seems to concern only the server)

### Synergy Version ###

Synergy 1.10.1 Pro

### Steps to Reproduce ###

Try to initiate Synergy in server mode on a Windows computer, using an user which have a home directory containing spaces and accentuation (French, and probably any language).

### Run Method ###

Config app.

### Log URLs ###

Synergy Windows 10 Server: https://pastebin.com/xD7V1ZT9
Synergy Ubuntu 16.04 Client: https://pastebin.com/JAXyTnAs

Both having Synergy 1.10.1 installed.
I think the issue was already there before i tried to update from some Synergy 1.8 version, but I cannot tell that for sure.

### Extra Info ###

The issue seem to be caused by Synergy not being able to handle accentuation and/or spaces in the path of the server config file. The same configuration works perfectly fine if I reverse server and client roles, and if I tell Synergy to use a config file located in a space and accentuation free directory (in my case, D:\ drive root)/ But it does not work with interactive config or with a config file located in my home directory.

It works with Ubuntu in server mode, but I did not try with space nor accentuation in server config file path on Ubuntu side, so the bug could concern all platforms.

**Comment by lemw** [comment]
This bug seems not taken care of still, caused me some days of troubleshooting without know the reason.

My last name contains an "å", thus causing the problem mentioned.
This is a paid SW; and an honstly a bit puzzled this would even be an issue to solve?

**Comment by lemw** [comment]
Time to fix this issue?
