### ISSUE TITLE
Mouse cursor movement drifts over time

### ISSUE THREAD

**Issue by L4Z3RC47** [symless/synergy-core#6427]
Issue #5648 seems unresolved in current releases although issue is resolved via  https://github.com/symless/synergy-core/files/902511/synergy-v1.8.8-pr-5648-stable-1c1067d-MacOSX-x86_64.dmg.zip

**Comment by nbolton** [comment]
Hey, looks like #5648 wasn't back-ported to 1.x. I'll use this issue for the backport.

**Comment by nbolton** [comment]
Ah, never mind, there's already an issue for that: https://github.com/symless/synergy-core/issues/6403
