### ISSUE TITLE
Cannot write umlauted vowels and the sharp-S

### ISSUE THREAD

**Issue by ghost** [symless/synergy-core#6428]
### Operating Systems ###

Server: Windows 10 Pro (with German keyboard)
Client: Windows 10 Pro (with German keyboard)

### Synergy Version ###

Server: Synergy v1.10.1
Client: Synergy v1.10.1

### Steps to Reproduce ###

1. Start Synergy
2. Move your mouse to the client
3. Press the keys for umlauted vowels (ä, ö, ü) and the sharp-S (ß) on your keyboard

Result: I can't write umlauted vowels (ä, ö, ü) and the sharp-S (ß) on my client.

### Run Method ###

Config App

### Log URLs ###

Server: https://paste.ee/p/RGIMp
Client: https://paste.ee/p/IRF3Y

### Extra Info ###

Example:
If I write "aouäöüaouß" on my Client, only "aouaou" will appear.

**Comment by bjoernmartin** [comment]
Having the exact same issue. I noticed it with a 1.8.x version (1.8.8 I think) but - after seeing this issue - downloaded the newest ones and tried again. Same result.

### Operating System
Server: Windows 10.0.17134.407 Home (64 bit)
Client: Windows 10.0.17134.407 Pro (64 bit)

### Keyboard layout
Server: German QWERTZ (standard layout)
Client: German QWERTZ (Notebook layout, thus "custom", but registered as standard QWERTZ to Windows)

### Synergy Version
Server + Client: 1.10.1-stable-8941241e (64 bit)

### Log URLs
Server + Client: https://paste.ee/p/eXBKj (for 1 year)

### Extra Info
* This worked at some point, as I was able to use Synergy 1 just fine a while back. 
* It might have been an occasional issue before but that could also have been the case for Synergy 2 (before it re-entered Beta), don't remember.

**Comment by HackXIt** [comment]
Having the same issue with version 1.13.1-stable-063519a8 _(same for Server + Client)_

# Operating System
Server: Windows 10 Pro 19043.1110 (64-Bit)
Client: Windows 10 Home 19043.1110 (64-Bit)

# Keyboard layout
Server: QWERTZ
Client: QWERTZ

**Comment by bjoernmartin** [comment]
Just an FYI: this works flawlessly on Synergy 3 between two Windows 10 machines. So if you still have issues with this, maybe just try Synergy 3 and see if it's fixed there.

Windows version: 10.0.19045.3516 (client) + 10.0.19045.3448 (server)
Synergy version: v3.0.73.7-rc2 (both)
