### ISSUE TITLE
Alt key cause Chrome address bar to be highlighted

### ISSUE THREAD

**Issue by AlexeyPilya** [symless/synergy-core#6430]
### Operating Systems ###

Client - macOS High Sierra (10.13) 
Server - Debian 9 (Stretch) 

### Synergy Version ###

Synergy v1.10.1

### Steps to Reproduce ###
1. Move mouse to mac client
2. Open Chrome on Mac client 
3. Press ALT key 

Expected nothing happens.
Actual, all text in Chrome address bar got selected. 

### Extra Info ###

The "alt" key seems to cause the Chrome address bar to be highlighted.
Also, when user press the "alt" key (keyboard is connected to the Debian host machine), Chrome's address bar (on the Mac client machine) gets all text selected. This means that when user press "Alt-V" to paste, it overwrites the URL that is already there. For example:

http://foo/ is just replaced with "sometext", because ALT causes "http://foo/" to be selected.

**Comment by orcinus** [comment]
Just FYI.
This seems to have been resolved in the past few weeks of Chrome Canary builds.

Also, the Chromium team seems to have successfully built synergy binaries from the open source fork.
