### ISSUE TITLE
Config app doesn't remember the server hostname

### ISSUE THREAD

**Issue by xmstspider** [symless/synergy-core#6432]
Server: Fedora 28
Client: macOS 10.14

Synergy 1.10.1-stable-8941241e on both server and client

1. On macOS, use Manual Config mode, select client and fill the hostname. After macOS restart, Synergy client asks for the hostname and the Server field is empty
3. Seen after each restart

Last log line before the restart:
[2018-10-12T09:03:59] INFO: stopping synergy desktop process

**Comment by jamesshallcross** [comment]
Also seeing this, on MacOS, with synergy_v1.11.0-stable_b193-b2173efb_macos

![Screenshot 2020-01-14 at 10 11 19](https://user-images.githubusercontent.com/3843248/72335090-54a0e600-36b6-11ea-8a54-6dd6cd15d94e.png)
