### ISSUE TITLE
Specified solution configuration is invalid

### ISSUE THREAD

**Issue by cranedrop** [symless/synergy-core#6434]
![image](https://user-images.githubusercontent.com/20478353/47164245-33045380-d2e7-11e8-9207-52f04c97c1a4.png)

I'm getting this build error. Can someone help?

I'm using Win10 x64.

**Comment by nbolton** [comment]
I checked out [compile](https://github.com/symless/synergy-core/wiki/Compiling) wiki page, and it seems that it was specifying `%CMAKE_BUILD_TYPE%`, so I [fixed it](https://github.com/symless/synergy-core/wiki/Compiling/_compare/ad2f7a15dcf4f15253eae4c71ac78bb4b3f8f52b...1ac71e476d0ee69700cceae2614e22f955b13c04). That was lifted directly from our CI system. You actually need to replace this variable with `Debug`.

So, the build line should be...
`msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Debug /m`

Does that help? We can reopen if not.
