### ISSUE TITLE
Lock screen causes cursor to freeze on Windows 10

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6436]
### Operating Systems ###

Server: Windows 10
Client: macOS 10.14 Mojave

### Synergy Version ###

1.10.2-snapshot

### Steps to Reproduce ###

1. Change server elevate setting to "Always"
1. Lock Windows server screen and macOS client screen
2. Go away for 5 mins and return
3. Move mouse from server to client

Expected: Mouse moves and keyboard types
Actual: Only keyboard can type on client

### Log URLs ###

Windows Server: https://paste.ee/p/B7BwQ
macOS Client: https://paste.ee/p/R3ZSL

### Extra Info ###

Workaround: Run terminal on macOS client (Cmd+Space, Terminal), and type: `killall synergyc`.

I find it only happens when you leave your computer for like 5-10 mins. If you lock the screens and try to reproduce it immediately it doesn't seem to break. But maybe if you have it locked for a few hours, the machines go to sleep so it has to be within a certain time period. I had to change the elevate option to always, because the constant core restart (on user switch) was driving me nuts.

This probably has something to do with the bug:
```
[2018-10-26T12:02:29] DEBUG: dropped bogus delta motion: -965,+20
[2018-10-26T12:02:29] DEBUG: dropped bogus delta motion: -963,+21
[2018-10-26T12:02:29] DEBUG: dropped bogus delta motion: -961,+21
[2018-10-26T12:02:29] DEBUG: dropped bogus delta motion: -962,+21
[2018-10-26T12:02:29] DEBUG: dropped bogus delta motion: -961,+21
```

**Comment by doostee** [comment]
I also see this issue with Windows 10 server and client on 1.10.1. 

When the server automatically locks after in-activity I can't move the mouse on the server anymore. Workaround is to just use the client's physical keyboard and kill synergy service.
