### ISSUE TITLE
Mouse moves up and left twice as fast on Mac client

### ISSUE THREAD

**Issue by stingray88** [symless/synergy-core#6445]
### Operating Systems ###

Server: Mac OS 10.13.6 - 2013 Mac Pro with two 3840x2160 displays
Client: Mac OS 10.13.6 - 2018 15" MacBook Pro with 2880 x 1800 display

### Synergy Version ###

Currently the most recent - 1.10.1-stable-8941241e

### Steps to Reproduce ###

I've tried completely reinstalling Synergy, as well as restarting my machines. The problem is reproducible 100% of the time. When moving my mouse up or left, the cursor on the client machine travels twice as far as when I'm moving down or right. This causes the cursor to become very difficult to control.

### Log URLs ###

I'm not sure where to find the logs. Can you point me in the right direction?

### Extra Info ###

I was previously on Mac OS 10.11 on the Mac Pro (server) and did not experience these issues. It was only when I updated to Mac OS 10.13 today that I started to experience these issues. I was previously a version behind on Synergy for both the server/client, so I tried updating first, however it made no difference.

**Comment by nbolton** [comment]
Possibly related to: https://github.com/symless/synergy-core/issues/6403

**Comment by Jnewbon** [comment]
Solved by #6469
