### ISSUE TITLE
Clipboard sharing re-enables on config app restart

### ISSUE THREAD

**Issue by GranoblasticMan** [symless/synergy-core#6447]
### Operating Systems ###

Windows 10 18305.1003

### Synergy Version ###

1.10.1-stable-8941241e

### Steps to Reproduce ###

Disable clipboard sharing.
Stop and close Synergy 1.
Open up Synergy 1 again, clipboard sharing is re-enabled.

**Comment by kylessnell** [comment]
+1 - this causes my client to crash regularly. would love to turn it off permanently.

**Comment by nbolton** [comment]
Reproduced, what an irritating bug.

**Comment by volt4ire** [comment]
This happens on the latest versions of Ubuntu (18.04 LTS & 19.10) and macOS (10.15.3) as well.

**Comment by volt4ire** [comment]
Hi @nbolton do you know if there are any updates on addressing this issue? It has major security ramifications

**Comment by nbolton** [comment]
Hi @volt4ire. Agreed, I have prioritized this on our backlog. Thanks for bringing it to my attention.

**Comment by volt4ire** [comment]
@nbolton great thank you so much for the quick reply and wonderful piece of software!!
