### ISSUE TITLE
Changelog lagging behind (stops at 1.9.0-rc3)

### ISSUE THREAD

**Issue by ccoenen** [symless/synergy-core#6455]
Currently, this repository only shows commits up to october 2018. The changelog stops at 1.9.something.

~~In the meantime 1.10.1 has been released. I would like to request pushing that source code to github or any other public repository.~~ Turns out, the commits are there, but the changelog is not up to date. Sorry for the confusion.

**Comment by Jnewbon** [comment]
The repo has recently been restructured as seen in issue #6475 

The changelog for v1 of synergy is [here ](https://github.com/symless/synergy-core/blob/master/ChangeLog)
