### ISSUE TITLE
Shift key gets stuck down on macOS client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6459]
### Operating Systems ###

Server: macOS 10.13
Client: macOS 10.13

### Synergy Version ###

1.10.0

### Steps to Reproduce ###

1. Connect macOS client to macOS server
1. Move mouse from server to client
2. See that shift key is stuck down on client

### Extra Info ###

Happens as many times as the user mouses from the Server to the Client. It’s very consistent. No pattern of apps as far as I can tell. Some programs that might have focus are Slack, Chrome, Synergy, Avid MediaComposer. It happens without fail as soon as the client makes the connection to the server. After tapping Shift, only one keypress would register, as expected.

**Comment by poptix** [comment]
I'm having the same issue between a Windows server and Linux client with the Alt key.

**Comment by daviddavo** [comment]
The same issue with mod4 (windows key) on linux client/server.

For more info, I'm using i3, so Mod4 is one of the most used keys
