### ISSUE TITLE
TLS memory leak on Linux server when using client

### ISSUE THREAD

**Issue by lusor** [symless/synergy-core#6460]
### Operating Systems ###

Server: Linux (Debian Testing/Buster)
Client: Windows 10

### Synergy Version ###

Synergy 1: synergys 1.10.1, protocol version 1.6

### Steps to Reproduce ###

1. Use Synergy on Windows client for a few hours

Expected: Memory consumption on server remains stable
Actual: The server process starts building up memory consumption (> 5GB)

### Extra Info ###

This behavior started in v1.10.1, v1.10.0 was ok.
I'm having the issue since end of last year, the workaround is to `killall synergys` every few hours of use.
The memory consumption only build up when connected to the client (and probably using it on the client, but I'm not quite sure there).

**Comment by catrielmuller** [comment]
+1
I think this issue is related with the Log, because i don't have any option to disable the logs and its unlimited the amount of lines it's saved on the memory.

**Comment by Jnewbon** [comment]
Is TLS enabled, if it is can you try disabling it and seeing if the issue persists? 

Needs to be done on both the client and server (Recommend doing the client first as it will disconnect)
[Edit] -> [Settings] -> Untick "Enable TLS Encryption" 
Click [Ok] Then [Apply]

**Comment by lusor** [comment]
I've tried disabling TLS and it fixes the issue, memory usage is now <1MB

**Comment by Jnewbon** [comment]
Fixed by #6488
