### ISSUE TITLE
Removal of confusing and redundant apply button

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6464]
Problem: The Apply button is very obsolete and not common in modern UI design; settings should automatically apply without the need of an apply button.

Solution: Remove the Apply button, and make everything apply automatically. Because the current UI is built around the Apply button, this would take some major work (e.g. what happens when you edit the IP field, do you wait until focus has changed?)

**Comment by xmstspider** [comment]
Well this may be dangerous in case of a typo in IP address or server name.
