### ISSUE TITLE
Grey out Apply button until changes are made

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6466]
Problem: People don't know that they should hit the apply button to apply changes (e.g. changing an IP address in manual mode).

Solution: Grey out Apply button until changes are made.

**Comment by nbolton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Greyed out apply button](https://trello.com/c/YuJCT9wI/1-greyed-out-apply-button)

**Comment by simonbloom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Greyed out apply button](https://trello.com/c/YuJCT9wI/1-greyed-out-apply-button)
