### ISSUE TITLE
CI solution with on-demand containers

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6470]
Problem: We are using Jenkins with static VM instances, So the VM's are always online wasting resources. Also, macOS builder is a physical machine and is always online.

Solution: Use a CI as-a-service which offers on-demand instances preferable using Docker images. Cirrus CI could be a good solution, however, their Mac builder doesn't support Docker.

Note: This issue does not include deployment (i.e. no snapshot upload). This will be a separate issue.

**Comment by fkorotkov** [comment]
How do you use Docker on Mac right now?

**Comment by Jnewbon** [comment]
> How do you use Docker on Mac right now?

Currently, we don't, we use a physical machine in the office connected to Jenkins, for the Mac builds. I have a build working on Mac on Cirrus CI. It would have been nice to have all the builds using Docker for ease of maintaining them.
