### ISSUE TITLE
Change master branch to current version

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6475]
Problem: We are no longer developing Synergy 2 Beta (as we're skipping to Synergy 3 Alpha), but the master branch is Synergy 2 Beta. As well as going against the general consensus of what is in a master branch, this is confusing when people want to contribute, etc.

Solution: The master branch should be the current stable public release (Synergy 1 in this case), so we'll put S2 on a branch (e.g. `v2.x` branch) and change master to be S1 (`v1.x` should be renamed to `master`).

**Comment by Jnewbon** [comment]
Following changes have been done
- Master -> v2.x
- v1.10.2 -> Development
- Updated PRs to new branch names

Changes left to do
- Change the default branch to Development
- Delete master
- v1.x -> master
- Set master to the default branch
- Delete v1.10.2

**Comment by hopeseekr** [comment]
I totally feel like I inspired this!

Thanks!
