### ISSUE TITLE
Cursor gets stuck off screen on Windows server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6479]
### Operating Systems ###

Windows 10 on both

### Synergy Version ###

v1.10.1

### Steps to reproduce bug ###

1. Move mouse off server screen
2. See that mouse doesn't appear on client
3. Unable to move mouse back to server

**Comment by nyetwurk** [comment]
Affects 1.9.1 as well

**Comment by nyetwurk** [comment]
Affects 1.10.2 as well

**Comment by Jnewbon** [comment]
Duplicate of #5294
