### ISSUE TITLE
Enterprise build RPM header has incorrect name

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6480]
### Operating Systems ###

RHEL

### Synergy Version ###

1.10.x

### Steps to reproduce bug ###

1. Install enterprise build v1.10.x on RHEL

Expected: Package should identify as `synergy-enterprise`
Actual: Installed package identifies as `synergy`

### Other info ###

An enterprise customer depends on the package being called `synergy-enterprise` for a deployment script. Pre-v1.10.x the enterprise package was called `synergy-enterprise` but this was omitted in the non-enterprise/enterprise code merge.

**Comment by andreacndn** [comment]
A fix for this issue is not needed anymore
