### ISSUE TITLE
synergy fails to run as server on Fedora 30

### ISSUE THREAD

**Issue by adatum** [symless/synergy-core#6491]
Fedora 30 MATE
synergy-2.0.0-5.fc30.src.rpm

Synergy shows an error message when launched:

> Failed to get local IP address. Please manually type in server address on your clients

The terminal shows:

> QMetaObject::connectSlotsByName: No matching signal for on_windowShown()
> *** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
> *** WARNING *** Please fix your application to use the native API of Avahi!
> *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
> ("-f", "--debug", "INFO", "--name", "[HOSTNAME]", "-c", "/tmp/qt_temp.J10639", "--address", ":24800")

The last line repeats every second, though the name (last 6 characters) of the temp file change. That temp file contains synergy option settings.

I tried turning off firewalld but it did not help.

**Comment by adatum** [comment]
I found my previous settings are pulled from `~/.config/Synergy/Synergy.conf`. I removed that conf file to reconfigure synergy as though it is starting for the first time.

I still get the "failed to get local IP address" but at least now the GUI interface shows up. 

However synergy keeps auto restarting every second. The log shows:

```
[2019-05-04T18:37:49] INFO: starting server
[2019-05-04T18:37:49] INFO: config file: /tmp/qt_temp.Ni1524
[2019-05-04T18:37:49] INFO: log level: INFO
warning: synergys is deprecated. instead, use: synergy-core --server
synergys: no configuration available
[2019-05-04T18:37:49] WARNING: failed to set process uid to: -1
[2019-05-04T18:37:49] ERROR: process exited with error code: 4
[2019-05-04T18:37:49] INFO: detected process not running, auto restarting
[2019-05-04T18:37:50] INFO: starting server
[2019-05-04T18:37:50] INFO: config file: /tmp/qt_temp.Pi1524
[2019-05-04T18:37:50] INFO: log level: INFO
warning: synergys is deprecated. instead, use: synergy-core --server
synergys: no configuration available
[2019-05-04T18:37:50] WARNING: failed to set process uid to: -1
[2019-05-04T18:37:50] ERROR: process exited with error code: 4
```

**Comment by adatum** [comment]
More info:

* synergy runs fine as client, but not as server as seen in the above errors in the log output
* synergy's tray icon is not working correctly in MATE, left clicks on it do nothing, right click brings a menu with one entry, but there is no text
* not sure if it matters, but I have multiple network interfaces such as ethernet, wireless, virtualbox, docker, etc

**Comment by Jnewbon** [comment]
I have just looked into this one the package synergy-2.0.0-5.fc30.src.rpm is not built by us but by the Fedora project. After looking at the spec file they are using it seems that they are jerry-rigging the v2 synergy-core with v1.8.8 GUI. There was quite a lot of functionality changes between these versions so I would expect there to be bugs as a result of the jerry-rigging other than existing known bugs.

We can't guarantee support for problems that may occur as a result of the jerry-rigging. I will, however, try my best to add a Fedora build to our CI environment so there is a supported version for you to use in the next release.

**Comment by adatum** [comment]
Thanks @Jnewbon. Supporting Fedora in future releases would be appreciated.

With your knowledge of synergy, would you consider pointing out the issues with the packaging of synergy-2.0.0-5.fc30.src.rpm in a bug report? https://apps.fedoraproject.org/packages/synergy/bugs/

That might be the most expedient way by solving any potential issue at its source.

**Comment by adatum** [comment]
I can confirm the issue on GNOME Shell too, not just MATE. 

I also compiled synergy 2.0.0 from source and it still has the issue.

Compiling synergy 1.10.2 works.

Specifically, the error happens after adding a client screen from the "Configure Server..." window while in server mode, and applying the change.

**Comment by daobrien** [comment]
Just FYI I installed synergy-1.10.2-1.fc31.x86_64.rpm on F30 and it works fine. I love synergy and hope it keeps going.

**Comment by adatum** [comment]
I noticed that F31 has synergy-1.10.2-1.fc31 available in the main repository.

Running compiled synergy 1.10.3-stable has been working well for me.

**Comment by sevmartinezjr1** [comment]
It seems as though the package fails to create a proper configuration to be used. I was able to get it to work after trial and error please see the information below.

--conf start
section: screens
	servername.local:
	clientname.local:
end

section: aliases
end

section: links
	servername.local:
		right = clientname.local
	clientname.local:
		left = clientname.local
end

section: options
	relativeMouseMoves = false
	screenSaverSync = true
	win32KeepForeground = false
	clipboardSharing = true
	switchCorners = none 
	switchCornerSize = 0
end
---conf end

I am able to properly use the Synergy package that is installed via dnf on Fedora 30 with this configuration.

**Comment by sevmartinezjr1** [comment]
Also, agreed synergy is great product.
