### ISSUE TITLE
Retry timer isn't stopped or unregistered properly

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6495]
@smejkar #6077
> While investigating another timer related issue I have encountered that ServerApp::stopRetryTimer does not unregister the event handler for the retry timer. Note stopRetryTimer attempts to unregister an event handler for target NULL by calling m_events->removeHandler(Event::kTimer, NULL). This actually unregisters nothing.
> 
> This should be addressed as the event queue refers to the event handler for deleted retry timer.

**Comment by nbolton** [comment]
@Jnewbon This issue needs a more useful title. What is the effect of the retry timer not being unregistered? What problem does it solve?

**Comment by nbolton** [comment]
@smejkar @Jnewbon This issue needs a more useful title. What is the effect of the retry timer not being unregistered? What problem does it solve?
