### ISSUE TITLE
 ipc connection error, connection refused, after uninstalling synergy

### ISSUE THREAD

**Issue by dank92** [symless/synergy-core#6508]
Windows 10

Server: Windows 10 
Client: Windows 10 

Synergy ver. 1.10.2

1.setup Compiling for Desktop QT 5.9.5 MSVS2017 64bit (https://github.com/symless/synergy-core/wiki/Compiling)
2. install pre-compile synergy 1.10.2 win 10 64-bit (https://symless.com/synergy/downloads/list/s1)
3. uninstall pre-compiled synergy 1.10.2 
4. run synergy from qt
5. attempt to run server

Expected: synergy that is compiled should still work 
Actual: getting error:  ipc connection error

I believe installing/uninstalling pre-compiled synergy has removed synergy as a service, similar to #3514. Is there a way to re-install the synergyd.exe service without using the pre-compiled installer?
 

Log:
https://paste.ee/p/BDsOS

**Comment by Jnewbon** [comment]
If you uninstalled synergy from the system the Service no longer runs, so when running from source you have to manually run synergyd with the -f argument before starting synergy.

**Comment by dank92** [comment]
Thanks that worked!
