### ISSUE TITLE
Make client's input languages independant from server

### ISSUE THREAD

**Issue by claude-ws01** [symless/synergy-core#6510]
Synergy v1.10.2
Server: win7pro; Client: win7ultimate

### Problem ###

Languages used on client must me installed on the server. Also, every time I need to use a language in the client, I have to set it in the server. This makes it impossible to work in 2 languages (server & client) at the same time.

(edit) 
CLARIFICATION:
Synergy is not using the keyboard layout of the client while typing in the client; it's using the server's keyboard layout.

### Solution ###

transmit keys, not chars, to the client.  And pass the keys through the keyboard layout on the client. 

### more infos ###
Switching input language with window's hotkeys, through Synergy while on the client, does change the keyboard layout on the client, and typing on the client's physical keyboard I will get the chosen language, but typing through Synergy I will not get the chosen language.

I might as well put a keyboard on the client machine!!! It does defeat the purpose of Synergy, no?

-----------------

thank you
C.

**Comment by samuelwalton** [comment]
So what you are saying is that synergy is not replicating the correct language?

**Comment by claude-ws01** [comment]
> So what you are saying is that synergy is not replicating the correct language?
That is one way of putting it. Yes.
To simplify my request: Make synergy use the keyboard layout of the client (not the server's) while typing in the client.
Does that clarify my request?

**Comment by J-Siu** [comment]
This should be a bug, not enhancement. Let me try to clarify more.

Client and server both MacOS 10.14.6. Both configured to have Sucheng and U.S. input.

On server if my input method is U.S.
    I move my mouse to client, switch between U.S. and Sucheng on client and can type correctly.
On server if my input method is Sucheng
    I move my mouse to client, no matter which input method I use, I cannot type anything.

**Comment by claude-ws01** [comment]
> This should be a bug, not enhancement. Let me try to clarify more.

I agree. 
BTW, I'm not the one who labeled it as "enhancement".
regards

**Comment by AnrDaemon** [comment]
I'd very much like Synergy to stop even trying to touch keyboard layout.
I'm tired of having same layout for all client windows and inability to change keyboard layout for more than a few typed characters.

In my case it's Win10+Win7. Each can be client and server, same issue in either combination.
In order to type text in more than one language I have to 

1. Return to server screen.
2. Change language.
3. Go to client screen.
4. Type a few words.
5. Rinse.
6. Repeat.

**Comment by fiftin** [comment]
@Jnewbon, @nbolton Why you can't implement switching server's keyboard layout when cursor on the client?

**Comment by AnrDaemon** [comment]
Why this is even necessary to begin with?
To what language you are going to switch, if server don't have any of the client languages/keyboard layouts? What if they are different OS's?

**Comment by fiftin** [comment]
I think subject hard to implement. 
But switching keyboard layout on the server can be implemented very easy - just don't forward Ctrl+Shift/Ctrl+Space/... to the client.

**Comment by fiftin** [comment]
I think current implementation of the hotkeys can be extended with option - "Do not forward". In this case user can fix Ctrl+Shift/Ctrl+Space/... on the server.

**Comment by fiftin** [comment]
Sorry, it should works like you say, this bug from 2015: https://github.com/symless/synergy-core/issues/4309

**Comment by AnrDaemon** [comment]
Good find, thank you.
