### ISSUE TITLE
How to generate installer exe after build and run standalone (windows)

### ISSUE THREAD

**Issue by danilofuchs** [symless/synergy-core#6511]
I don't know how to generate the executable for `synergy-core` on Windows. I followed all the steps in [the compiling guide](https://github.com/symless/synergy-core/wiki/Compiling).

I WAS able to run it in debug / release mode, through Qt Creator, but was not able to create the `installer.exe`. I believe I need to use WiX, but the current docs don't mention it.

When running `synergy.exe` directly, I am greeted with an error message saying Qt5Network.dll wasn't found.

### Operating Systems ###
Windows 10 64-bit
Visual Studio 2017 15.9.12
Qt Creator 4.9.1
Qt 5.12.3
Compiler: MSVC2017_64bit

### Synergy Version ###
1.10.2-stable

**Comment by Jnewbon** [comment]
Yeah there are 6 dlls that need copying to the build output dir on windows as its not done automatically. 
synergy-core/ext/openssl/windows/x64/bin/*
And 
{QtInstallDir}/{Version}/MSVC2017_64bit/bin/
- Qt5Core.dll
- Qt5Gui.dll
- Qt5Network.dll
-Qt5Widgets.dll
For release, Debug requires the *d.dll versions

**Comment by danilofuchs** [comment]
That worked perfectly to run `synergy.exe`, thanks!
Are there any extra steps needed to bundle it into an installer or should I set it up by myself?

I'm willing to make a PR documenting the steps you mentioned, just let me know if I should add anything else.

**Comment by danilofuchs** [comment]
https://github.com/symless/synergy-core/wiki/Compiling/99674600814436a3ff8e0c4842d0777657b02c75

I did some changes to the documentation. If you feel like it should be moved to another section or the FAQ, let me know.
