### ISSUE TITLE
Synergy does not send AltGr Linux to Windows if EN US layout is not first

### ISSUE THREAD

**Issue by AstralStorm** [symless/synergy-core#6512]
### Operating Systems ###

Server: Ubuntu Linux 18.04.2 LTS with MATE, latest updates as of posting.
Client: Windows 7 SP 1 Enterprise, latest updates.

### Synergy Version ###

Tested with 1.8.8 and 1.10.2, matching on both client and server.

### Steps to Reproduce ###

Set up keyboard layouts so that EN US (plain, non-intl.) layout is not listed as first, another international layout (EN US intl, Polish tested) is also added.

If EN US plain layout is not set as first, AltGr/ISO Level 3 Shift is not sent to Windows or is received as a wrong key that does not produce diacritics.

If EN US is set as first layout, then any other international layout works fine and passing AltGr/ISO Level 3 Shift to Windows works correctly. EN US does not have to be the active layout, whatever is set in Windows is used.

Keyboard type does not affect it, any from 101 through 105 intl. behaves the same.

Tool used to set up the layouts was MATE desktop keyboard configuration.

**Comment by bond-os** [comment]
The same happens on macos 10.14 as client to ubuntu 18.04 with kde when keyboard is not set to us; must add altgr = shift to configuration file.

**Comment by oscarholst** [comment]
If this is the case also bugging with the "ÅÄÖ" and other diacrit letters, if so, any status or update from the developers if/when this is going to be prioritized?
