### ISSUE TITLE
cursor can work but keyboard doesn't work

### ISSUE THREAD

**Issue by ericlee1994** [symless/synergy-core#6513]
2 mac both 10.14.5
synergy : 1.10.0 stable
So the cursor can work very well, but when use keyboard, the client can't printout, i find the key such as "shift" , "f1", "f2"...can work, but character such as "a" "b" "c" , it can't work。Both macs have the same input method。
 I have try to reinstall the software and recheck the setting in Security and Privacy, but it's unhelpful. 
Sorry for my poor English， i hope you can understand what i mean.

**Comment by xingchenxuanfeng** [comment]
I got the same problem.

Synergy print this log:

2019-07-05 10:03:53.298 synergys[13131:143425] pid(13131)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!

**Comment by ericlee1994** [comment]
> I got the same problem.
> 
> Synergy print this log:
> 
> 2019-07-05 10:03:53.298 synergys[13131:143425] pid(13131)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!

haha, I have solved the problem, because i delete the "ABC Keyboard". When i add it in keyboard setting and restart my mac, it's work!
