### ISSUE TITLE
Client incompatible with UE4Editor

### ISSUE THREAD

**Issue by photex** [symless/synergy-core#6515]
Server: Windows 10
Client: Ubuntu 18.04

Server: 1.10.1-stable-8941241e
Client: 1.8.8, protocol version 1.6

1. Run Synergy server on a windows machine
2. Configure Linux machine as Synergy client
3. Build UE4
4. Run the editor and create a new empty project
5. Interact with the viewport (middle mouse click and drag) and watch everything go horribly horribly wrong.

Expected: I would like to use synergy and also interact with the UE4 editor.
Actual: Impossible camera interaction in the viewport.

**Comment by deanranderson** [comment]
Enabling "Lock to Screen" is a work-around that I use.
