### ISSUE TITLE
Key combination that will force a server restart

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6518]
### Problem ###

There are situations where a server and client may have problems, like the cursor stuck in a location, etc. where the user is not easily able to restart synergy and reconnect quickly.

### Solution ###

Having the ability to press a key combination that will force the server to terminate all current connections and allow all clients to reconnect. All clients will automatically attempt to reconnect once the connection is lost to the server.

**Comment by pythlang** [comment]
I actually kill all in htop or activity monitor... I have become quite good at it.

**Comment by nbolton** [comment]
https://github.com/symless/synergy-core/pull/6574

**Comment by Jnewbon** [comment]
A release candidate is available that incorporates a fix for this issue

[Download v1.11.0-rc2](https://snapshots.symless.com/public/1.11.0-rc2?github#6518)

If you find any bugs in the release candidate related to this issue please comment here.
