### ISSUE TITLE
Compiling error on CentOS 7

### ISSUE THREAD

**Issue by MovieSong** [symless/synergy-core#6532]
### Operating Systems ###

Server: CentOS 7

Compiling Error:

In file included from /home/rd/synergy-core-master/src/gui/src/ZeroconfBrowser.cpp:18:0:
/home/rd/synergy-core-master/src/gui/src/ZeroconfBrowser.h:25:20: 致命错误：dns_sd.h：没有那个文件或目录
 #include <dns_sd.h>
                    ^
编译中断。
make[2]: *** [src/gui/CMakeFiles/synergy.dir/src/ZeroconfBrowser.cpp.o] 错误 1
make[1]: *** [src/gui/CMakeFiles/synergy.dir/all] 错误 2
make: *** [all] 错误 2

Where can I download dns_sd.h?

Thanks!

**Comment by Jnewbon** [comment]
Hi @MovieSong 

That should be provided by the package libavahi-compat-libdnssd-dev

Jamie
