### ISSUE TITLE
Bluetooth emulation

### ISSUE THREAD

**Issue by ahmadie** [symless/synergy-core#6533]
I would like synergy to have Bluetooth support, which can be done through HID Bluetooth, with this client does not need to install software, only server side software is needed. There is a software called across from Clixon which can share inputs through both Bluetooth and WiFi. In Bluetooth mode client need only to pair with the server.

**Comment by magillus** [comment]
I thought about same thing, I would like to use Samsung Dex desktop with my synergy keyboard.

HID Bluetooth device to control and connects to network as a Synergy Client. 
Quick google points to: https://www.instructables.com/id/3-Bluetooth-HID-Module-HC05-With-RN42-Firmware/
that combined with some Wifi enabled microcontroller might work out.

**Comment by TobiaszCudnik** [comment]
I agree, this would be a very useful feature - having synergy to operate as a regular bluetooth keyboard & mouse (a BT HID device).

@magillus TCP and network wouldnt be involved at all. Everything would take place on the host computer, then using the host's bluetooth device it would do one-way communication with the client.

Use case: control iOS without installing anything on the client.

Similar project: https://acrosscenter.com/ Cons: paid, low quality, no stable linux support (ATM).

Im currently using a workaround in the form of a hardware switch (usb splitter) to achieve the same result. Good code reference for creating a BT HID (win, nix) can be taken from the [Gimx project](https://github.com/matlo/GIMX).

**Comment by drwonky** [comment]
Bluetooth or keyboard/mouse emulation would be much appreciated for environments where the VPN prevents local network access.  Using a Raspberry pi as an interposer would be a viable cross-platform solution.  The Zero series can act as USB gadgets, so connecting as a USB HID device to the computer you want to control, then have the Rpi connect to synergy over the Wifi interface.  The Rpi4 also has USB gadget capability, so rpi4, zero2W and zeroW would be usable choices.

**Comment by drwonky** [comment]
Bump, any plans to try and emulate BT?
