### ISSUE TITLE
Super key gets captured by gnome3

### ISSUE THREAD

**Issue by antonae** [symless/synergy-core#6537]
... and key not sent to clients.

Hi,

I just updated to gnome 3.30.2 (new Debian 10 installation) and synergy can not transfer super key to clients, as it seems it is 'captured' by gnome (displays the window switch dialog). With my prior setup (gnome 3.22.1) everything worked fine. 

Same happens with Alt key, and apparently any combination used by gnome.

Thanks,

Anton

**Comment by VeNoMouS** [comment]
Experiencing the same thing, and frankly this should have been fixed LONG ago....

@nbolton can you weigh on this please...

super / meta / windows key ... what ever you wish to call it, is not sent to windows even though you are on a windows screen , key is sent to gnome (server) instead

the same action is repeatable with alt tab..

**Comment by VeNoMouS** [comment]
Status update please?

**Comment by VeNoMouS** [comment]
The issue is wayland btw not gnome3.

**Comment by VeNoMouS** [comment]
The issue is wayland btw not gnome3.

@antonae to get around this, on the login screen for Xorg... at the password section of your login, switch to __gnome xorg__ instead of __gnome__ via the gear setting near cancel, you'll get your super keys etc back

**Comment by antonae** [comment]
@VeNoMouS tx, will try :)

**Comment by Necktwi** [comment]
thanks! it works in xorg, i hope it'll be fixed in wayland.

**Comment by VeNoMouS** [comment]
Wayland disabled access to the super key on purpose etc... , i cant see it being fixed without some sort of work around.
