### ISSUE TITLE
Mouse some time hang up in remote screen while selecting text

### ISSUE THREAD

**Issue by AlexeyPilya** [symless/synergy-core#6543]
### Operating Systems ###

Server : Windows 10 (1809)
Client : Ubuntu 18.04

### Synergy Version ###

1.10.3-rc1-ba9e83b7

### Extra Info ###

The customer informed us in slack channel: Does anyone found that the mouse some time hang up in remote screen while selecting text.  and take a few seconds to recover.

**Comment by Jnewbon** [comment]
Probable duplicate of #6481
