### ISSUE TITLE
world spins in minecraft with slightest movement

### ISSUE THREAD

**Issue by dogmatic69** [symless/synergy-core#6545]
### Operating Systems ###

---BEGIN HELP---
Server: Ubuntu 18.04
Client: Windows 8

### Synergy Version ###

synergys 1.10.0, protocol version 1.6

### Steps to Reproduce ###

1. Open latest minecraft on windows client
2. mouse works fine in menus
3. start game and things go crazy

Expected: Game should be playable
Actual: Player spins round with the slightest movement. Can only look at the sky or ground.

**Comment by nathan818fr** [comment]
You should lock your mouse on the current screen when you use applications that grab the cursor.
By default the shortcut is the <scroll lock> key on synergy 1.

**Comment by dogmatic69** [comment]
> By default the shortcut is the key on synergy 1.

Could you elaborate, what key?

**Comment by nathan818fr** [comment]
Oops, I've put the name between &lt; and &gt; so it was hidden... It's the "scroll lock" key.

**Comment by nathan818fr** [comment]
You can change that key by manually editing your synergy text config like:
```
section: options
	keystroke(F4) = lockCursorToScreen(toggle)
end
```
(here it's the F4 key which lock the cursor to the current screen instead of ScrollLock)

More info here: https://github.com/symless/synergy-core/wiki/Text-Config

**Comment by dogmatic69** [comment]
Thanks, `scroll lock` works :+1:
