### ISSUE TITLE
wayland support for synergy v1

### ISSUE THREAD

**Issue by modernNeo** [symless/synergy-core#6558]
I just did an upgrade on my ThinkPad from Debian 9 to 10 and lo and behold, it resulted in an issue with my synergy v1 [mouse wont actually show up on the debian client]. did some googling and came across https://github.com/symless/synergy-core/issues/5803 which then lead me to https://github.com/symless/synergy-core/issues/4090 where it seems that @nbolton made the final word that wayland support would be coming to synergy v2.1. 

However, I once had v2 and [no disrepect to the devs who I am sure are working thier hardest but] it was a nighmare to get working on my arch [iirc, some issue with X11 compatibilty] so I would rather not touch that again until its at least out of beta mode. So, will waylang support not be brought to v1? Or will it and I just was not able to find anything online that stated as much?

**Comment by nbolton** [comment]
Hi there, we do plan on adding Wayland support to the next major version. https://github.com/symless/synergy-core/issues/4090

**Comment by nbolton** [comment]
Fixed by: https://github.com/symless/synergy/pull/7449
