### ISSUE TITLE
Mouse speed is different on MacOS and Ubuntu with same DPI

### ISSUE THREAD

**Issue by upgle** [symless/synergy-core#6560]
### Operating Systems ###

Server: macOS Mojave 10.14.5(18F132) (U2718Q 4K, 3840x2160, 150% scale)
Client: Ubuntu 19.04  (U2718Q 4K, 3840x2160, 150% scale)

### Synergy Version ###
- Synergy 1 Pro
- 1.10.3-stable-ca35737a

### Steps to Reproduce ###

1. Set up macOS server (3840x2160, 150% scaling, Looks like 2560x1440)
2. Set up ubuntu 19.04 (3840x2160, 150% scaling)
3. Move mouse macOS server to ubuntu client
4. Mouse speed on the ubuntu is slower than macOS

**Comment by Bogidon** [comment]
Also experiencing this between macOS server and Windows client. Why not give users an option to adjust tracking speed on each client?

**Comment by upgle** [comment]
I agree with you. It would be more convenient to provide an option to adjust tracking speed for various resolutions.

**Comment by svaningelgem** [comment]
afaik this is still open
