### ISSUE TITLE
Service start error on Windows

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6575]
### Operating Systems ###

Windows 10

### Synergy Version ###

1.10.3

### Steps to Reproduce ###

1. Install
2. See service error

> Service "Synergy" (synergy) failed to start. Verify that you have sufficient privileges to start system services.

### Extra Info ###

Installing the [latest VC redist](https://support.microsoft.com/en-ph/help/2977003/the-latest-supported-visual-c-downloads) seems to solve the issue. Perhaps the installer isn't including the latest redist? See forum posts for more detail.

https://members.symless.com/forums/topic/6321-service-start-error-on-windows/
https://members.symless.com/forums/topic/6316-upgrade-to-1103-has-broken-my-installation/

**Comment by Jnewbon** [comment]
A release candidate is available that incorporates a fix for this issue

[Download v1.11.0-rc2](https://snapshots.symless.com/public/1.11.0-rc2?github#6575)

If you find any bugs in the release candidate related to this issue please comment here.
