### ISSUE TITLE
end button has the same effect as page down

### ISSUE THREAD

**Issue by pryorda** [symless/synergy-core#6576]
### Operating Systems ###

Server: Windows
Client: mac 10.x

### Synergy Version ###

1.10.3

### Steps to Reproduce ###

Press end in document, or a text field.

**Comment by Jnewbon** [comment]
Macs don't have a Home or End keys. the function is reached by pressing Fn + Left/Right. Which scrolls to the start/end of a scrollable document.

I know i have been caught out by tapping home in a text field or terminal only for it to scroll up miles.When i asked a Mac user they said this was normal. 

The keys to press to jump to start of line is Command + Left and Command + Right to jump to end of line.

If I'm wrong or misinformed, please do comment here.

**Comment by pryorda** [comment]
Good to know. I can probably mask the keys. 

Thanks
