### ISSUE TITLE
about version is 1.10.3 error

### ISSUE THREAD

**Issue by Iven-hoo** [symless/synergy-core#6581]
this is my error message:

ERROR: process exited with error code: 4
INFO: detected process not running, auto restarting
INFO: starting server
INFO: config file: /var/folders/tj/5hyjmwt95qvfpj0_z3g5_sfr0000gn/T/Synergy.I20710
INFO: log level: INFO
INFO: drag and drop enabled
ERROR: cannot read configuration "/var/folders/tj/5hyjmwt95qvfpj0_z3g5_sfr0000gn/T/Synergy.H20710": read error: line 9: invalid character 0xffffffe6
synergys: no configuration available

excuse me     What is the reason for this problem

**Comment by Iven-hoo** [comment]
my system mac pro

**Comment by Jnewbon** [comment]
Looks like there is an error in the config, try opening the file it links to and seeing what's on line 9.

**Comment by Iven-hoo** [comment]
> Looks like there is an error in the config, try opening the file it links to and seeing what's on line 9.

thank you very much，The question is really on line 9  ，There is a new host information I added, indicating that it is in command status. I can manually change it to the client name.
