### ISSUE TITLE
bad CPU type in executable: /Applications/Synergy.app/Contents/MacOS/synergys

### ISSUE THREAD

**Issue by orchief** [symless/synergy-core#6585]

**Comment by Jnewbon** [comment]
Closed due to not enough information provided.

Please try to provide as much information as to what caused the bug and how to reproduce it, Eg
- OS Verison
- Synergy version
- Hardware details, Like CPU architecture.
- When the error occurred and steps to reproduce the error

**Comment by territorial** [comment]
I'm getting this error after upgrade to macOs Catalina 10.15.1 

Synergy Version: 1.8.8

MacBook Pro (Retina, 15-inch, Late 2013)
Model Identifier:	MacBookPro11,2
Processor Name:	Quad-Core Intel Core i7
Processor Speed:	2 GHz
Number of Processors:	1
Total Number of Cores:	4
L2 Cache (per Core):	256 KB
L3 Cache:	6 MB
Hyper-Threading Technology:	Enabled
Memory:	8 GB

**Comment by Jnewbon** [comment]
The only version of Synergy currently passing notarization process which is required on Catalina is 1.10.3+ 

Could you try installing that version?
