### ISSUE TITLE
Version number header with update check

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6588]
### Problem ###

The version check request doesn't include a current version header, meaning that the version request server log is missing version numbers.

### Solution ###

Add a header to the version check call.

**Comment by Jnewbon** [comment]
A release candidate is available that incorporates a fix for this issue

[Download v1.11.0-rc2](https://snapshots.symless.com/public/1.11.0-rc2?github#6588)

If you find any bugs in the release candidate related to this issue please comment here.
