### ISSUE TITLE
Bug \ typo in wiki page on Mac launch on boot instructions

### ISSUE THREAD

**Issue by PaluMacil** [symless/synergy-core#6594]
### Operating Systems ###

---BEGIN HELP---

OS not relevant. This is a bug \ typo in wiki which is obscuring meaning of key parts of documentation (but to comply, I run the server on Ubuntu Desktop 18.04 and the client is MacOS).

---END HELP---

### Synergy Version ###

---BEGIN HELP---

live version of wiki, page https://github.com/symless/synergy-core/wiki/Running-Synergy-at-startup-on-MacOS

---END HELP---

### Steps to Reproduce ###

---BEGIN HELP---

Lots of key details are replaced with the word "please" in brackets, omitting the actual words that are needed to understand the instructions: https://github.com/symless/synergy-core/wiki/Running-Synergy-at-startup-on-MacOS

---END HELP---

### Log URLs ###

# README & DELETE #

---BEGIN HELP---

https://github.com/symless/synergy-core/wiki/Running-Synergy-at-startup-on-MacOS

---END HELP---

### Extra Info ###

# README & DELETE #

---BEGIN HELP---

no further details

---END HELP---

**Comment by nbolton** [comment]
Hi there, the wiki is publicly editable.

**Comment by PaluMacil** [comment]
@nbolton Wait, are you saying that as the CEO you don't know the answer to these questions or even have employees that do? I checked the history on the pages, so I know the answer isn't there. Do you just not support Mac anymore? Or are you saying supporting Mac on boot is only community supported and not supported by your company?

**Comment by PaluMacil** [comment]
Now was the article deleted? I thought it was better than nothing. Not being able to run a mouse and keyboard on boot defeats the purpose of having this tool in the first place.
