### ISSUE TITLE
Build break on Mac when CMAKE_OSX_SYSROOT undefined

### ISSUE THREAD

**Issue by ethouris** [symless/synergy-core#6597]
### Operating Systems ###

macOS 10.12.6

### Synergy Version ###

Latest commit 52c3337 on 8 Oct

### Steps to Reproduce ###

1. Enter repo root dir
2. Type `cmake .`
3. Type `make`

Result:

Compile error: file not found at: `#include <assert.h>`.

Reason:

The `--sysroot` option passed to the compiler command is not followed by an argument, at least the `-Dsomething` cannot be a valid argument for this option.

This is because `CMAKE_OSX_SYSROOT` variable was empty and so it resulted with an empty option value.

To fix:

Before adding the `--sysroot` option, check if `CMAKE_OSX_SYSROOT` is defined first.

**Comment by Jnewbon** [comment]
Isn't this already in the compiling guide?

https://github.com/symless/synergy-core/wiki/Compiling#macos-post-cmake

**Comment by ethouris** [comment]
Ok, I understand that maybe you have added this to the compile guide, but why should the user explicitly define this `CMAKE_OSX_SYSROOT` to a value that is a long string to copy and paste and it likely looks exactly the same on every system, and moreover, if you simply skip the `--sysroot` option, everything still works?

If you simply make the `CMAKE_OSX_SYSROOT` optional - as predicted for cases when users have multiple SDKs or possibly do crosscompiling - it should work.

Moreover, according to what is written in the cmake documentation, this variable will be used to correctly set up the `-isysroot` option for the compiler, so I moreover don't understand why this option is here used manually.
