### ISSUE TITLE
Missing caret in IntelliJ IDEA after switching apps using Barrier

### ISSUE THREAD

**Issue by mrog** [symless/synergy-core#6598]
### Operating Systems ###
Server: Ubuntu 18.04.3
Client: macOS Catalina 10.15.1

### Synergy Version ###
Both computers are running Synergry 1.11.0-rc2

### Steps to Reproduce ###
1. Run IntelliJ IDEA on the Mac. https://www.jetbrains.com/idea/download/#section=mac
2. Open a couple of files in different tabs in IDEA.
3. Click in another application window to make that app active.
4. Click in one of the IDEA editor panes. Note that you can select text in the editor pane, but you don't get a caret and you can't type in the pane.

Note that selecting a different file tab in IDEA restores the caret and allows typing in the pane.

Also note that if you use the Mac's mouse to click the editor pane in step 4, a caret appears and the user can type normally. The issue is only seen if the mouse click is coming from the server machine via Synergy.

### Extra Info ###
* Are there any workarounds? Yes, but switching editor tabs every time I change the focus between apps is a pain.
* Does it stop you using Synergy entirely? No
* Did restarting Synergy or the computer help? No
* This doesn't happen with Synergy 2.0.12-beta.  It must have been fixed in one of the 2.x versions.  It would be great to get that same fix into 1.x.

**Comment by nickescobedo** [comment]
This same issue happened with me another app called SoapUI, but also happening in PhpStorm for me.

**Comment by dsringari** [comment]
Server: Windows 10
Client: macOS Catalina 10.15.2

I'm also seeing this issue. In fact, this issue appears in many java based applications including Netbeans. When I switch focus away, and use the server's mouse to bring focus back to IntelliJ (clicking inside the text editor), the caret disappears and any click with the client/server's mouse does nothing to fix it. 

If I bring focus back with the client's mouse, everything behaves normally.

**Comment by Sexual** [comment]
Experiencing this as well.

Server: Windows 10
Client: MacOS Catalina 10.15.2 Beta

**Comment by spronkey** [comment]
I too believe this is a copy of #6331 and it is something I've experienced with Synergy from time to time over the years with several apps, from what I can remember they are mostly Java-based such as Netbeans.

Whatever has changed in recent versions of IntelliJ/PHPStorm/Synergy though has caused this problem to be essentially permanent - clicks just aren't registering. I almost wonder whether these apps are doing something e.g. detecting mousedown then mouse up, and eliminating pairs that happen quicker than some threshold, which programmatic clicks may.

**Comment by dstutzman1** [comment]
I'm also experiencing this issue, using Jetbrains WebStorm 2019.3.2 on macOS 10.14.6, sharing from a Windows 10 PC.

This issue was also submitted to the JetBrains bug tracker: https://youtrack.jetbrains.com/issue/IDEA-215477

Further discussion can be found on the Synergy forums: https://members.symless.com/forums/topic/2171-keyboard-input-sometimes-ignored-for-some-java-programs/

**Comment by atomsfat** [comment]
I have the same problem, using intellij 2020.1 on macOS 10.15.4, sharing from windows 10 pc.

**Comment by dstutzman-nt** [comment]
Looks like this was fixed in WebStorm 2020.2.3, which was just released today.
