### ISSUE TITLE
Support for CentOS 8 (also CentOS 8 Stream

### ISSUE THREAD

**Issue by nfunke** [symless/synergy-core#6600]
I re-imaged my old machine, which was a CentOS 7, where Synergy worked fine. The new version I use is on CentOS 8. But I cannot find any download for that version.

Is support for CentOS 8 in the works?

**Comment by niemann8r** [comment]
I tried downloading for CentOS 8, and I got it to run successfully. I had to install a new package that Yum was yelling at me about: 

https://centos.pkgs.org/8/centos-powertools-x86_64/avahi-compat-libdns_sd-0.7-19.el8.x86_64.rpm.html

After this I could get the binary installed. There's a small issue where the mouse isn't reading... probably 'cause it isn't officially supported yet.

**Comment by lbrigman124** [comment]
It seems that Synergy is using a library call that is no longer supported. 
I found this in my messages file as I was debugging the same issue.
`synergy.desktop[23773]: *** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
synergy.desktop[23773]: *** WARNING *** Please fix your application to use the native API of Avahi!
synergy.desktop[23773]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
`
