### ISSUE TITLE
Documentation (man page) for synergyc missing --enable-crypto option

### ISSUE THREAD

**Issue by hmedway** [symless/synergy-core#6601]
Even if it's a paid only feature, the feature is still there isn't it? I'm currently using 1.10.2 from the fedora repos with my subscription key. The option is available, but not documented in the man page for synergyc.

Let me know if I'm barking up the wrong tree here, but it should be there even if there is an accompanying note mentioning that it's a paid feature.

**Comment by Jnewbon** [comment]
That's correct, I can't speak for the package in the fedora repositories, but if it was built from this git without modification then it will be there. 

It just needs a license key to work.

**Comment by Jnewbon** [comment]
Clicked the close button instead of just comment :)
