### ISSUE TITLE
Warning: Failed to set process uid to -1

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [symless/synergy-core#6603]
### Operating Systems ###

Server: Ubuntu 18.04
Client: N/A

### Synergy Version ###

Synergy Version v2.0.0-stable 

### Steps to Reproduce ###

1. Build Synergy 2.0.0 from git.
2. Run Synergy as any user but root.

Expected: Clean Run with success
Actual: Runs and then silently fails with code 0 and a warning about setuid

## Extra Information ##

I believe that this may be an ongoing issue looking at the logs posted by other users (for example if you look at the log files of #6491 you can see he gets the same warning). Unless you are supposed to run this application as root, the usage of setuid() will always fail. 

This is a chunk from line 182 in App.cpp that uses the setuid function:

```
if (!argsBase().m_runAsUid != -1) {
        if (setuid(argsBase().m_runAsUid) == 0) {
            LOG((CLOG_DEBUG "process uid was set to: %d", argsBase().m_runAsUid));
        }
        else {
            LOG((CLOG_WARN "failed to set process uid to: %d", argsBase().m_runAsUid));
        }
    }
```

**Comment by francoisjacques** [comment]
similar behavior under funtoo linux

**Comment by alexfornuto** [comment]
Same using Fedora 30

**Comment by YikeStone** [comment]
Similar under Gentoo. Is there any workaround?

**Comment by devwhjeon** [comment]
What's the status of this issue?
I'm using Gentoo Linux && Windows 10.
Gentoo gives same error.
[ver info.]
Gentoo: 2.0.0
Win10: 2.0.12-beta

**Comment by Nathan-Nesbitt** [comment]
@devwhjeon Unfortunately no input ATM!

**Comment by yovelas** [comment]
Same in ubuntu 20
