### ISSUE TITLE
Debian 10 client/server connected but mouse won't move nor click on client

### ISSUE THREAD

**Issue by sabueso** [symless/synergy-core#6605]
### Operating Systems ###

Server: Debian 10
Client: Debian 10

### Synergy Version ###

synergys 1.10.3-stable, protocol version 1.6 (in client & server)

### Steps to Reproduce ###

1. Clone the master branch from Github.
2. Compile it on both clean Debian 10 freshly installed, following the wiki instructions.
3. Connect from client to server, using Gnome 3.
4. Move the mouse between screens (from server to client and viceversa)

### Log URLs ###

[client.log](https://github.com/symless/synergy-core/files/3958584/client.log)
[server.log](https://github.com/symless/synergy-core/files/3958585/server.log)
[synergy-server-conf.txt](https://github.com/symless/synergy-core/files/3958621/synergy-conf.txt)

### Extra Info ###

- No too much extra info, I'm not using wayland and both installations are really clean.
- I've compiled both from the master branch without any special warning and everything seems to work OK but the mouse on client don't move in any direction and no click is map on it.
- NVIDIA proprietary driver on server (Dual head installation), same layout with Debian 8 was working OK
 
Thanks!!

**Comment by ChillerDragon** [comment]
I could reproduce the issue with the same setup.

**Comment by sabueso** [comment]
AFAIK seems to be something related Wayland non support (specified in some docs). :(

**Comment by aairey** [comment]
This is because #4090 is still not implemented.
