### ISSUE TITLE
Synergy cant create TLS certificate on windows

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6608]
### Operating Systems ###

Windows

### Synergy Version ###

1.11.0

### Steps to Reproduce ###

1. Delete the TLS certificate from the user home
1. Run synergy and connect with TLS enabled
1. See error that cert doesn't exsist

### Logs

`ERROR: secure socket error: tls certificate doesn't exist`

### Extra Info ###

It appears that one of the ported commits changed the openSSL binary location to the synergy base dir but didn't change the location of the openSSL binaries. (See https://github.com/symless/synergy-core/commit/1bc2cf57d90533bc3a4f4a029f4bab74caa12275) This commit shouldn't have been ported and needs to be reverted

**Comment by ryan-brazeal-ufl** [comment]
The issue appears to be with lines 37 and 38 in src/gui/src/SslCertificate.cpp for commit b2173ef ?

As a temporary work around, I copied the files _openssl.exe_ and _synergy.conf_ from C:/Program Files/Synergy/OpenSSL back one directory (i.e., the parent directory) to C:/Program Files/Synergy/ and restarted the server with TLS enabled. The SSL Fingerprint now appeared and the C:/Users/$USER/AppData/Local/Synergy/SSL/Synergy.pem file was created.

**Comment by m-p-3** [comment]
Confirmed on my end, had to generate a key on my Ubuntu server 

`openssl req -nodes -new -x509 -keyout synergy.key -out synergy.cert -days 3650 -sha256 -subj "//CN=computername"`
then
`cat synergy.key synergy.cert > synergy.pem` and copy `synergy.pem` to my `%LocalAppData%\Synergy\SSL` directory.

**Comment by Jnewbon** [comment]
We have a test build that has a fix for this issue in it. Please try it out.

[Synergy v1.11.1-snapshot](https://snapshots.symless.com/public/1.11.1-snapshot-1/)

**Comment by octogonz** [comment]
I encountered this issue also, and the test build fixed it.  Thanks!

**Comment by adfaklsdjf** [comment]
I just installed synergy on a fresh Windows 10 system and encountered this.  The work-around posted above fixed it.....

(wondering out loud: should we assume every user who uses Synergy is technical enough to google the error, find this issue ticket, and implement the work around...?)

**Comment by free-style** [comment]
> (wondering out loud: should we assume every user who uses Synergy is technical enough to google the error, find this issue ticket, and implement the work around...?)

Definitely not.  I'm surprised I found it.

**Comment by ttimasdf** [comment]
After moved OpenSSL binary from server, I got the following exception on macOS client.
```
2020-02-17 14:20:06.844 synergyc[31846:843080] unable to obtain configuration from file:///Library/Preferences/com.apple.ViewBridge.plist due to Error Domain=NSCocoaErrorDomain Code=260 "The file “com.apple.ViewBridge.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Library/Preferences/com.apple.ViewBridge.plist, NSUnderlyingError=0x7fd505c40710 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

I deleted `~/Library/Synergy/SSL/Fingerprints/TrustedServers.txt` from client side and it works. Just in case someone may need this.

**Comment by tohn** [comment]
I just had this problem as well:

```
ERROR: secure socket error: tls certificate doesn't exist: C:\Users\xyz\AppData\Local\Synergy/SSL/Synergy.pem
```

I solved it via https://github.com/symless/synergy-core/issues/6608#issuecomment-574350347, thanks! 👍
