### ISSUE TITLE
Incomplete Compilation documentation

### ISSUE THREAD

**Issue by BSFishy** [symless/synergy-core#6609]
I just compiled Synergy on Windows 10, and got everything working, but there was one last step that wasn't specified on the wiki page. Getting the project compiled, and copying everything worked find, but once I ran it for the first time, I kept getting the following message in the log:

```log
ERROR: ipc connection error, connection refused
```
After a little bit of digging, I noticed the service was not even showing up. After a brief look into the code, I noticed I could run an install command on `synergyd`. After starting an admin command prompt and running `synergyd /install`, the error messages went away and everything worked fine.

Perhaps there should be a little addition to compiling for Windows or a setup section that specifies how the service should be installed.

**Comment by AnrDaemon** [comment]
Definitely requires a "setup" section with service registration and a list of Qt components required to run GUI.
```
$ find . -type f -iname q\*
./plugins/bearer/qgenericbearer.dll
./plugins/imageformats/qgif.dll
./plugins/imageformats/qicns.dll
./plugins/imageformats/qico.dll
./plugins/imageformats/qjpeg.dll
./plugins/imageformats/qsvg.dll
./plugins/imageformats/qtga.dll
./plugins/imageformats/qtiff.dll
./plugins/imageformats/qwbmp.dll
./plugins/imageformats/qwebp.dll
./plugins/platforms/qdirect2d.dll
./plugins/platforms/qminimal.dll
./plugins/platforms/qoffscreen.dll
./plugins/platforms/qwebgl.dll
./plugins/platforms/qwindows.dll
./qt.conf
./Qt5Core.dll
./Qt5Gui.dll
./Qt5Network.dll
./Qt5Widgets.dll

$ cat qt.conf
[Paths]
Prefix=.
```

I'm not even sure if all of `platforms` plugins are required.
