### ISSUE TITLE
Mismatched TLS SHA fingerprint types

### ISSUE THREAD

**Issue by adam-vessey** [symless/synergy-core#6611]
### Operating Systems ###

Server: Windows 10 Pro
Client: MacOS 10.15.2

### Synergy Version ###

1.11.0-stable-b2173efb

### Steps to Reproduce ###

1. Configure server with TLS
2. Connect with client
3. On the client, get prompted to match the fingerprint in a dialog to that on the server

Expected: Fingerprints to match
Actual: Fingerprints do not match

### Extra Info ###

Appears to be due to different fingerprinting algorithms being used: The server interface displaying the SHA256 fingerprint, while the verification on the client showing the SHA1... which will never match, being different lengths... generating the SHA1 fingerprint _did_ appear to checkout, with (on the server), something like:
```
> OpenSSL x509 -noout -fingerprint -sha256 -inform pem -in "%APPDATA%\..\Local\Synergy\SSL\Synergy.pem"
> OpenSSL x509 -noout -fingerprint -sha1 -inform pem -in "%APPDATA%\..\Local\Synergy\SSL\Synergy.pem"
```
... the first matching that provided in the server interface, the second matching that in the verification dialog on the client.

**Comment by Jnewbon** [comment]
We have a test build that has a fix for this issue in it. Please try it out.

[Synergy v1.11.1-snapshot](https://snapshots.symless.com/public/1.11.1-snapshot-1/)

**Comment by adam-vessey** [comment]
Appears to do the trick; however, one other thing noticed: The length of the fingerprint in the server dialog overflows, and is hidden without any hint (ellipsis or whatever); however, one can still adjust the size of the dialog to see all of the fingerprint... Unsure if relevant, but still running `1.11.0-stable-b2173efb` on the server side.
