### ISSUE TITLE
Create installer building tutorial

### ISSUE THREAD

**Issue by JuniorJPDJ** [symless/synergy-core#6626]
There is provided synergy building tutorial, but you can't build the installer for windows.
Windows version doesn't work without service, which you would need to install yourself, which is also not covered in any wiki page.

**Comment by iUnknwn** [comment]
I added a new page to the Wiki explaining how to build the MSI package. 

https://github.com/symless/synergy-core/wiki/Building-the-Windows-MSI-Package
