### ISSUE TITLE
Keys are not correctly sent to client

### ISSUE THREAD

**Issue by Aymkdn** [symless/synergy-core#6630]
### Operating Systems ###

Server: Windows 10 Home
Client: Windows 10 Enterprise

### Synergy Version ###

Synergy Server: v1.11.1-snapshot-f8595fd3
Synergy Client: v1.11.1-stable-b2173efb

### Steps to Reproduce ###

I have an AFNOR Compliant AZERTY Keyboard with this open source layout: https://github.com/springcomp/optimized-azerty-win

Some keys (all the yellow ones) are not sent to the client, like <kbd>à</kbd> or <kbd>é</kbd>:
![Capture](https://user-images.githubusercontent.com/946315/74250952-ae172780-4ceb-11ea-9977-374792286e40.png)

I used AutoHotKey to try to detect the key received on the client side, but nothing is received at all. If I do it on the server side, I can see the correct key that appear.

### Log URLs ###

_(please, not that the links provided in your template are incorrect… It should be https://symless.com/help/articles/s1-sending-logs instead of https://symless.com/help/s1-troubleshooting/s1-sending-logs)_

No need to paste the log because nothing reflects the action of pressing the keys, and there is no error or interesting information!

### Extra Note ###

I spent an hour searching for info and trying things without success. Things I tried:
  - Set a shortcut key in the server configuration
  - Remap keys using AutoHotKey on both server and client

It might be related to https://github.com/symless/synergy-core/issues/6157 and https://github.com/symless/synergy-core/issues/6005

Thanks

**Comment by Aymkdn** [comment]
For people with the same kind of issues, I resolved it by uninstalling Synergy and installing [Input Director](http://www.inputdirector.com) (that is free for non-commercial). The interface is not as good as Synergy, but at least in **Master Preferences** there is an option **"Use this system's keyboard layout when directing slaves"** that magically made my keyboard to work with the slave!

**Comment by lexxxel** [comment]
> For people with the same kind of issues, I resolved it by uninstalling Synergy and installing [Input Director](http://www.inputdirector.com) (that is free for non-commercial). The interface is not as good as Synergy, but at least in **Master Preferences** there is an option **"Use this system's keyboard layout when directing slaves"** that magically made my keyboard to work with the slave!

Which is a Windows-Only solution :unamused:
