### ISSUE TITLE
Broken hyperlink on https://github.com/symless/synergy-core/wiki/Compiling

### ISSUE THREAD

**Issue by GlenCooper** [symless/synergy-core#6634]
There is a broken link on https://github.com/symless/synergy-core/wiki/Compiling.  When that "Core Compiling" hyperlink is clicked, it goes to a "Create New Page" page.  I'm not sure how to fix it, so I'm opening this as an issue.  Please fix if you can.

![20200220T041832Z-synergy_broken_link](https://user-images.githubusercontent.com/967793/74903089-e085ec00-539f-11ea-917a-87d664a31395.png)

**Comment by Jnewbon** [comment]
Hi, 

The compiling page does need to be rewritten (There is an issue for that task), the page that link refers to is not longer applicable.
