### ISSUE TITLE
Download link requires a log in

### ISSUE THREAD

**Issue by jzadra** [symless/synergy-core#6645]
The download link goes to a page that requires a login.  There is no way to create a new login.

**Comment by Jnewbon** [comment]
This is expected on the website, to create an account you need to purchase a license.

**Comment by jzadra** [comment]
Might be worth stating that prior to the link and on the web site as well.  Github is typically used for open source projects, so putting a link that requires payment without any indication of such is confusing.

**Comment by Jnewbon** [comment]
This is something we have been meaning to change on the website is you are right, it is confusing.

As for the open source aspect, Synergy is open source this repo contains all the the code.
