### ISSUE TITLE
Slack meetings steal mouse focus

### ISSUE THREAD

**Issue by benjymous** [symless/synergy-core#6646]
### Operating Systems ###

Windows 10 - 1909
Windows 19 - 1903

### Synergy Version ###

Synergy 2.0.12-beta

### Steps to Reproduce ###

Run a Slack meeting from the slack desktop client - when the meeting window loses focus, it displays a small "picture in picture" floating preview window.

This preview seems to mess with mouse focus, which prevents the mouse pointer from leaving the machine running the slack application

**Comment by AnrDaemon** [comment]
I've noticed similar behavior with 1.11.1 and Skype (currently `Skype version 8.58.0.93`).
I have my notebook  below my main PC monitor. Notebook is a server. When I leave NB screen to my main PC, if Skype window is open on NB, it repeatedly stealing mouse from that other screen.
