### ISSUE TITLE
How to copy files in VS?

### ISSUE THREAD

**Issue by Thisisaline** [symless/synergy-core#6650]
**Update:** Updated in last post below.

**Comment by AnrDaemon** [comment]
Run
`SETX /?`

**Comment by Thisisaline** [comment]
I've got no idea how to do that or where to do that. A simple explanation would be helpful.

Thank you for your help.

**Comment by Thisisaline** [comment]
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 10.0.18362.0
!ERROR! Windows SDK 10.0.18362.0 : 'include\10.0.18362.0\um'
The system cannot find the path specified.

It's the same when I use 10.0.18362.1

**Comment by AnrDaemon** [comment]
`~/build-2015.cmd`
```bat
@ECHO OFF

SET BUILD_CONFIG=RelWithDebInfo

MKDIR "%~dp0build"

CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

(
CD /D "%~dp0build"

cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% ..

msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=%BUILD_CONFIG% /m

COPY "%~dp0ext\openssl\windows\x64\bin"\* bin\%BUILD_CONFIG%\
) > cmake.log 2> cmake.err
```

**Comment by Thisisaline** [comment]
Thanks for your help, but to be clear I've only ever done something like this once before and it was on Ubuntu, and so was much easier. So your reply, unfortunately, doesn't really mean anything to me without more detailed step by step instruction.
All I can say was that I tried running the CLI commands, including the CMAKE_PREFIX_PATH in command prompt step by step in accordance with the guide, but when I got to calling vcvarsall.bat, the outcome was as per my previous post.
Thank you in advance for any help you can render.

**Comment by AnrDaemon** [comment]
I've successfully built the 1.11.1 core with the aforementioned batch file.
You can add setting CMAKE_PREFIX_PATH to it directly.
Said that, for VC14 it should be `SET CMAKE_PREFIX_PATH=C:\Qt\5.12.5\msvc2015_64`

**Comment by Thisisaline** [comment]
Thanks. So I can just copy and paste all of this into command prompt?

**Comment by AnrDaemon** [comment]
[google:"batch file" +windows](https://lmgtfy.com/?q=%22batch+file%22+%2Bwindows)

**Comment by Thisisaline** [comment]
Hah, thanks mate.. had a feeling i'd have to create a batch file or something along those lines

**Comment by Thisisaline** [comment]
So I was able to create and run the above batch file, and I downloaded Wix to properly open the solution file in VS. However, I have never used VS before. How do I copy the relevant files to run synergy.exe and/or build the msi package?

**Comment by AnrDaemon** [comment]
One issue per thread, please.
https://github.com/symless/synergy-core/issues/6609

**Comment by Thisisaline** [comment]
Noted. Thanks.

**Comment by AnrDaemon** [comment]
However you like. Do I need to write an instruction how to copy files?

**Comment by Thisisaline** [comment]
Well, I know it sounds rather absurd when you put it that way, but having never used VS before, I'm really quite confused. I've assumed thus far that I'm somehow supposed to copy the files from within VS since it supposedly requires release and debug modes. I've noticed the bin folder is inactive in the explorer pane until I right-click it and include it in the project, after which I can right-click it and open it in file explorer. I'm not sure whether I can just copy and paste the files like usual from here or what, or if these steps are even remotely along the right lines.
That said, based on some feedback I've received, I'm starting to think I don't even need to copy the files from _within_ VS and then I just supposed to have copied them like normal all along, and that I'm then supposed to 'Attach' in release and debug modes in VS or something along those lines. The requirement for release and debug modes are really whats confusing me.
So yea, pardon my ignorance, but any simplified clarifications as far as is reasonable would be much appreciated.

**Comment by AnrDaemon** [comment]
You copy these files from Qt. It's rather cumbersome to build installer, if you ask me. I did not plan to redistribute the compiled binaries, so I haven't even tried to build MSI.

I had to find a better compilation target though, since debug builds do not work with retail MSVC runtime.

**Comment by Thisisaline** [comment]
![image](https://user-images.githubusercontent.com/53150196/78503698-d9257100-779a-11ea-9d79-182064fa4430.png)
I open the sln file and this is what I see and I literally don't know what I'm supposed to do. Am I supposed to copy and paste the files in file explorer like normal or what am I supposed to do in VS?

**Comment by AnrDaemon** [comment]
I have no idea, how to work with SLN, can't comment.

**Comment by Thisisaline** [comment]
So I don't even need to do anything with the sln file? How did you do it? Copy the files form Qt in file explorer or where? Then what happens and how does synergy run from there?

**Comment by AnrDaemon** [comment]
Yes. See https://github.com/symless/synergy-core/issues/6609

**Comment by Thisisaline** [comment]
I've copied the files in file explorer in accordance with https://github.com/symless/synergy-core/wiki/Compiling#run-synergyexe-standalone-in-windows. Sooo, can I just copy and paste this in to command prompt?:
```
$ find . -type f -iname q\*
./plugins/bearer/qgenericbearer.dll
./plugins/imageformats/qgif.dll
./plugins/imageformats/qicns.dll
./plugins/imageformats/qico.dll
./plugins/imageformats/qjpeg.dll
./plugins/imageformats/qsvg.dll
./plugins/imageformats/qtga.dll
./plugins/imageformats/qtiff.dll
./plugins/imageformats/qwbmp.dll
./plugins/imageformats/qwebp.dll
./plugins/platforms/qdirect2d.dll
./plugins/platforms/qminimal.dll
./plugins/platforms/qoffscreen.dll
./plugins/platforms/qwebgl.dll
./plugins/platforms/qwindows.dll
./qt.conf
./Qt5Core.dll
./Qt5Gui.dll
./Qt5Network.dll
./Qt5Widgets.dll

$ cat qt.conf
[Paths]
Prefix=.
```

**Comment by Jnewbon** [comment]
You should only need to copy the following 4 files into the synergy bin folder on windows
```
./Qt5Core.dll
./Qt5Gui.dll
./Qt5Network.dll
./Qt5Widgets.dll
```
The documentation does require some TLC which i hope to get round to soon.

I'm going to close this issue as its a question rather then a bug and the documentation update is already tracked here #6609

**Comment by AnrDaemon** [comment]
Not quite true.
```
---------------------------
Synergy
---------------------------
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

---------------------------
ОК   
---------------------------
```
