### ISSUE TITLE
Support horizontal scroll from mouses with 2nd wheel

### ISSUE THREAD

**Issue by sheepdestroyer** [symless/synergy-core#6655]
I have a Logitec MX Master mouse whith a seconday horizontal scroll wheel under the thumb
This secondary wheel is not working on synergy client.

**Comment by Hereimz** [comment]
Ditto, I have been using that mouse for a few years and it's never worked with Synergy for horizontal scroll.
At the beginning I figured it was NBD, but as more time goes by I find the lack of support for the function to be more and more disappointing.

**Comment by asymptotic1** [comment]
Any update on this?  Been years now.

**Comment by posita** [comment]
It is stale because no one has addressed it. It is still very much a problem.

**Comment by teaforchris** [comment]
@desymless any updates please?
