### ISSUE TITLE
Non-ASCII characters replaced with ? on client

### ISSUE THREAD

**Issue by NicolasGoeddel** [symless/synergy-core#6660]
#### Server
OS: Windows 10 Version 1909 (Build 18363.720)
#### Client
OS: Ubuntu 19.10
Kernel: 5.3.0-42-generic
Shell: GNOME Shell 3.34.3

#### Server
1.11.1-stable-55ec3105
#### Client
1.11.1-stable-55ec3105

### Steps to Reproduce ###

It's the same issue as mentioned in https://github.com/symless/synergy-core/issues/6593, but I open a new issue because the other one seems not to be reopened again.

If you copy text on the server's side and paste it on the client side all non-ASCII characters gets converted to `?` while pasting.

### Extra Info ###

This seems not to happen with all the applications. It seems to work fine when pasting into VSCode and Chromium. I also tested it with a simple GTK2 and GTK3 application. GTK2 receives the text correctly without replaced characters. And GTK3 only receives the `?`. I don't know the exact solution here, maybe the clipboard data was not properly marked as UTF-8.

**Comment by WuerfelDev** [comment]
Confirm, with Windows 10 1909 as server (v1.10.1) and Pop!OS 20.04 (gnome shell 3.36.1) as client (v1.11.1)

**Comment by NicolasGoeddel** [comment]
Oh nice. Does that mean it will be available as an update to the stable 1.x version soon? Or do I have to wait 3 years until version 3 is ready?

**Comment by Jnewbon** [comment]
@NicolasGoeddel Should be available to v1 soon, im hoping to get a test build done that can be tested to confirm the issue as solved externally that you can use.
