### ISSUE TITLE
Limit GUI log Window to prevent it using up too much RAM over time

### ISSUE THREAD

**Issue by sionzeecz** [symless/synergy-core#6663]
### Problem ###
I'm running the laptop for 30 days in a month without a restart.
All the time is synergy running and waiting for connection or works as expected.
But log has around xxx thousands of lines. It is eating 1GB memory RAM now.
So restart of synergy is a solution but then I have to open the laptop, use keyboard and mouse there.

### Solution ###

Add "clean buffer" option to context menu when user press down right mouse button in the log area.

### More Info ###

At the moment there are two options: "Copy", "Select All".
It will be easy to add something what cleans the buffer list/vector/array whatever.

**Comment by Jnewbon** [comment]
Is a good idea, but i think users having it actively think about clearing the log isn't the best solution.

Instead i think setting a maximum number of lines to the log window would be best as if more logging history is wanted the option to save to a log file is provided.
