### ISSUE TITLE
Upgrading to Ubuntu 20 doesn't increase key length

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6671]
### Operating Systems ###

Ubuntu 20

### Synergy Version ###

1.11.1

### Steps to Reproduce ###

1. Have 1.11.0 or lower installed (1024 key length)
2. Upgrade to Ubuntu 20
3. See key length error

Related to: #6561 and #6669

```
[2019-09-29T21:11:45] NOTE: started server, waiting for clients
[2019-09-29T21:11:45] ERROR: secure socket error: could not use tls certificate
[2019-09-29T21:11:45] ERROR: openssl error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
```

**Comment by nbolton** [comment]
Will be fixed by #6669

**Comment by 130s** [comment]
To me I had to manually set "Settings -> Key length" from 1024 to 2048, in order for the connection b/w server and clients to be re-established.

What I did before starting to see an issue: Upgrade from Ubuntu 18.04 to 20.04 (synergy_1.12.0.stable~b20200827 was installed)

What else I did in addition: Installed 1.12.2-1 on both server and client.

**Comment by LeadManPL** [comment]
Synergy: synergy_1.13.1-stable.063519a8_ubuntu20_amd64
I had same situation as @130s : "I had to manually set "Settings -> Key length" from 1024 to 2048, in order for the connection b/w server and clients to be re-established."
