### ISSUE TITLE
Horizontal scrolling not respecting scroll settings

### ISSUE THREAD

**Issue by volt4ire** [symless/synergy-core#6675]
### Operating Systems ###

---BEGIN HELP---

Server: macOS 10.15.4
Client: macOS 10.15.4

### Synergy Version ###

1.11.1

### Steps to Reproduce ### 
When connecting from a macOS server to a macOS client, the horizontal trackpad scrolling direction is reversed. They are both running the latest version of macOS (10.15.4) and Synergy (1.11.1).
It appears there was a prior issue opened regarding this issue, but the suggested solution only addressed vertical scrolling, not horizontal, which is the issue for for me and [other] [users]. Can you please help me resolve this issue? Thanks!

[other]: https://github.com/symless/synergy-core/issues/624#issuecomment-578997767
[users]: https://github.com/symless/synergy-core/issues/624#issuecomment-345867184

**Comment by carpdiem** [comment]
This is also affecting me with different hardware, and with vertical scrolling:

Server: Ubuntu 21.10
Client: Windows 10 Enterprise, 21H1
Synergy Version: 1.14.2-stable-c6918b74
Input Device: Apple Magic Trackpad

### Steps to Reproduce:

Connect client to server, move cursor to client screen and attempt to two-finger scroll. Observe that the client only scrolls as if you were clicking-and-dragging the scrollbar (e.g., fingers moving down moves the scrollbar down). Setting scroll direction on client does not affect behavior. Setting mouse scroll wheel direction on client does not affect behavior.
