### ISSUE TITLE
Mac keyboard doesn't work

### ISSUE THREAD

**Issue by rikybordo** [symless/synergy-core#6683]
### Operating Systems ###

Server: macOS Catalina 10.15.4
Client: Windows 10 Pro 10.0.18362

### Synergy Version ###

Synergy 1: synergys 1.11.1-stable
Synergy 2: synergys 1.11.1-stable

### Steps to Reproduce ###

My original bluetooth apple keyboard doesn't work on the windows client, i focus the input, try to write but it doesn't work.  
From logs there are no error or strange message.

### Extra Info ###

My server layout keyboard is Italian, the client also has Italian keyboard.
I tried to invert client and server and all worked fine, so the problem is from Mac to Win.

**Comment by below43** [comment]
I've had this issue when apps are using Secure Input mode (eg. 1Password or BitWarden use this). You have to hide or close the application to then make the keyboard work in the client. 

see https://symless.com/help-articles/keyboard-not-working-on-client-but-mouse-works

**Comment by andreacndn** [comment]
This is addressed in 1.14.1
