### ISSUE TITLE
TLS connection problems

### ISSUE THREAD

**Issue by bikice** [symless/synergy-core#6684]
### Operating Systems ###

Server: Ubuntu 20.04 LTS (Focal Fossa)
Client: Ubuntu 20.04 LTS (Focal Fossa)

### Synergy Version ###

Server: 1.11.1-stable
Client: 1.11.1-stable

### Steps to Reproduce ###

Enable TLS Encryption on server & client

### Log URLs ###

Server: https://paste.ee/p/mLHpe
Client: https://paste.ee/p/tyFCs

### Extra Info ###

Server: OpenSSL 1.1.1f
Client: OpenSSL 1.1.1f

### Config ###

Server: https://paste.ee/p/PCPas
Client: https://paste.ee/p/9t3Ve

**Comment by rmiddle** [comment]
I am also seeing this issue.  To work around I had to disable TLS on both ends.

**Comment by bikice** [comment]
I'm using the same workaround

**Comment by bikice** [comment]
> I am also seeing this issue. To work around I had to disable TLS on both ends.

I'm using the same workaround

**Comment by bikice** [comment]
It will be fixed with #6669 

Workaround is to [manually delete the TLS key](https://github.com/symless/synergy-core/issues/6561#issuecomment-619821694)
