### ISSUE TITLE
CPU maxed when there is no server to connect to

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6686]
Looks like when no server is available the snapshot from May 4th (1.12.0-shnapshot-a324957e) again causes 100% cpu usage. I have synergy autostarted, so it tries to connect to a server after the login, but as I'm using my notebook also when not at home, it won't find any.
Stopping synergy (via gui) ends the 100% usage of the synergyc process of course.

_Originally posted by @Corben78 in https://github.com/symless/synergy-core/issues/6487#issuecomment-625055552_
# Synergy version

1.11.0-stable

# Effected OS's

Linux, Possibly others

# Steps to reproduce

1. Open synergy
1. Set to client mode
1. Type in address to a computer that inst running synergy (or unallocated IP)
1. Press start

Expected result: Very little CPU usage
Actual result: One CPU core is pinned to 100% by synergyc

**Comment by Corben78** [comment]
Looks like latest [snapshot](https://github.com/symless/synergy-core/issues/6487#issuecomment-635909125) fixing issue #6487 also fixes this.
I observed some CPU spikes with the previous snapshot, even when synergy was connected to a server. But now I don't see any CPU spikes or the maxed out behaviour anymore.

Awesome work!

**Comment by Jnewbon** [comment]
Thats epic, thanks for updating. I'll close this out as your the original reporter
