### ISSUE TITLE
Missing dependencies on ubuntu 20.04 popos that are needed for synergy  

### ISSUE THREAD

**Issue by JakeBenjamin** [symless/synergy-core#6701]
### Problem ###

Add support for Ubuntu 20.04 

Cannot Install the deb package because of missing dependencies that are not available on 20.04
I'm on popos 20.04

**Comment by JakeBenjamin** [comment]
![Screenshot from 2020-06-19 01-26-03](https://user-images.githubusercontent.com/58758017/85167340-abe34d80-b236-11ea-9de3-7e315b9e60ab.png)

**Comment by Jnewbon** [comment]
Hi, 

I looks like your running quite an old version of Synergy, Synergy-core hasn't depended on QT 4 for a number of years

Please try [downloading](https://members.symless.com/synergy/downloads/list/s1) a more up to date version or [compiling](https://github.com/symless/synergy-core/wiki/Compiling) from the source

I'm going to close the issue as I run PopOs myself with Synergy. If your still getting problems with the latest version, reply here and ill reopen the issue

Jamie
