### ISSUE TITLE
Modifier keys don't affect local mouse

### ISSUE THREAD

**Issue by nemzes** [symless/synergy-core#6703]
### Operating Systems ###

Server: Windows 10
Client: MacOS 10.14.6

### Synergy Version ###

synergys 1.11.1-stable, protocol version 1.6

### Steps to Reproduce ###

My setup is a bit weird. I use a Windows server and Mac client to share keyboard, but use a mouse connected directly to the Mac client. With this setup, modifier keys held down on the Windows keyboard don't affect the client mouse. For instance, ctrl+click won't trigger the pop-up menu, Shift+click won't select multiple files on Finder, etc.

If I use the server's mouse then everything works properly. (The reason for a local mouse is latency over wifi).

**Comment by canadaduane** [comment]
Out of curiosity, how would Synergy know which computer to send modifier keys to, if you aren't using the mouse to "direct" synergy's attention? Would you expect it to set "all computers" modifier keys?

**Comment by nemzes** [comment]
I would expect it to send modifiers to the current target computer (global Synergy hotkeys would still be intercepted on the server, of course, but this issue is about modifiers, not hotkeys).

**Comment by Kallin** [comment]
I think I'm experiencing a similar issue.

I have a Windows 11 sharing mouse and keyboard to a client Mac. I use the macbook's built-in keyboard but the PC's mouse, and the modifier keys don't work when using the mac keyboard with the PC's mouse on the mac desktop. They do work if I use the PC keyboard with the PC mouse on the mac desktop.

**Comment by paulcarbone** [comment]
I believe I have a similar issue:
I have a Win10 server, and a Mac 12.5 Client.  The Mac also has a macro keypad attached to it, and when I press shift on the Mac (via the macro keyboard or the built-in keyboard), and click with the mouse via synergy, the shift key is ignored.

**Comment by desymless** [comment]
With this particular issue, when input devices are being mixed - Are other keys affected, or only the modifier keys?

and what happens if you interact with the client computer using the client mouse, then use the client keyboard?

**Comment by paulcarbone** [comment]
I think it's only modifier keys - I can confirm that shift and control when pressed locally on the client, gets released when a remote mouse click is received from the server.
If I hold down another key on the client, say a period in a text editor, it will repeat, get momentarily interrupted by a mouse click (either locally on the client, or remote from the server), and continue repeating.
Client mouse + client keyboard works as expected, as does remote mouse + remote keyboard. 
Client mouse + remote keyboard has the similar issue - if I move the mouse over to the client to make sure it's under synergy control, but then use the local client mouse with the remote keyboard, there's the same issue.

**Comment by desymless** [comment]
Oh I understand. Yes, the modifier state would be reset when inputs from the server are received (syncing with the server state). There isn't a fix for this at the moment, although we are considering developing a solution where any keyboard/mouse can be used on any computer. In order to solve this particular issue we would need to decouple the keyboard and mouse when developing such a solution
