### ISSUE TITLE
Windows 10 / Server fails to start on startup/reboot 

### ISSUE THREAD

**Issue by attilarios** [symless/synergy-core#6706]
### Operating Systems ###

Server: Windows 10 64bit
Client: Windows 10 64 bit

### Synergy Version ###

Synergy 1: Client v1.11.0
Synergy 2: Server v1.10.3

### Steps to Reproduce ###

1. Reboot PC
2. Launch synergy (I have Startup enabled)

### Log URLs ###

Client
Log: https://paste.ee/p/UfE9I

Server
Log: https://paste.ee/p/TUm5a

### Extra Info ###

Only way to get it to work again is to stop and start 
This is intermittent, some times it will start after reboot without an issue

**Comment by zpwr** [comment]
Synergy config
[Synergyconfig.zip](https://github.com/symless/synergy-core/files/4834572/Synergyconfig.zip)
