### ISSUE TITLE
Support for iPadOS

### ISSUE THREAD

**Issue by jcrowthe** [symless/synergy-core#6727]
### Problem ###

Support for iPadOS (and likely also iOS) would be very helpful for developers of apps. One ipad app I'm in the process of writing has a dependency on a physical iPad, which means I cannot use the provided iOS Simulator. It would be very useful to use Synergy to be able to control the iPad with my keyboard/mouse instead of constantly removing hands in order to touch the iPad screen. Other use cases will definitely arise, this is just one I'm experiencing at the moment.

### Solution ###

Support for iPadOS.

### More Info ###

Referencing https://github.com/symless/synergy-core/issues/553 which was closed due to lack of pointer support at that time. As of iPadOS 13.4, [pointers are now first class citizens](https://support.apple.com/en-us/HT211008) and fully supported.

**Comment by GowthamKudupudi** [comment]
and Android as well. I'm ready to buy it.

**Comment by GowthamKudupudi** [comment]
I still wish it supports both ios and android

**Comment by Saviio** [comment]
feature request + 1

**Comment by nbolton** [comment]
Thanks for the +1 but this is beyond scope for Deskflow.

**Comment by sucy171106** [comment]
feature request + 1

**Comment by sithlord48** [comment]
Nothing is stoping anyone who wants to write an IOS compatibe app the same way someone wrote a Android compatible one.(https://github.com/deskflow/deskflow/discussions/8701)
