### ISSUE TITLE
Account name with space on windows causes synergy to error when starting

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6758]
### Operating Systems ###
Windows

### Synergy Version ###
Synergy 1.12.0-stable

### Steps to Reproduce ###
1. Have a user account with a space in the name eg "Jamie Newbon"
1. Set the TLS cert path in settings 
1. Attempt to start synergy

Expected: Synergy to start with the TLS path
Actual: Error starting synergy

### Extra info
The command line argument setting the TLS path doesn't have " around them thus spaces messes with the arguments sent to the child process

**Comment by mindcreations** [comment]
I confirm the bug, cannot run Synergy on Windows 10 with a username with space like "Matt Damon".

Can you suggest a workaround in the meantime you fix it?

**Comment by Jnewbon** [comment]
Currently its to move the TLS certificate to a path not containing a space. I'm going to be fixing this soon and ill provide a dev build link here till we can get a release done,
