### ISSUE TITLE
Synergy accepts a screen name that contains spaces

### ISSUE THREAD

**Issue by mindcreations** [symless/synergy-core#6764]
### Operating Systems ###
Server: any
Client: any

### Synergy Version ###
1.12.0-stable

### Steps to Reproduce ###

Following the [official guide](https://support.symless.com/hc/en-us/articles/360004804358-Installation-guide?_ga=2.255604107.229769218.1599675409-1611033419.1599581902) 

1. Go to -> Step 2.1: Naming the Server computer
2. Read -> Note: Your screen names should not contain any spaces.
3. You type into the screen name a name WITH spaces and Synergy does not complain.

Expected: Synergy UI must display an error message stating that screen names must not contain any spaces.
Actual: it saves the name with the space and then it does not work properly.

**Comment by dneprqa** [comment]
This should have now been fixed in Synergy 1.14+.
Please let us know if the problem persists.

Thanks,
Oleksandr
