### ISSUE TITLE
synergyc reporting _client_ fingerprint instead of server ssl fingerprint

### ISSUE THREAD

**Issue by nneul** [symless/synergy-core#6769]
### Operating Systems ###

1.12.0.stable~b20200827.1+cb8064e8 on Ubuntu 20 amd64

connecting to 

1.12.0.stable~b20200827.1+cb8064e8 on Ubuntu 18 amd64

### Synergy Version ###

synergys 1.12.0-stable, protocol version 1.6
Copyright (C) 2012-2019 Symless Ltd.
Copyright (C) 2008-2014 Nick Bolton
Copyright (C) 2002-2014 Chris Schoeneman

### Steps to Reproduce ###

Attempt to connect from client. Displayed ssl fingerprint is that of the client (i.e. the one it's complaining about not trusting is the one displayed in the grayed out 'Server' section of the client UI. 

It also shows the same incorrect 'server' fingerprint in the log. 

### Log URLs ###

[2020-09-14T10:41:59] NOTE: connecting to 'infinity.domain': a.b.c.d:24800
[2020-09-14T10:41:59] NOTE: server fingerprint: F4:F8:D2:4B:8F:48:8E:51:A1:30:2F:0C:D6:9A:2D:64:65:AA:A2:CB:9D:B3:E5:19:BE:99:04:39:DE:E7:A7:5D

nneul@infinity:~ $ echo -n | openssl s_client -connect infinity.domain:24800 2>/dev/null | openssl x509  -noout -fingerprint
SHA1 Fingerprint=EC:A1:0D:5A:8F:80:F6:BF:46:82:F0:D3:C8:F5:43:9F:AD:F0:E9:38

**Comment by SerhiiGadzhilov** [comment]
@nneul
Unfortunately I'm not able to reproduce the issue.
Could you please set logging level "Debug2", reproduce the issue and provide full log.

**Comment by nneul** [comment]
Can no longer reproduce. It was consistent before, but I've since applied full OS upgrade to one of the involved machines, and no longer seeing the behavior.
