### ISSUE TITLE
Synergy crashed after Sleep mode on Mac.

### ISSUE THREAD

**Issue by AlexeyPilya** [symless/synergy-core#6790]
### Operating Systems ###

Server: Windows 10
Client: Catalina

### Synergy Version ###

1.12.0

### Steps to Reproduce ###

1. Install Synergy on Win and Mac
2. All good.
3. Mac goes sleep
4. After wake up Synergy crashing and cant connect. 
![Synergy](https://user-images.githubusercontent.com/43998106/94133437-4e7c1f80-fe69-11ea-8877-df11df6a3efc.JPG)

**Comment by dhain** [comment]
Same behavior in 1.12.2

**Comment by dneprqa** [comment]
Fixed in 1.14.1
