### ISSUE TITLE
Mouse Suddenly Not Scrolling on Client Computer

### ISSUE THREAD

**Issue by wfoaktown** [symless/synergy-core#6805]
I have been using my mouse with only my server laptop for the last month. Upon returning home and setting back up, the mouse will now not scroll on the client computer for any software or browser window: Word, Excel, Chrome, Firefox, etc.

I confirmed that it seems to be a Synergy issue by setting up the mouse on the client computer directly and it behaves as expected, in that case. I also returned my mouse settings to restore defaults as well as tried numerous other adjustments to no avail. Time suck frustration - I hope you can help!

**RESPONSE FROM DANIEL**:
 Daniel Alarcon (Symless)

Oct 6, 2020, 2:10 EDT
Hi Winnie,

We are aware of the problem you’re experiencing, and we do plan to fix it. The info from this ticket has been added to our internal issue tracker system which will help us fix the problem.

For issues that we plan to work on next, we add them to our public [GitHub issue tracker](https://github.com/symless/synergy-core/issues). You are welcome to follow your issue and comment.

We are also offering the opportunity for users to participate in the alpha version of the next version of Synergy, Synergy 3. Based on your feedback, I would suggest that you [learn more and register to share your feedback](https://symless.com/blog/synergy-3-free-upgrades-for-most-users).

I’d like to give you an estimate on how long until it’s fixed, but I don’t want to over-promise. I do appreciate how frustrating the problem is though.

Do you have other questions for me?

Thanks,
Daniel

**Comment by cosmikwolf** [comment]
Related issue: https://github.com/symless/synergy-core/issues/6259

**Comment by cosmikwolf** [comment]
Related issue from 2016: https://github.com/symless/synergy-core/issues/5227

**Comment by paulettea** [comment]
If client is Mac: try looking at this:
https://bonnyeagletechdept.blogspot.com/2019/04/scrolling-issues-in-chrome-with-syngery.html?m=0

**Comment by MansaRP** [comment]
This is not a fix, nor a work around. I have that set by default on both macs already, this is a serious bug.

**Comment by CeilidhAN** [comment]
I also encounter this issue between various systems - I have 3 Windows 10 PC's, two Macs, and a Linux box that all have this same problem using the scroll wheel on my MX Ergo, whether Logitech Options is installed and configured, or not, and whether or not I have the scroll wheel scroll direction reversed in any of the OS's mentioned. Most with the latest drivers/updates and so on.

**Comment by andreacndn** [comment]
We have made various improvements and fixes in this area in 1.14.1, would you mind trying the release candidate and let us know if the problem persists?

**Comment by CeilidhAN** [comment]
I would love to

**Comment by andreacndn** [comment]
https://symless.com/synergy/releases/synergy-1-14-1-release-candidate

> We have made various improvements and fixes in this area in 1.14.1, would you mind trying the release candidate and let us know if the problem persists?

**Comment by CeilidhAN** [comment]
> https://symless.com/synergy/releases/synergy-1-14-1-release-candidate
> 
> > We have made various improvements and fixes in this area in 1.14.1, would you mind trying the release candidate and let us know if the problem persists?

I have updated both copies, rebooted, and reconnected, and the problem still persists. I will try a cold boot just to be sure, but I don't think that will fix it.
