### ISSUE TITLE
Server and Client can not start

### ISSUE THREAD

**Issue by XiaoliChan** [symless/synergy-core#6807]
**Problem**

Can not start synergy service which is complied from newest commit.

**Platform: Windows
Version: 1.12.0-snapshot-7e019179**

Log:

```
[2020-10-09T19:55:58] INFO: connecting to service...
[2020-10-09T19:55:59] INFO: connection established
[2020-10-09T19:55:59] INFO: service status: idle
```

Also, it show me "synergy is starting"

**Comment by Jnewbon** [comment]
Just to confirm the problem have you tried compiling from the last release commit? cb8064e856b7630bfd07e971a3d60c23d4aa686a

**Comment by XiaoliChan** [comment]
@Jnewbon Thanks for your reply, I have use this version `cb8064e` last month, it work ! 

But now that commit is out of date, so I want to update to newest commit. :)

**Comment by XiaoliChan** [comment]
Well, I roll back to cb8064e, it worked.

**Comment by XiaoliChan** [comment]
@Jnewbon This bug has been fixed. I build from last commit 4f655785, it worked!

**Comment by andreacndn** [comment]
Great work @SerhiiGadzhilov !
