### ISSUE TITLE
Fixed processing of non-ASCII symbols missing in CP_THREAD_ACP but present in current KB layout

### ISSUE THREAD

**Issue by eugenegff** [symless/synergy-core#6812]
Hi guys, you could be interested in applying https://github.com/debauchee/barrier/pull/910/commits/09e1dbdf8484c8ed18fa715bdf4ef303ff854591 fix to Synergy. Detailed problem description is in https://github.com/debauchee/barrier/pull/910 but basically there are problems with non-ASCII symbols on otherwise English Windows where only "Current language for non-Unicode programs" changed to non cp1252 language and national KB layout installed. Conversion UTF16 => ANSI => UTF16 uses mismatching codepages and user input is corrupted. Being the Synergy user in the past I know that it is affected.

**Comment by eugenegff** [comment]
FYI, this pull request was merged to Barrier. Right now Barrier has better support for non-English users than Synergy. Shame? Shame.

**Comment by eugenegff** [comment]
Fix was ported to synergy with errors, in places like SYNERGY_MSG_DEBUG, wParam | 0x0500000 constants should be shifted left by 4 as wParam holds 28 bits of payload after switching to ToUnicode. May be it is not so important, but it is error nevertheless. In simple words - replace 0x0500000 with 0x50000000

**Comment by desymless** [comment]
> Fix was ported to synergy with errors, in places like SYNERGY_MSG_DEBUG, wParam | 0x0500000 constants should be shifted left by 4 as wParam holds 28 bits of payload after switching to ToUnicode. May be it is not so important, but it is error nevertheless. In simple words - replace 0x0500000 with 0x50000000

Hi 👋 We made some changes related KB layouts a while ago, so I thought I should ask if you are still seeing the errors mentioned in the latest version of Synergy?

**Comment by eugenegff** [comment]
Unfortunately I don't use nor Synergy nor Barrier anymore, replacing physical Windows PC by Parallels VM, so I can not test the quality of transplanting the patch. OTOH, two years ago patched Barrier worked without errors.

Seems that new scheme of wParam packing in toAscii > toUnicode Synergy patch
https://github.com/symless/synergy-core/commit/bcebb6519f6d3baeaf9fce27e0be81cf0e3737d7
was taken without modifications from my toAscii > toUnicode patch for Barrier
https://github.com/debauchee/barrier/commit/09e1dbdf8484c8ed18fa715bdf4ef303ff854591
except places producing wParam for SYNERGY_MSG_DEBUG.

From what I see, end users should not be affected by this omission, as it is logging/debug interface.

But new scheme of wParam packing uses previously unused bits, so wParams packing for SYNERGY_MSG_DEBUG should be adjusted to avoid collision and confusing debug logs. Note, that logs are usually used to debug confusing situations, and logs that create additional confusion is definitely a bad thing, especially if fix is so easy.

Actually, in one place Synergy did the right thing
![image](https://user-images.githubusercontent.com/34012295/211015518-2f5827bb-b48a-4f32-b5e1-69f4ca1ad751.png)
compare to my patch for Barrier:
<img width="515" alt="Screenshot 2023-01-06 at 13 50 13" src="https://user-images.githubusercontent.com/34012295/211015804-5c021881-24df-4b3c-8d16-e7b4c36f28c5.png">

but all other places like that were not ported.
<img width="549" alt="Screenshot 2023-01-06 at 13 52 27" src="https://user-images.githubusercontent.com/34012295/211016102-e59ef3b0-96bf-49eb-990a-3e6b8b96597d.png">
