### ISSUE TITLE
Mouse jumps every 7-8 seconds or so on client

### ISSUE THREAD

**Issue by abstractls** [symless/synergy-core#6813]
### Operating Systems ###

---BEGIN HELP---

Server: MACOS 10.15.3
Client: Windows 10 build 19041.508

Please distinguish which operating system is the client and which is the server. The server is the computer that the mouse and keyboard are shared from.

---END HELP---

### Synergy Version ###

---BEGIN HELP---

Synergy 1: 1.12 on both server and client

---END HELP---

### Steps to Reproduce ###

---BEGIN HELP---

Every 7-8 seconds or so WHILE USING the mouse, it will jump across the screen.  It seems that it is dependent on the speed as to how far so it seems like its more of a drop out issue

---END HELP---

### Log URLs ###

---BEGIN HELP---

https://paste.ee/p/bmPQO

---END HELP---

### Extra Info ###

---BEGIN HELP---

* What maybe causing it? NO IDEA AS IT SEEMS TO BE RECENT, BUT I HAVENT BEEN USING THE WINDOWS COMPUTER FOR A LITTLE BIT
* What other apps are you running?  HAPPENS WHEN NOTHING IS RUNNIGN BUT WINDOWS
* Does it stop you using Synergy entirely?   IT WOULD BE USELESS FOR VIDEO EDITING AS IT WOULD MESS UP MY WORFLOW
* Did restarting Synergy or the computer help?  NO, I EVEN UPDATED BOTH COMPUTERS TO USING TEH CURRENT SYNERGY FROM 1.10 AND IT STILL PRODUCES THE ISSUE

---END HELP---

**Comment by abstractls** [comment]
no response?

**Comment by andreacndn** [comment]
Hello @abstractls ,

We are currently wrapping up the 1.13 release, this bug is a candidate for the next version.

Andrea
VP of Technology @Symless
