### ISSUE TITLE
Windows machine unable to sleep without being woken by Synergy whilst connection active

### ISSUE THREAD

**Issue by AnthonyWharton** [symless/synergy-core#6815]
### Operating Systems ###

Computer 1 is the server, Computer 2 is the client.

Both are running Windows 10.

### Synergy Version ###

Server and Client are using `synergys.exe 1.12.0-stable, protocol version 1.6`

### Steps to Reproduce ###

When putting Computer 2 to sleep, it is woken up about 1 second later whenever a synergy connection is active. If the connection is not active this behaviour does not happen and the computer sleeps successfully.

Attempts at fixing:

- Disabling the "Synchronize screen savers" option on the server.
- Adding a powercfg requeste override with the following command:
> POWERCFG /REQUESTSOVERRIDE PROCESS synergyc.exe DISPLAY SYSTEM

### Log URLs ###

Below are the relevant entries from Windows Event Viewer (on Computer 2):

Event Viewer Sleep Log:
```
> The system is entering connected standby
> Reason: Screen Off Request.
```

Event Viewer Wake Log:
```
> The system is exiting connected standby
> Reason: Input Mouse.
```

From this I think it is reasonable to assume Synergy is applying some synthesised mouse movement perhaps? I'm not sure how it works but it's being worken by a mouse and no mouse is connected/the trackpad was not touched.

---

Outputs to some POWERCFG commands (on Computer 2) that have been suggested on the forums for similar issues. https://pastebin.com/z88F5f0w

From this you can see that synergyc.exe requests DISPLAY from POWERCFG when "Synchronize screen savers" is on, however this bug happens regardless of this setting, so I am fairly confident that it is nothing to do with this functionality, more likely the mouse movements shown above.

### Extra Info ###

* Attach any screenshots - N/A
* What maybe causing it? - Synergy syntehsised mouse movements waking the device.
* Are there any workarounds? - None found, `POWERCFG` commands made no difference and all mouse devices are disallowed from waking the device.
* What other apps are you running? - N/A
* Does it stop you using Synergy entirely? - No.
* Did restarting Synergy or the computer help? - No.
* Is there anything else you can think of - At this moment, no.

**Comment by berniecase** [comment]
I wonder if this is, in some way, related to #4116.
