### ISSUE TITLE
Polish characters does not work on client computer

### ISSUE THREAD

**Issue by mjh-krk** [symless/synergy-core#6827]
### Operating Systems ###

Server: Windows 10 2004 
Client: Windows 10 2004 

### Synergy Version ###

Synergy 1: synergys.exe 1.12.0-stable, protocol version 1.6
Synergy 2: synergyc.exe 1.12.0-stable, protocol version 1.6

### Steps to Reproduce ###

On both computer Polish language and Polish programmers keyboard has to bet

1. Open notepad on server computer type those letters with alt: azsxecnol you should get: ążśźźęćńół
2. Move to client computer
3. Open notepad on client computer type those letters with alt: azsxecnol you should get only: ó

Expected: All polish special characters to work on both computers server and client
Actual: Polish special characters working only on server 

### Log URLs ###

No logs to report

**Comment by jameskentTX** [comment]
I'm using Debian 10 and I can type polish characters on client computer. I looked at my `synergy.conf` but I don't see any relevant options there.
My `synergy` version is `synergys 1.12.0-snapshot.b1-786890db, protocol version 1.6`, but I had polish characters in earlier versions too.

On client computer you should run `synergyc` not `synergys`. Or you should correct `Synergy Version` in your comment :)

**Comment by mjh-com-pl** [comment]
@jameskentTX I guess this is because you are using Linux not Windows, try not to compare apple with pears.
As for version is still the same "1.12.0-stable, protocol version 1.6". You are confusing binary name (this is now corrected) with application version. On Windows server and client are installed with same package.

p.s. I ditch this for "Mouse without barriers" with is free and working opposite to Synergy which is paid and not working (and no plans for fixing this soon).

**Comment by dkondraszuk** [comment]
Is that going to be fixed any time soon? 
I have the same issue with Ubuntu 20.04 as a server + windows 10 as a client

**Comment by stamart** [comment]
> Is that going to be fixed any time soon? I have the same issue with Ubuntu 20.04 as a server + windows 10 as a client

I have the same config and problem as you. Just bought this app and i'm disappointed. its makes this app useless

**Comment by vitalPixel** [comment]
Hey @dkondraszuk and @stamart , can you confirm which version of Synergy you have installed on your computers?

The latest version (1.14.3) has a new option under Preferences for client computers: `Use server's keyboard language on this machine`.
Could you try turning that on and see if it fixes the problem?
You need to make sure that the same language and keyboard layouts are installed on the server and the clients tho.

Let me know if it works.
