### ISSUE TITLE
SSL key too small

### ISSUE THREAD

**Issue by bcdonadio** [symless/synergy-core#6833]
## The Issue

Since I upgraded from Fedora 32 to Fedora 33, I was unable to start `synergys` because of the following error:

```
ERROR: secure socket error: could not use tls certificate
ERROR: openssl error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
```

This is because the [default Security Policy got raised](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2), and 1024-bit RSA keys are not supported any more by default and I was using a 1024-bit key [because that was the Synergy default up to v1.11.0-rc1](https://github.com/symless/synergy-core/commit/7d8a09f514876bd2d928366948244f400b718b0c). Even though it is possible to override this policy by running `sudo update-crypto-policies --set LEGACY` and have Synergy working again by restarting the application, it's better to upgrade the key size.

However, the issue that in my opinion that needs to be fixed is the workflow in the Settings dialog to generate a new certificate with a bigger key when you have been a Synergy user since before v1.11.0-rc2.

## Fix Workflow

My thinking procedure went like this when I noticed that couldn't use remote screens:

1. Hmm, Synergy is not working. I haven't gotten any error pop-ups, but let's open the GUI to see what's happening.
2. Read SSL key size too small in the logs. I know that Synergy uses a SSL key to secure connections, let's see if there's a setting for that.
3. Found it. It's set to 1024, and there's a Regenerate button. That looks easy to fix.
4. Changed the drop-down menu from 1024 to 4096, but now the Regenerate button became disabled? How am I going to regenerate this thing?
5. Pasted the error on Google, found a bunch of other people complaining about that in other applications, but nothing related to Synergy.
6. Found a Red Hat documentation instructing how to change the Security Policy to LEGACY and why that was a bad idea.
7. Executed the command from the Red Hat docs, but now let's fix the issue on Synergy.
8. By actually reading the source code, I found [this comment stating that the key would be regenerated by just pressing OK in the Settings dialog](https://github.com/symless/synergy-core/blob/cb8064e856b7630bfd07e971a3d60c23d4aa686a/src/gui/src/SettingsDialog.cpp#L284).
9. Indeed, it worked, I got a new key and then I rolled back the system crypto config.

## Possible Improvements

1. At step 1, Synergy could have identified the error and thrown a pop-up with an explanation. This almost certainly happen with other GNU/Linux distros soon as well, since Fedora normally is the bleeding edge.
2. At step 4, that Regenerate button enable logic is just weird. I see two ways to solve this:
  a. It should either be always available and allow the user to regenerate the key at will with the key size that is selected.
  b. Simply not have the Regenerate button and pressing the OK button at the bottom would be the intuitive workflow.
3. At step 5, this issue can be explained in a FAQ of some sort, with the typical error message on it so the user can easily find it with a Google search.

Aside from that, great work. Synergy has been awesome.

**Comment by jorvis** [comment]
I just upgraded to 1.14.5-stable-a975f61a on both client and server and now get this message when I try to connect.

**Comment by jorvis** [comment]
Notes for anyone else reading this, it was fixed when I went to:

Edit -> Preferences -> Key length 

And changed the value to 4096, then clicked Save.  Not the "Regenerate" described above.  The server restarted and my client connected.
