### ISSUE TITLE
Text copied and pasted on macOS 11 (Big Sur) on iMessage appears in an Asian character set

### ISSUE THREAD

**Issue by barronlroth** [symless/synergy-core#6839]
### Operating Systems ###
Windows 10
Mac Big Sur 11.0.1

### Synergy Version ### 
version 1.12.1-stable-cb8064e8 on both windows (server) and mac

### Steps to Reproduce ###
1. Copy any text on Windows 10
2. Paste text into Macbook running Big Sur

Expected: Text pastes as normal
Actual: Text pastes in Japanese or some other asian character set

### Log URLs ###

# README & DELETE #

---BEGIN HELP---

Please do not paste entire logs here, it looks really silly. Instead, upload your logs, and share the URLs to the uploaded logs. Here's how you that:

Synergy 1: https://symless.com/help/s1-troubleshooting/s1-sending-logs
Synergy 2: https://symless.com/help/s2-troubleshooting/s2-sending-logs

Make sure you say which log is for which computer, and also which computer is the client and which one is the server. This helps to avoid any confusion.

---END HELP---

### Extra Info ###

# README & DELETE #

---BEGIN HELP---

* Attach any screenshots
* What maybe causing it?
* Are there any workarounds?
* What other apps are you running?
* Does it stop you using Synergy entirely?
* Did restarting Synergy or the computer help?
* Is there anything else you can think of

---END HELP---

**Comment by andreacndn** [comment]
@barronlroth, we haven't been able to reproduce the issue. Could you please send us debug logs from both computers?
Could you also please try to update to 1.12.2 (it will go live tomorrow) and keep us posted?

Thanks,
Andrea

**Comment by fearlesschicken** [comment]
I thought I had this same problem but so far it seems to happen when pasting into imessage.  Copying text to Textedit seems fine but in imessage, it is all chinese/kanji.

**Comment by andreacndn** [comment]
Thank you @fearlesschicken! I have reproduced this issue! Does it happen only on iMessage?
We'll investigate the root cause.

**Comment by fearlesschicken** [comment]
Just tried a number of different apps (Notes, Firefox, Facetime) and they all worked, just iMessage so far...

**Comment by BillSavastano-LeaguePals** [comment]
I have the same issue here, seems to be only iMessage.

**Comment by doowruc** [comment]
I have the same problem, only happening on Messages app... I can paste elsewhere on the client Mac, copy again, then paste successfully into Messages

**Comment by wjbabicz** [comment]
Have also been getting this issue since updating to Big Sur. Server is a Windows 10 PC, client is Big Sur. Happens when copying a link from a Windows PC and pasting into Messages.app. Doesn't seem to happen anywhere else.

**Comment by andreacndn** [comment]
@wjbabicz thanks for confirming that the issue doesn't happen anywhere else, and I can also add that the same issue is still present after updating to macOS 11.1.
We are working on it and we'll soon have a fix.

**Comment by terencemcdonnell** [comment]
Hello - having same issue cutting and pasting from UltraEdit for Mac to Messages.  

Doesn't seem to affect any other apps.  

If I paste into another text editor, reselect and copy again then paste into Messages, it seems to work OK.

**Comment by ElvisExMachina** [comment]
I can confirm this issue affecting only Win10 paste into iMessage on Big Sur 11.1. Can paste into any other text field and get the correct result but pasting into iMessage results in asian characters.

For example, the URL of this issue copied from Win10 and pasted into iMessage results in this output.

栀琀琀瀀猀㨀⼀⼀最椀琀栀甀戀⸀挀漀洀⼀猀礀洀氀攀猀猀⼀猀礀渀攀爀最礀ⴀ挀漀爀攀⼀椀猀猀甀攀猀⼀㘀㠀㌀㤀

**Comment by barronlroth** [comment]
@SerhiiGadzhilov Has this pushed to production yet? If so, how can I download it? I'm still getting this bug.

**Comment by andreacndn** [comment]
@barronlroth it's included in 1.13.1, which is currently in release candidate https://symless.com/synergy/releases/synergy-1-13-1-release-candidate

**Comment by jtara** [comment]
FYI, this bug seems to appear as well in Barrier. Mentioning this here as it may be helpful to Barrier users and developers. And since the code has common heritage, perhaps may be useful.

I have observed that you don't actually have to copy/paste across machines, but it even affects copy/paste on the same machine.
