### ISSUE TITLE
Symless 1.12.0-rc2 and 1.11.1-rc2 Crashing Big Sur

### ISSUE THREAD

**Issue by burneremail** [symless/synergy-core#6840]
I can open the app, but as soon as it starts trying to connect, the machine crashes instantly.

**Comment by andreacndn** [comment]
Hello, could you please share any more detail if you have? Such as logs related to the problem?
Few of us have been using Synergy 1.12.0-stable on Big Sur since it was in beta without any issue, and I am using it right now on the latest release of Big Sur without any crash or error.

Thanks,
Andrea

**Comment by burneremail** [comment]
I'm just using the DMG for 1.12.0-rc2, and my machine is crashing slightly after connecting to my Windows machine;  it did this earlier on Big Sur beta 4, so I just downgraded back then thinking nothing of it, but now, I'm able to confirm that it's Synergy causing the crash.

I'm not really a developer, so I don't know how to get to other information.  If you could guide me, that'd be great.

**Comment by andreacndn** [comment]
Could you please email to support@symless.com so we can arrange a remote troubleshooting session?
I'd love to investigate more this problem.

**Comment by andreacndn** [comment]
@burneremail do you still have this issue, or was it resolved?
