### ISSUE TITLE
Auto hide on start changing too false when open Synergy configuration

### ISSUE THREAD

**Issue by karnasw** [symless/synergy-core#6843]
Operating system: Windows 10 Pro 64bit 20H2
### Synergy Version ###
1.12.0-stable
Auto hide configuration not working in that version. When I open configuration window key autoHide in HKEY_CURRENT_USER\SOFTWARE\Synergy\Synergy, changes to false.

Checkbox not working, option is still set to false in reg tree.
AutoHide only works when I don't open the configuration window.

**Comment by andreacndn** [comment]
Hi @karnasw thanks for flagging this issue.
It has been added to our backlog and it will be fixed soon.

Andrea

**Comment by ipkpjersi** [comment]
I can reliably replicate this issue on Ubuntu 18.04 on Xfce 4.12.

I would really like for this to be looked into. It's a very "small" thing but the annoyance of it can definitely build up quickly and it becomes a bigger problem than you would think. It's so seamless having it autostart and having it autohide on startup, especially where Synergy is seamless by design, it would be great to be able to have this fixed.

**Comment by andreacndn** [comment]
@karnasw , @ipkpjersi the bug has been fixed in 1.13.0, could you please test the rc2 and confirm if it's solved for you?
https://symless.com/synergy/releases/synergy-1-13-release-candidate-2

Thanks!
Andrea

**Comment by ipkpjersi** [comment]
I can confirm that the bug is fixed in 1.13.0 RC2, thank you for the quick and decisive action.

**Comment by andreacndn** [comment]
Thank you for the prompt feedback!

> edit: now the minimize to system tray no longer works when it is auto-hidden, should I open a new bug report for this?
No need I'll get it checked right now and fixed for the final release.

**Comment by ipkpjersi** [comment]
If it helps, 1.11.1 stable does not have the auto-hide resetting or invisible minimize to system tray bugs so I am now using that on Ubuntu 18.04.

**Comment by andreacndn** [comment]
Thank you very useful

**Comment by ipkpjersi** [comment]
I did some more looking into this and I think I found the PR where the tray icon may have broken for me on Ubuntu 18.04: https://github.com/symless/synergy-core/pull/6859

**Comment by karnasw** [comment]
@andreacndn Everything is okay in 1.13.0.

**Comment by ipkpjersi** [comment]
Yep, I can confirm, any remaining issues I had are all solved in 1.13.0 stable, seems to be a very good release. :+1:

**Comment by andreacndn** [comment]
@ipkpjersi thanks for your feedback, much appreciated!
