### ISSUE TITLE
[question] What is the latest version?

### ISSUE THREAD

**Issue by yurivict** [symless/synergy-core#6850]
On one hand, ```v1.13.0-rc01``` was tagged 19 days ago.
On the other hand, ```2.3.2``` was released on Oct 2, 2019.

Repology shows a variety of versions: https://repology.org/project/synergy/versions
I think this is because people are confused.

**Comment by Jnewbon** [comment]
Hmm you are right, i just had a look through the tags, and there seem to be a number of tags that don't belong to this repo but forks of the repo, `2.3.2` was an example of that. 

I have cleaned up all the tags that don't belong on our repository. 

As for the current release, I believe that will be a question for @andreacndn as he is in control of the release schedule and numbering. I believe the current stable release is 1.12.2, and 1.13.0 is in testing.

**Comment by andreacndn** [comment]
@yurivict , 1.12.2 is the latest stable release, and 1.13.0 is approaching rc2

**Comment by yurivict** [comment]
@andreacndn @Jnewbon 

There are still v2.0.12-beta  , v2.0.11-beta  , v2.0.8-beta , v2.0.7-beta

Please consider removing them as well because they might confuse some automated version discovery systems.

**Comment by andreacndn** [comment]
@yurivict we have now marked all 2.x releases as pre-release, could you please check if this solves your problem?

**Comment by yurivict** [comment]
Yes, this solved the problem.

Thank you.
