### ISSUE TITLE
Is it Possible to have some official API for local network device to call with

### ISSUE THREAD

**Issue by cenzwong** [symless/synergy-core#6851]
### Problem ###

A machine only need few key. And I would like to have a network keyboard device which I can control it remotely

### Solution ###

Maybe there will be a Python API which can connect and simulate a synergy server. That Python server can then send key to a particular machine using synergy.

**Comment by andreacndn** [comment]
Hi @cenzwong , unfortunately Synergy currently doesn't offer network APIs.
Maybe you can try to use a Raspberry Pi 400 as network keyboard?
