### ISSUE TITLE
[BUG] Only Mouse works, not Keyboard, with Mac OS Catalina Host and Mac OS Big Sur client

### ISSUE THREAD

**Issue by eapostol** [symless/synergy-core#6857]
### Operating Systems ###

* Server / Host: Mac OS Catalina 10.15.7
* Client: Mac OS Big Sur 11.0.1

### Synergy Version ###

* Server: 1.12.2-stable-a52ccb2d
* Client : 1.12.0-stable-a52ccb2d

### Steps to Reproduce ###

1. Launch Synergy on host machine.
2. Server configured interactively. Host in the middle. Mac Guest Machine (running Big Sur) on right.
3. Launch Synergy on Guest Machine running OS Big Sur,
4. Log on Synergy on Host Machine returns `[2020-11-29T21:40:51] NOTE: client "macs-MacBook-Pro.local" has connected`
5. Log on Synergy on Guest Machine returns ...`Note: connected to server`

Expected:
*Both Mouse and Keyboard Should Work

Actual:
* Only Mouse works

### Log URLs ###

# README & DELETE #

---BEGIN HELP---

Please do not paste entire logs here, it looks really silly. Instead, upload your logs, and share the URLs to the uploaded logs. Here's how you that:

Synergy 1: https://paste.ee/p/Vjdy3 (contains both host and client logs)

### Extra Info ###

# README & DELETE #

* Attach any screenshots

HOST MACHINE CONFIGURATION
<img width="800" alt="synergy-catalina-host-configuration" src="https://user-images.githubusercontent.com/565104/100564074-f0672080-328d-11eb-8d58-062baaf39e24.png">

CONFIRMATION OF CLIENT CONNECTING TO HOST
<img width="701" alt="Screen Shot 2020-11-29 at 9 58 56 PM" src="https://user-images.githubusercontent.com/565104/100564185-4045e780-328e-11eb-84d8-447a37443609.png">

* What maybe causing it?

No idea. The only difference is the OS update on the client machine. It used to work previously.

* Are there any workarounds?

None. Or get another keyboard / mouse and plug it into the client machine. Which makes synergy a moot point, no?

* What other apps are you running?
I was running zeroTier One VPN, thinking there was some confusion tunneling into and office VPN, but nope, that did not work.

* Does it stop you using Synergy entirely?

At the moment, YES.

* Did restarting Synergy or the computer help?

No, neither restarting synergy or restarting my computer helped.

* Is there anything else you can think of

I note that the mouse movement, although working, is somewhat erratic , often pausing briefly and starting to move again.

**Comment by andreacndn** [comment]
Hi @eapostol , thank you very much for your detailed bug report.
I was wondering if these hosts are Virtual machines or physical computers.

Andrea

**Comment by eapostol** [comment]
Hi @andreacndn  thank you for responding. The Big Sur Machine is a physical laptop (Macbook Pro 2018). the "mini-local
" and "bryson" machines are a mac mini and macbook pro, connected from a VPN. I since turned off the VPN to remove those computers from the picture.

Also note that I actually _did test the other way_ i.e had the big sur macbook pro act as a host machine and the catalina OS Macbook pro act as the client and that _did appear to work_ although it is slow with the mouse. However in my use case the big Sur machine is a test machine, so it's not that useful for me development wise to have  the Big Sur machine be the host (where all my work is on the catalina OS machine).

**Comment by novioleo** [comment]
same Issue

**Comment by novioleo** [comment]
reboot my mac help me out for some time.it will be reappear in hours.

**Comment by novioleo** [comment]
@eapostol have you solve it ?

**Comment by eapostol** [comment]
@novioleo this issue is still unsolved for me. I reached out to symless for tech support. I will follow up to see what results of it

**Comment by novioleo** [comment]
@eapostol thks for your reply.Looking forward to further information.

**Comment by Muiphy** [comment]
Does the client use root permission？or Server？

**Comment by novioleo** [comment]
> Does the client use root permission？or Server？

neither client nor client under the root permission.

**Comment by markneumann** [comment]
Happens for me also. 
Server: MacBook Air (Retina, 13-inch, 2018) running Big Sur 14.1.1
Client:  MacBook Pro (MacBook Pro (Retina, 13-inch, Mid 2014) running Big Sur 14.1

Seems to have started with Big Sur...

**Comment by sergioaguila** [comment]
I'm having the same issue here.

Host: Mac OS Catalina
Client: Mac OS Big Sur
Synergy version on both: 1.14.0

For some reason. Some keys from the keyboard like Volume Up / Down actually works.

**Comment by andreacndn** [comment]
This issue is addressed in Synergy 1.14.1 that will be publicly released in the next few days.

**Comment by sergioaguila** [comment]
Awesome. Thanks!!

**Comment by dneprqa** [comment]
Fixed in 1.14.1
In case it happens again please check this article: https://symless.com/help-articles/keyboard-not-working-on-client-but-mouse-works
