### ISSUE TITLE
nothing gets typed on client if server has different keyboard layout

### ISSUE THREAD

**Issue by bellerofonte** [symless/synergy-core#6862]
Hi 
I'm using Synergy v1.12.0-stable on my Mac (server) and Ubuntu (client). 
On Mac I use 2 keyboard layouts: en-US and ru-RU, on Ubuntu - en-US only. 
So when I type smth on Mac using ru-RU layout and then switch to Ubuntu and try to type smth where - nothing is typed. 
I have to move my mouse to Mac, switch layout there and move mouse to the client again. Too inconvenient.

Is it possible to send to client always en-US symbols/keycodes, even if server has another layout? 
I mean server[ru-RU] -> client[en-US]; server[en-US] -> client[en-US]

Or maybe there is a way to remap cyrillic keycodes/keynames to latin ones in config file?

**Comment by bellerofonte** [comment]
recently made PR #6890

**Comment by ignacionr** [comment]
@bellerofonte congratulations on your first PR! Also, your opening an issue and going on and creating a PR for it, is the kind of attitude that makes Open Source carry great value. As explained on the PR comments, I don't believe we can merge as is, but as a general idea it can certainly be considered. Thank you and please keep in touch! This issue will remain open for the time being.
