### ISSUE TITLE
Windows client receive wrong key event when MacOS server is Korean input source

### ISSUE THREAD

**Issue by nereusuj** [symless/synergy-core#6868]
SYNERGY-671

**Comment by andreacndn** [comment]
SYNERGY-671

**Comment by nereusuj** [comment]
Any update?

**Comment by desymless** [comment]
> Any update?

Could you please try the latest release of Synergy? In the initial report, the version used was v.1.11, and we added additional support for international keyboard layouts in Synergy 1.14.2
