### ISSUE TITLE
Pasting from Ubuntu to Mac imessage results in chinese text

### ISSUE THREAD

**Issue by pookiemaker** [symless/synergy-core#6883]
SYNERGY-680

**Comment by pookiemaker** [comment]
This is an example 
https://github.com/symless/synergy-core/issues/6883
栀琀琀瀀猀㨀⼀⼀最椀琀栀甀戀⸀挀漀洀⼀猀礀洀氀攀猀猀⼀猀礀渀攀爀最礀ⴀ挀漀爀攀⼀椀猀猀甀攀猀⼀㘀㠀㠀㌀

**Comment by andreacndn** [comment]
@pookiemaker we are tracking this issue in https://github.com/symless/synergy-core/issues/6839
