### ISSUE TITLE
The keyboard layout (ENG>>Thai) can't  switched on client machine 

### ISSUE THREAD

**Issue by dannycentaury** [symless/synergy-core#6891]
SYNERGY-711

**Comment by nmanovic** [comment]
@dannycentaury , I have the same problem. It looks like the value for the language is taken from the server machine. If you switch the keyboard on the server, it works as expected.
At the same time if you switch the keyboard on the client, it will be reset to the previous value. Interesting to check if the list of keyboard languages are not equal on the server and the client.
