### ISSUE TITLE
Locked out of client machine 

### ISSUE THREAD

**Issue by lilbitzz** [symless/synergy-core#6893]
SYNERGY-716

**Comment by lilbitzz** [comment]
### Operating Systems ###

---BEGIN HELP---

Server: macOS 11.0.1
Client: macOS 10.15.7

---END HELP---

1.12.2-stable-a52ccb2d

---BEGIN HELP---

When my screensaver is running on both machines, I am unable to unlock/wake my client machine intermittently using inputs for either computer. The server inputs work on both machines but using either set of inputs to wake the client machine often achieves the same result: I move the mouse or tap a key to wake the client and see the unlock dialog as usual, but when I enter my correct password and hit enter the screensaver remains on the screen rendering the computer totally unusable—the only way get rid of the screensaver that I have found is a hard reset. I have tried waking the client first using the inputs for that machine but get the same result no matter what inputs I use or what order I wake the machines. Server machine functions perfectly and synergy appears to function perfectly across both machines even when the client is otherwise inoperable (so even though I'm locked out of the machine, synergy is still running on the client as it should). 

In other words, I try to wake my client machine from screensaver and get the usual unlock dialog, but upon entering my password the screensaver remains on the screen with the machine totally inoperable, requiring a hard reset. 

---END HELP---

### Steps to Reproduce ###

---BEGIN HELP---
 
Each of these methods leads to the same result, as I said, intermittently:

1. Wake my server machine from screensaver, then enter password to login. 
2. Wake the client machine from screensaver using the server inputs.
3. Enter my password using server inputs.
4. Screensaver remains on client screen with computer inoperable without a hard reset. 
____________
1. Wake my server machine from screensaver, then enter password to login. 
2. Wake the client machine from screensaver using the *client* inputs.
3. Enter my password using *client* inputs.
4. Screensaver remains on client screen with computer inoperable without a hard reset. 
____________ 
1. Wake my *client* machine from screensaver using server inputs. 
2. Enter *client* password using server inputs.
4. Screensaver remains on client screen with computer inoperable without a hard reset. 
4. Wake server computer using server inputs and enter password to login—server machine works as usual. 
____________
1. Wake my *client* machine from screensaver using *client* inputs. 
2. Enter client password using *client* inputs.
4. Screensaver remains on client screen with computer inoperable without a hard reset. 
4. Wake server computer using server inputs and enter password to login—server machine works as usual.

---END HELP---

No URLs.

---BEGIN HELP---

No logs. Happy to find and submit with instructions. 

---END HELP---

No additional info.

---BEGIN HELP---

* What maybe causing it?
> No clue, and I have no idea why it only happens intermittently. 

* Are there any workarounds?
> Hard reset of client machine. 

* What other apps are you running?
> Chrome, Messages, Flycut — Both machines

* Does it stop you using Synergy entirely?
> Synergy works perfectly but this issue only occurs when Synergy is running. 

* Did restarting Synergy or the computer help?
> Yes. 

---END HELP---

**Comment by lilbitzz** [comment]
One more quick thing to mention: I have never experienced this problem when waking the client machine from screensaver prior to the computer locking itself. Screensaver appears after 20 minutes, computer locks after 30 minutes. If I catch it in that ten minute window everything's fine.

**Comment by jmerkow** [comment]
Any update on this issue?  I am having the same.
