### ISSUE TITLE
Question: Building on Apple sillicon macOS 11 required openssl hack

### ISSUE THREAD

**Issue by schafdog** [symless/synergy-core#6899]
### Problem ###
Building on macOS with brew ARM in /opt/homebrew/ and brew Intel in /usr/local (which is/was the recommended way to do it). 

When building the arm64 arch for some reason the the build tries to link with openssl Intel in /usr/local/opt/openssl instead of the one in /opt/homebrew. 

I am as far as I know using the right tools from /opt/homebrew. 
### Solution ###
My work-around was to replace the symlink to the Intel version with the arm64 in /opt/homebrew/Cellar/openssl/.. 

I now have: 
bin/synergyc: Mach-O 64-bit executable arm64
bin/synergys: Mach-O 64-bit executable arm64

I tried using PKG_CONFIG_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1i/lib/pkgconfig and CFLAGS + LDFLAGS but that did not seem to work. 

### Correct solution ### 
Maybe I am just not doing it right, but some way configure build system to use alternative location of brew. openssl seem to be the only library that didn't work when building. 

### More Info ###
- Since homebrew is getting quite along with arm64 build I will put the arm in /usr/local and intel in /opt/homebrew.

**Comment by andreacndn** [comment]
Hi @schafdog thanks for your suggestion!

**Comment by andreacndn** [comment]
Hi @schafdog , we are still on the optimal build on Apple Silicon, in the meanwhile thank you for your suggestion.

**Comment by schafdog** [comment]
Homebrew is apparently "hard coded" to have ARM in /opt/homebrew and Intel in /usr/local. I tried switching but that wasn't allowed. 

Not sure what you meant by last comment. Do you have a way to build on ARM without my hack?

Ran successfully synergy server on ARM and a Intel client.

**Comment by aquacash5** [comment]
We are changing the way we integrate OpenSSL in CMake #6952. After this change, the macOS becomes really easy to build on.

```sh
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(brew --prefix qt5);$(brew --prefix openssl)" ..
```

This command should work on all versions of macOS as long as you are using Homebrew.
