### ISSUE TITLE
Ubuntu 20.04 LTS SSL Issues

### ISSUE THREAD

**Issue by Plasmarobo** [symless/synergy-core#6902]
### Operating Systems ###

Server: Windows 10
Client: Ubuntu 20.04 LTS
Additional Clients: Ubuntu 16.04 LTS, Windows 10

### Synergy Version ###

Synergy 2: 2.0.12-beta

### Steps to Reproduce ###

Extract Deb File 
`sudo dpkg-deb -R synergy_2.0.12.beta_b1705+e5daaeda_amd64.deb synergy_2.0.12.beta`
Rename Service
`sudo mv synergy_2.0.12.beta/usr/lib/systemd/system/synergy.service synergy_2.0.12.beta/usr/lib/systemd/system/synergy.service.dpkg-new`
Repackage deb file
`sudo dpkg-deb -b synergy_2.0.12.beta synergy_2.0.12.beta-ubuntu-20.04.deb`
Acquire Libssl1.0.0
`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.5_amd64.deb`
Install libssl1.0.0
`sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.5_amd64.deb`
Install corrected deb
`sudo apt-get install ./synergy_2.0.12.beta-ubuntu-20.04.deb`
Launch Synergy
`synergy-config`
Click on sign in with Symless
### Log URLs ###
https://pastebin.com/jYwYSP1k

### Extra Info ###
I suspect this is an issue with using libssl1.0.0 instead of the newer libssl1.1.X
Synergy 2 is working on an older version of Ubuntu, and windows 10.

**Comment by andreacndn** [comment]
Hi @Plasmarobo, could you please confirm if you have the same issue on Synergy 1.13.0?
Thank you!

**Comment by Plasmarobo** [comment]
Just spun up 1.13.0 on my Server and the Ubuntu 20.04 LTS client.
Using the version from the download page and a pro key.

No issues, but I'd really prefer to be using Synergy 2.0.12, I've found it a much better experience.
But it looks like this issue isn't present in 1.13.0

**Comment by andreacndn** [comment]
Hi @Plasmarobo, thanks for taking the time to check and give us feedback.
I am afraid we have stopped the development of Synergy 2, so that we can focus on improving Synergy 1 and releasing the next generation product Synergy 3.
We hope you can either use Synergy 1, or hold on until we release Synergy 3.
