### ISSUE TITLE
Public web site doesn't have downloads for older versions

### ISSUE THREAD

**Issue by hunterpankey** [symless/synergy-core#6911]
I have a Mac Pro 3,1 client that's maxed out on 10.11. Now that there are apparently great, new Synergy features that require 10.14, I'm locked out of upgrading. Synergy 1.11.1, I guess, is the latest compatible release, but it's not available to download, even though the message in the Synergy application has a hyperlink to download it. So I guess this is a UX issue in the client application providing a link to something that doesn't actually exist, though there's clearly a bigger issue here.

**Comment by andreacndn** [comment]
@hunterpankey if you could please contact support@symless.com we'd be pleased to send you the version you need.
Could you please share on the same channel the details of the UX issue you mentioned, including a screenshot of the UI displaying the wrong link and the link that is displayed?

Thanks for your help,
Andrea

**Comment by jelammers** [comment]
Hey Symless, are you not aware that your download page is broken?  It won't let you download any previous version of Synergy 1.

Backstory:  I was able to solve a minor problem with Synergy 1.13-something by upgrading to 1.14-2-stable but the new version introduced a new much much worse-can't-live-with problem so now I desperately want to downgrade ... but no, your download page is broken.

Thanks in advance,
John
