### ISSUE TITLE
Unable to Compile on Windows 10

### ISSUE THREAD

**Issue by IdioticProphet** [symless/synergy-core#6917]
While compiling Synergy on Windows 10 Ver 2004 (OS Build 21292.1010) I get these errors. 

```
W:\Desktop\synergy-core\src\lib\synergy\KeyMap.cpp:1332: error: C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
W:\Desktop\synergy-core\src\lib\synergy\KeyMap.cpp:1338: error: C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
```

This prevents the application from compiling. I don't understand since I have followed the tutorial. It should also be noted that the [Windows ](https://github.com/symless/synergy-core/wiki/Compiling#windows) portion of "Compiling" lists visual studio 2019 professional as a requirement but the link to which leads to a download for VC community 2015

I have installed all of the requirements, uninstalled, and reinstalled them after figuring out it doesn't seem to work. I followed each step to the T. No dice. Any Ideas as to what is going on here or if this is an easy fix I'm too tired to figure out.

**Comment by ignacionr** [comment]
@IdioticProphet hello! Thanks for this report, and let me try to help. My question would be, where are you getting the source code with? The current code on the **master** branch does not match the error messages you shared.
Let's work together on this.

**Comment by IdioticProphet** [comment]
@ignacionr Thanks for the response. Here is my output for the upstream URL
```
PS W:\desktop> cd synergy-core
PS W:\desktop\synergy-core> git config --get remote.origin.url
https://github.com/symless/synergy-core.git
```
and my git log has the most recent pull on `commit 6cdd5a05835ef3e5804b016f0f23e4d270474682`

Heres the more specific code that it has an issue with
![image](https://user-images.githubusercontent.com/20072862/105152519-ec58c180-5acc-11eb-8d0e-2712b0ec6abd.png)
Which appears to be a part of `KeyMap.cpp` under the directories `src/lib/synergy/synlib/KeyMap.cpp`

Oh and I might have left out the full error (not very familiar with Qt) 
```
W:\Desktop\synergy-core\src\lib\synergy\KeyMap.cpp:1332: error: C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
W:\Desktop\synergy-core\src\lib\synergy\KeyMap.cpp:1332: while trying to match the argument list '(synergy::KeyMap::Keystroke::Button, initializer list)'
```

**Comment by ignacionr** [comment]
Well actually we decided not to use that way of initialisation (it was me who had introduced it, but unluckily many of the compilers we need to support will not work with it). I will make sure to merge this new version ASAP and get back to you.

**Comment by ignacionr** [comment]
@IdioticProphet  #6918 will resolve this for you (either wait for it to be merged -we will need one of my friends here to approve-, or you can use the branch this PR comes from instead of master). If you want a manual resolution, the Microsoft compiler will know how to handle that union initialisation, if you add /std:c++latest to the compilation options (or from a dropdown on the C++ section menu if you use Visual Studio for configuring).

Hope this helps. I see you have a good background on Python (envious of that!), so I understand if this C++ particularities may seem arbitrary. Happy to expand on anything you may be interested to know.

**Comment by ignacionr** [comment]
@IdioticProphet good news! As the code was merged, you can safely pull from **master** again and hopefully get it to compile. Do open new issues if you find any. Thanks for this!

**Comment by IdioticProphet** [comment]
@ignacionr  The issue does appear to be fixed! ; however, I do get a rather strange error on the linking stage of building on visual studio. 

For some quick context I opened the synergy-core folder, generated cmake cache and tried to build as is, I changed a few paths to ensure it was short
 ```console
 [2/2] Linking CXX executable bin\synergy.exe
  FAILED: bin/synergy.exe 
  cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=src\gui\CMakeFiles\synergy.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~3\2019\PROFES~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe /nologo src\gui\CMakeFiles\synergy.dir\synergy_autogen\mocs_compilation.cpp.obj src\gui\CMakeFiles\synergy.dir\src\AboutDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\Action.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ActionDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ActivationDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ActivationNotifier.cpp.obj src\gui\CMakeFiles\synergy.dir\src\AddClientDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\AppConfig.cpp.obj src\gui\CMakeFiles\synergy.dir\src\BaseConfig.cpp.obj src\gui\CMakeFiles\synergy.dir\src\BonjourWindows.cpp.obj src\gui\CMakeFiles\synergy.dir\src\CancelActivationDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\CommandProcess.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ConfigWriter.cpp.obj src\gui\CMakeFiles\synergy.dir\src\CoreInterface.cpp.obj src\gui\CMakeFiles\synergy.dir\src\DataDownloader.cpp.obj src\gui\CMakeFiles\synergy.dir\src\FailedLoginDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\Fingerprint.cpp.obj src\gui\CMakeFiles\synergy.dir\src\Hotkey.cpp.obj src\gui\CMakeFiles\synergy.dir\src\HotkeyDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\Ipc.cpp.obj src\gui\CMakeFiles\synergy.dir\src\IpcClient.cpp.obj src\gui\CMakeFiles\synergy.dir\src\IpcReader.cpp.obj src\gui\CMakeFiles\synergy.dir\src\KeySequence.cpp.obj src\gui\CMakeFiles\synergy.dir\src\KeySequenceWidget.cpp.obj src\gui\CMakeFiles\synergy.dir\src\LicenseManager.cpp.obj src\gui\CMakeFiles\synergy.dir\src\MainWindow.cpp.obj src\gui\CMakeFiles\synergy.dir\src\NewScreenWidget.cpp.obj src\gui\CMakeFiles\synergy.dir\src\QSynergyApplication.cpp.obj src\gui\CMakeFiles\synergy.dir\src\QUtility.cpp.obj src\gui\CMakeFiles\synergy.dir\src\Screen.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ScreenSettingsDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ScreenSetupModel.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ScreenSetupView.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ServerConfig.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ServerConfigDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\SettingsDialog.cpp.obj src\gui\CMakeFiles\synergy.dir\src\SetupWizard.cpp.obj src\gui\CMakeFiles\synergy.dir\src\SslCertificate.cpp.obj src\gui\CMakeFiles\synergy.dir\src\SynergyLocale.cpp.obj src\gui\CMakeFiles\synergy.dir\src\TrashScreenWidget.cpp.obj src\gui\CMakeFiles\synergy.dir\src\TrayIcon.cpp.obj src\gui\CMakeFiles\synergy.dir\src\VersionChecker.cpp.obj src\gui\CMakeFiles\synergy.dir\src\Zeroconf.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ZeroconfBrowser.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ZeroconfRegister.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ZeroconfServer.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ZeroconfService.cpp.obj src\gui\CMakeFiles\synergy.dir\src\ZeroconfThread.cpp.obj src\gui\CMakeFiles\synergy.dir\src\main.cpp.obj src\gui\CMakeFiles\synergy.dir\res\win\Synergy.rc.res src\gui\CMakeFiles\synergy.dir\synergy_autogen\PNK5WDWK6L\qrc_Synergy.cpp.obj src\gui\CMakeFiles\synergy.dir\synergy_autogen\PR4VE6O6XJ\qrc_Languages.cpp.obj  /out:bin\synergy.exe /implib:src\gui\synergy.lib /pdb:bin\synergy.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:windows /NODEFAULTLIB:LIBCMT  src\lib\shared\shared.lib  C:\ProgramData\Anaconda3\Library\lib\Qt5Widgets.lib  C:\ProgramData\Anaconda3\Library\lib\Qt5Network.lib  "C:\Program Files\Bonjour SDK\Lib\x64\dnssd.lib"  src\lib\arch\arch.lib  src\lib\base\base.lib  C:\ProgramData\Anaconda3\Library\lib\Qt5Gui.lib  C:\ProgramData\Anaconda3\Library\lib\Qt5Core.lib  C:\ProgramData\Anaconda3\Library\lib\qtmain.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D W:\Desktop\synergy-core\out\build\x64-Release\src\gui && set PATH=%PATH%;C:/ProgramData/Anaconda3/Library/bin && C:\ProgramData\Anaconda3\Library\bin\windeployqt.exe W:/Desktop/synergy-core/out/build/x64-Release/bin/synergy.exe""
  The input line is too long.
  ninja: build stopped: subcommand failed.
```

Says command is too long, in which it definitely is! IT definitely seems ot be because it tries to link many many many objects all at once. Am I missing something here? 

Not a new problem because I wasn't sure if I'm just clueless about visual studio or if its an actual bug
