### ISSUE TITLE
Synergy GUI did not work on windows

### ISSUE THREAD

**Issue by XiaoliChan** [symless/synergy-core#6923]
### Operating Systems ###
Windows 10 19042.746

### Synergy Version ###
master latest commit

### Steps to Reproduce ###
I used this commands to build synergy
```
$env:CMAKE_PREFIX_PATH="C:\Qt\5.12.5\msvc2017_64"
mkdir build
cd build
cmake -G "Visual Studio 16 2019"  -DCMAKE_BUILD_TYPE=release ..
. ./version
msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Release /m
.\bin\Release\unittests.exe
```

After complied, the synergy.exe run with no reply. (openssl already installed by using choco)

**Comment by andreacndn** [comment]
SYNERGY-772

**Comment by XiaoliChan** [comment]
`unittests.exe` said all things is OK.

**Comment by XiaoliChan** [comment]
@ignacionr Well, I spent many times to rebuild it. :)

Now ,I just waiting for the new commit, Thank you !

**Comment by ignacionr** [comment]
Dear @XiaoliChan if you want, you can build directly from the PR's source branch. That will give you a working product.
And truly thank you for the time and interest in our product.

**Comment by XiaoliChan** [comment]
OK, I will switch to that commit and test it. @ignacionr

**Comment by ignacionr** [comment]
@XiaoliChan one of my colleagues was able to review and approve, so the code is merged into **master**. Thank you once again, and we count with your help again next time.

**Comment by XiaoliChan** [comment]
@ignacionr Nice merge, I will close this comment until I rebuild it.

**Comment by XiaoliChan** [comment]
@ignacionr It worked pretty good ! Thanks for your help. :)
