### ISSUE TITLE
preserveFocus does not appear to work on the server

### ISSUE THREAD

**Issue by reversefold** [symless/synergy-core#6929]
### Operating Systems ###
Server: Windows 10 Pro 10.0.19042 Build 19042
Client 1: Windows 10 Pro 10.0.19042 Build 19042
Client 2: macOS Catalina 10.15.7 (19H114)

### Synergy Version ###
Server: 1.13.0-stable-bdb8f767
Client 1: 1.13.0-stable-bdb8f767
Client 2: 1.13.0-stable-863f70a5

### Steps to Reproduce ###

Set `preserveFocus = true` on the Server screen in the config.

### Log URLs ###

The log shows nothing relevant.

### Extra Info ###

Restarting Synergy and upgrading Synergy to the latest (v1) version did not seem to help.

**Comment by andreacndn** [comment]
SYNERGY-794
