### ISSUE TITLE
(-.-)Zzz...

### ISSUE THREAD

**Issue by neilrichins** [symless/synergy-core#6932]
### Problem ###

Synergy lacks native drives for many operating systems like Chrome OS , Android and iOS

### Solution ###

VNC  server is a common open source application available on most all modern platforms.

If Synergy were to support a virtual VNC client as one of it's connection modes, then a virtual window could be positioned just off screed so that when a user moved the mouse in that space, the keyboard and mouse interactions would be relayed to the VNC host.

### More Info ###

Ms RDP, X2X, No Machine, and X2GO are great protocols for remote access but lack the support found in VNC across a wide platform base.

The cursor on may not be displayed on some systems without a mouse installed, likewise some VNC servers may hide the cursor or be slow in updating the cursor.  The focus of Virtual Vnc Support for Synergy should not be in trying to resolve or recommending VNC servers, but in providing basic KVM support for systems that otherwise could not be supported by Synergy.  

Adding Virtual VNC support to Synergy would significantly increase its user base by leveraging an industry standard and circumventing the need for the Synergy development team to design, create, test, support and pass OS app vetting, and deploy software in every operating system it works with.

**Comment by andreacndn** [comment]
Thank you @neilrichins for the valuable idea! We' consider it for the roadmap.

**Comment by neilrichins** [comment]
<bump>

**Comment by neilrichins** [comment]
Great follow up team!  
Keep up the good work.

No use keeping this open if no one is going to work on in nearly 2 years.
It's subtle, but I get what you're saying.
Have a nice day.
