### ISSUE TITLE
Utf-8 keys are not detected

### ISSUE THREAD

**Issue by absmoca** [symless/synergy-core#6940]
Server : macOS Big Sur 11.2
Client : Raspberry PI 4 (Linux raspberrypi 5.10.11-v7l)

Barrier Server don't send keys with accents : é è à ç ...

A GIF speaks more than a description : [GIF](https://i.ibb.co/4gkfTxD/71-A1-A86-B-FE68-471-D-8-C0-E-B5-FE6383-AA4-D.gif)

**Comment by andreacndn** [comment]
SYNERGY-819

**Comment by sheepdestroyer** [comment]
I observe similar behavior on my setup but not all the time. 
Usually, accented letters and other AZERTY characters stop working after the server wakes up from sleep.

Server : win 10 FR - AZERTY keyboard
Client : Fedora 33

Sometimes, I can't send é è à ç ... to the client, even when restarting synergy on either sides.
What usually works to solve the problem, and the only way I found, is to fully reboot the Windows server
