### ISSUE TITLE
One release per commit makes following Synergy repo very noisy

### ISSUE THREAD

**Issue by sheepdestroyer** [symless/synergy-core#6948]
I have a notification set up for new releases of Synergy as I am expecting fixes to my current bugs in the next official build.

Hoewver I recently started to receive emails several times a day as it seems you are making full "snapshot" releases for each handful of commits.

It may be better to just use the tag functionallity that does not emit an alert for those pre-release snaphots, instead of making full releases each time.

**Comment by andreacndn** [comment]
SYNERGY-822

**Comment by sheepdestroyer** [comment]
No improvement in your process since?
I see you are doing both tags and release for each -snapshot, it's quite redondant

I would really like to be notified when you release a stable build for real, not many times a day like currently...
