### ISSUE TITLE
wikis out of date

### ISSUE THREAD

**Issue by srl295** [symless/synergy-core#6963]
### Operating Systems ###
n/a

### Synergy Version ###
n/a

### Steps to Reproduce ###

1. goto <https://github.com/symless/synergy-core/search?q=v1-dev&type=wikis>
2. goto <https://github.com/symless/synergy-core/wiki/Getting-Started>

Expected: wikis contain up to date info

Actual: wikis mention branch `v1-dev` which is nowhere to be seen.

**Comment by andreacndn** [comment]
SYNERGY-884
