### ISSUE TITLE
fails to generate server certificate on Fedora

### ISSUE THREAD

**Issue by notEthan** [symless/synergy-core#6970]
on Fedora (core 33) synergy server fails to start, with:

```
ERROR: secure socket error: tls certificate doesn't exist: /home/ethan/.synergy/SSL/Synergy.pem
```

I did not have openssl installed. after a `dnf install openssl` the server started fine.

I think the rpm should indicate its dependence on the openssl package, though I know relatively little of rpm.

### Synergy Version ###

synergys 1.13.1-stable.b41-063519a8, protocol version 1.6

### Steps to Reproduce ###

install synergy, without openssl installed - the most recent synergy fedora rpm is for 30 and I'm on 33 but this doesn't appear to be a problem.

attempt to start synergy server.

no error message about failing to create the certificate or not being able to use openssl, but errors trying to use the Synergy.pem file that was not created.

**Comment by andreacndn** [comment]
SYNERGY-914
