### ISSUE TITLE
Windows 10 Synergy Server problems copying clipboard to Ubuntu 20.04 Synergy Client

### ISSUE THREAD

**Issue by SpaceCowboy850** [symless/synergy-core#6980]
### Operating Systems ###

First seen with
Server:  Windows 10 Synergy 1.8.8 GUI as Server
Client:  Ubuntu 20.04 with user compiled synergyc 1.13.2-snapshot.b1-f767aa3a, protocol version 1.6

Second Attempt with 
Server:  User compiled Windows 10 synergys 1.13.2-snapshot.b1-f767aa3a, protocol version 1.6
Client:  Ubuntu 20.04 with user compiled synergyc 1.13.2-snapshot.b1-f767aa3a, protocol version 1.6

### Steps to Reproduce ###

1. Ctrl-C on text in sublime on Windows 10 machine
2. Move mouse cursor to sublime on Ubuntu 20.04 machine
3. Ctrl-V in sublime in Ubuntu 20.04.
    ALT:  Ctrl-Shift-V in console in Ubuntu 20.04
    ALT:  Mouse menu, paste in sublime in Ubuntu 20.04

Expected:  Text copied from Windows 10 is pasted into Sublime/console/etc
Actual:  Nothing happens.

Note:  Reversing steps works - i.e. Copy on Ubuntu 20.04 and paste in Windows 10 works as expected.

### Log URLs ###

HTTP links didn't work...

### Extra Info ###

I tried server with 1.8.8 that I had used with Ubuntu 16.04 and client 1.8.8 initially.  I have used this original setup for years and it has been fine.

When I first moved to 20.04, I attempted to use 1.8.8 client, but could not because of a qt4 dependency that 20.04 has deprecated.

That's when I built 1.13.2 on Ubuntu.

**Comment by andreacndn** [comment]
SYNERGY-939

**Comment by SpaceCowboy850** [comment]
Note, falling back to 1.12.2-stable on the Ubuntu 20.04 client everything works.
