### ISSUE TITLE
Is Hebrew language supported? 

### ISSUE THREAD

**Issue by eriauerbach** [symless/synergy-core#6982]
Hello, 
I know that in the far past I opened a ticket that Hebrew was not supported in Synergy when the Client PC is writting in Hebrew language. Wanted to ask if this is still an issue or was it already solved? 

Thanks,
Eri

**Comment by andreacndn** [comment]
SYNERGY-947

**Comment by eriauerbach** [comment]
What do you mean by that? Is this a version number? Is it there?

**Comment by andreacndn** [comment]
@eriauerbach Task automatically created in our development management platform.
We are not aware of any specific issue with Hebrew language.
