### ISSUE TITLE
Clipboard paste disconnects client even when clipboard sharing is disabled on server (two Macs)

### ISSUE THREAD

**Issue by fnl** [symless/synergy-core#7019]
I am using Synergy 1.13.1-stable-63519a8 on Mac OS (Client: Big Sur 11.3; Server: Catalina 10.15.7) and have disabled clipboard sharing (if I enable clipboard sharing, Synergy basically doesn't work at all, I cannot "enter" my client's screen).

However, even in that clipboard disabled state, when the cursor and focus is on to the client, and I copy some piece of text, the moment I try to paste it, the server looses control of the client and the mouse cursor completely disappears on the client.

**Comment by andreacndn** [comment]
SYNERGY-1016
