### ISSUE TITLE
Meta shows up as hotkey when registered, but doesn't actually work.

### ISSUE THREAD

**Issue by janacm** [symless/synergy-core#7021]
### Operating Systems ###

Server: MacOS Big Sur
Client: Windows 10 

### Steps to Reproduce ###

1. Add keyboard shortcut from server: `meta + ctrl + f10`
2. Press `meta + ctrl + f10` on server's keyboard:

Expected: Keyboard shortcut is executed
Actual: Nothing is executed. However, when I leave out the `meta` key and just press `ctrl + f10` the action is triggered.

![image](https://user-images.githubusercontent.com/2055312/119682348-d196b080-be10-11eb-9141-f3e9ea2adbfd.png)

Tried with a variety of different shortcuts and actions. Same issue.

**Comment by andreacndn** [comment]
SYNERGY-1018
