### ISSUE TITLE
Unable to run synergy in linux

### ISSUE THREAD

**Issue by BinchaoPeng** [symless/synergy-core#7054]
After I compiled with CLI and QT，the target files is in `bulid\bin`, but I can't run it. It shows command is not found.
And I found the compiled version is 1.x, so how to compiled 2.x version.

**Comment by BinchaoPeng** [comment]
I use `git check master`

**Comment by andreacndn** [comment]
SYNERGY-1070

**Comment by andreacndn** [comment]
Do you have issues with compiling Synergy 1 or Synergy 2? 
Synergy two is discontinued and not supported

**Comment by BinchaoPeng** [comment]
yes,I compile synergy 1，after compiling， I type `synergy` in `bulid\bin`, it shows "command not found"
