### ISSUE TITLE
Copying from server and pasting to client doesn't work

### ISSUE THREAD

**Issue by raspberrypieman** [symless/synergy-core#7062]
I am using Barrier version 2.3.3-release-3395cca9 on Windows/10 as the server and
Barrier version 2.3.2-Release-00000000 (Build Date: Monday , 23 March 2020) running on Ubuntu 20.04.2 LTS as a client.

When I copy some text on the server, then mouse over to the client, and paste - it does not work, it just pastes whatever was already in the clipboard on the client.

It is OK when I copy on the client and paste on the server.

I noticed there as an issue #5502 similar to this but has been closed - is it fixed, if so which version?

**Comment by andreacndn** [comment]
SYNERGY-1107

**Comment by andreacndn** [comment]
Hi @raspberrypieman I'd recommend you try the latest version of Synergy, as it should satisfy your needs.
In case it doesn't work out for you, you can always ask for a no-hassle refund within 30 days.
