### ISSUE TITLE
Mouse moves on server while moving on the client

### ISSUE THREAD

**Issue by IanMoroney** [symless/synergy-core#7071]
### Operating Systems ###

Server: MacOS 11.4
Client: Windows 10 - 21H1

### Synergy Version ###

Synergy 1 version 1.14.0

### Steps to Reproduce ###

On the server's primary screen, have a window open (such as slack) that has windows that change colour on hover (slack messages for example change colour on hover)

Move mouse to client
Move mouse up and down fast
You'll notice the "mouse" is moving on the server primary screen (no cursor) when you move the mouse on the client.
The effect appears as if the mouse cursor is "locked" on the primary screen on the server, in the centre, and hidden but it still moves and resets to the centre if you move the mouse fast enough on the client.

Video: https://drive.google.com/file/d/1A77oQ9WA90Dza-JkRrQs2XxmP005zBQK/view?usp=sharing

**Comment by andreacndn** [comment]
SYNERGY-1164
