### ISSUE TITLE
Issue with configuring QT Project (OpenSSL not found CMake)

### ISSUE THREAD

**Issue by mapuya19** [symless/synergy-core#7073]
Hi, attempting to compile on macOS 11.2.3 (Big Sur) w/ Qt 5.12.11.

Worked fine on my Windows machine, but for some reason during the configuration process (after opening project in Qt Creator), it says OpenSSL is not found.

> CMake Error at /usr/local/Cellar/cmake/3.21.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
>   OPENSSL_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.21.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/Cellar/cmake/3.21.1/share/cmake/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
>   CMakeLists.txt:332 (find_package)

Should note that I installed OpenSSL via Homebrew already.

Any ideas? Thanks!

**Comment by abatyiev** [comment]
Hi!
Think the problem is in cmake temp files. You should remove synergy build folder.
If this will not help - try to reinstall openssl
```
brew uninstall openssl
brew remove openssl
brew install openssl
```
Also recheck all compile steps from [wiki](https://github.com/symless/synergy-core/wiki/Compiling)
