### ISSUE TITLE
synergy on lenovo chrome book

### ISSUE THREAD

**Issue by the-gambit-bandit** [symless/synergy-core#7075]
Hey i have a question on my lenovo chrome book iv been able to download synergy and even connect everything the only thing that does'nt work is even though it even tells me its going to the screen of the chrome book the chromebook mouse doesnt move but on all 3 other computers it has no problem what so ever

**Comment by andreacndn** [comment]
Hi @the-gambit-bandit I am afraid Synergy doesn't support ChromeOS
