### ISSUE TITLE
Where is the 'free' unlicensed version?

### ISSUE THREAD

**Issue by hb9eue** [symless/synergy-core#7076]
Hi

I have been using synergy for ages. There was always a debian package.

Now I updated my machines to debian bullseye and that package is not longer included, worse, the existing one got de-installed. So I followed the download link to: https://github.com/symless/synergy/releases which does not exist anymore. But searching github for compiled packages I got to: https://symless.com/synergy/purchase

No I don't need to buy a support license. I just want to keep using this great opensource tool without needing to compile from the source myself.

Why can't I find the unlicensed version anywhere anymore?

-Benoit-

**Comment by andreacndn** [comment]
Hi Benoit, 

The packaged version of Synergy is available only for customers.

Best regards,
Andrea
