### ISSUE TITLE
Mouse still moves to the server display after application on the client (Windows) gets pointer lock

### ISSUE THREAD

**Issue by andyearnshaw** [symless/synergy-core#7079]
### Operating Systems ###

Server: macOS 10.15.7
Client: Windows 11 beta (version 21H2; build 22000.132)

### Synergy Version ###

![image](https://user-images.githubusercontent.com/1826067/130782156-54402392-fa72-4f8b-a995-46ff6ab10d5d.png)

### Steps to Reproduce ###

1. After connecting client to server, open a modern web browser (e.g. Chrome, Firefox, Edge)
2. Visit https://mdn.github.io/dom-examples/pointer-lock/
3. Click the red dot in the demo
4. Move your mouse towards the server display

Although the mouse is supposedly "locked" to the browser, once it reaches the point where it crosses over to the server display then the browser no longer receives the mouse events and the server receives mouse input as it would if the mouse were not locked.

### Extra Info ###

It occurred to me to try this when I noticed the mouse does not work for the game _Genshin Impact_ once the game tries to obtain pointer lock. It seems like the two issues could be related so I have not submitted an issue for the game as this one seems easier to test than downloading a 20GB game. The behaviour is different in the game, however: where the web browser works as expected up until the point the mouse crosses over to the server display, the game does not work as expected at all -- nothing happens when you move the mouse.

**Comment by andreacndn** [comment]
SYNERGY-1177
