### ISSUE TITLE
Huge bug: Keyboard doesn't type on client, when server is focused on password field

### ISSUE THREAD

**Issue by IanMoroney** [symless/synergy-core#7083]
### Operating Systems ###

Server: macOS Big Sur
Client: Windows 10 21H1

### Synergy Version ###
1.14.0

### Steps to Reproduce ###

On server:
Go to any website page with a password field, such as : https://session.bbc.co.uk/session?ptrt=https%3A%2F%2Faccount.bbc.com%2Faccount%2Ftv&policy=tv

Click into the password field. Don't type anything.

Move mouse onto the client, open a browser and start typing into the address field.
The keyboard types into the password field on the server instead of the address field on the client.

**Comment by andreacndn** [comment]
@IanMoroney this has been addressed in 1.14.1, you can find the release candidate at https://symless.com/synergy/releases/synergy-1-14-1-release-candidate
