### ISSUE TITLE
Keyboard does not work on the client screen when the server at the current terminal window begins to switch to the client

### ISSUE THREAD

**Issue by michaelzhye** [symless/synergy-core#7086]
The keyboard does not work on the client screen when the server at the current terminal window begins to switch to the client, but the mouse works ok.
When I meet this case, I often switch windows from terminal to other any window in server host and move the mouse to client window again, then keyboard and mouse are all working good in the client. Is it a bug?

### Operating Systems ###
Server: MacOS BigSur 11.5.2
Client: Ubuntu Desktop 20.04 LTS

### Synergy Version ###

Synergy server:  `1.14.0-stable-67d824b8`
Synergy client :  `1.14.0-stable-67d824b8`

### Log  ###
Haven't any error log in synergy.log yet, all is INFO log

**Comment by andreacndn** [comment]
SYNERGY-1224
