### ISSUE TITLE
Clipboard not cleared by client, client keeps grabbing and updating the clipboard once per second

### ISSUE THREAD

**Issue by george2050** [symless/synergy-core#7087]
### Operating Systems ###

Server: Windows 10
Client: macOS Big Sur

### Synergy Version ###

Synergy 1: 1.14.0-stable.b4-67d824b8
Synergy 2: 1.14.0-stable.b4-67d824b8

### Steps to Reproduce ###

1. Copy photo on server.
2. Pastes just fine in other applications on server.
3. Move cursor to client screen.
4. Photo not in clipboard in client.
4. Move back to server screen.
5. Try to paste the photo again on the server -> nothing in clipboard.

Expected: Clipboard not cleared by client
Actual: Client keeps grabbing and updating the clipboard once per second (see logs)

### Log URLs ###

Server logs: https://pastebin.com/aFrfuwB9
Client logs: https://pastebin.com/8rDYTt1C

### Extra Info ###
Same behavior with or without TLS.
Tried restarting both server and client countless times, same behavior.
Plain text copy paste works fine, as in i can copy paste to and from the server and client, but the server logs keep showing that client grabbed and updated the clipboard once per second.

**Comment by andreacndn** [comment]
SYNERGY-1226
