### ISSUE TITLE
Linux integration tests crash since #7038

### ISSUE THREAD

**Issue by yan12125** [symless/synergy-core#7106]
### Operating Systems ###

Server: Arch Linux
Client: N/A

### Synergy Version ###
```
$ ./build/bin/synergys --version
synergys 1.14.2-snapshot.b1-65ec5046, protocol version 1.7
Copyright (C) 2012-2021 Symless Ltd.
Copyright (C) 2008-2014 Nick Bolton
Copyright (C) 2002-2014 Chris Schoeneman
```

### Steps to Reproduce ###

1. `cmake -B build -D CMAKE_BUILD_TYPE=Debug`
2. `make -C build -j3`
3. `./build/bin/integtests`

Expected: tests pass
Actual: tests crash (see the log below)

### Log URLs ###

[integtests.log](https://github.com/symless/synergy-core/files/7350699/integtests.log)

### Extra Info ###

This line crashes:

https://github.com/symless/synergy-core/blob/65ec5046965f2915f56478156e6b34f8bf90c282/src/lib/synergy/AppUtil.cpp#L52

That class seems a singleton, but not correctly initialized. Before #7038, integtests run fine.

**Comment by andreacndn** [comment]
SYNERGY-1292

**Comment by yan12125** [comment]
I still get crashes in Linux integration tests as of 9cedc57dc393fb5eea497ec65d72c6d7898fc1e9

**Comment by yan12125** [comment]
This seems the same issue as #7244. Closing as the newer issue includes more details.
