### ISSUE TITLE
While CMD is in focus move mouse to client and keyboard layout will change

### ISSUE THREAD

**Issue by arhi** [symless/synergy-core#7107]
### Operating Systems ###
Server: Windows 10
Client: MacOS 11.6

### Synergy Version ###
1.14.1-stable-37bbd3c0

### Steps to Reproduce ###

1. Start "cmd" on server
2. while CMD is in focus move mouse to client and keyboard layout will change

**Comment by andreacndn** [comment]
SYNERGY-1295
