### ISSUE TITLE
MacOS: Cmake warning compiling

### ISSUE THREAD

**Issue by simplesisu** [symless/synergy-core#7129]
Hi,

Firstly thanks for making this open-source.

I'm getting this error while trying to compile and build the app with cli:

"
catalina@Catalina build % cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
make

with that command I am getting this error:

-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.a (found version "3.0.1")  
CMake Error at CMakeLists.txt:363 (message):
  The submodules were not downloaded! GIT_SUBMODULE was turned off or failed.
  Please update submodules and try again.

-- Configuring incomplete, errors occurred!
See also "/Users/catalina/Desktop/synergy-core-master/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
catalina@Catalina build % 

How can I update submodules or solve this issue?

[synergy build.txt](https://github.com/symless/synergy-core/files/7806552/synergy.build.txt)

Best regards,

**Comment by simplesisu** [comment]
Nothing?

**Comment by Franck-Nein** [comment]
@simplesisu
Did you try:
<code>git submodule update --init</code>

**Comment by xu20160924** [comment]
Facing the same  problem on Mac

**Comment by simplesisu** [comment]
I will give this a second try during the week, after that I will update the issue!
