### ISSUE TITLE
New "Switch to screen" hotkey action: "Cycle"

### ISSUE THREAD

**Issue by robmonte** [symless/synergy-core#7131]
### Problem ###

I want to use only a single keyboard shortcut to switch between my synergy devices.

### Solution ###

When configuring a hotkey action, one of the choices is "Switch to screen" which lists out all of my synergy device names. I think a new option called "Cycle" should be added as a choice here, which means that each time I press the hotkey it will go through my list of devices.

### More Info ###

Say I set Shift+ScrollLock to be my "Switch to screen" hotkey and that I have 3 devices: A windows server, a linux client, and a mac client. If my cursor begins on windows, pressing Shift+ScrollLock should give the cursor to the linux client. Upon pressing Shift+ScrollLock again, the cursor activates on the mac client. A final Shift+ScrollLock activation returns the cursor back to the windows server device.

**Comment by vitalPixel** [comment]
Hi @robmonte , thanks for the suggestion.

We're currently developing the next major version of Synergy and, while we can't promise anything, your comments will certainly be helpful 👍
