### ISSUE TITLE
Feature Request: Improve "Switch after waiting" with "Glance Suppression"

### ISSUE THREAD

**Issue by zackees** [symless/synergy-core#7180]
### Problem ###

The "switch after waiting" feature seems aimed at preventing the mouse from accidentally moving across computers. The current feature as-is works 'ok' but feels sticky. I think it can be made much better by taking into account of the vector of motion. See below for solution.

### Solution ###

"Glance Suppression"

This feature looks at the direction vector of the mouse and filters whether to allow the mouse to cross over depending on the vector of mouse motion.

Assume a screen layout that is side-by-side:

  * If the mouse is moving slowly, then the mouse is locked to the current screen
  * else
    * When the user moves side to side
      * the filter should allow the mouse movement to pass across computers
      * When the user is moving up / down (and drifts to the border) then the filter should prevent the mouse from moving over.

Algorithm

  1. Take the mouse vector computed from last few 3 frames
  2. If the mouse touches boundary
    a. If the mouse just crossed over 1000 ms ago, then allow the cross over again
    b. else if the speed of the mouse is below a threshold, suppress the cross over
    c. else If the `dot_product(mouse_vector, screen_vector) >= cos(45 degrees)`, then suppress the cross over, else allow to pass

I think this would cover all the use cases and perform better than the status-quo.

### More Info ###

Thanks for a great product!

**Comment by vitalPixel** [comment]
Hey @zackees , thank you so much for the suggestion.

I agree something like this could be an improvement over the "switch after waiting" feature but to be honest it doesn't fit our strategic priorities in the short term.

However, we'll definitely keep this on file and I hope we can revisit in the future.
