### ISSUE TITLE
Headless synergy server

### ISSUE THREAD

**Issue by avilleret** [symless/synergy-core#7207]
As described [on this forum post](https://forums.symless.com/topic/661-headless-synergy-server/), it would be very useful to be able to share the mouse and the keyboard connected to a headless system.

For example, in my current setup, my mouse and keyboard are connected to my laptop running Manjaro. 
I have to keep it up and running to share mouse and keyboard.
I would like to move the synergy server to a small, low power computer like a Raspberry Pi and connect my mouse and keyboard to this headless computer. 
However, Synergy is based on some X11 libraries to grab the mouse and keyboard afaik, thus we need to run a desktop envionment to use it. I would like to avoid that.

Is it something Synergy developers could consider for a future release ?

Kind regards

**Comment by vitalPixel** [comment]
Hi @avilleret , thanks for you suggestion.

While a very interesting idea, this is not something we currently have in our roadmap.
This is not to say it won't happen, just that it is not aligned with our short-term priorities.

We do have builds for the Raspberry Pi though, so maybe you can achieve a similar result by using a Pi with a desktop environment as the server?
I understand it's not as elegant, but it might be a decent workaround for the time being.


Thanks,
Francisco

**Comment by avilleret** [comment]
Hi @vitalPixel,

thanks for your reply.
Of course having a desktop environment is a workaround. But in that case, is it possible to disable the server screen in the Synergy configuration ?
Since this computer won't have a display attached to it, I don't want my mouse to be lost on this display. 
And I only want this computer to forward the mouse and keyboard to others without controlling the server's cursor.
Is it already feasable ?

**Comment by ig0rmin** [comment]
I have RPi as a headless Synergy server. You can wrap the RPi screen by manually editing links like this:

```
section: links
    desktop-a:
      right = desktop-b
   rpi:
      left = desktop-a
      right = desktop-b
   desktop-b:
     left = desktop-a
end
```
Or you can disable links at all and switch between screens only by shortcuts.

The problem with this approach is that sometimes (when client disconnects) cursor goes to the invisible RPi screen and you need manually return it back. So it kinda works, but not so smooth as it could if Synergy had explicit headless server support.

**Comment by vitalPixel** [comment]
Thanks for chiming in @ig0rmin , that sounds like a great workaround!

We could probably document it in our public knowledge base.
