### ISSUE TITLE
Nick: [Wayland] "was a high priority until"...

### ISSUE THREAD

**Issue by christoofar** [symless/synergy-core#7256]
It was a high priority until Ubuntu decided to revert to X as the default in 18.04. So now it's a low priority, but we do plan to add support, but it requires a huge rewrite of a lot of the Linux code. I appreciate that Fedora is championing it, but it's not the most popular distro. Since Ubuntu 18.04, we've heard almost nothing about Wayland from our users (literally not mentioned once in any support tickets over the last 2 months-- not to be confused with GitHub issues, but that's also been quiet). So it'd be really unwise for us to prioritize it above more serious issues.

_Originally posted by @nbolton in https://github.com/symless/synergy-core/issues/5803#issuecomment-410053220_

**Comment by christoofar** [comment]
I wonder if Nick regrets this now since Pipewire is now fully out on most distros and the number of X.org users is rapidly plummeting.

**Comment by desymless** [comment]
Hi 👋 We are planning to add Wayland support in Synergy, the main issue right now is that Wayland doesn't have an API we can work with, and looks to be designed to block emulated human inputs. Hence we need to find a different way to support Synergy on Wayland, which unfortunately will take time to develop.

For now, there is an implementation that uses the wlroots compositor - https://github.com/r-c-f/waynergy

**Comment by ariktaurendil** [comment]
> Hi wave We are planning to add Wayland support in Synergy, the main issue right now is that Wayland doesn't have an API we can work with, and looks to be designed to block emulated human inputs. Hence we need to find a different way to support Synergy on Wayland, which unfortunately will take time to develop.

Did you checked out this?

http://who-t.blogspot.com/2022/12/libei-opening-portal-doors.html

**Comment by christoofar** [comment]
I'm caught between two worlds;  where synergy can't play on Wayland... but then Alacritty can't ever seem to slay its painting/damage X race bugs, so I run Xorg on host and Wayland on QEMU.

**Comment by sheldonmaschmeyer** [comment]
It might be a duplicate of #4090 but it is locked for comments from the rabble. 
Until recently, more apps worked in X11 but were broken in Wayland. 
However, in 2023/24 I am using Ubuntu 23.10 (not a polished LTS). In X11 my Wacom stylus stopped working but works perfectly in Wayland. In X11, Ubuntu RDP will only mirror, will not extend to my iPad screen but, extend works in Wayland (not perfect but usable). So, as we transition slowly to Wayland, an increasing number of apps will have issues in X11 (perhaps less testing in X11). This is from observation.

**Comment by R3ITOSv87** [comment]
> Duplicates #4090

@nbolton Why did you closed this as completed? 

No Wayland Support = Not Completed  

I would like to know: when will you implement this?

**Comment by LiGoldragon** [comment]
It will be easier to implement this without synergy with a minimal amount of code. Then, synergy can re-use the API thus created.

**Comment by nbolton** [comment]
Fixed by: https://github.com/symless/synergy/pull/7449
