### ISSUE TITLE
Windows Synergy service install

### ISSUE THREAD

**Issue by DieselDriver** [symless/synergy-core#7337]
Same issue.
How can I install the synergyd service?
I downloaded the synergy-1.xx.xx.xx-adxxxxx-windows-10-amd64.zip file - there is no installer included.
Here I could fine the ame issue - https://github.com/symless/synergy-core/issues/4786

How can I install the Synergy service?

Thanks.

**Comment by nbolton** [comment]
Hello, could you let us know where you found the file?

**Comment by DieselDriver** [comment]
Solved - I used the .msi installer file there the service also will be installed.
