### ISSUE TITLE
Make wiki editable by everyone

### ISSUE THREAD

**Issue by mmvanheusden** [symless/synergy-core#7338]
Currently, the wiki can't be edited by regular GitHub users. Only (I assume) a small group of people.

I think this must change, I made an edit locally today but I have nowhere to propose that edit, because it is read-only.

**Comment by nbolton** [comment]
Unfortunately, we had a big problem with spammers, so we had to make it read-only.

**Comment by nbolton** [comment]
I know, it's sad. Let me know what changes you want to make and I'll be more than happy to make them for you.
