### ISSUE TITLE
Is synergy-core Synergy1 or Synergy3?

### ISSUE THREAD

**Issue by jiapei100** [symless/synergy-core#7340]
### Problem ###

Sorry for my naive question: Is **synergy-core** Synergy1 or Synergy3?

### Solution ###

Just ask this naive questino: Is **synergy-core** Synergy1 or Synergy3?

Cheers

**Comment by nbolton** [comment]
Hello, Synergy 1 is built entirely from Synergy Core, and Synergy 3 uses Synergy Core.
