### ISSUE TITLE
Linux: synergy core won't start on fresh Ubuntu 24.04 install, cannot add other computers

### ISSUE THREAD

**Issue by chriswalken** [symless/synergy-core#7347]
### Operating Systems ###

---BEGIN HELP---
Server: Ubuntu 24.04
Client: Windows 10
---END HELP---

### Synergy Version ###

---BEGIN HELP---
Both v3.0.79.1-rc3 and v3.1.2-beta
---END HELP---

### Steps to Reproduce ###

---BEGIN HELP---

1. Download and install synergy .deb from website
2. Start synergy from app launcher
3. Try to add Windows 10 computer by IP address, get "Connection failed message"
4. Right-click synergy tray icon, see "Start" instead of expected "Stop"
5. Open debug logs, right-click synergy tray icon, clock "Start" see the following message in debug logs:

v3.0.79.1-rc3: "INFO - skipping core start, core mode is not set"
v3.1.2-beta: "INFO - core mode is unknown, skipping core start"

---END HELP---

**Comment by chriswalken** [comment]
I'm actually running *Kubuntu* 24.04.  It's not allowing me to update the issue to correct this.

**Comment by chriswalken** [comment]
Ubuntu is now actively pushing 24.04.  Are then any plans to address this soon?

**Comment by nathonius** [comment]
I'm seeing this on Ubuntu 24.04 as well as Lubuntu and Mint, both based on the same version of Ubuntu.

**Comment by nathonius** [comment]
```
synergy-tray     [2024-05-28T20:58:22] - DEBUG2  - tray event: START
synergy-service  [2024-05-28T20:58:22] - INFO    - user requested core start from tray
synergy-service  [2024-05-28T20:58:22] - INFO    - skipping core start, core mode is not set
```

**Comment by Mykola-Veryha** [comment]
It's unbelievable that the open-source version(Barrier) has much better support than the commercial one. The person who decided to work on UI instead of logic should start taking responsibility.

**Comment by Mykola-Veryha** [comment]
You can follow these instructions. It works for me
```


Excellent support, apparently the serial key being pulled down on the new box didn't match the existing serial. Now I am all up and running.

For anyone else has a similiar issue. Check if your serial keys are matching between machines. It can be found in Synergy>About .
```
from here
https://www.reddit.com/r/SynergyApp/comments/1ddud7u/comment/l8h9pvc/

**Comment by chriswalken** [comment]
Hi @Mykola-Veryha ,

Thanks for commenting.  Can you please confirm this worked for you on a Ubuntu 24.04 based version?  The thread you linked mentions Mint 21.3 but since that released in Jan 2024 it cannot be based on Ubuntu 24.04.  I've back on Ubuntu 23.10 in part for this reason but also due to a couple other broken apps.  Googling confirms those apps are fixed now so Synergy is the last thing I'd like to confirm works before I upgrade again.  I now have what is basically a permanent notification from Ubuntu telling me to get off Ubuntu 23.10.

I'm also surprised there hasn't been been any comment from Synergy in here yet but the linked reddit thread was responded to within 1 day.  It suggests Synergy does not monitor github, which is unfortunate because I thought it would be better to report the Ubuntu 24.04 issue in here versus raising a support ticket.

Thanks

**Comment by nbolton** [comment]
Hi all, I'm working on 1.15.0 now.  I'm currently working on Synergy Core and Synergy 1 as my primary focus and have been for a few weeks now. I can confirm it's working on Ubuntu 24.04. Sorry about the lack of updates recently, we had been prioritising the new Synergy 3 GUI and a new website back-end. 

Snapshots here if you want to give it a shot! 🙂 
https://drive.google.com/drive/folders/1wXtFXjY1ExvvZbF_Tid05MLkal8-N_1t?usp=drive_link

**Comment by chriswalken** [comment]
Thanks for the response.

Coincidentally I upgraded to Kubuntu 24.04 again yesterday and Synergy is now working for me.  As part of the Kubuntu upgrade I had to up both update to Synergy 3.0.80.1-rc3 and reenter my serial number.  I don't know if either of those had an impact, but I can confirm 3.0.80.1-rc3 is working on Kubuntu 24.0.4.

As such I will close this.  Please reopen if you don't agree.
