### ISSUE TITLE
Missing pip module when running install deps script

### ISSUE THREAD

**Issue by korant96** [symless/synergy-core#7446]
### Discussion

- [X] Yes, and I still want to report a bug

### What type of Synergy user are you?

Community user

### Product name

Synergy 1

### Synergy version number

1.15

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux or Unix
- [ ] Other

### OS versions or Linux distros

ubuntu22.04

### Synergy configuration

not yet

### What steps will reproduce the problem?

1.clone git
2.cd synergy-core
3.python scripts/install_deps.py

### Additional information

python scripts/install_deps.py
Using virtual environment for: /home/korantli/workspace/synergy-core/scripts/install_deps.py
Python is missing pip module
Installing Python dependencies...
Running: sudo apt update
Hit:2 https://mirror.xtom.com.hk/ubuntu jammy InRelease                                                                      
Hit:3 https://mirror.xtom.com.hk/ubuntu jammy-security InRelease                                                             
Hit:4 https://mirror.xtom.com.hk/ubuntu jammy-updates InRelease                                                              
Hit:5 https://mirror.xtom.com.hk/ubuntu jammy-proposed InRelease                                                             
Hit:6 https://mirror.xtom.com.hk/ubuntu jammy-backports InRelease                                                            
Hit:1 https://packages.microsoft.com/repos/code stable InRelease                                                             
Hit:7 https://dl.google.com/linux/chrome/deb stable InRelease                                                                
Hit:8 https://repo.steampowered.com/steam stable InRelease                                                   
Hit:9 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Running: sudo apt install -y python3-pip python3-venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.4).
python3-venv is already the newest version (3.10.6-1~22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Python is missing pip module
Traceback (most recent call last):
  File "/home/korantli/workspace/synergy-core/scripts/install_deps.py", line 152, in <module>
    main()
  File "/home/korantli/workspace/synergy-core/scripts/install_deps.py", line 31, in main
    env.ensure_in_venv(__file__, auto_create=True)
  File "/home/korantli/workspace/synergy-core/scripts/lib/env.py", line 109, in ensure_in_venv
    check_dependencies(raise_error=True)
  File "/home/korantli/workspace/synergy-core/scripts/lib/env.py", line 160, in check_dependencies
    raise RuntimeError("Python is missing pip")
RuntimeError: Python is missing pip

**Comment by nbolton** [comment]
Thanks for reporting this. Hmm, that's odd, it should install `pip` automatically on Ubuntu. I will investigate.

**Comment by nbolton** [comment]
Ah, I think I figured it out. I have update the [README](https://github.com/symless/synergy-core/blob/master/README.md) with the correct instructions. Please use this command instead:

`./scripts/install_deps.py`

The readme says to use `python` for all OS, but on Linux and macOS, this is not Python 3 (unlike Windows). You could install `python-is-python3` if you want to use `python` for Python 3, but using the default interpreter (which is set to `python3`) is probably the best approach:
```
#!/usr/bin/env python3
```

**Comment by nbolton** [comment]
I will assume this fixes your issue and so will close the issue. If this isn't the case, please let me know and I can reopen the issue.

**Comment by korant96** [comment]
> I will assume this fixes your issue and so will close the issue. If this isn't the case, please let me know and I can reopen the issue.

good job～～！！
